'use client';
import {useState} from 'react';
import {Check,Layers,LockKeyhole,Orbit} from 'lucide-react';
import type {Projection,PublicCard,Side} from '@/lib/native-proof/types';

export function SetupStudy({game,onInspect}:{game:Projection;onInspect:(card:PublicCard)=>void}){
 const s=game.setup!,[handSide,setHandSide]=useState<Side>('dark');
 const drawn=s.stage==='start'||s.stage==='complete';
 const shownSide=s.openingHands?handSide:game.seat,hand=s.openingHands?.[shownSide]||game.players[shownSide].hand;
 const step=['choose','reveal','collision'].includes(s.stage)?0:s.stage==='place'?1:['shuffle','draw'].includes(s.stage)?2:3;
 const selected=(side:Side)=>s.selected[side];
 const inspectCard=(card:PublicCard,wide=false)=><button key={card.id} className={'proof-setup-card'+(wide?' location':'')} onClick={()=>onInspect(card)} aria-label={'Inspect '+card.name+' '+card.id.toUpperCase()}><img src={card.image} alt={card.name} loading="lazy"/><span>{card.name}<small>{card.id.toUpperCase()}</small></span></button>;
 return <section className="proof-setup-study" aria-label="Starting setup">
  <div className="proof-setup-heading"><span className="eyebrow amber"><Orbit size={15}/>BEFORE THE FIRST TURN</span><h2>{game.complete?'The table is ready.':s.stage==='collision'?'One site. Two claims.':drawn?'Eight cards. A new beginning.':'Choose where it begins.'}</h2><p>{game.complete?'Dark reaches Activate. No Force has been activated; this study ends before ordinary card actions.':s.stage==='collision'?'A shared starting location needs agreement. The player accepting conversion keeps their card underneath the opponent’s copy.':drawn?'Both hands were drawn together. Dark starts; the opening timing windows finish before Force generation is counted.':'Starting locations are free. Commit privately, reveal together, then prepare both opening hands.'}</p></div>
  <ol className="proof-setup-progress" aria-label="Setup progress">{['Choose & reveal','Place sites','Prepare & draw','First turn'].map((text,i)=><li key={text} className={i===step?'current':i<step?'done':''} aria-current={i===step?'step':undefined}>{i<step?<Check size={14}/>:<span>{i+1}</span>}{text}</li>)}</ol>
  {s.groups.length?<div className="proof-setup-groups">{s.groups.map(group=><section key={group.name}><h3>{group.name}<small>{group.cards.length===2?'Two adjacent sites':'One active site'}</small></h3><div>{group.cards.map(c=>inspectCard(c,true))}</div>{s.covered&&group.cards.some(c=>c.name===s.covered!.name)&&<div className="proof-setup-covered"><Layers size={17}/><p><b>{s.covered.side==='dark'?'Dark':'Light'}’s copy is underneath.</b> Its icons and text are inactive.</p><button onClick={()=>onInspect(s.covered!)}>Inspect {s.covered.id.toUpperCase()}</button></div>}</section>)}{s.groups.length>1&&<p className="proof-setup-caption">Separate systems · these sites are not adjacent.</p>}</div>:<div className="proof-setup-commitments">{(['dark','light'] as const).map(side=><section key={side} className={side}><h3>{side==='dark'?'Dark':'Light'} <small>{s.committed[side]?'Committed':'Choosing'}</small></h3>{selected(side)?inspectCard(selected(side)!,true):<div className="proof-setup-secret"><LockKeyhole size={23}/><p>{s.committed[side]?'Choice sealed':'Location not selected'}</p><small>Revealed when both players are ready</small></div>}</section>)}</div>}
  {s.candidates.length>0&&<details className="proof-setup-candidates"><summary>Inspect your {s.candidates.length} eligible starting cards</summary><div>{s.candidates.map(c=>inspectCard(c,true))}</div></details>}
  {s.rejected.length>0&&<details className="proof-setup-rejected"><summary>Earlier choices · {s.rejected.length} {s.rejected.length===1?'round':'rounds'}</summary><p>Only these physical copies are excluded from reselection. They return before the opening shuffle.</p>{s.rejected.map((cards,i)=><p key={i}><b>Round {i+1}</b>{cards.map(c=><button key={c.id} onClick={()=>onInspect(c)}>{c.side==='dark'?'Dark':'Light'} · {c.name} · {c.id.toUpperCase()}</button>)}</p>)}</details>}
  <div className="proof-setup-opening"><h3>{drawn?'Your opening hand':'The opening deal'}<small>8 cards each</small></h3>{drawn?<>{s.openingHands&&<div className="proof-setup-hand-tabs" aria-label="Inspect the two study hands">{(['dark','light'] as const).map(side=><button key={side} aria-pressed={shownSide===side} onClick={()=>setHandSide(side)}>{side==='dark'?'Dark':'Light'} hand</button>)}</div>}<p className="proof-setup-caption">{shownSide==='dark'?'Dark':'Light'} · {game.players[shownSide].counts.reserve} in Reserve · {game.players[shownSide].counts.force} activated{s.openingHands?' · Both views available in your two-seat study':' · Only your hand is visible'}</p><div className="proof-setup-hand">{hand.map(c=>inspectCard(c))}</div></>:<p>Both players draw eight together after locations are placed. The recorded shuffle, including any opponent cut, makes each path repeatable.</p>}</div>
  {s.generation&&<div className="proof-setup-generation"><span><Orbit size={18}/>Dark’s first Activate</span><strong>{s.generation.dark}<small>Force generation</small></strong><p>Personal Force + active location icons.<br/>The covered copy contributes no icons.</p></div>}
 </section>;
}
