import {Check,Orbit,RotateCcw} from 'lucide-react';
import type {Projection} from '@/lib/native-proof/types';

const stages=[['start','Start'],['activate','Activate'],['control','Control'],['deploy','Deploy'],['battle','Battle'],['move','Move'],['draw','Draw'],['end','Turn ends']] as const;
export function TurnCycleStudy({game}:{game:Projection}){
 const extended=game.scenario==='second-contact',count=extended?4:2,History=extended?'details':'div';
 const turn=game.turn!,cycle=game.cycle!,side=game.active==='dark'?'Dark':'Light',current=stages.findIndex(([stage])=>stage===turn.stage);
 const detail=game.complete?(extended?'All four':'Both')+' full turns are complete. Dark’s next activation is ready; the board, hands and piles remain exactly where play left them.':turn.stage==='start'?'Start-of-turn actions finish before counting Force generation. The incoming player is now active.':turn.stage==='end'?'Both players recirculate, then temporary effects expire and end-of-turn actions finish. The outgoing player stays active until the handoff.':turn.stage==='control'&&game.locationStudy?'Each controlled site may drain once this turn. Use the active top location’s opposing Force icons and any applicable game text.':turn.stage==='control'&&game.scenario==='desert-patrol'?'A controlled site can drain once this turn. Jawa Camp and Dune Sea each have one opposing Force icon.':turn.stage==='control'?'A controlled site can drain once this turn. Light’s printed bonus makes its drain at the Corridor 2; Dark’s drain there is 0.':turn.stage==='activate'?'Activate up to your generated Force, one card at a time. Unspent Force from the last turn is still available.':'Choose your actions or pass. The same board continues into the other side’s turn.';
 return <div className="proof-cycle-study">
  <div className="proof-cycle-heading"><span className="eyebrow amber"><Orbit size={15}/>{game.complete?(extended?'FOUR':'TWO')+' TURNS COMPLETE':(extended?'FOUR':'TWO')+' TURNS / ONE BOARD'}</span><h2>{game.complete?'Dark is ready again.':side+'’s turn.'}</h2><p>{detail}</p></div>
  <ol className={"proof-cycle-turns"+(extended?" extended":"")} aria-label="Study turns">{Array.from({length:count+1},(_,i)=>i+1).map(number=><li key={number} className={turn.number===number?'current':turn.number>number?'done':''} aria-current={turn.number===number?'step':undefined}><span>{turn.number>number?<Check size={14}/>:number}</span><div>{number%2?'Dark':'Light'}<small>{number===count+1?'Next activation':extended?(number<=2?'First turn':'Second turn'):'Full turn'}</small></div></li>)}</ol>
  <div className="proof-cycle-force" aria-label={side+' turn Force'}><div><span>Generation</span><strong>{turn.stage==='start'?'—':cycle.generation}</strong></div><div><span>Activated</span><strong>{cycle.activated}<small> this turn</small></strong></div><div><span>Force available</span><strong>{game.players[game.active].counts.force}</strong></div></div>
  <ol className="proof-cycle-phases" aria-label="Current turn phases">{stages.map(([stage,label],i)=><li key={stage} className={i===current?'current':i<current?'done':''} aria-current={i===current?'step':undefined}>{i<current?<Check size={12}/>:<span>{i+1}</span>}{label}</li>)}</ol>
  {cycle.history.length>0&&<History className="proof-cycle-history">{extended?<summary><RotateCcw size={15}/>Completed turns · {cycle.history.length}</summary>:<h3><RotateCcw size={15}/>Across the turn boundary</h3>}{cycle.history.map(record=><div key={record.number}><strong>Turn {record.number} · {record.side==='dark'?'Dark':'Light'} complete</strong><p>Force retained: <b>Dark {record.carriedForce.dark}</b> · <b>Light {record.carriedForce.light}</b></p><p>Recirculated: Dark {record.recirculated.dark} · Light {record.recirculated.light}</p><span>{record.expired?record.expired+' Barrier expired · ':''}Activation, drain, battle and movement limits reset</span></div>)}</History>}
 </div>;
}
