import {Check,Crosshair,Link2,ShieldAlert} from 'lucide-react';
import type {Choice,Projection,PublicCard,Side} from '@/lib/native-proof/types';
const sideName=(s:Side)=>s==='light'?'Light':'Dark';
export function WeaponStudy({game,onInspect}:{game:Projection;onInspect:(c:PublicCard)=>void}){
 const study=game.weaponStudy!,b=game.battle!,latest=b.shots?.at(-1);
 const order=study.lostOrder;
 return <section className="proof-weapon-study" aria-label="Character weapon study">
  <header><span className="eyebrow amber">{sideName(game.active).toUpperCase()} / {study.stage==='deploy'?'ARM YOUR TROOPERS':'WEAPON STUDY'}</span><h2>{game.complete?'Cease fire.':order?'Together into Lost.':latest&&latest.status!=='resolved'?'A shot is resolving.':study.stage==='deploy'?'Choose your weapon.':'Hold your ground.'}</h2><p>{order?'The trooper and its weapons left together. Their owner chooses the order; only the trooper’s forfeit pays battle losses.':study.stage==='deploy'?'Deploy or transfer weapons to your warriors. A trooper may carry several, but can use only one different weapon this turn.':'A hit trooper still adds power and ability and can return fire. It must be forfeited during the damage segment.'}</p></header>
  <div className="proof-weapon-site"><button onClick={()=>onInspect(game.locations[0])}><img src={game.locations[0].image} alt="Inspect Docking Bay 327"/></button><div><span className="eyebrow">DEATH STAR</span><strong>Docking Bay 327</strong><span>Trooper defense 1 · Forfeit 2</span></div></div>
  {latest&&<div className={'proof-shot-result '+(latest.status==='resolved'?(latest.hit?'hit':'miss'):'pending')} aria-live="polite"><Crosshair size={21}/><div><span className="eyebrow">{sideName(latest.side)} / {latest.weapon.toUpperCase()} → {latest.target.toUpperCase()}</span><strong>{latest.status==='pending'?'Force paid · awaiting firing responses':latest.status==='drawn'?'Weapon destiny revealed · awaiting responses':latest.hit?'Target hit':'Shot missed'}</strong>{latest.destiny!==undefined&&<p><b>{latest.destiny}</b>{latest.bonus?<> + <b>{latest.bonus}</b></>:null} {latest.status==='resolved'?(latest.hit?'>':'≤'):'compared with'} defense <b>{latest.defense}</b>{latest.status==='resolved'&&!latest.hit?' · A hit requires a greater total.':''}</p>}</div></div>}
  <div className="proof-weapon-lines">{(['dark','light'] as const).map(side=><section key={side} className={side} aria-label={sideName(side)+' troopers'}><div className="proof-weapon-side"><strong>{sideName(side)}</strong><span>Power {b.power[side]}</span></div>{game.table.filter(c=>c.type==='Character'&&c.side===side).map(c=>{
   const attached=game.table.filter(w=>w.attachedTo===c.id);
   return <article className={'proof-armed-trooper'+(c.hit?' is-hit':'')} key={c.id}>
    <button className="proof-armed-character" onClick={()=>onInspect(c)} aria-label={'Inspect '+c.name+' '+c.id.toUpperCase()}><img src={c.image} alt=""/><span><strong>{c.name}</strong><small>{c.id.toUpperCase()}</small></span></button>
    {c.hit&&<div className="proof-hit-label"><ShieldAlert size={13}/>Hit · must forfeit<small>Still fights · forfeit stays 2</small></div>}
    <div className="proof-attached-weapons">{attached.map(w=><button key={w.id} onClick={()=>onInspect(w)} aria-label={'Inspect '+w.name+' '+w.id.toUpperCase()}><img src={w.image} alt=""/><span>{w.name}<small>{b.fired?.includes(w.id)?'Fired this battle':b.weaponUsers?.[c.id]?'Another weapon used this turn':'Ready when battle permits'}</small></span>{b.fired?.includes(w.id)?<Check size={12}/>:<Link2 size={12}/>}</button>)}{!attached.length&&<span className="proof-no-weapon">No weapon attached</span>}</div>
   </article>;
  })}{!game.table.some(c=>c.type==='Character'&&c.side===side)&&<p>No troopers remain here.</p>}</section>)}</div>
  {order&&<div className="proof-loss-order"><span className="eyebrow">{sideName(order.side).toUpperCase()} / CARDS LEAVING TOGETHER</span><div>{order.remaining.map(c=><button key={c.id} onClick={()=>onInspect(c)}><img src={c.image} alt=""/><span>{c.name}<small>{c.id.toUpperCase()} · awaiting placement</small></span></button>)}</div><p>Each selection goes on top of Lost. The last card placed ends on top.</p>{order.placed.length>0&&<small>Already placed, top first: {order.placed.map(c=>c.name+' '+c.id.toUpperCase()).join(' → ')}</small>}</div>}
  {!!b.shots?.length&&<details className="proof-shot-history"><summary>Weapon fire history · {b.shots.length}</summary><ol>{b.shots.map((shot,i)=><li key={i}>{sideName(shot.side)} {shot.weapon.toUpperCase()} → {shot.target.toUpperCase()}<span>{shot.status==='resolved'?(shot.destiny+' + '+shot.bonus+' = '+(shot.destiny!+shot.bonus)+' · '+(shot.hit?'hit':'miss')):'Resolving'}</span></li>)}</ol></details>}
 </section>;
}
export function WeaponChoice({choice}:{choice:Choice}){const p=choice.weaponPreview!;return <span className="proof-weapon-choice"><strong>{choice.label}</strong><small>Trooper {p.user.toUpperCase()} · Use {p.cost} Force</small><span>Draw destiny{p.bonus?' + '+p.bonus:''} <b>&gt; {p.defense}</b> to hit</span></span>}
export function MandatoryHits({game}:{game:Projection}){
 const hits=game.weaponStudy?.hits;if(!hits||!game.losses||!hits.light.length&&!hits.dark.length)return null;
 return <div className="proof-mandatory-hits"><ShieldAlert size={18}/><div><strong>Hit troopers must still be forfeited</strong>{(['dark','light'] as const).filter(side=>hits[side].length).map(side=><p key={side}>{sideName(side)}: {hits[side].map(id=>id.toUpperCase()).join(', ')}</p>)}<small>Clearing damage and attrition does not clear a weapon hit. You may choose other legal losses first.</small></div></div>;
}
