'use client';
import {useEffect,useState} from 'react';
import type {DeckChoice,NativeDeck} from '@/lib/native-decks';
import {matchRequest} from '@/lib/native-engine/client';
import type {SealedView} from '@/lib/native-sealed';
import type {Side} from '@/lib/native-engine/types';
import {nativeCards} from './cards';

export function DeckPicker({label,decks,selected,onChange,disabled=false}:{label:string;decks:DeckChoice[];selected?:DeckChoice;onChange:(id:string)=>void;disabled?:boolean}){
 return <div className="native-deck-picker"><label>{label}<select aria-label={label} value={selected?.id??''} onChange={e=>onChange(e.target.value)} disabled={disabled||!decks.length}>{!decks.length&&<option value="">No decks in this format</option>}{decks.map(d=><option key={d.id} value={d.id}>{d.name}{d.source==='starter'?' · Starter':''} · {d.cards.length}/{d.size}{d.poolId?' · Sealed':''}</option>)}</select></label>{selected&&<p className="native-muted" role="status">{selected.eligible?'Card checks passed. The server checks your deck again when you take a seat.':selected.issues.join(' ')}</p>}</div>;
}
export function DeckLibrary({selected,onSaved,side,size,startPool}:{selected?:DeckChoice;onSaved:(deck:DeckChoice)=>void;side:Side;size:40|60;startPool?:SealedView|null}){
 const [draftPool,setDraftPool]=useState<SealedView|null>(null);
 const [draft,setDraft]=useState<NativeDeck|null>(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{if(startPool){setDraftPool(startPool);setDraft({id:crypto.randomUUID(),name:'My OTSD deck',side:startPool.side,size:40,cards:[],revision:0,updated:0,poolId:startPool.id});setQuery('');setError('');setNotice('')}},[startPool]);
 const inventory=draft?.poolId===draftPool?.id?draftPool:undefined;
 const stock=new Map<string,number>();for(const bp of inventory?.cards??[])stock.set(bp,(stock.get(bp)??0)+1);
 const start=(copy:boolean)=>{setDraftPool(selected?.pool??null);setError('');setNotice('');setQuery('');setDraft(selected?{...selected,id:copy||selected.source==='starter'?crypto.randomUUID():selected.id,name:copy||selected.source==='starter'?selected.name+' copy':selected.name,revision:copy||selected.source==='starter'?0:selected.revision}:{id:crypto.randomUUID(),name:'My deck',side,size,cards:[],revision:0,updated:0})};
 const counts=new Map<string,number>();for(const bp of draft?.cards??[])counts.set(bp,(counts.get(bp)??0)+1);
 const change=(bp:string,n:number)=>setDraft(d=>{if(!d)return d;const cards=[...d.cards];if(n>0&&cards.length<120&&(!d.poolId||(stock.get(bp)??0)>(counts.get(bp)??0)))cards.push(bp);else if(n<0){const i=cards.lastIndexOf(bp);if(i>=0)cards.splice(i,1)}return {...d,cards}});
 const save=async()=>{if(!draft||busy)return;setBusy(true);setError('');try{const {id,name,side,size,cards,revision,poolId}=draft;const d=await matchRequest<DeckChoice>('/api/match-decks',{id,name,side,size,cards,revision,...(poolId?{poolId}:{})});onSaved(d);setDraft(null);setNotice('Deck saved to your account.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const matches=[...nativeCards.values()].filter(c=>c.side===draft?.side&&(!draft.poolId||stock.has(c.gempId))&&(!query.trim()||[c.name,c.gempId,c.type,c.text].join(' ').toLowerCase().includes(query.trim().toLowerCase()))).sort((a,b)=>a.name.localeCompare(b.name));
 return <section className="native-panel native-deck-library" aria-label="Native deck library"><h2>Your native decks</h2><p>Build an open-play deck, save a draft, or customize a starter. Saving a deck does not unlock unverified cards for matches.</p>{notice&&<p role="status">{notice}</p>}{!draft?<div className="native-tools"><button className="button" onClick={()=>{setError('');setNotice('');setDraft({id:crypto.randomUUID(),name:'My deck',side,size,cards:[],revision:0,updated:0})}}>New deck</button>{selected&&<><button className="button" onClick={()=>start(false)}>{selected.source==='starter'?'Customize starter':'Edit selected deck'}</button><button className="button" onClick={()=>start(true)}>Copy selected deck</button></>}</div>:<>
 <div className="native-deck-fields"><label>Deck name<input value={draft.name} maxLength={80} disabled={busy} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Deck side<select aria-label="Deck side" value={draft.side} disabled={busy||!!draft.poolId||draft.cards.length>0} onChange={e=>setDraft({...draft,side:e.target.value as Side})}><option value="light">Light side</option><option value="dark">Dark side</option></select></label><label>Deck size<select aria-label="Deck size" value={draft.size} disabled={busy||!!draft.poolId} onChange={e=>setDraft({...draft,size:Number(e.target.value) as 40|60})}><option value="60">60 cards</option><option value="40">{draft.poolId?'40 cards · sealed':'40 cards · open variant'}</option></select></label></div>
 <p>{draft.poolId?'Sealed pool · only the copies you received may be used.':'Open-play deck'}</p><p role="status">{draft.cards.length} / {draft.size} cards · {draft.cards.length===draft.size?'Deck count complete':draft.cards.length<draft.size?`${draft.size-draft.cards.length} to add`:`${draft.cards.length-draft.size} to remove`}</p>
 <div className="native-deck-editor"><div><h3>In your deck</h3>{!counts.size?<p>No cards yet. Search the collection to add some.</p>:<ul className="native-deck-list">{[...counts].map(([bp,count])=><li key={bp}><span>{nativeCards.get(bp)?.name??bp}<small>{bp}</small></span><button className="button" aria-label={'Remove '+(nativeCards.get(bp)?.name??bp)} disabled={busy} onClick={()=>change(bp,-1)}>−</button><b>{count}</b><button className="button" aria-label={'Add another '+(nativeCards.get(bp)?.name??bp)} disabled={busy||draft.cards.length>=120||!!draft.poolId&&(counts.get(bp)??0)>=(stock.get(bp)??0)} onClick={()=>change(bp,1)}>+</button></li>)}</ul>}</div><div><label>Find cards<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, card text or identifier"/></label><p className="native-muted">{matches.length} {draft.poolId?'different cards in your sealed pool':'cards in the native collection'}. Card text may still need implementation before play.</p><ul className="native-deck-list">{matches.slice(0,30).map(c=><li key={c.gempId}><span>{c.name}<small>{c.type} · {c.gempId}{draft.poolId?` · ${stock.get(c.gempId)!-(counts.get(c.gempId)??0)} remaining`:''}</small></span><button className="button" aria-label={'Add '+c.name} disabled={busy||draft.cards.length>=120||!!draft.poolId&&(counts.get(c.gempId)??0)>=(stock.get(c.gempId)??0)} onClick={()=>change(c.gempId,1)}>Add</button></li>)}</ul>{matches.length>30&&<p>Refine your search to see more cards.</p>}</div></div>
 {error&&<p role="alert" className="native-error">{error}</p>}<div className="native-tools"><button className="button primary" disabled={busy||!draft.name.trim()} onClick={save}>{busy?'Saving…':'Save deck'}</button><button className="button" disabled={busy} onClick={()=>setDraft(null)}>Close editor</button></div></>}
 </section>;
}
