'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Copy,Orbit,RefreshCw,Shield,Swords} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {MatchConnection,MatchRequestError,matchRequest,matchHref,emptyOpportunity,type ClientState,type MatchView,type SavedMatch} from '@/lib/native-engine/client';
import {premiereSites} from '@/lib/native-engine/premiere-setup';
import type {Battle} from '@/lib/native-engine/battle';
import type {Card,Side} from '@/lib/native-engine/types';
import {clockMinutes as timeControls} from '@/lib/native-engine/match-clock';
import {nativeCards,nativeStarters} from './cards';
import './table.css';
const clockLabel=(minutes:number|null|undefined)=>minutes?`${minutes} minutes per player`:'Untimed';
const clockText=(ms:number)=>`${Math.floor(Math.ceil(ms/1000)/60)}:${String(Math.ceil(ms/1000)%60).padStart(2,'0')}`;
const sideName=(s:Side)=>s==='dark'?'Dark side':'Light side';
const browserStorage=()=>{try{return sessionStorage}catch{return undefined}};
const initial:ClientState={view:null,pending:null,busy:false,error:'',status:0,receivedAt:0};
type RulesView={peek?:Card[];peekInserts?:Card[];peekSelected?:Card[];scavenge?:{cards:Card[]}|null;battle?:Battle|null;scan?:{stage:string;cards:Card[]}|null;searchCards?:Card[];retrievedCards?:Pick<Card,'id'|'blueprint'>[]};
type Invitation={clockMinutes?:number|null;inviteToken:string;side:Side;size:40|60;commandId:string};
type Creation={clockMinutes?:number|null;id:string;mode:'cpu'|'pvp';side:Side;deckSize:60;deck:string[];computerDeck?:string[]};
export default function NativeMatches({id}:{id?:string}){
 const [state,setState]=useState(initial),[saved,setSaved]=useState<SavedMatch[]>([]),[admitted,setAdmitted]=useState<string[]>([]),[loaded,setLoaded]=useState(false),[report,setReport]=useState(false),[visible,setVisible]=useState(true),[tab,setTab]=useState('table'),[paused,setPaused]=useState(false),[remaining,setRemaining]=useState(2),[inspect,setInspect]=useState<Pick<Card,'id'|'blueprint'>|null>(null),[concede,setConcede]=useState(false),[notice,setNotice]=useState(''),[side,setSide]=useState<Side>('light'),[mode,setMode]=useState<'cpu'|'pvp'>('cpu'),[invitation,setInvitation]=useState<Invitation|null>(null);
 const [minutes,setMinutes]=useState<number|null>(null),[clockNow,setClockNow]=useState(0);
 const siteStrip=useRef<HTMLDivElement|null>(null);
 const conn=useRef<MatchConnection|null>(null),creation=useRef<Creation|null>(null),locked=useRef(false);
 useEffect(()=>{
  setState(initial);setLoaded(false);setReport(new URLSearchParams(location.search).has('progress-report'));
  const onVisibility=()=>setVisible(!document.hidden);onVisibility();document.addEventListener('visibilitychange',onVisibility);
  if(id){
   try{const fragment=new URLSearchParams(location.hash.slice(1)),stored=sessionStorage.getItem('native-invite:'+id),invite=fragment.has('invite')?{inviteToken:fragment.get('invite'),side:fragment.get('side'),size:Number(fragment.get('size')),clockMinutes:fragment.has('minutes')?Number(fragment.get('minutes')):null,commandId:crypto.randomUUID()}:stored?JSON.parse(stored):null;
    if(invite&&typeof invite.inviteToken==='string'&&['light','dark'].includes(invite.side)&&[40,60].includes(invite.size)){setInvitation(invite);sessionStorage.setItem('native-invite:'+id,JSON.stringify(invite))}
   }catch{/* An invitation remains available in its original link. */}
   try{const c=new MatchConnection(id,setState,matchRequest,browserStorage());conn.current=c;setState(c.state);void c.load().finally(()=>setLoaded(true))}catch(e){setState({...initial,error:(e as Error).message});setLoaded(true)}
  }else{
   try{const draft=JSON.parse(sessionStorage.getItem('native-create')||'null');if(draft?.id&&nativeStarters.some(d=>d.side===draft.side)){creation.current=draft;setSide(draft.side);setMode(draft.mode);setMinutes(draft.clockMinutes??null)}}catch{}
   void matchRequest<{matches:SavedMatch[];starters:{id:string;admitted:boolean}[]}>('/api/matches').then(r=>{setSaved(r.matches);setAdmitted(r.starters.filter(s=>s.admitted).map(s=>s.id))}).catch(e=>setState({...initial,error:e.message,status:e.status})).finally(()=>setLoaded(true));
  }
  return()=>{conn.current?.dispose();conn.current=null;document.removeEventListener('visibilitychange',onVisibility)};
 },[id]);
 const v=state.view,g=v?.game,p=g?.prompt,rules=g?.rules as RulesView|undefined;
 useEffect(()=>{setClockNow(Date.now());if(!v?.clock?.running||!visible)return;const timer=setInterval(()=>setClockNow(Date.now()),250);return()=>clearInterval(timer)},[v?.revision,state.receivedAt,v?.clock?.running,visible]);
 const computerReady=v?.mode==='cpu'&&(p?.side!==v.side||(g?.status==='setup'&&g.setup?.stage==='choose'&&!g.setup.committed[v.side==='dark'?'light':'dark']));
 useEffect(()=>{const strip=siteStrip.current,target=strip?.querySelector<HTMLElement>('[data-battle="true"]');if(strip&&target)strip.scrollTo({left:target.offsetLeft-strip.offsetLeft-(strip.clientWidth-target.clientWidth)/2})},[rules?.battle?.site,tab]);
 const blocked=state.busy||!!state.pending||!!state.error||concede||!!inspect;
 // Polling recovers other-player moves and server deadlines. CPU requests never
 // contain a chosen move. No work continues while hidden or a command is uncertain.
 useEffect(()=>{if(!id||!v||g?.status==='finished'||!visible||blocked)return;const timer=setTimeout(()=>{if(computerReady)void conn.current?.advance();else void conn.current?.load()},computerReady?350:3000);return()=>clearTimeout(timer)},[id,v?.revision,state.receivedAt,visible,blocked,g?.status,p?.side,v?.mode,v?.side,computerReady]);
 const empty=emptyOpportunity(v);
 useEffect(()=>{setRemaining(2);if(!empty||blocked||paused||!visible)return;const revision=v!.revision,start=Date.now(),timer=setInterval(()=>{const n=Math.max(0,2-(Date.now()-start)/1000);setRemaining(n);if(n===0){clearInterval(timer);void conn.current?.choose('pass',revision)}},100);return()=>clearInterval(timer)},[empty,v?.revision,blocked,paused,visible]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key!=='ArrowRight'||e.repeat||e.altKey||e.ctrlKey||e.metaKey||e.shiftKey||!empty||blocked||!visible)return;if((e.target as Element)?.closest('input,textarea,select,button,a,[contenteditable="true"],[role="dialog"]'))return;e.preventDefault();void conn.current?.choose('pass',v!.revision)};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[empty,blocked,visible,v?.revision]);
 const scan=rules?.scan;
 // Inspection is tied to the current projection. Revoked private
 // cards vanish even if a card dialog was open during the previous response.
 const shown=[...(g?.inserts||[]).flatMap(x=>x.card?[x.card]:[]),...(g?.table||[]),...(g?.buried||[]),...(g?.players[v?.side||'light'].hand||[]),...(['dark','light'] as const).flatMap(s=>[...(g?.players[s].lost||[]),...(g?.players[s].destiny||[])]),...(g?.setup?.candidates||[]),...Object.values(g?.setup?.selected||{}),...(rules?.peek||[]),...(rules?.peekInserts||[]),...(rules?.scavenge?.cards||[]),...(rules?.searchCards||[]),...(rules?.retrievedCards||[]),...(scan?.cards||[])];
 const inspected=inspect&&shown.find(c=>c?.id===inspect.id&&c?.blueprint===inspect.blueprint),printed=inspected?nativeCards.get(inspected.blueprint):null;
 useEffect(()=>{if(inspect&&!inspected)setInspect(null)},[inspect,!!inspected]);
 function card(c:Pick<Card,'id'|'blueprint'>|null){if(!c)return null;const d=nativeCards.get(c.blueprint);return <button className="native-card" key={c.id} onClick={()=>setInspect(c)} aria-label={'Inspect '+(d?.name||'card')}><img src={d?.image} alt="" loading="lazy"/><span>{d?.name||'Card'}</span>{g?.table.find(x=>x.id===c.id)?.stackedOn&&<b className="native-hit native-patient">PATIENT · INACTIVE</b>}{rules?.battle?.hits.includes(c.id)&&<b className="native-hit">HIT</b>}</button>}
 async function launch(){if(locked.current)return;locked.current=true;setState(s=>({...s,busy:true,error:''}));const d=nativeStarters.find(d=>d.side===side)!,op=nativeStarters.find(d=>d.side!==side)!;
  if(!creation.current||creation.current.side!==side||creation.current.mode!==mode||(creation.current.clockMinutes??null)!==(mode==='pvp'?minutes:null))creation.current={id:crypto.randomUUID(),mode,side,clockMinutes:mode==='pvp'?minutes:null,deckSize:60,deck:[...d.main],...(mode==='cpu'?{computerDeck:[...op.main]}:{})};
  try{sessionStorage.setItem('native-create',JSON.stringify(creation.current))}catch{}
  try{await matchRequest('/api/matches',creation.current);try{browserStorage()?.removeItem('native-create')}catch{}location.assign(matchHref(creation.current.id,report))}catch(e){setState(s=>({...s,error:(e as Error).message,status:(e as MatchRequestError).status||0,busy:false}));locked.current=false}
 }
 async function join(){if(!id||!invitation||locked.current)return;locked.current=true;setState(s=>({...s,busy:true,error:''}));try{
  const deck=nativeStarters.find(d=>d.side===invitation.side)!;if(invitation.size!==deck.size)throw Error('This invitation needs a custom 40-card deck. Native custom-deck selection is still being connected.');
  await matchRequest('/api/matches/'+id,{operation:'join',commandId:invitation.commandId,inviteToken:invitation.inviteToken,clockMinutes:invitation.clockMinutes??null,deck:deck.main});try{browserStorage()?.removeItem('native-invite:'+id)}catch{}history.replaceState(history.state,'',location.pathname+location.search);setInvitation(null);await conn.current?.load();
 }catch(e){setState(s=>({...s,busy:false,error:(e as Error).message,status:(e as MatchRequestError).status||0}))}finally{locked.current=false}}
 async function copy(invite=false){const url=new URL(matchHref(id,report),location.origin);if(invite&&v?.inviteToken)url.hash=new URLSearchParams({invite:v.inviteToken,side:v.side==='dark'?'light':'dark',size:String(v.deckSize),...(v.clock?{minutes:String(v.clock.minutes)}:{})}).toString();try{await navigator.clipboard.writeText(url.href);setNotice(invite?'Private invitation copied.':'Match link copied.')}catch{setNotice(url.href)}}
 function player(s:Side){if(!v||!g)return null;const x=g.players[s],b=rules?.battle,c=v.clock,ms=c?Math.max(0,c.remainingMs[s]-(c.running===s?Math.max(0,clockNow-state.receivedAt):0)):0;return <section className={'native-player '+s} aria-label={sideName(s)}><header><Shield size={18}/><strong>{sideName(s)}</strong><small>{s===v.side?'YOU':v.mode==='cpu'?'COMPUTER':'OPPONENT'}</small><b title={x.lifeForce === null ? 'Count unavailable while an insert is in Reserve' : undefined}>{x.lifeForce ?? '?'}<span>LIFE FORCE</span></b></header>{c&&<div className="native-clock" data-running={c.running===s} data-low={ms<60000} aria-label={sideName(s)+' match clock'}><span>{g.status==='setup'?'Starts after setup':g.status==='finished'?'Final time':c.running===s?ms===0?'Confirming time…':'Clock running':'Clock paused'}</span><strong>{clockText(ms)}</strong></div>}<div className="native-piles">{(['reserve','force','used','lost','hand'] as const).map(z=><span key={z}><b title={x.counts[z] === null ? 'Count unavailable while an insert is in Reserve' : undefined}>{x.counts[z] ?? '?'}</b>{z}</span>)}</div>{b&&b.stage!=='complete'&&<div className="native-losses" aria-label={sideName(s)+' battle losses'}><span>Power <b>{b.power[s]}</b></span><span>Destiny <b>{b.destiny[s]??'—'}</b></span><span>Attrition <b>{b.totalsReady?b.attrition[s]:'—'}</b></span><span>Damage <b>{b.totalsReady?b.damage[s]:'—'}</b></span></div>}</section>}
 const tabItems=[['table','Table'],['hand','Your hand'],['actions','Actions']];
 return <div className="native-shell"><header className="native-header"><a href={report?'/?progress-report':'/'}><ArrowLeft size={16}/>THE HOLOTABLE</a><span><Orbit size={18}/>NATIVE MATCHES</span><a href={matchHref(undefined,report)}>Your matches</a></header>
 <main className="native-main"><div className="native-heading"><div><span className="eyebrow">{id?g?.status==='setup'?'PREPARE FOR BATTLE':g?.status==='finished'?'MATCH COMPLETE':'THE LIVING TABLE':'YOUR NEXT ENCOUNTER'}</span><h1>{id?g?.status==='setup'?'The opening table.':g?.status==='finished'?`${sideName(g.result!.winner)} wins.`:'Across the galaxy.':'Take your seat.'}</h1></div>{id&&<div className="native-tools"><button className="button" onClick={()=>copy()}><Copy size={16}/>Copy match link</button><button className="button" disabled={state.busy} onClick={()=>conn.current?.load()}><RefreshCw size={16}/>Refresh</button></div>}</div>
 {notice&&<p role="status" className="native-notice">{notice}</p>}
 {state.error&&!(state.status===404&&invitation)&&<div role="alert" className="native-error"><p>{state.error}</p>{state.status===401?<a className="button" href={'/signin-with-chatgpt?return_to='+encodeURIComponent(matchHref(id,report)+(typeof location!=='undefined'?location.hash:''))}>Sign in to your matches</a>:id&&<button className="button" disabled={state.busy} onClick={()=>conn.current?.retry()}>{state.pending?'Retry the same move':'Reload match'}</button>}</div>}
 {state.pending&&!state.error&&<div role="status" className="native-notice">A move awaits confirmation. <button className="button" disabled={state.busy} onClick={()=>conn.current?.retry()}>Recover saved move</button></div>}
 {!loaded&&<p role="status">Opening your table…</p>}
 {!id&&loaded&&<div className="native-lobby"><section className="native-panel"><Swords size={28}/><h2>A full match, every choice saved.</h2><p>Premiere Introductory decks · 60 cards. Full native matches unlock as their rules and card behavior are verified.</p><label>Your side<select value={side} disabled={state.busy} onChange={e=>setSide(e.target.value as Side)}><option value="light">Light side</option><option value="dark">Dark side</option></select></label><label>Your opponent<select value={mode} disabled={state.busy} onChange={e=>setMode(e.target.value as 'cpu'|'pvp')}><option value="cpu">Computer</option><option value="pvp">Invite a friend</option></select></label>{mode==='pvp'&&<><label>Match clock<select aria-label="Match clock" value={minutes??'untimed'} disabled={state.busy} onChange={e=>setMinutes(e.target.value==='untimed'?null:Number(e.target.value))}><option value="untimed">Untimed</option>{timeControls.map(n=><option key={n} value={n}>{clockLabel(n)}</option>)}</select></label><p>Setup is untimed. During play, your clock runs while a choice is yours, including while disconnected. Running out of time ends the match.</p></>}<button className="button primary" disabled={state.busy||!admitted.includes(nativeStarters.find(d=>d.side===side)!.id)||(mode==='cpu'&&!admitted.includes(nativeStarters.find(d=>d.side!==side)!.id))} onClick={launch}>Start match</button>{!admitted.length&&<p className="native-muted">Starter admission is not open yet. Your saved matches remain available below.</p>}</section><section className="native-panel"><h2>Your saved matches</h2>{!saved.length?<p>No native matches yet.</p>:saved.map(m=><a className="native-saved" key={m.id} href={matchHref(m.id,report)}><strong>{sideName(m.side)} · {m.mode==='cpu'?'Computer':'Private opponent'}</strong><span>{m.deckSize} cards · {new Date(m.updated).toLocaleDateString()}</span><ArrowLeft style={{transform:'rotate(180deg)'}} size={18}/></a>)}</section></div>}
 {id&&invitation&&!v&&state.status!==401&&<section className="native-panel"><h2>A seat is waiting.</h2><p>Join as {sideName(invitation.side)} with a {invitation.size}-card deck. {clockLabel(invitation.clockMinutes)}. {invitation.clockMinutes?'Setup is untimed; running out of time during play loses the match. ':''}The server checks the invitation and your deck before seating you.</p><button className="button primary" disabled={state.busy} onClick={join}>Join match</button></section>}
 {v?.waitingForOpponent&&<section className="native-panel"><h2>Your opponent’s seat is open.</h2><p>{clockLabel(v.clock?.minutes)}. Share a private invitation. This match link restores your table after a refresh.</p><button className="button primary" onClick={()=>copy(true)}>Copy private invitation</button></section>}
 {v&&g&&<><div className="native-scoreboard">{player(v.side==='dark'?'light':'dark')}{player(v.side)}</div><div className="native-turn"><span>Turn {g.turn.number} · {sideName(g.turn.side)}</span><ol>{['activate','control','deploy','battle','move','draw'].map(phase=><li key={phase} aria-current={phase===g.turn.phase?'step':undefined}>{phase}</li>)}</ol><small>Saved · move {v.revision}</small></div>
 <nav className="native-tabs" aria-label="Match panels">{tabItems.map(([value,label])=><button key={value} aria-pressed={tab===value} onClick={()=>setTab(value)}>{label}{value==='hand'?` (${g.players[v.side].counts.hand})`:value==='actions'&&p?.side===v.side?' •':''}</button>)}</nav>
 <div className={'native-play native-tab-'+tab}><section className="native-table" aria-label="Table"><h2>{g.status==='setup'?'Choose your starting location':'The battlefield'}</h2>{g.status==='setup'&&<><p>Each location’s printed Force icons appear beside its legal choice. Starting selections remain private until revealed.</p><div className="native-card-row">{g.setup?.candidates.map(card)}{Object.values(g.setup?.selected||{}).map(card)}</div></>}{!g.locations.length&&g.status!=='setup'&&<p>No locations in play.</p>}<div className="native-card-row">{g.table.filter(c=>!c.location&&!g.locations.includes(c.id)&&!c.coveredBy).map(card)}</div><div className="native-sites" ref={siteStrip}>{g.locations.map(site=>{const c=g.table.find(c=>c.id===site);return <article key={site} className="native-site" data-battle={rules?.battle?.site===site&&rules.battle.stage!=='complete'}><h3>{c?nativeCards.get(c.blueprint)?.name:'Location'}</h3>{c&&premiereSites[c.blueprint]&&<span className="native-force">Dark ✦ {premiereSites[c.blueprint].icons.dark} · Light ✦ {premiereSites[c.blueprint].icons.light}</span>}{rules?.battle?.site===site&&rules.battle.stage!=='complete'&&<b className="native-battle-label">BATTLE · {rules.battle.stage.toUpperCase()}</b>}<div className="native-site-side opponent">{g.table.filter(c=>c.location===site&&c.owner!==v.side&&!c.coveredBy).map(card)}</div>{c&&card(c)}<div className="native-site-side own">{g.table.filter(c=>c.location===site&&c.owner===v.side&&!c.coveredBy).map(card)}</div></article>})}</div>{!!g.buried.length&&<details className="native-panel"><summary>Your buried cards</summary><div className="native-card-row">{g.buried.map(card)}</div></details>}<details className="native-panel native-public-piles"><summary>Public Lost Piles & destiny</summary>{(['dark','light'] as const).map(s=><div key={s}><h3>{sideName(s)}</h3><div className="native-card-row">{g.players[s].lost.map(card)}{g.players[s].destiny.map(card)}</div></div>)}</details></section>
 <aside className="native-actions" aria-label="Actions"><div className="native-panel"><span className="eyebrow">{p?.timing||'RESULT'}</span><h2>{g.status==='finished'?g.result?.winner===v.side?'Victory.':'Until next time.':p?.side===v.side?'Your move.':v.mode==='cpu'?'Computer is considering…':'Your opponent’s move.'}</h2>{g.status==='finished'?<p>{g.result?.reason==='concession'?'The match ended by forfeit.':g.result?.reason==='timeout'?'The losing side ran out of match time.':'The losing side has no Life Force remaining.'}</p>:<><p>{p?.mandatory?'Resolve this required choice.':empty?'No action is available in this opportunity.':'Choose a legal action, or pass when ready.'}</p>{empty&&<div className="native-auto"><span>{paused?'Automatic passing paused':`Passing in ${Math.ceil(remaining)}s`}</span><button onClick={()=>setPaused(!paused)}>{paused?'Resume':'Pause'}</button></div>}{g.turn.phase==='activate'&&g.activation&&<p aria-label="Declared activation">{sideName(g.activation.side)} declared {g.activation.count} Force. {g.activation.count-g.activation.remaining} activated{g.activation.done?' · activation ended':` · ${g.activation.remaining} remaining`}.</p>}{!!g.inserts?.some(x=>x.revealed)&&<section aria-label="Revealed inserts"><h3>Insert revealed</h3><p>Resolve this insert and its responses before continuing.</p><div className="native-card-row">{g.inserts.filter(x=>x.revealed).map(x=>card(x.card))}</div></section>}<div className="native-choices">{p?.choices.map(choice=><button key={choice.id} className="native-choice" disabled={blocked} onClick={()=>conn.current?.choose(choice.id,v.revision)}><strong>{choice.id==='pass'&&empty?'Pass empty opportunity':choice.label}</strong>{choice.forceIcons&&<span className="native-force">Dark ✦ {choice.forceIcons.dark} <i/> Light ✦ {choice.forceIcons.light}</span>}</button>)}</div></>}
 {scan&&<section className="native-inspection"><h3>{scan.stage==='peek'?'Hand inspection':'Revealed choices'}</h3>{scan.stage==='peek'&&<p>Choose Finish viewing when you’re ready.</p>}<div className="native-card-row">{scan.cards.map(card)}</div></section>}{!!rules?.peek?.length&&<section><h3>Look at these cards</h3>{!!rules.peekSelected?.length&&<p>First card selected for the Lost Pile: {nativeCards.get(rules.peekSelected[0].blueprint)?.name}. Choose the second card to place on top of it.</p>}<div className="native-card-row">{rules.peek.map(card)}</div>{!!rules.peekInserts?.length&&<><h4>Inserts passed during this peek</h4><p>These do not resolve while peeking. Returned cards go above them.</p><div className="native-card-row">{rules.peekInserts.map(card)}</div></>}</section>}{!!rules?.scavenge?.cards.length&&<section><h3>Revealed Used Pile</h3><div className="native-card-row">{rules.scavenge.cards.map(card)}</div></section>}{!!rules?.searchCards?.length&&<section><h3>Search revealed cards</h3><div className="native-card-row">{rules.searchCards.map(card)}</div></section>}{!!rules?.retrievedCards?.length&&<section><h3>Retrieved cards</h3><div className="native-card-row">{rules.retrievedCards.map(card)}</div></section>}
 </div>{g.status!=='finished'&&<button className="native-concede" disabled={state.busy||!!state.pending} onClick={()=>setConcede(true)}>Forfeit match</button>}</aside><section className="native-hand" aria-label="Your hand"><h2>Your hand <small>{g.players[v.side].counts.hand} cards</small></h2><div className="native-card-row">{g.players[v.side].hand.map(card)}</div></section></div></>}
 </main>{report&&<a className="report-return" href="http://localhost:4189">Progress Report ↗</a>}
 <Dialog open={!!printed} onOpenChange={open=>{if(!open)setInspect(null)}}><DialogContent className="printed-inspect"><DialogTitle>{printed?.name}</DialogTitle><DialogDescription>Printed card reference. Legal actions come from the match’s rules.</DialogDescription>{printed&&<div className="printed-body"><div className="printed-scan"><img src={printed.image} alt={printed.name}/></div><div><p className="printed-text">{printed.text}</p>{inspected&&premiereSites[inspected.blueprint]&&<p className="native-force">Dark ✦ {premiereSites[inspected.blueprint].icons.dark} · Light ✦ {premiereSites[inspected.blueprint].icons.light}</p>}<dl className="printed-stats">{Object.entries(printed.stats).map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl></div></div>}</DialogContent></Dialog>
 <Dialog open={concede} onOpenChange={setConcede}><DialogContent><DialogTitle>Forfeit this match?</DialogTitle><DialogDescription>Your opponent wins immediately. This cannot be undone.</DialogDescription><button className="button primary" disabled={state.busy} onClick={()=>{setConcede(false);void conn.current?.choose('concede')}}>Confirm forfeit</button><button className="button" onClick={()=>setConcede(false)}>Keep playing</button></DialogContent></Dialog>
 </div>;
}
