'use client';
import {useEffect,useState} from 'react';
import type {SealedView} from '@/lib/native-sealed';
import type {Side} from '@/lib/native-engine/types';
import {matchRequest} from '@/lib/native-engine/client';
import {nativeCards} from './cards';
const storage=()=>{try{return sessionStorage}catch{return undefined}};
export function SealedLibrary({onBuild}:{onBuild:(pool:SealedView)=>void}){
 const [pools,setPools]=useState<SealedView[]>([]),[selected,setSelected]=useState<SealedView|null>(null),[side,setSide]=useState<Side>('light'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<{id:string;side:Side}|null>(null),[invite,setInvite]=useState<{id:string;inviteToken:string}|null>(null);
 const accept=(p:SealedView)=>{setSelected(p);setPools(ps=>[p,...ps.filter(x=>x.id!==p.id)]);const url=new URL(location.href);url.searchParams.set('sealed',p.id);history.replaceState(history.state,'',url.pathname+url.search+url.hash)};
 useEffect(()=>{
  const url=new URL(location.href),id=url.searchParams.get('sealed'),token=new URLSearchParams(url.hash.slice(1)).get('sealedInvite');
  try{const draft=JSON.parse(storage()?.getItem('native-sealed-create')||'null');if(draft?.id&&['light','dark'].includes(draft.side))setPending(draft);const incoming=token&&id?{id,inviteToken:token}:JSON.parse(storage()?.getItem('native-sealed-invite')||'null');if(incoming?.id&&incoming?.inviteToken){setInvite(incoming);storage()?.setItem('native-sealed-invite',JSON.stringify(incoming))}}catch{}
  void matchRequest<{pools:SealedView[]}>('/api/sealed-pools').then(r=>{setPools(r.pools);const p=r.pools.find(p=>p.id===id);if(p){setSelected(p);setInvite(null)}}).catch(e=>setError(e.message));
 },[]);
 useEffect(()=>{if(!selected||selected.opponentReady||busy)return;const timer=setTimeout(()=>{void matchRequest<SealedView>('/api/sealed-pools/'+selected.id).then(p=>{setSelected(p);setPools(ps=>ps.map(x=>x.id===p.id?p:x))}).catch(e=>setError(e.message))},3000);return()=>clearTimeout(timer)},[selected,busy]);
 const open=async()=>{if(busy)return;setBusy(true);setError('');const request=pending??{id:crypto.randomUUID(),side};setPending(request);try{storage()?.setItem('native-sealed-create',JSON.stringify(request))}catch{}try{accept(await matchRequest<SealedView>('/api/sealed-pools',request));setPending(null);storage()?.removeItem('native-sealed-create')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const join=async()=>{if(busy||!invite)return;setBusy(true);setError('');try{accept(await matchRequest<SealedView>('/api/sealed-pools/'+invite.id,{inviteToken:invite.inviteToken}));setInvite(null);storage()?.removeItem('native-sealed-invite');const url=new URL(location.href);url.hash='';history.replaceState(history.state,'',url.pathname+url.search)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const copy=async()=>{if(!selected?.inviteToken)return;const url=new URL(location.href);url.pathname='/matches';url.searchParams.set('sealed',selected.id);url.hash=new URLSearchParams({sealedInvite:selected.inviteToken}).toString();try{await navigator.clipboard.writeText(url.href);setNotice('Private sealed invitation copied.')}catch{setNotice(url.href)}};
 return <section className="native-panel native-sealed" aria-label="Sealed play"><span className="eyebrow">UNOPENED POSSIBILITIES</span><h2>Make the most of your delivery.</h2><p>OTSD sealed · 40-card decks. Each player contributes one digital box: 18 premium cards, four Premiere boosters and one A New Hope booster. Both boxes stay hidden until a friend joins; off-side cards are exchanged automatically.</p><p className="native-muted">Build a 40-card deck from your pool, then choose OTSD sealed in the match lobby. Matches unlock when every selected card’s rules are verified.</p>
 {error&&<p role="alert" className="native-error">{error}</p>}{notice&&<p role="status" className="native-notice">{notice}</p>}
 {invite?<div className="native-sealed-invite"><h3>Your sealed seat is waiting.</h3><p>Joining opens both boxes and gives each player only their assigned side’s cards.</p><button className="button primary" disabled={busy} onClick={join}>Join sealed table</button></div>:<div className="native-tools"><label>Your sealed side<select aria-label="Your sealed side" value={side} disabled={busy||!!pending} onChange={e=>setSide(e.target.value as Side)}><option value="light">Light side</option><option value="dark">Dark side</option></select></label><button className="button" disabled={busy} onClick={open}>{pending?'Recover sealed table':'Create sealed table'}</button></div>}
 {!!pools.length&&<label className="native-sealed-select">Your sealed tables<select aria-label="Your sealed tables" value={selected?.id??''} onChange={e=>accept(pools.find(p=>p.id===e.target.value)!)}><option value="" disabled>Choose a table</option>{pools.map(p=><option key={p.id} value={p.id}>{p.side==='light'?'Light':'Dark'} · {p.opponentReady?p.cards.length+' cards':'Waiting for opponent'} · {new Date(p.created).toLocaleDateString()}</option>)}</select></label>}
 {selected&&!selected.opponentReady&&<div className="native-sealed-delivery"><h3>Two boxes. One unopened table.</h3><p>Invite your opponent to reveal the products and complete the private exchange.</p><button className="button primary" onClick={copy}>Copy sealed invitation</button></div>}
 {selected?.opponentReady&&<div className="native-sealed-delivery"><h3>Your {selected.side==='light'?'Light':'Dark'} side pool · {selected.cards.length} cards</h3><p>The exchange is complete. Your opponent’s cards remain private. Build only with copies in this pool.</p><button className="button primary" onClick={()=>{onBuild(selected);document.getElementById('native-decks')?.scrollIntoView({behavior:'smooth',block:'start'})}}>Build from this pool</button><details><summary>Inspect your delivery by pack</summary>{selected.packs.map((pack,i)=><details key={i}><summary>{pack.name} · {pack.cards.length} cards for your side</summary><ul>{pack.cards.map((bp,j)=><li key={j}>{nativeCards.get(bp)?.name??bp}</li>)}</ul></details>)}</details></div>}
 <a className="native-muted" href="https://res.starwarsccg.org/wp/wp-content/uploads/Alternate-Formats-Guide.pdf" target="_blank" rel="noreferrer">Official sealed format guide ↗</a>
 </section>;
}
