package com.gempukku.swccgo.rules.devices;
import com.gempukku.swccgo.common.*;
import com.gempukku.swccgo.framework.*;
import com.gempukku.swccgo.game.*;
import com.google.gson.GsonBuilder;
import org.junit.Test;
import org.junit.AfterClass;
import java.nio.file.*;
import java.util.*;
import static org.junit.Assert.*;
public class NativeEngineObiWanOracleTests {
 static final List<Map<String,Object>> rows=new ArrayList<>();
 @AfterClass public static void output()throws Exception{Files.writeString(Path.of("/opt/gemp-swccg/obi-wan-results.json"),new GsonBuilder().setPrettyPrinting().create().toJson(rows));}
 void pass(VirtualTableScenario s){if(s.GetCurrentDecision().getText().equalsIgnoreCase("Choose card to put on Lost Pile")){s.PlayerDecided(s.GetDecidingPlayer(),s.GetCurrentDecision().getDecisionParameters().get("cardId")[0]);}else s.PlayerPass(s.GetDecidingPlayer());}
 boolean offered(VirtualTableScenario s,PhysicalCardImpl obi){return s.GetDecidingPlayer().equals(VirtualTableScenario.LS)&&s.GetCurrentDecision().getDecisionParameters().containsKey("actionId")&&s.LSCardActionAvailable(obi,"Make a character");}
 VirtualTableScenario fixture(String mode){var ls=new HashMap<String,String>(Map.of("obi","1_21","adj","1_132","troop","1_28"));var ds=new HashMap<String,String>(Map.of("target",mode.equals("guard")?"1_181":mode.equals("ability-two")?"1_173":"1_194","second","1_194","gun","1_315"));var s=new VirtualTableScenario(ls,ds,40,40,StartingSetup.LSStartingLocation("1_129"),StartingSetup.DSStartingLocation("1_284"),StartingSetup.NoLSStartingInterrupts,StartingSetup.NoDSStartingInterrupts,StartingSetup.NoLSShields,StartingSetup.NoDSShields,VirtualTableScenario.Open);s.StartGame();s.DSActivateForceCheat(12);s.LSActivateForceCheat(12);var site=s.GetLSStartingLocation();s.MoveCardsToLocation(site,s.GetLSCard("obi"),s.GetDSCard("target"));if(!mode.equals("last")&&!mode.equals("ability-two"))s.MoveCardsToLocation(site,s.GetDSCard("second"));if(!mode.equals("no-adj"))s.MoveLocationToTable(s.GetLSCard("adj"));if(mode.equals("attachments")||mode.equals("lose"))s.AttachCardsTo(s.GetDSCard("target"),s.GetDSCard("gun"));if(mode.equals("own")){s.SkipToLSTurn(Phase.BATTLE);s.LSInitiateBattle(site);}else{s.SkipToDSTurn(Phase.BATTLE);s.DSInitiateBattle(site);}return s;}
 @Test public void eligibility(){for(String mode:List.of("no-adj","ability-two")){var s=fixture(mode);if(mode.equals("ability-two"))s.MoveCardsToDSHand(s.GetDSCard("second"));boolean seen=false;for(int i=0;i<100&&!s.AwaitingLSWeaponsSegmentActions()&&!s.AwaitingDSWeaponsSegmentActions();i++){if(offered(s,s.GetLSCard("obi")))seen=true;pass(s);}rows.add(Map.of("mode",mode,"offered",seen));}}
 @Test public void outcomes(){for(String mode:List.of("move","own","lose","guard","attachments","source-left","last")){System.out.println("MODE "+mode);var s=fixture(mode);var obi=s.GetLSCard("obi");var target=s.GetDSCard("target");var adj=s.GetLSCard("adj");for(int i=0;i<100&&!offered(s,obi);i++)pass(s);assertTrue(offered(s,obi));int light=s.GetLSForcePileCount(),dark=s.GetDSForcePileCount();s.LSUseCardAction(obi,"Make a character");s.LSChooseCard(target);if(mode.equals("source-left"))s.MoveCardsToLSHand(obi);boolean choice=false;for(int i=0;i<150&&!s.GetDSLostPile().contains(target)&&target.getAtLocation()!=adj;i++){String text=s.GetCurrentDecision().getText().toLowerCase();System.out.println(text);if(text.startsWith("do you want to have ")&&text.contains("move away")){choice=true;if(mode.equals("lose"))s.DSChooseNo();else s.DSChooseYes();}else if(text.contains("where to move"))s.DSChooseCard(adj);else pass(s);}assertTrue(s.GetDSLostPile().contains(target)||target.getAtLocation()==adj);rows.add(Map.of("mode",mode,"offered",true,"choice",choice,"lightCost",light-s.GetLSForcePileCount(),"darkCost",dark-s.GetDSForcePileCount(),"moved",target.getAtLocation()==adj,"lost",s.GetDSLostPile().contains(target),"gunLost",s.GetDSLostPile().contains(s.GetDSCard("gun")),"gunMoved",s.GetDSCard("gun").getAttachedTo()==target&&target.getAtLocation()==adj));}}
 @Test public void deployment(){var s=fixture("move");var obi=s.GetLSCard("obi");s.MoveCardsToLSHand(obi);s.SkipToLSTurn(Phase.DEPLOY);int before=s.GetLSForcePileCount();s.LSDeployCard(obi);s.LSChooseCard(s.GetLSStartingLocation());for(int i=0;i<100&&obi.getZone()!=Zone.AT_LOCATION;i++)pass(s);assertEquals(Zone.AT_LOCATION,obi.getZone());rows.add(Map.of("mode","deploy","cost",before-s.GetLSForcePileCount(),"immunity",s.game().getModifiersQuerying().getImmunityToAttritionLessThan(s.gameState(),obi)));}
}
