package com.gempukku.swccgo.rules.devices;
import com.gempukku.swccgo.common.*;
import com.gempukku.swccgo.framework.*;
import com.gempukku.swccgo.game.*;
import com.google.gson.GsonBuilder;
import org.junit.Test;
import org.junit.AfterClass;
import java.nio.file.*;
import java.util.*;
import static org.junit.Assert.*;
public class NativeEngineWrongTurnOracleTests {
 static final List<Map<String,Object>> rows=new ArrayList<>();
 @AfterClass public static void output()throws Exception{Files.writeString(Path.of("/opt/gemp-swccg/wrong-turn-results.json"),new GsonBuilder().setPrettyPrinting().create().toJson(rows));}
 void pass(VirtualTableScenario s){System.out.println("PASS "+s.GetDecidingPlayer()+" "+s.GetCurrentDecision().getText()+" "+s.GetCurrentDecision().getDecisionParameters());s.PlayerPass(s.GetDecidingPlayer());}
 VirtualTableScenario fixture(){var ls=new HashMap<String,String>(Map.of("hero","1_19","troop","1_28","droid","1_6","sky","1_110","tank","3_32"));var ds=new HashMap<String,String>(Map.of("wrong","1_232","bad","4_116","troop","1_194","boring","1_235"));var s=new VirtualTableScenario(ls,ds,40,40,StartingSetup.LSStartingLocation("1_132"),StartingSetup.DSStartingLocation("1_284"),StartingSetup.NoLSStartingInterrupts,StartingSetup.NoDSStartingInterrupts,StartingSetup.NoLSShields,StartingSetup.NoDSShields,VirtualTableScenario.Open);s.StartGame();s.DSActivateForceCheat(12);s.LSActivateForceCheat(12);s.MoveCardsToHand(s.GetDSCard("wrong"),s.GetDSCard("boring"),s.GetLSCard("sky"),s.GetLSCard("hero"));s.SkipToDSTurn(Phase.DEPLOY);return s;}
 @Test public void attributes(){for(String zone:List.of("hand","lost","table")){var s=fixture();var wrong=s.GetDSCard("wrong");var hero=s.GetLSCard("hero");if(zone.equals("lost"))s.MoveCardsToTopOfOwnLostPile(hero);if(zone.equals("table"))s.MoveCardsToLocation(s.GetLSStartingLocation(),hero);s.MoveCardsToLSSideOfTable(wrong);var q=s.game().getModifiersQuerying();float on=q.getDeployCost(s.gameState(),hero);s.MoveCardsToLSSideOfTable(s.GetDSCard("bad"));float combined=q.getDeployCost(s.gameState(),hero);s.MoveCardsToDSHand(wrong);float off=q.getDeployCost(s.gameState(),hero);rows.add(Map.of("mode","attribute-"+zone,"on",on,"combined",combined,"afterRemoval",off));}}
 @Test public void unaffected(){var s=fixture();s.MoveCardsToLSSideOfTable(s.GetDSCard("wrong"));var q=s.game().getModifiersQuerying();rows.add(Map.of("mode","types","warrior",q.getDeployCost(s.gameState(),s.GetLSCard("troop")),"droid",q.getDeployCost(s.gameState(),s.GetLSCard("droid")),"ownWarrior",q.getDeployCost(s.gameState(),s.GetDSCard("troop"))));}
 @Test public void cancellations(){for(String mode:List.of("pending","table","countered")){System.out.println("MODE "+mode);var s=fixture();var wrong=s.GetDSCard("wrong");var sky=s.GetLSCard("sky");var boring=s.GetDSCard("boring");int before=s.GetDSForcePileCount();s.DSDeployCard(wrong);if(!mode.equals("pending")){for(int i=0;i<100&&wrong.getZone()!=Zone.SIDE_OF_TABLE;i++)pass(s);assertEquals(Zone.SIDE_OF_TABLE,wrong.getZone());}for(int i=0;i<100&&!(s.GetDecidingPlayer().equals(VirtualTableScenario.LS)&&s.GetCurrentDecision().getDecisionParameters().containsKey("actionId")&&s.LSCardActionAvailable(sky,"Cancel"));i++)pass(s);s.LSUseCardAction(sky,"Cancel");if(!mode.equals("pending"))s.LSChooseCard(wrong);if(mode.equals("countered")){for(int i=0;i<100&&!(s.GetDecidingPlayer().equals(VirtualTableScenario.DS)&&s.GetCurrentDecision().getDecisionParameters().containsKey("actionId")&&s.DSCardActionAvailable(boring,"Cancel"));i++)pass(s);s.DSUseCardAction(boring,"Cancel");}for(int i=0;i<100&&!s.GetLSLostPile().contains(sky);i++)pass(s);assertTrue(s.GetLSLostPile().contains(sky));for(int i=0;i<30&&mode.equals("countered")&&!s.GetDSUsedPile().contains(boring);i++)pass(s);rows.add(Map.of("mode",mode,"cost",before-s.GetDSForcePileCount(),"wrongLost",s.GetDSLostPile().contains(wrong),"skyLost",s.GetLSLostPile().contains(sky),"boringUsed",s.GetDSUsedPile().contains(boring),"heroDeploy",s.game().getModifiersQuerying().getDeployCost(s.gameState(),s.GetLSCard("hero"))));}}
 @Test public void actualDeployment(){var s=fixture();var wrong=s.GetDSCard("wrong");int before=s.GetDSForcePileCount();s.DSDeployCard(wrong);for(int i=0;i<100&&wrong.getZone()!=Zone.SIDE_OF_TABLE;i++)pass(s);assertEquals(Zone.SIDE_OF_TABLE,wrong.getZone());int cost=before-s.GetDSForcePileCount();s.MoveCardsToLSHand(s.GetLSCard("troop"));s.SkipToLSTurn(Phase.DEPLOY);before=s.GetLSForcePileCount();s.LSDeployCard(s.GetLSCard("troop"));s.LSChooseCard(s.GetLSStartingLocation());for(int i=0;i<100&&s.GetLSCard("troop").getZone()!=Zone.AT_LOCATION;i++)pass(s);assertEquals(Zone.AT_LOCATION,s.GetLSCard("troop").getZone());rows.add(Map.of("mode","deployment","effectCost",cost,"troopCost",before-s.GetLSForcePileCount()));}
 @Test public void patient(){var s=fixture();var tank=s.GetLSCard("tank");var hero=s.GetLSCard("hero");s.MoveCardsToLSSideOfTable(tank,s.GetDSCard("wrong"),s.GetDSCard("bad"));s.StackCardsOn(tank,hero);s.SkipToLSTurn(Phase.DEPLOY);for(int i=0;i<100&&!(s.GetDecidingPlayer().equals(VirtualTableScenario.LS)&&s.GetCurrentDecision().getDecisionParameters().containsKey("actionId")&&s.LSCardActionAvailable(tank,"Take"));i++)pass(s);int before=s.GetLSForcePileCount();s.LSUseCardAction(tank,"Take");for(int i=0;i<100&&!s.GetLSHand().contains(hero);i++)pass(s);assertTrue(s.GetLSHand().contains(hero));rows.add(Map.of("mode","patient","cost",before-s.GetLSForcePileCount()));}
}
