package com.gempukku.swccgo.rules.devices;
import com.gempukku.swccgo.common.*;
import com.gempukku.swccgo.framework.*;
import com.gempukku.swccgo.game.*;
import com.google.gson.GsonBuilder;
import org.junit.Test;
import org.junit.AfterClass;
import java.nio.file.*;
import java.util.*;
import static org.junit.Assert.*;
public class NativeEngineDeployCostOracleTests {
 static final List<Map<String,Object>> rows=new ArrayList<>();
 @AfterClass public static void output() throws Exception{Files.writeString(Path.of("/opt/gemp-swccg/deploy-cost-results.json"),new GsonBuilder().setPrettyPrinting().create().toJson(rows));}
 void pass(VirtualTableScenario s){try{if(s.GetCurrentDecision().getText().toLowerCase().contains("battle destiny?"))s.PlayerChooseNo(s.GetDecidingPlayer());else s.PlayerPass(s.GetDecidingPlayer());}catch(RuntimeException e){throw new AssertionError(s.GetDecidingPlayer()+" "+s.GetCurrentDecision().getText()+" "+s.GetCurrentDecision().getDecisionParameters(),e);}}
 VirtualTableScenario fixture(String bp){var ls=new HashMap<>(Map.of("hero",bp.equals("5_99")?"1_19":bp,"fx","3_9","fx2","3_9","lab","3_60","tank","3_32","trooper","1_28","feeling","1_91"));var ds=new HashMap<>(Map.of("bad","4_116","hero","5_99","trooper","1_194"));for(int i=0;i<8;i++)ds.put("enemy"+i,"1_194");var s=new VirtualTableScenario(ls,ds,18,18,StartingSetup.LSStartingLocation("1_129"),StartingSetup.DSStartingLocation("1_284"),StartingSetup.NoLSStartingInterrupts,StartingSetup.NoDSStartingInterrupts,StartingSetup.NoLSShields,StartingSetup.NoDSShields,VirtualTableScenario.Open);s.StartGame();s.SkipToPhase(Phase.CONTROL);s.LSActivateForceCheat(12);s.DSActivateForceCheat(12);return s;}
 @Test public void globalQueries(){for(String bp:new String[]{"1_19","101_2","1_11","1_21","4_2","5_5","5_99"})for(String zone:new String[]{"hand","lost","table"}){var s=fixture(bp);var h=bp.equals("5_99")?s.GetDSCard("hero"):s.GetLSCard("hero");if(zone.equals("hand"))s.MoveCardsToHand(h);else if(zone.equals("lost"))s.MoveCardsToTopOfLostPile(h.getOwner(),h);else s.MoveCardsToLocation(s.GetLSStartingLocation(),h);var bad=s.GetDSCard("bad");s.MoveCardsToLSSideOfTable(bad);float on=s.game().getModifiersQuerying().getDeployCost(s.gameState(),h);s.MoveCardsToDSHand(bad);float off=s.game().getModifiersQuerying().getDeployCost(s.gameState(),h);rows.add(Map.of("name","query-"+bp+"-"+zone,"on",on,"off",off));}}
 @Test public void actualDeployment(){var s=fixture("101_2");s.MoveCardsToDSHand(s.GetDSCard("bad"));s.SkipToPhase(Phase.DEPLOY);int before=s.GetDSForcePileCount();s.DSDeployCard(s.GetDSCard("bad"));for(int i=0;i<80&&s.GetDSCard("bad").getZone()!=Zone.SIDE_OF_TABLE;i++)pass(s);assertEquals(Zone.SIDE_OF_TABLE,s.GetDSCard("bad").getZone());int effectCost=before-s.GetDSForcePileCount();s.MoveCardsToLSHand(s.GetLSCard("hero"));s.SkipToLSTurn(Phase.DEPLOY);before=s.GetLSForcePileCount();s.LSDeployCard(s.GetLSCard("hero"));s.LSChooseCard(s.GetLSStartingLocation());for(int i=0;i<80&&s.GetLSCard("hero").getZone()!=Zone.AT_LOCATION;i++)pass(s);rows.add(Map.of("name","deployment","effectCost",effectCost,"heroCost",before-s.GetLSForcePileCount()));}
 @Test public void medicalDeployment(){var s=fixture("1_19");PhysicalCardImpl lab=s.GetLSCard("lab"),fx=s.GetLSCard("fx"),second=s.GetLSCard("fx2");s.MoveLocationToTable(lab);s.MoveCardsToLSHand(fx,second);s.SkipToLSTurn(Phase.DEPLOY);int before=s.GetLSForcePileCount();s.LSDeployCard(fx);s.LSChooseCard(s.GetLSStartingLocation());for(int i=0;i<80&&fx.getZone()!=Zone.AT_LOCATION;i++)pass(s);int first=before-s.GetLSForcePileCount();for(int i=0;i<80&&!(s.GetDecidingPlayer().equals(VirtualTableScenario.LS)&&s.GetCurrentDecision().getDecisionParameters().containsKey("actionId")&&s.LSDeployAvailable(second));i++)pass(s);before=s.GetLSForcePileCount();s.LSDeployCard(second);s.LSChooseCard(lab);for(int i=0;i<80&&second.getZone()!=Zone.AT_LOCATION;i++)pass(s);rows.add(Map.of("name","medical","first",first,"second",before-s.GetLSForcePileCount()));}
 @Test public void patients(){for(int fxCount:new int[]{0,1,2}){var s=fixture("1_19");PhysicalCardImpl tank=s.GetLSCard("tank"),hero=s.GetLSCard("hero");s.MoveCardsToLSSideOfTable(tank,s.GetDSCard("bad"));s.StackCardsOn(tank,hero);s.MoveLocationToTable(s.GetLSCard("lab"));if(fxCount>0)s.MoveCardsToLocation(s.GetLSStartingLocation(),s.GetLSCard("fx"));if(fxCount>1)s.MoveCardsToLocation(s.GetDSStartingLocation(),s.GetLSCard("fx2"));s.SkipToLSTurn(Phase.DEPLOY);for(int i=0;i<80&&!(s.GetDecidingPlayer().equals(VirtualTableScenario.LS)&&s.GetCurrentDecision().getDecisionParameters().containsKey("actionId")&&s.LSCardActionAvailable(tank,"Take"));i++)pass(s);int before=s.GetLSForcePileCount();s.LSUseCardAction(tank,"Take");for(int i=0;i<80&&!s.GetLSHand().contains(hero);i++)pass(s);assertTrue(s.GetLSHand().contains(hero));rows.add(Map.of("name","patient-"+fxCount,"cost",before-s.GetLSForcePileCount()));}}
 @Test public void drains(){for(String mode:new String[]{"imperial","alien","contested","empty"}){var s=fixture("1_19");var lab=s.GetLSCard("lab");s.MoveLocationToTable(lab);if(!mode.equals("empty"))s.MoveCardsToLocation(lab,s.GetDSCard(mode.equals("alien")?"hero":"trooper"));if(mode.equals("contested"))s.MoveCardsToLocation(lab,s.GetLSCard("trooper"));rows.add(Map.of("name","drain-"+mode,"amount",s.game().getModifiersQuerying().getForceDrainAmount(s.gameState(),lab,VirtualTableScenario.DS)));}}
 @Test public void playBan(){boolean blocked=false,allowed=false;for(boolean active:new boolean[]{true,false}){var s=fixture("1_19");PhysicalCardImpl site=s.GetLSStartingLocation(),feeling=s.GetLSCard("feeling"),bad=s.GetDSCard("bad");s.MoveCardsToLocation(site,s.GetLSCard("trooper"));for(int i=0;i<8;i++)s.MoveCardsToLocation(site,s.GetDSCard("enemy"+i));if(active)s.MoveCardsToLSSideOfTable(bad);else s.MoveCardsToDSHand(bad);s.MoveCardsToLSHand(feeling);s.SkipToLSTurn(Phase.BATTLE);s.LSInitiateBattle(site);boolean seen=false;for(int i=0;i<80&&!s.AwaitingLSWeaponsSegmentActions()&&!s.AwaitingDSWeaponsSegmentActions();i++){if(s.GetDecidingPlayer().equals(VirtualTableScenario.LS)&&s.GetCurrentDecision().getDecisionParameters().containsKey("actionId")&&s.LSCardPlayAvailable(feeling))seen=true;pass(s);}if(active)blocked=!seen;else allowed=seen;}assertTrue(blocked);assertTrue(allowed);rows.add(Map.of("name","play-ban","blocked",blocked,"allowed",allowed));}
}
