package com.gempukku.swccgo.rules.devices;
import com.gempukku.swccgo.common.*;
import com.gempukku.swccgo.framework.*;
import com.gempukku.swccgo.game.*;
import com.gempukku.swccgo.filters.Filters;
import com.gempukku.swccgo.logic.modifiers.CancelsGameTextModifier;
import com.google.gson.GsonBuilder;
import org.junit.Test;
import org.junit.AfterClass;
import java.nio.file.*;
import java.util.*;
import static org.junit.Assert.*;
/** Component interventions are explicit: prepared board/Force/destiny and
 * removal/cancellation during responses. Deployment and firing use real actions. */
public class NativeEngineBionicHandOracleTests {
 static final List<Map<String,Object>> rows=new ArrayList<>();
 @AfterClass public static void output()throws Exception{Files.writeString(Path.of("/opt/gemp-swccg/bionic-hand-results.json"),new GsonBuilder().setPrettyPrinting().create().toJson(rows));}
 void pass(VirtualTableScenario s){String t=s.GetCurrentDecision().getText();if(t.equalsIgnoreCase("Choose card to put on Lost Pile"))s.PlayerDecided(s.GetDecidingPlayer(),s.GetCurrentDecision().getDecisionParameters().get("cardId")[0]);else s.PlayerPass(s.GetDecidingPlayer());}
 boolean lost(PhysicalCardImpl c){return c.getZone()==Zone.LOST_PILE||c.getZone()==Zone.TOP_OF_LOST_PILE;}
 boolean offered(VirtualTableScenario s,boolean light,PhysicalCardImpl c,String label){return s.GetDecidingPlayer().equals(light?VirtualTableScenario.LS:VirtualTableScenario.DS)&&s.GetCurrentDecision().getDecisionParameters().containsKey("actionId")&&(light?s.LSCardActionAvailable(c,label):s.DSCardActionAvailable(c,label));}
 void ready(VirtualTableScenario s,boolean light,PhysicalCardImpl c,String label){for(int i=0;i<120&&!offered(s,light,c,label);i++)pass(s);assertTrue("Missing "+label+": "+s.GetCurrentDecision().getText(),offered(s,light,c,label));}
 VirtualTableScenario fixture(){var ls=new HashMap<String,String>(Map.of("hand","5_12","target","1_28","gun","1_152","spare","1_152","saber","1_155","die1","1_109","die2","1_109","support","1_28"));var ds=new HashMap<String,String>(Map.of("effect","1_214","second","1_214","target","1_194","gun","1_317"));var s=new VirtualTableScenario(ls,ds,40,40,StartingSetup.LSStartingLocation("1_129"),StartingSetup.DSStartingLocation("1_284"),StartingSetup.NoLSStartingInterrupts,StartingSetup.NoDSStartingInterrupts,StartingSetup.NoLSShields,StartingSetup.NoDSShields,VirtualTableScenario.Open);s.StartGame();s.DSActivateForceCheat(15);s.LSActivateForceCheat(15);var site=s.GetLSStartingLocation();s.MoveCardsToLocation(site,s.GetLSCard("target"),s.GetDSCard("target"));s.AttachCardsTo(s.GetLSCard("target"),s.GetLSCard("gun"));s.AttachCardsTo(s.GetDSCard("target"),s.GetDSCard("gun"));s.MoveCardsToDSHand(s.GetDSCard("effect"),s.GetDSCard("second"));s.MoveCardsToLSHand(s.GetLSCard("hand"));s.SkipToDSTurn(Phase.CONTROL);return s;}
 void disarm(VirtualTableScenario s,String key){var e=s.GetDSCard(key);ready(s,false,e,"Deploy");s.DSDeployCard(e);s.DSChooseCard(s.GetLSCard("target"));for(int i=0;i<120&&!(s.GetLSCard("target").isDisarmed()&&lost(s.GetLSCard("gun"))&&s.GetCurrentDecision().getText().contains("Choose Control action"));i++)pass(s);assertTrue(s.GetLSCard("target").isDisarmed());}
 void hand(VirtualTableScenario s){s.SkipToLSTurn(Phase.DEPLOY);var h=s.GetLSCard("hand");ready(s,true,h,"Deploy");int before=s.GetLSForcePileCount();s.LSDeployCard(h);if(s.GetCurrentDecision().getText().contains("Choose" )&&!s.GetCurrentDecision().getText().contains("responses"))s.LSChooseCard(s.GetLSCard("target"));for(int i=0;i<120&&!(h.getAttachedTo()==s.GetLSCard("target")&&!s.GetLSCard("target").isDisarmed()&&s.GetCurrentDecision().getText().contains("Choose Deploy action"));i++)pass(s);assertFalse(s.GetLSCard("target").isDisarmed());assertEquals(2,before-s.GetLSForcePileCount());}
 @Test public void persistentStatus(){for(String mode:List.of("effect-leaves","effect-canceled","character-leaves")){var s=fixture();disarm(s,"effect");var t=s.GetLSCard("target");if(mode.equals("effect-leaves"))s.MoveCardsToDSHand(s.GetDSCard("effect"));if(mode.equals("effect-canceled")){var e=s.GetDSCard("effect");e.setGameTextCanceled(true);s.game().getModifiersEnvironment().addUntilEndOfTurnModifier(new CancelsGameTextModifier(s.GetDSStartingLocation(),e));}if(mode.equals("character-leaves"))s.MoveCardsToLSHand(t);rows.add(Map.of("mode",mode,"disarmed",t.isDisarmed()));assertEquals(!mode.equals("character-leaves"),t.isDisarmed());}}
 @Test public void rearmAndDisarmAgain(){var s=fixture();disarm(s,"effect");hand(s);var h=s.GetLSCard("hand");var t=s.GetLSCard("target");assertTrue(lost(s.GetDSCard("effect")));assertEquals(2,s.GetPower(t),0.01);rows.add(Map.of("mode","rearmed","disarmed",t.isDisarmed(),"power",s.GetPower(t),"cost",2,"effectLost",true,"protected",s.game().getModifiersQuerying().mayNotRemoveDeviceUnlessDisarmed(s.gameState(),h)));s.AttachCardsTo(t,s.GetLSCard("spare"));s.SkipToDSTurn(Phase.CONTROL);disarm(s,"second");for(int i=0;i<80&&!lost(h);i++)pass(s);assertTrue(lost(h));rows.add(Map.of("mode","disarmed-again","disarmed",t.isDisarmed(),"handLost",lost(h),"gunLost",lost(s.GetLSCard("spare")),"power",s.GetPower(t)));}
 @Test public void totalBonus(){for(String weapon:List.of("spare","saber"))for(String mode:List.of("stay","leave","return","cancel","weapon-cancel")){var s=fixture();disarm(s,"effect");hand(s);var h=s.GetLSCard("hand");var t=s.GetLSCard("target");var w=s.GetLSCard(weapon);s.AttachCardsTo(t,w);s.SkipToLSTurn(Phase.BATTLE);s.LSInitiateBattle(s.GetLSStartingLocation());ready(s,true,w,"Fire");s.MoveCardsToTopOfLSReserveDeck(s.GetLSCard("die1"),s.GetLSCard("die2"));s.LSUseCardAction(w,"Fire");s.LSChooseCard(s.GetDSCard("target"));for(int i=0;i<150&&!s.GetCurrentDecision().getText().contains("DRAWING_DESTINY_COMPLETE");i++)pass(s);assertTrue(s.GetCurrentDecision().getText().contains("DRAWING_DESTINY_COMPLETE"));var effect=s.gameState().getTopDrawDestinyState().getDrawDestinyEffect();float before=effect.getTotalDestiny(s.game());if(mode.equals("leave")||mode.equals("return")){s.MoveCardsToHand(h);if(mode.equals("return"))s.AttachCardsTo(t,h);}if(mode.equals("cancel")||mode.equals("weapon-cancel")){var c=mode.equals("cancel")?h:w;c.setGameTextCanceled(true);s.game().getModifiersEnvironment().addUntilEndOfTurnModifier(new CancelsGameTextModifier(s.GetLSStartingLocation(),c));}float after=effect.getTotalDestiny(s.game());rows.add(Map.of("mode",mode,"weapon",weapon,"before",before,"after",after,"power",s.GetPower(t),"protected",s.game().getModifiersQuerying().mayNotRemoveDeviceUnlessDisarmed(s.gameState(),h)));}}

 @Test public void transferEligibility(){for(boolean canceled:new boolean[]{false,true}){var s=fixture();disarm(s,"effect");hand(s);var h=s.GetLSCard("hand");var support=s.GetLSCard("support");s.MoveCardsToLocation(s.GetLSStartingLocation(),support);support.setDisarmed(true);if(canceled){h.setGameTextCanceled(true);s.game().getModifiersEnvironment().addUntilEndOfTurnModifier(new CancelsGameTextModifier(s.GetLSStartingLocation(),h));}boolean transferable=h.getBlueprint().getTransferDeviceOrWeaponAction(VirtualTableScenario.LS,s.game(),h,false,false,Filters.sameCardId(support))!=null;rows.add(Map.of("mode","transfer","canceled",canceled,"transferable",transferable));}}
}
