package com.gempukku.swccgo.rules.devices;
import com.gempukku.swccgo.common.*;
import com.gempukku.swccgo.framework.*;
import com.gempukku.swccgo.game.*;
import com.google.gson.GsonBuilder;
import org.junit.Test;
import org.junit.AfterClass;
import java.nio.file.*;
import java.util.*;
import static org.junit.Assert.*;
/** Real setup, mobile movement, no-hyperdrive transfers and mounted weapon firing. */
public class NativeEngineMobileSystemsOracleTests {
 static final List<Map<String,Object>> rows=new ArrayList<>();
 @AfterClass public static void output()throws Exception{Files.writeString(Path.of("/opt/gemp-swccg/mobile-systems-results.json"),new GsonBuilder().serializeNulls().setPrettyPrinting().create().toJson(rows));}
 void pass(VirtualTableScenario s){System.out.println("MOBILE "+s.GetDecidingPlayer()+" "+s.GetCurrentDecision().getText()+" "+new GsonBuilder().create().toJson(s.GetCurrentDecision().getDecisionParameters()));s.PlayerPass(s.GetDecidingPlayer());}
 VirtualTableScenario fixture(){var s=new VirtualTableScenario(new HashMap<>(Map.of("ywing","1_147")),new HashMap<>(Map.of("fighter","1_300","pilot","1_179","scout","1_305","gun","1_323","second","1_323","isd","1_302","d1","1_262","d2","1_262")),55,55,StartingSetup.LSStartingLocation("1_135"),StartingSetup.DSStartingLocation("2_143"),StartingSetup.NoLSStartingInterrupts,StartingSetup.NoDSStartingInterrupts,StartingSetup.NoLSShields,StartingSetup.NoDSShields,VirtualTableScenario.Open);s.StartGame();return s;}
 @Test public void starting(){var s=fixture();rows.add(Map.of("mode","setup","first",s.gameState().getCurrentPlayerId().equals(VirtualTableScenario.LS)?"light":"dark","parsec",s.GetDSStartingLocation().getParsec()));}
 @Test public void movement(){for(String mode:List.of("forward","orbit","leave","enter","depart")){
  var s=fixture();var death=s.GetDSStartingLocation();var yavin=s.GetLSStartingLocation();int start=mode.equals("forward")?0:mode.equals("orbit")?3:4;int to=mode.equals("forward")?1:mode.equals("depart")?5:4;boolean orbit=mode.equals("orbit")||mode.equals("enter");death.setParsec(start);if(mode.equals("leave")||mode.equals("depart"))death.setSystemOrbited(yavin.getTitle());s.MoveCardsToLocation(death,s.GetDSCard("scout"),s.GetLSCard("ywing"));s.AttachCardsTo(death,s.GetDSCard("gun"));s.DSActivateForceCheat(10);s.SkipToDSTurn(Phase.MOVE);int before=s.GetDSForcePileCount();assertTrue(s.DSCardActionAvailable(death,"Move using hyperspeed"));s.DSUseCardAction(death,"Move using hyperspeed");s.DSChoose(String.valueOf(to));
  for(int i=0;i<100&&!(death.getParsec()==to&&Objects.equals(death.getSystemOrbited(),orbit?yavin.getTitle():null));i++){if(s.DSDecisionAvailable("Choose destination"))s.DSChoose(orbit?"Orbit "+yavin.getTitle():"Deep Space");else if(s.DSDecisionAvailable("Choose system"))s.DSChooseCard(yavin);else pass(s);}
  assertEquals(to,death.getParsec());assertEquals(orbit?yavin.getTitle():null,death.getSystemOrbited());rows.add(Map.of("mode",mode,"cost",before-s.GetDSForcePileCount(),"parsec",death.getParsec(),"orbit",death.getSystemOrbited()==null?"deep":death.getSystemOrbited(),"darkCarried",s.GetDSCard("scout").getAtLocation()==death,"lightCarried",s.GetLSCard("ywing").getAtLocation()==death,"gunCarried",s.GetDSCard("gun").getAttachedTo()==death,"regularMove",s.game().getModifiersQuerying().hasPerformedRegularMoveThisTurn(death)));
 }}
 @Test public void transfer(){for(boolean out:List.of(true,false)){
  var s=fixture();var death=s.GetDSStartingLocation();var yavin=s.GetLSStartingLocation();death.setParsec(4);death.setSystemOrbited(yavin.getTitle());var ship=s.GetDSCard("fighter");var target=out?yavin:death;s.MoveCardsToLocation(out?death:yavin,ship);s.BoardAsPilot(ship,s.GetDSCard("pilot"));s.DSActivateForceCheat(10);s.SkipToDSTurn(Phase.MOVE);int before=s.GetDSForcePileCount();System.out.println("TRANSFER "+s.GetCurrentDecision().getText()+" "+new GsonBuilder().create().toJson(s.GetCurrentDecision().getDecisionParameters()));s.DSUseCardAction(ship,"Move");
  for(int i=0;i<100&&ship.getAtLocation()!=target;i++){if(s.DSDecisionAvailable("Choose" )&&s.DSHasCardChoiceAvailable(target))s.DSChooseCard(target);else pass(s);}assertEquals(target,ship.getAtLocation());rows.add(Map.of("mode",out?"ship-out":"ship-in","cost",before-s.GetDSForcePileCount(),"arrived",ship.getAtLocation()==target,"regularMove",s.game().getModifiersQuerying().hasPerformedRegularMoveThisTurn(ship)));
 }}
 @Test public void weapon(){var s=fixture();var death=s.GetDSStartingLocation();var gun=s.GetDSCard("gun");var target=s.GetLSCard("ywing");var second=s.GetDSCard("second");s.MoveCardsToLocation(death,s.GetDSCard("scout"),target);s.MoveCardsToDSHand(gun);s.DSActivateForceCheat(12);s.SkipToDSTurn(Phase.DEPLOY);int before=s.GetDSForcePileCount();s.DSDeployCard(gun);for(int i=0;i<100&&gun.getAttachedTo()!=death;i++){if(s.DSDecisionAvailable("Choose where"))s.DSChooseCard(death);else pass(s);}assertEquals(death,gun.getAttachedTo());int deploy=before-s.GetDSForcePileCount();s.AttachCardsTo(death,second);s.SkipToPhase(Phase.BATTLE);s.DSInitiateBattle(death);for(int i=0;i<100&&!(s.GetDecidingPlayer().equals(VirtualTableScenario.DS)&&s.DSCardActionAvailable(gun,"Fire"));i++)pass(s);s.MoveCardsToTopOfDSReserveDeck(s.GetDSCard("d2"),s.GetDSCard("d1"));before=s.GetDSForcePileCount();s.DSUseCardAction(gun,"Fire");s.DSChooseCard(target);for(int i=0;i<150&&!(s.gameState().getWeaponFiringState()==null&&s.GetCurrentDecision().getText().contains("weapons segment"));i++)pass(s);for(int i=0;i<10&&!s.GetDecidingPlayer().equals(VirtualTableScenario.DS);i++)pass(s);rows.add(Map.of("mode","weapon","deploy",deploy,"fire",before-s.GetDSForcePileCount(),"hit",target.isHit(),"secondWeapon",s.DSCardActionAvailable(second,"Fire")));}
}
