package com.gempukku.swccgo.rules.devices;
import com.gempukku.swccgo.common.*;
import com.gempukku.swccgo.framework.*;
import com.gempukku.swccgo.game.*;
import com.google.gson.GsonBuilder;
import org.junit.Test;
import org.junit.AfterClass;
import java.nio.file.*;
import java.util.*;
import static org.junit.Assert.*;
public class NativeEngineProtocolOracleTests {
 static final String LS=VirtualTableScenario.LS,DS=VirtualTableScenario.DS;
 static final List<Map<String,Object>> rows=new ArrayList<>();
 @AfterClass public static void output() throws Exception{Files.writeString(Path.of("/opt/gemp-swccg/protocol-results.json"),new GsonBuilder().setPrettyPrinting().create().toJson(rows));}
 void pass(VirtualTableScenario s){try{if(s.GetCurrentDecision().getText().toLowerCase().contains("battle destiny?"))s.PlayerChooseNo(s.GetDecidingPlayer());else s.PlayerPass(s.GetDecidingPlayer());}catch(RuntimeException e){throw new AssertionError(s.GetDecidingPlayer()+" "+s.GetCurrentDecision().getText()+" "+s.GetCurrentDecision().getDecisionParameters(),e);}}
 VirtualTableScenario fixture(){var ls=new HashMap<>(Map.of("c3po","1_5","r2","2_14","alien","1_30"));for(int i=0;i<4;i++){ls.put("rebel"+i,"1_28");ls.put("droid"+i,"3_9");}var ds=new HashMap<>(Map.of("droid","3_86","barrier","1_249"));for(int i=0;i<18;i++)ds.put("enemy"+i,"1_194");var s=new VirtualTableScenario(ls,ds,30,30,StartingSetup.LSStartingLocation("1_129"),StartingSetup.DSStartingLocation("1_284"),StartingSetup.NoLSStartingInterrupts,StartingSetup.NoDSStartingInterrupts,StartingSetup.NoLSShields,StartingSetup.NoDSShields,VirtualTableScenario.Open);s.StartGame();s.SkipToPhase(Phase.CONTROL);s.LSActivateForceCheat(12);s.DSActivateForceCheat(12);return s;}
 float total(VirtualTableScenario s){return s.game().getModifiersQuerying().getTotalPowerAtLocation(s.gameState(),s.GetLSStartingLocation(),LS,s.gameState().getBattleState()!=null,false);}
 float fv(VirtualTableScenario s){return s.game().getModifiersQuerying().getForfeit(s.gameState(),s.GetLSCard("r2"));}
 @Test public void pairs(){for(int d=1;d<=4;d++)for(int r=0;r<=4;r++){var s=fixture();var site=s.GetLSStartingLocation();s.MoveCardsToLocation(site,s.GetLSCard("c3po"));if(d>=2)s.MoveCardsToLocation(site,s.GetLSCard("r2"));for(int i=2;i<d;i++)s.MoveCardsToLocation(site,s.GetLSCard("droid"+i));for(int i=0;i<r;i++)s.MoveCardsToLocation(site,s.GetLSCard("rebel"+i));rows.add(Map.of("name","pairs-"+d+"-"+r,"total",total(s),"individual",s.GetPower(s.GetLSCard("c3po"))));}}
 @Test public void locality(){for(String mode:List.of("same","source-other","target-other","source-hand","target-hand","opposing-droid","alien","source-return")){var s=fixture();var site=s.GetLSStartingLocation();PhysicalCardImpl c=s.GetLSCard("c3po"),r=s.GetLSCard("r2");s.MoveCardsToLocation(site,c,r,s.GetLSCard("rebel0"),s.GetLSCard("rebel1"));if(mode.equals("source-other"))s.MoveCardsToLocation(s.GetDSStartingLocation(),c);if(mode.equals("target-other"))s.MoveCardsToLocation(s.GetDSStartingLocation(),r);if(mode.equals("source-hand"))s.MoveCardsToHand(c);if(mode.equals("target-hand"))s.MoveCardsToHand(r);if(mode.equals("opposing-droid")){s.MoveCardsToLocation(s.GetDSStartingLocation(),r);s.MoveCardsToLocation(site,s.GetDSCard("droid"));}if(mode.equals("alien")){s.MoveCardsToHand(s.GetLSCard("rebel1"));s.MoveCardsToLocation(site,s.GetLSCard("alien"));}if(mode.equals("source-return")){s.MoveCardsToHand(c);s.MoveCardsToLocation(site,c);}rows.add(Map.of("name",mode,"total",total(s),"forfeit",fv(s)));}}
 @Test public void forfeiture(){for(boolean sourceFirst:List.of(false,true)){var s=fixture();var site=s.GetLSStartingLocation();PhysicalCardImpl c=s.GetLSCard("c3po"),r=s.GetLSCard("r2");s.MoveCardsToLocation(site,c,r,s.GetLSCard("rebel0"),s.GetLSCard("rebel1"));for(int i=0;i<18;i++)s.MoveCardsToLocation(site,s.GetDSCard("enemy"+i));s.SkipToPhase(Phase.BATTLE);s.DSInitiateBattle(site);s.SkipToEndOfPowerSegment(false);int power=s.GetLSTotalPower();s.PassResponses("INITIAL_ATTRITION_CALCULATED");for(int i=0;i<80&&!s.AwaitingLSBattleDamagePayment();i++)pass(s);if(sourceFirst){s.LSChooseCard(c);for(int i=0;i<80&&!s.GetLSLostPile().contains(c);i++)pass(s);for(int i=0;i<80&&!s.AwaitingLSBattleDamagePayment();i++)pass(s);}int before=s.GetUnpaidLSBattleDamage();float forfeit=fv(s);s.LSChooseCard(r);for(int i=0;i<80&&!s.GetLSLostPile().contains(r);i++)pass(s);rows.add(Map.of("name","forfeit-"+sourceFirst,"power",power,"forfeit",forfeit,"paid",before-s.GetUnpaidLSBattleDamage()));}}
 @Test public void deploymentAndBarrier(){for(boolean barrier:List.of(false,true)){var s=fixture();var site=s.GetLSStartingLocation();PhysicalCardImpl c=s.GetLSCard("c3po"),r=s.GetLSCard("r2"),b=s.GetDSCard("barrier");s.MoveCardsToLocation(site,r,s.GetLSCard("rebel0"),s.GetLSCard("rebel1"));for(int i=0;i<18;i++)s.MoveCardsToLocation(site,s.GetDSCard("enemy"+i));s.MoveCardsToHand(c,b);s.SkipToLSTurn(Phase.DEPLOY);int before=s.GetLSForcePileCount();s.LSDeployCard(c);s.LSChooseCard(site);boolean used=false;for(int i=0;i<100;i++){if(s.GetDecidingPlayer().equals(DS)&&s.GetCurrentDecision().getDecisionParameters().containsKey("actionId")&&s.DSCardPlayAvailable(b)){if(barrier){s.DSPlayCard(b);used=true;}else pass(s);break;}pass(s);}if(barrier)assertTrue(used);s.SkipToPhase(Phase.BATTLE);float outside=total(s);s.LSInitiateBattle(site);s.SkipToEndOfPowerSegment(false);for(int i=0;i<100&&!s.GetCurrentDecision().getText().startsWith("INITIAL_ATTRITION_CALCULATED");i++)pass(s);assertTrue(s.GetCurrentDecision().getText().startsWith("INITIAL_ATTRITION_CALCULATED"));int battlePower=s.GetLSTotalPower();float forfeit=fv(s);for(int i=0;i<180&&s.gameState().getBattleState()!=null;i++){if(s.AwaitingLSBattleDamagePayment())s.LSPayBattleDamageFromReserveDeck();else pass(s);}assertNull(s.gameState().getBattleState());rows.add(Map.of("name","deploy-"+barrier,"cost",before-s.GetLSForcePileCount()-1,"outside",outside,"battlePower",battlePower,"forfeit",forfeit,"afterPower",total(s),"afterForfeit",fv(s)));}}
}
