package com.gempukku.swccgo.rules.devices;
import com.gempukku.swccgo.common.*;
import com.gempukku.swccgo.framework.*;
import com.gempukku.swccgo.game.*;
import com.google.gson.GsonBuilder;
import org.junit.Test;
import org.junit.AfterClass;
import java.nio.file.*;
import java.util.*;
import static org.junit.Assert.*;
public class NativeEngineLarsOracleTests {
 static final String LS=VirtualTableScenario.LS,DS=VirtualTableScenario.DS;
 static final List<Map<String,Object>> rows=new ArrayList<>();
 @AfterClass public static void output() throws Exception{Files.writeString(Path.of("/opt/gemp-swccg/lars-results.json"),new GsonBuilder().setPrettyPrinting().create().toJson(rows));}
 void pass(VirtualTableScenario s){try{if(s.GetCurrentDecision().getText().toLowerCase().contains("battle destiny?"))s.PlayerChooseNo(s.GetDecidingPlayer());else s.PlayerPass(s.GetDecidingPlayer());}catch(RuntimeException e){throw new AssertionError(s.GetDecidingPlayer()+" "+s.GetCurrentDecision().getText()+" "+s.GetCurrentDecision().getDecisionParameters(),e);}}
 VirtualTableScenario fixture(){var ls=new HashMap<>(Map.of("beru","1_2","owen","1_22","hydro","1_37","vapor","1_41","luke","101_2","jedi","9_24","rebel","1_28"));var ds=new HashMap<String,String>();for(int i=0;i<12;i++)ds.put("enemy"+i,"1_194");var s=new VirtualTableScenario(ls,ds,40,40,StartingSetup.LSStartingLocation("1_132"),StartingSetup.DSStartingLocation("1_284"),StartingSetup.NoLSStartingInterrupts,StartingSetup.NoDSStartingInterrupts,StartingSetup.NoLSShields,StartingSetup.NoDSShields,VirtualTableScenario.Open);s.StartGame();s.SkipToPhase(Phase.CONTROL);s.LSActivateForceCheat(12);s.DSActivateForceCheat(12);return s;}
 float forfeit(VirtualTableScenario s,String card){return s.game().getModifiersQuerying().getForfeit(s.gameState(),s.GetLSCard(card));}
 @Test public void locality(){for(String mode:List.of("alone","paired","devices","both","remote","device-remote","source-hand")){var s=fixture();var site=s.GetLSStartingLocation();s.MoveCardsToLocation(site,s.GetLSCard("beru"),s.GetLSCard("owen"));if(mode.equals("alone"))s.MoveCardsToHand(s.GetLSCard("owen"));if(List.of("devices","both","device-remote").contains(mode)){s.AttachCardsTo(site,s.GetLSCard("hydro"),s.GetLSCard("vapor"));if(mode.equals("devices")||mode.equals("device-remote"))s.MoveCardsToLocation(s.GetDSStartingLocation(),s.GetLSCard("beru"));if(mode.equals("device-remote")){s.AttachCardsTo(s.GetDSStartingLocation(),s.GetLSCard("hydro"),s.GetLSCard("vapor"));}}
 if(mode.equals("remote"))s.MoveCardsToLocation(s.GetDSStartingLocation(),s.GetLSCard("owen"));if(mode.equals("source-hand"))s.MoveCardsToHand(s.GetLSCard("beru"),s.GetLSCard("owen"));rows.add(Map.of("name",mode,"beruForfeit",forfeit(s,"beru"),"owenPower",s.GetPower(s.GetLSCard("owen"))));}}
 @Test public void deployment(){for(String who:List.of("beru","owen"))for(boolean farm:List.of(false,true)){var s=fixture();var c=s.GetLSCard(who);s.MoveCardsToHand(c);s.MoveCardsToLocation(s.GetDSStartingLocation(),s.GetLSCard("rebel"));s.SkipToLSTurn(Phase.DEPLOY);int before=s.GetLSForcePileCount();s.LSDeployCard(c);s.LSChooseCard(farm?s.GetLSStartingLocation():s.GetDSStartingLocation());for(int i=0;i<100&&c.getZone()!=Zone.AT_LOCATION;i++)pass(s);assertEquals(Zone.AT_LOCATION,c.getZone());rows.add(Map.of("name","deploy-"+who+"-"+farm,"cost",before-s.GetLSForcePileCount()));}}
 @Test public void losses(){for(String mode:List.of("beru","owen","both","late-luke","own-turn")){var s=fixture();var site=s.GetLSStartingLocation();var b=s.GetLSCard("beru");var o=s.GetLSCard("owen");var luke=s.GetLSCard("luke");s.MoveCardsToLocation(site,b,o,s.GetLSCard("rebel"));if(mode.equals("late-luke"))s.MoveCardsToHand(luke);else s.MoveCardsToLocation(s.GetDSStartingLocation(),luke);for(int i=0;i<12;i++)s.MoveCardsToLocation(site,s.GetDSCard("enemy"+i));if(mode.equals("own-turn"))s.SkipToLSTurn(Phase.BATTLE);else s.SkipToPhase(Phase.BATTLE);if(mode.equals("own-turn"))s.LSInitiateBattle(site);else s.DSInitiateBattle(site);s.SkipToDamageSegment();System.out.println("LARS BEGIN "+mode+" power "+s.GetDSTotalPower()+" vs "+s.GetLSTotalPower()+" decision "+s.GetCurrentDecision().getText());for(String who:mode.equals("both")||mode.equals("late-luke")?List.of("beru","owen"):List.of(mode.equals("owen")?"owen":"beru")){for(int i=0;i<100&&!s.AwaitingLSBattleDamagePayment();i++)pass(s);assertTrue(s.AwaitingLSBattleDamagePayment());s.LSChooseCard(s.GetLSCard(who));System.out.println("LARS PAID "+mode+" "+who+" lost "+s.GetLSLostPile().contains(s.GetLSCard(who))+" decision "+s.GetCurrentDecision().getText());for(int i=0;i<100&&!s.GetLSLostPile().contains(s.GetLSCard(who));i++)pass(s);for(int i=0;i<100&&s.gameState().getBattleState()!=null&&!s.AwaitingLSBattleDamagePayment();i++)pass(s);}
 float immediate=s.GetPower(luke);if(mode.equals("late-luke"))s.MoveCardsToLocation(s.GetDSStartingLocation(),luke);float later=s.GetPower(luke);for(int i=0;i<200&&s.gameState().getBattleState()!=null;i++){if(s.AwaitingLSBattleDamagePayment())s.LSPayBattleDamageFromReserveDeck();else pass(s);}assertNull(s.gameState().getBattleState());
 // A global modifier follows new Luke instances and applies to other personas.
 s.MoveCardsToHand(luke);float hand=s.GetPower(luke);s.MoveCardsToLocation(site,s.GetLSCard("jedi"));float jedi=s.GetPower(s.GetLSCard("jedi"));s.MoveCardsToHand(s.GetLSCard("jedi"));s.MoveCardsToLocation(s.GetDSStartingLocation(),luke);
 float next=-1,expired=-1;if(!mode.equals("own-turn")){try{s.SkipToLSTurn(Phase.CONTROL);next=s.GetPower(luke);s.SkipToDSTurn(Phase.CONTROL);expired=s.GetPower(luke);}catch(RuntimeException e){throw new AssertionError(mode+" | "+s.GetDecidingPlayer()+" | "+s.GetCurrentDecision().getText()+" | "+s.GetCurrentDecision().getDecisionParameters(),e);}}
 rows.add(Map.of("name","loss-"+mode,"immediate",immediate,"later",later,"hand",hand,"jedi",jedi,"next",next,"expired",expired));}}
 @Test public void deviceInBattle(){for(String who:List.of("beru","owen")){var s=fixture();var site=s.GetLSStartingLocation();var character=s.GetLSCard(who);s.MoveCardsToLocation(site,character,s.GetLSCard("rebel"));s.MoveCardsToHand(s.GetLSCard(who.equals("beru")?"owen":"beru"));s.AttachCardsTo(site,s.GetLSCard(who.equals("beru")?"hydro":"vapor"));for(int i=0;i<12;i++)s.MoveCardsToLocation(site,s.GetDSCard("enemy"+i));s.SkipToPhase(Phase.BATTLE);s.DSInitiateBattle(site);s.SkipToEndOfPowerSegment(false);rows.add(Map.of("name","battle-device-"+who,"value",who.equals("beru")?forfeit(s,who):s.GetPower(character)));}}

}
