package com.gempukku.swccgo.rules.devices;
import com.gempukku.swccgo.common.*;
import com.gempukku.swccgo.framework.*;
import com.gempukku.swccgo.game.*;
import com.google.gson.GsonBuilder;
import org.junit.Test;
import org.junit.AfterClass;
import java.nio.file.*;
import java.util.*;
import static org.junit.Assert.*;
public class NativeEngineMentorOracleTests {
 static final List<Map<String,Object>> rows=new ArrayList<>();
 @AfterClass public static void output()throws Exception{Files.writeString(Path.of("/opt/gemp-swccg/mentor-results.json"),new GsonBuilder().serializeNulls().setPrettyPrinting().create().toJson(rows));}
 void pass(VirtualTableScenario s){System.out.println("PASS "+s.GetDecidingPlayer()+" "+s.GetCurrentDecision().getText());s.PlayerPass(s.GetDecidingPlayer());}
 VirtualTableScenario fixture(boolean space){var ls=new HashMap<String,String>(Map.of("gift","1_82","cocky","1_76","luke","101_2","obi","1_21","yoda","4_2","han","1_11","saber","1_157","ship","106_7"));var ds=new HashMap<String,String>(Map.of("eye","1_277","vader","101_5","tarkin","1_179","tie","1_304","second","1_304","boring","1_235","capital","1_302"));var s=new VirtualTableScenario(ls,ds,55,55,StartingSetup.LSStartingLocation(space?"1_127":"1_129"),StartingSetup.DSStartingLocation("1_284"),StartingSetup.NoLSStartingInterrupts,StartingSetup.NoDSStartingInterrupts,StartingSetup.NoLSShields,StartingSetup.NoDSShields,VirtualTableScenario.Open);s.StartGame();s.DSActivateForceCheat(12);s.LSActivateForceCheat(12);return s;}
 @Test public void additions(){for(String mode:List.of("gift","gift-yoda","cocky","eye","eye-imperial")){
  System.out.println("MODE "+mode);var s=fixture(false);boolean dark=mode.startsWith("eye");var card=dark?s.GetDSCard("eye"):s.GetLSCard(mode.equals("cocky")?"cocky":"gift");var site=s.GetLSStartingLocation();s.MoveCardsToLocation(site,s.GetLSCard(dark?"han":"luke"),s.GetDSCard(mode.equals("eye")||mode.equals("gift-yoda")?"vader":"tarkin"));if(!dark)s.MoveCardsToLocation(site,s.GetLSCard(mode.equals("cocky")?"han":mode.equals("gift-yoda")?"yoda":"obi"));s.MoveCardsToHand(card);if(dark){s.SkipToLSTurn(Phase.BATTLE);s.LSInitiateBattle(site);}else{s.SkipToDSTurn(Phase.BATTLE);s.DSInitiateBattle(site);}s.PassBattleStartResponses();for(int i=0;i<5&&!s.GetDecidingPlayer().equals(dark?VirtualTableScenario.DS:VirtualTableScenario.LS);i++)pass(s);var q=s.game().getModifiersQuerying();var player=dark?VirtualTableScenario.DS:VirtualTableScenario.LS;int before=q.getNumBattleDestinyDraws(s.gameState(),player,false,false);float power=q.getTotalPowerAtLocation(s.gameState(),site,player,true,false);if(dark)s.DSUseCardAction(card,mode.equals("eye")?"Add 1 to power":"Add one battle destiny");else s.LSUseCardAction(card,"Add two battle destiny");for(int i=0;i<100&&!(dark?s.GetDSLostPile():s.GetLSLostPile()).contains(card);i++)pass(s);assertTrue((dark?s.GetDSLostPile():s.GetLSLostPile()).contains(card));rows.add(Map.of("mode",mode,"before",before,"after",q.getNumBattleDestinyDraws(s.gameState(),player,false,false),"powerBonus",q.getTotalPowerAtLocation(s.gameState(),site,player,true,false)-power,"lost",true));
 }}
 @Test public void search(){var s=fixture(false);PhysicalCardImpl card=s.GetLSCard("gift"),saber=s.GetLSCard("saber");s.MoveCardsToHand(card);s.SkipToLSTurn(Phase.DEPLOY);s.MoveCardsToTopOfLSReserveDeck(saber);int force=s.GetLSForcePileCount();s.LSUseCardAction(card,"Take lightsaber into hand from Reserve Deck");for(int i=0;i<100&&!s.GetLSHand().contains(saber);i++){var text=s.GetCurrentDecision().getText().toLowerCase();if(s.GetDecidingPlayer().equals(VirtualTableScenario.LS)&&text.contains("choose")&&text.contains("into hand"))s.LSChooseCard(saber);else pass(s);}assertTrue(s.GetLSHand().contains(saber));for(int i=0;i<100&&!s.GetLSLostPile().contains(card);i++)pass(s);assertTrue(s.GetLSLostPile().contains(card));rows.add(Map.of("mode","search","forcePaid",force-s.GetLSForcePileCount(),"targetInHand",true,"interruptLost",true));}
 @Test public void tie(){var s=fixture(true);PhysicalCardImpl card=s.GetLSCard("cocky"),tie=s.GetDSCard("tie"),second=s.GetDSCard("second"),site=s.GetLSStartingLocation();s.MoveCardsToLocation(site,s.GetLSCard("ship"),tie,second);s.MoveCardsToHand(card);s.SkipToDSTurn(Phase.BATTLE);s.DSInitiateBattle(site);for(int i=0;i<100&&!(s.GetDecidingPlayer().equals(VirtualTableScenario.LS)&&s.LSCardActionAvailable(card,"Make a TIE/ln lost"));i++)pass(s);s.LSUseCardAction(card,"Make a TIE/ln lost");s.LSChooseCard(tie);for(int i=0;i<100&&!s.GetLSLostPile().contains(card);i++)pass(s);assertTrue(s.GetLSLostPile().contains(card));assertTrue(s.GetDSLostPile().contains(tie));rows.add(Map.of("mode","tie","targetLost",true,"secondOnTable",second.getAtLocation()==site,"interruptLost",true));}
 @Test public void deployTie(){for(boolean capital:List.of(false,true)){var s=fixture(true);PhysicalCardImpl card=s.GetDSCard("tie"),site=s.GetLSStartingLocation();if(capital)s.MoveCardsToLocation(site,s.GetDSCard("capital"));s.MoveCardsToHand(card);s.SkipToDSTurn(Phase.DEPLOY);int force=s.GetDSForcePileCount();float ability=s.game().getModifiersQuerying().getTotalAbilityAtLocation(s.gameState(),VirtualTableScenario.DS,site);s.DSDeployCard(card);for(int i=0;i<100&&card.getAtLocation()!=site;i++){if(s.DSDecisionAvailable("Choose target")||s.DSDecisionAvailable("Choose where"))s.DSChooseCard(site);else pass(s);}assertEquals(site,card.getAtLocation());rows.add(Map.of("mode","deploy-tie","capital",capital,"forcePaid",force-s.GetDSForcePileCount(),"ability",s.game().getModifiersQuerying().getTotalAbilityAtLocation(s.gameState(),VirtualTableScenario.DS,site)-ability));}}
}
