'use client';
import {useDeferredValue,useMemo,useState} from 'react';
import {Search,ArrowUpRight,RotateCw,SlidersHorizontal,Plus,Minus,LibraryBig} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {CatalogControls,CatalogSort,Filter} from './catalog-controls';
import {catalogStats,defaultCatalogOptions,filterAndSortCards,sortStatLabel,type CatalogOptions} from '@/lib/catalog-filters';
export {Filter} from './catalog-controls';
import {Pagination,PaginationContent,PaginationItem} from '@/components/ui/pagination';
import {searchCards,type CatalogCard,type CatalogManifest} from '@/lib/catalog';
function Scan({src,name}:{src:string;name:string}){const [failed,setFailed]=useState(false);return failed?<div className="scan-unavailable"><LibraryBig size={30}/><span>{name}</span><small>Scan unavailable · open card details</small></div>:<img src={src} alt={name+' card scan'} loading="lazy" onError={()=>setFailed(true)}/>}
export default function Catalog({cards,manifest,deckSide,onAdd,counts={}}:{cards:CatalogCard[];manifest:CatalogManifest;deckSide?:string;onAdd?:(card:CatalogCard,delta:number)=>void;counts?:Record<string,number>}){
 const [query,setQuery]=useState(''),[side,setSide]=useState('all'),[type,setType]=useState('all'),[set,setSet]=useState('all'),[era,setEra]=useState('all'),[page,setPage]=useState(0),[inspect,setInspect]=useState<CatalogCard|null>(null),[back,setBack]=useState(false),[advanced,setAdvanced]=useState(false),[options,setOptions]=useState<CatalogOptions>(defaultCatalogOptions);const deferred=useDeferredValue(query);
 const stats=useMemo(()=>catalogStats(cards),[cards]);
 const filtered=useMemo(()=>filterAndSortCards(searchCards(cards,deferred,deckSide||side,type,set,era),options),[cards,deferred,deckSide,side,type,set,era,options]);
 const activeCount=[type,set,era,options.subType,options.rarity,options.persona,options.characteristic,options.icon,options.uniqueness,options.layout].filter(v=>v!=='all').length+(options.face!=='either'?1:0)+options.rules.length;
 const hasFilters=!!query||(!deckSide&&side!=='all')||activeCount>0;
 const updateOptions=(patch:Partial<CatalogOptions>)=>{setOptions(previous=>({...previous,...patch}));setPage(0)};
 function resetFilters(){setSide('all');setType('all');setSet('all');setEra('all');setQuery('');setPage(0);setOptions(previous=>({...defaultCatalogOptions,sort:previous.sort,direction:previous.direction}))}
 const pages=Math.max(1,Math.ceil(filtered.length/24)),current=Math.min(page,pages-1);const face=inspect&&(back&&inspect.back?inspect.back:inspect);
 function change(fn:(value:string)=>void){return(value:string)=>{fn(value);setPage(0)}}
 return <section className="card-archive" aria-label="Card archive"><div className="archive-filters"><div className="search-input"><Search size={18}/><input aria-label="Search card names, text and personas" placeholder="Search a name, ability, or familiar face…" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}>×</button>}</div>{!deckSide&&<Filter label="Side" value={side} onChange={change(setSide)} items={[{value:'all',label:'Both sides'},{value:'light',label:'Light side'},{value:'dark',label:'Dark side'}]}/>}<button className={'button filter-toggle '+(advanced?'selected':'')} aria-expanded={advanced} onClick={()=>setAdvanced(!advanced)}><SlidersHorizontal size={16}/>Filters{activeCount>0&&<span className="catalog-filter-badge">{activeCount}</span>}</button></div>
 {advanced&&<CatalogControls cards={cards} manifest={manifest} options={options} onChange={updateOptions} type={type} set={set} era={era} onType={change(setType)} onSet={change(setSet)} onEra={change(setEra)} onReset={resetFilters}/>}
 <div className="catalog-results-bar"><div className="catalog-result-count" role="status"><b>{filtered.length.toLocaleString()}</b> cards {hasFilters?'found':'in the archive'}{hasFilters&&<button className="text-button" onClick={resetFilters}>Clear filters</button>}</div><CatalogSort stats={stats} options={options} onChange={updateOptions}/></div>
 {options.sort.startsWith('stat:')&&<p className="catalog-sort-help">Numbers first, then variable / special values, then unprinted stats.{options.face==='either'?' For two faces, sorting uses the '+(options.direction==='asc'?'lowest':'highest')+' number among matching faces.':''}</p>}
 <div className="archive-grid">{filtered.slice(current*24,(current+1)*24).map(c=><article key={c.id} className={'archive-card '+c.side}><button className="archive-inspect" onClick={()=>{setInspect(c);setBack(false)}} aria-label={'Inspect '+c.name}><div className={'archive-scan '+(c.type==='Location'?'landscape':'')}><Scan src={c.image} name={c.name}/>{c.back&&<span className="double-face"><RotateCw size={13}/>2 FACES</span>}</div><div className="archive-card-info"><h3>{c.title}</h3><p>{c.type}{c.subType?' · '+c.subType:''}</p><span>{c.setName}</span>{options.sort.startsWith('stat:')&&<small className="catalog-card-stat">{sortStatLabel(c,options)}</small>}</div></button>{onAdd&&<div className="card-counter"><button aria-label={'Remove '+c.name} disabled={!counts[c.gempId||'']} onClick={()=>onAdd(c,-1)}><Minus size={15}/></button><span>{counts[c.gempId||'']||0} <small>IN DECK</small></span><button aria-label={'Add '+c.name} disabled={!c.gempId} onClick={()=>onAdd(c,1)}><Plus size={15}/></button></div>}</article>)}</div>
 {!filtered.length&&<div className="empty-state"><Search size={30}/><h3>No signals in this sector.</h3><p>Try another name or reset your filters.</p><button className="button" onClick={resetFilters}>Reset filters</button></div>}
 <Pagination className="archive-pagination"><PaginationContent><PaginationItem><button className="button" disabled={current===0} onClick={()=>setPage(current-1)}>Previous</button></PaginationItem><PaginationItem><span aria-live="polite">{current+1} / {pages}</span></PaginationItem><PaginationItem><button className="button" disabled={current===pages-1} onClick={()=>setPage(current+1)}>Next</button></PaginationItem></PaginationContent></Pagination>
 <p className="archive-credit">Card data from the <a href={manifest.source} target="_blank" rel="noreferrer">Players Committee archive <ArrowUpRight size={12}/></a>. Includes current Decipher and virtual records, including alternate printings. Historical legacy virtual files are excluded. Game availability is checked by the rules engine.</p>
 <Dialog open={!!inspect} onOpenChange={o=>!o&&setInspect(null)}><DialogContent className="printed-inspect">{inspect&&face&&<><DialogTitle>{face.title}</DialogTitle><DialogDescription>{inspect.side==='light'?'Light':'Dark'} side · {inspect.type} · {inspect.setName}</DialogDescription><div className="printed-body"><div className="printed-scan"><Scan key={face.image} src={face.image} name={face.title}/>{inspect.back&&<button className="button" onClick={()=>setBack(!back)}><RotateCw size={16}/>{back?'Show front':'Flip card'}</button>}</div><div><span className="eyebrow amber">PRINTED GAME TEXT</span><p className="printed-text">{face.text||'This card has no printed game text in the archive.'}</p>{Object.keys(face.stats).length>0&&<dl className="printed-stats">{Object.entries(face.stats).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>}{face.lore&&<p className="printed-lore">{face.lore}</p>}<p className="tiny muted">Rarity {inspect.rarity||'unspecified'}{inspect.personas.length?' · '+inspect.personas.join(', '):''}</p><a className="text-button" href={face.image} target="_blank" rel="noreferrer">Open original scan<ArrowUpRight size={15}/></a>{onAdd&&<button className="button primary" disabled={!inspect.gempId} onClick={()=>onAdd(inspect,1)}><Plus size={16}/>Add to deck</button>}</div></div></>}</DialogContent></Dialog>
 </section>
}
