import {CARD_MAP,LOCATIONS,starter,validateDeck,type Deck,type Side} from './cards';
export const PHASES=['Activate','Control','Deploy','Battle','Move','Draw'] as const;
export type Unit={uid:string;id:string;location:number;bonus:number;moved:boolean};
export type Player={name:string;side:Side;reserve:string[];force:string[];used:string[];lost:string[];hand:string[];units:Unit[]};
export type Game={players:[Player,Player];turn:number;active:number;phase:number;activated:boolean;drained:number[];battled:number[];log:string[];winner:number|null;mode:'cpu'|'local'|'online';difficulty:'cadet'|'commander';started:boolean;sealed:boolean};
export type Action={type:'activate'|'next'|'deploy'|'battle'|'move'|'draw'|'drain'|'concede';card?:number;location?:number;unit?:string};
export function shuffle<T>(a:T[],rng= Math.random):T[]{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
export const life=(p:Player)=>p.reserve.length+p.force.length+p.used.length;
export const power=(p:Player,l:number)=>p.units.filter(u=>u.location===l).reduce((n,u)=>n+CARD_MAP[u.id].power+u.bonus,0);
function log(g:Game,s:string){g.log=[s,...g.log].slice(0,50)}
export function createGame(deck:Deck,other:Deck,mode:Game['mode'],difficulty:Game['difficulty']='commander'):Game{for(const d of [deck,other]){if(d.cards.length!==d.size||d.cards.some(id=>!CARD_MAP[id]||CARD_MAP[id].side!==d.side))throw Error('Invalid battle deck.')}if(deck.side===other.side)throw Error('Opponents must choose opposite sides.');const players=[deck,other].map((d,i)=>{const cards=shuffle(d.cards);return {name:i===0?'Rogue Leader':mode==='cpu'?'Computer':mode==='local'?'Player Two':'Friend',side:d.side,hand:cards.splice(0,8),reserve:cards,force:[],used:[],lost:[],units:[]}}) as unknown as Game['players'];return {players,turn:1,active:deck.side==='dark'?0:1,phase:0,activated:false,drained:[],battled:[],log:['Both sides draw 8 cards. The Dark Side moves first.'],winner:null,mode,difficulty,started:mode!=='online',sealed:!!deck.poolId}}
function lose(p:Player,n:number){for(let i=0;i<n;i++){const a=p.reserve.length?p.reserve:p.force.length?p.force:p.used;if(!a.length)break;p.lost.push(a.shift()!)}}
function spend(p:Player,n:number){if(p.force.length<n)throw Error(`You need ${n} available Force.`);p.used.push(...p.force.splice(0,n))}
function win(g:Game){const dead=g.players.map(p=>life(p)<=0);if(dead[0]||dead[1]){g.winner=dead[0]?1:0;log(g,`${g.players[g.winner].name} wins the battle for the galaxy.`)}}
export function act(game:Game,actor:number,a:Action):Game{const g=structuredClone(game);if(g.winner!==null)throw Error('This game has ended.');if(a.type==='concede'){g.winner=1-actor;log(g,`${g.players[actor].name} concedes.`);return g}if(!g.started)throw Error('Waiting for your friend.');if(g.active!==actor)throw Error('Wait for your turn.');const p=g.players[actor],o=g.players[1-actor];const l=a.location;if(l!==undefined&&(!Number.isInteger(l)||!LOCATIONS[l]))throw Error('Choose a valid location.');
if(a.type==='activate'){if(g.phase!==0||g.activated)throw Error('Force is already activated.');const n=Math.min(p.reserve.length,5+p.units.reduce((acc,u)=>acc+(u.location===0?1:0),0));p.force.push(...p.reserve.splice(0,n));g.activated=true;log(g,`${p.name} activates ${n} Force.`)}
else if(a.type==='next'){if(g.phase===0&&!g.activated)throw Error('Activate your Force first.');if(g.phase<5)g.phase++;else{for(const pl of g.players){pl.reserve.push(...pl.used.splice(0));pl.units.forEach(u=>u.moved=false)}g.active=1-actor;g.turn++;g.phase=0;g.activated=false;g.drained=[];g.battled=[];log(g,`${g.players[g.active].name} begins turn ${g.turn}.`);if(!p.hand.length&&!p.units.length&&!p.reserve.length&&!p.force.length)win(g)}}
else if(a.type==='drain'){if(g.phase!==1||l===undefined||g.drained.includes(l))throw Error('This location cannot drain now.');if(!p.units.some(u=>u.location===l)||o.units.some(u=>u.location===l))throw Error('Control a location without enemy units to drain.');lose(o,LOCATIONS[l].icons);g.drained.push(l);log(g,`${p.name} drains ${LOCATIONS[l].icons} Force at ${LOCATIONS[l].name}.`)}
else if(a.type==='deploy'){if(g.phase!==2||l===undefined||a.card===undefined||!Number.isInteger(a.card))throw Error('Deploy during your Deploy phase.');const id=p.hand[a.card],c=CARD_MAP[id];if(!c)throw Error('Choose a card from your hand.');if(['Character','Starship','Vehicle'].includes(c.type)){if((c.type==='Starship')!==(LOCATIONS[l].kind==='space'))throw Error(c.type==='Starship'?'Starships deploy at the Tatooine system.':'Ground units deploy at Mos Eisley or Yavin IV.');if(c.unique&&p.units.some(u=>u.id===id))throw Error('This unique card is already on the table.');spend(p,c.cost);p.hand.splice(a.card,1);p.units.push({uid:crypto.randomUUID(),id,location:l,bonus:0,moved:false});log(g,`${p.name} deploys ${c.name} at ${LOCATIONS[l].name}.`)}else if(c.type==='Weapon'){const target=p.units.find(u=>u.location===l&&CARD_MAP[u.id].type==='Character');if(!target)throw Error('Choose a site with one of your characters.');spend(p,c.cost);p.hand.splice(a.card,1);target.bonus+=c.power;p.used.push(id);log(g,`${c.name} gives ${CARD_MAP[target.id].name} +${c.power} power.`)}else{spend(p,c.cost);p.hand.splice(a.card,1);if(id==='courage'||id==='choke'){lose(o,2)}else{p.reserve.push(...p.lost.splice(0,c.type==='Effect'?3:1))}p.lost.push(id);log(g,`${p.name} plays ${c.name}. ${c.text}`)}}
else if(a.type==='battle'){if(g.phase!==3||l===undefined||g.battled.includes(l))throw Error('One battle per location in your Battle phase.');if(!p.units.some(u=>u.location===l)||!o.units.some(u=>u.location===l))throw Error('Both sides need units here to battle.');spend(p,1);g.battled.push(l);const destiny=(pl:Player)=>{const ability=pl.units.filter(u=>u.location===l).reduce((n,u)=>n+CARD_MAP[u.id].ability,0);if(ability<4||!pl.reserve.length)return 0;const id=pl.reserve.shift()!;pl.used.push(id);return CARD_MAP[id].destiny};const d1=destiny(p),d2=destiny(o),aPower=power(p,l)+d1,bPower=power(o,l)+d2;log(g,`Battle at ${LOCATIONS[l].name}: ${p.name} ${aPower} (destiny ${d1}) vs. ${o.name} ${bPower} (destiny ${d2}).`);if(aPower!==bPower){const loser=aPower<bPower?p:o;lose(loser,Math.abs(aPower-bPower));const units=loser.units.filter(u=>u.location===l).sort((a,b)=>(CARD_MAP[a.id].power+a.bonus)-(CARD_MAP[b.id].power+b.bonus));if(units[0]){loser.lost.push(units[0].id);loser.units=loser.units.filter(u=>u.uid!==units[0].uid)}log(g,`${loser.name} loses ${Math.abs(aPower-bPower)} Force and a unit.`)}}
else if(a.type==='move'){if(g.phase!==4||l===undefined)throw Error('Move during your Move phase.');const u=p.units.find(u=>u.uid===a.unit);if(!u||u.moved||u.location===l)throw Error('Choose a unit that has not moved.');if(CARD_MAP[u.id].type==='Starship'||LOCATIONS[l].kind==='space')throw Error('Ground units move between the two sites.');spend(p,1);u.location=l;u.moved=true;log(g,`${CARD_MAP[u.id].name} moves to ${LOCATIONS[l].name}.`)}
else if(a.type==='draw'){if(g.phase!==5||!p.force.length)throw Error('Draw from available Force during the Draw phase.');if(p.hand.length>=16)throw Error('Holotable hand limit: 16 cards.');p.hand.push(p.force.shift()!);log(g,`${p.name} draws a card.`)}else throw Error('Unknown action.');win(g);return g}
export function cpuTurn(input:Game):Game{let g=input;let guard=0;while(g.active===1&&g.winner===null&&g.mode==='cpu'&&guard++<200){const p=g.players[1],o=g.players[0];try{if(g.phase===0){g=act(g,1,{type:'activate'});g=act(g,1,{type:'next'})}else if(g.phase===1){for(let l=0;l<3;l++){if(g.winner===null&&p.units.some(u=>u.location===l)&&!o.units.some(u=>u.location===l))g=act(g,1,{type:'drain',location:l})}if(g.winner===null)g=act(g,1,{type:'next'})}else if(g.phase===2){let played=false;for(let i=0;i<p.hand.length;i++){const c=CARD_MAP[p.hand[i]];if(c.cost>p.force.length||c.unique&&p.units.some(u=>u.id===c.id))continue;let l=c.type==='Starship'?0:1;const ground=[1,2].sort((a,b)=>power(p,a)-power(p,b));if(c.type!=='Starship')l=ground[0];if(c.type==='Weapon'){const u=p.units.find(u=>CARD_MAP[u.id].type==='Character');if(!u)continue;l=u.location}if(g.difficulty==='cadet'&&played)break;g=act(g,1,{type:'deploy',card:i,location:l});played=true;break}if(!played||g.difficulty==='cadet')g=act(g,1,{type:'next'})}else if(g.phase===3){let fought=false;for(let l=0;l<3;l++)if(!g.battled.includes(l)&&p.force.length&&power(p,l)&&power(o,l)&&(g.difficulty==='cadet'||power(p,l)>=power(o,l))){g=act(g,1,{type:'battle',location:l});fought=true;break}if(!fought)g=act(g,1,{type:'next'})}else if(g.phase===4){g=act(g,1,{type:'next'})}else{if(p.force.length&&p.hand.length<8){g=act(g,1,{type:'draw'})}else g=act(g,1,{type:'next'})}}catch{if(g.winner===null)g=act(g,1,{type:'next'});else break}}return g}
export function publicGame(g:Game,viewer:number){const out=structuredClone(g);for(let i=0;i<2;i++){out.players[i].reserve=out.players[i].reserve.map(()=>'?');out.players[i].force=out.players[i].force.map(()=>'?');out.players[i].used=out.players[i].used.map(()=>'?');if(i!==viewer)out.players[i].hand=out.players[i].hand.map(()=>'?')}return out}
