import manifest from '../../data/native-proof/manifest.json';
import type {Side} from './types';
export {manifest};
export const definitions = new Map(manifest.cards.map(c => [c.gempId,c]));
export function definition(id:string){const c=definitions.get(id);if(!c)throw new Error('Unsupported card identity.');return c;}
export function printed(id:string,key:string){const raw=(definition(id).stats as Record<string,string>)[key];const n=Number(raw);if(raw===undefined||!Number.isFinite(n))throw new Error('This printed value needs an explicit rules handler.');return n;}
export const other=(side:Side):Side=>side==='light'?'dark':'light';
export const sites:Record<string,Record<Side,number>>={'1_124':{light:1,dark:1},'1_129':{light:1,dark:1},'1_132':{light:2,dark:1},'1_284':{light:0,dark:1}};
export const scenarios = [
 {id:'activation' as const,title:'The flow of the Force',subtitle:'Activation & priority',description:'Activate one Force at a time. Each action returns priority before another card can move.',rules:['Personal Force + location icons','Optional activation','Response and action opportunities'],phase:'Activate'},
 {id:'drain' as const,title:'Hold the docking bay',subtitle:'Control & Force loss',description:'A Stormtrooper controls the site. Resolve its drain, choose where to lose Force, and retain every decision after reload.',rules:['Presence and control','Opponent Force icons','Choice of Force-loss source'],phase:'Control'},
 {id:'battle' as const,title:'Crossfire at Docking Bay 327',subtitle:'Battle destiny & attrition',description:'Four troopers on each side. Initiate a battle, choose whether to draw destiny, then resolve attrition and battle damage.',rules:['One Force to initiate','Four ability for one destiny','Forfeit satisfies damage and attrition'],phase:'Battle'},
 {id:'recirculation' as const,title:'The Force returns',subtitle:'Both players recirculate',description:'Resolve the end-of-turn recirculation checkpoint. Used cards return beneath Reserve in order; unspent Force stays put.',rules:['Both players recirculate','Pile order preserved','Force pile retained'],phase:'End of turn'},
 {id:'takeel' as const,title:'A turn of destiny',subtitle:'Takeel & response timing',description:'A familiar battle, with Takeel in Dark’s hand. After both players draw one destiny, spend 1 Force to switch the numbers—or let them stand.',rules:['Optional Interrupt response','Pay cost before resolving','Destiny numbers switch; cards stay put'],phase:'Battle'},
 {id:'barrier' as const,title:'Reinforcements under fire',subtitle:'Dark deploys · Rebel Barrier',description:'Deploy Stormtroopers and give Light a chance to respond. Play out battle, movement and drawing, then watch the Barrier expire after recirculation.',rules:['Deploy using Force icons or presence','Barrier blocks battle and movement','Regular movement once per turn'],phase:'Deploy'},
 {id:'imperial-barrier' as const,title:'The Imperial blockade',subtitle:'Light deploys · Imperial Barrier',description:'Deploy Rebel Troopers and face Dark’s Barrier. The empty corridor has no Light Force icon: you can move there, but cannot initially deploy there.',rules:['Deployment and movement differ','Used Interrupt resolves to Used','Restrictions expire at turn end'],phase:'Deploy'},
 {id:'weapons' as const,title:'Blasters at the ready',subtitle:'Imperial weapons · Rebel return fire',description:'Arm your Stormtroopers, then trade fire with the Rebels. A hit does not stop a trooper fighting—but it must be forfeited later.',rules:['Weapon deployment and transfer','Weapon destiny and return fire','Mandatory hit losses and attached cards'],phase:'Deploy'},
 {id:'rebel-weapons' as const,title:'Return fire',subtitle:'Rebel weapons · Imperial resistance',description:'Choose Blasters or Rifles for your Rebels. Fire, pass, or save Force; resolve hit troopers alongside attrition and battle damage.',rules:['One different weapon per warrior','Hit troopers still add power and ability','Choose the order of simultaneous losses'],phase:'Deploy'},
 {id:'next-turn' as const,title:'The next turn',subtitle:'Two turns · one continuous board',description:'Take Dark and Light through all six phases. Drain, deploy, play a Barrier or save your Force, then reach Dark’s next activation with the same cards and board.',rules:['All six phases for both sides','Recirculation, expiry and turn handoff','Per-turn limits reset; unspent Force stays'],phase:'Start of turn'},
 {id:'opening-table' as const,title:'The opening table',subtitle:'Starting locations & opening hands',description:'Choose starting locations in secret. Resolve a shared-location clash, reveal your eight-card hand, and reach the first Activate phase.',rules:['Private choices, simultaneous reveal','Starting-location conversion or reselection','Eight-card hands; Dark begins'],phase:'Starting locations'},
 {id:'first-contact' as const,title:'First contact',subtitle:'From opening hands to the first clash',description:'Place the fixed Death Star sites, draw eight-card hands, and play both first turns. Deploy, arm, move or hold your Force for a Barrier and defensive fire.',rules:['Setup continues into both first turns','Blasters join deployment, movement and battle','Saved hands and piles carry through every phase'],phase:'Starting locations'},
 {id:'guard-post' as const,title:'Stand your ground',subtitle:'Guards & Death Star Troopers',description:'Bring Death Star Troopers and an Imperial guard to the Bay. A Rebel Guard waits with power to defend; compare battling, moving, and a timely Barrier.',rules:['Guards gain power only when defending','Printed deployment costs and location limits','Cannot move survives the end of a Barrier'],phase:'Deploy'},
 {id:'rebel-post' as const,title:'The sentry line',subtitle:'Rebel guards on the offensive',description:'Deploy a Rebel Guard or Trooper against the Imperial sentry. A guard can initiate battle, but its defensive bonus does not help it attack—and it cannot move away.',rules:['Presence does not require positive power','Defending guard +4; attacking guard +0','Barrier expiry does not erase printed restrictions'],phase:'Deploy'},
 {id:'corridor-crossfire' as const,title:'Corridor crossfire',subtitle:'Location bonuses & weapon destiny',description:'Arm four troopers on each side in the Detention Block Corridor. Dark adds 1 to every weapon destiny here; compare a basic Blaster with a Rifle and Light’s return fire.',rules:['Dark-only location bonus','Rifle and location modifiers add together','Strict hit threshold; printed destiny stays unchanged'],phase:'Deploy'},
 {id:'second-contact' as const,title:'Second contact',subtitle:'Four turns · a growing battlefront',description:'Start with guards, troopers, Barriers, Blasters and Rifles. Play both sides’ first and second turns on one board, carrying Force, casualties and weapons through each handoff.',rules:['Four complete turns from setup','Guards, Rifles and location bonuses together','New-turn actions reset; the battlefield persists'],phase:'Starting locations'},
 {id:'luke-arrives' as const,title:'Answer the call',subtitle:'Luke · location costs & reinforcements',description:'Deploy Luke at Docking Bay 94 or the Lars Farm, then call in Rebel Troopers. Compare the Farm discount, free deployment beside Luke, and Imperial Barrier.',rules:['Luke deploys on Tatooine; one copy at a time','Lars Farm reduces Luke’s deploy cost','Troopers deploy free beside Luke'],phase:'Deploy'},
 {id:'luke-support' as const,title:'Stand with Luke',subtitle:'Warrior support · the order of losses',description:'Luke, two Troopers and a guard face an Imperial force. Compare boosted forfeits and choose who leaves first: Luke’s support disappears when he does.',rules:['Same-site and adjacent warrior forfeit bonus','Luke benefits; guards do not','Recalculate choices after the source leaves'],phase:'Battle'},
 {id:'tusken-band' as const,title:'Strength in numbers',subtitle:'Tusken Raiders · presence & group power',description:'Build a band of Raiders across two Tatooine sites. A pair boosts each Raider; four add a single group bonus. A Rebel Barrier can change who counts in battle.',rules:['Tatooine-only deployment','Another Raider grants personal power +1','Four Raiders add total power +2 once'],phase:'Deploy'},
 {id:'reduce-drain' as const,title:'Weather the drain',subtitle:'It Could Be Worse · preserve Life Force',description:'Dark drains for 2 at the Lars Farm. Use saved Force to reduce the loss, hold the Interrupt, or lose one card before deciding again.',rules:['Loss reduction follows drain responses','Choose X and pay before resolving','Used Force is preserved in Life Force'],phase:'Control'},
 {id:'reduce-damage' as const,title:'Soften the blow',subtitle:'Battle damage · attrition stays',description:'Four Rebels face seven Stormtroopers. Use It Could Be Worse before taking battle losses, then compare how forfeiting a Trooper clears both damage and attrition.',rules:['Reduce remaining battle damage','Attrition is not Force loss','Reconsider after each loss'],phase:'Battle'},
 {id:'talz-rescue' as const,title:'Not this one',subtitle:'Talz · rescue a hit character',description:'Trade blaster fire with the Empire. During battle losses, forfeit Talz to restore a hit Rebel—even if Talz is also hit—and keep the Rebel’s weapon.',rules:['Replacement during the damage segment','One Talz can satisfy two hits','Talz forfeit also pays numeric losses'],phase:'Battle'},
 {id:'react-battle' as const,title:'Answer the alarm',subtitle:'Wolfman · battle react',description:'Three Rebels need help. Move one or both Wolfmen from the adjacent site before battle destiny is checked, or hold them back.',rules:['Pay 1 Force per moving card','React before battle destiny','Arriving ability counts in battle'],phase:'Battle'},
 {id:'react-drain' as const,title:'Contest the drain',subtitle:'Wolfman · presence cancels a drain',description:'Dark initiates a drain at the Bay. Bring a Wolfman from the Corridor to cancel it, or pass and take the loss.',rules:['React to a just-initiated drain','Presence cancels before Force loss','No further reacts after cancellation'],phase:'Control'},
 {id:'react-deploy' as const,title:'Call for backup',subtitle:'CZ-3 · deploy reinforcements',description:'Choose a battle at CZ-3’s site or the adjacent Corridor. Deploy reinforcements one at a time for their normal costs.',rules:['Same-site or adjacent CZ-3 support','Each deployment is a separate paid react','Normal Force-icon, presence and deployment rules'],phase:'Battle'},

 {id:'react-drain-deploy' as const,title:'Signal the defense',subtitle:'CZ-3 · deployment against a drain',description:'CZ-3 has no presence to stop a drain itself. Deploy help at the Bay, or compare the Corridor where no Light icon or presence allows deployment.',rules:['Droids alone do not provide presence','Deploy reacts obey normal restrictions','Arriving presence cancels the drain'],phase:'Control'},
 {id:'react-barrier' as const,title:'Reinforcements delayed',subtitle:'Deployment react meets Imperial Barrier',description:'Call reinforcements through CZ-3. Dark may Barrier a newly deployed character; compare its presence on the table with its exclusion from battle.',rules:['A react can receive a just-deployed response','Barrier pays before it resolves','Excluded cards add no battle ability or power'],phase:'Battle'},
 {id:'last-force' as const,title:'The last card',subtitle:'Final Life Force & victory',description:'Light has one card in Reserve and one in hand. Choose which to lose to the drain: preserve the final Life Force, or reach a decisive game-ending result.',rules:['Hand is not Life Force','Final Life Force loss ends the game','Terminal matches reject further actions'],phase:'Control'},

];
