import {database} from '@/db/raw';
import {CARDS,CARD_MAP,starter,sealedCards,sealedOpponent,validateDeck,type Deck,type Side} from '@/lib/cards';
import {createGame,act,cpuTurn,publicGame,type Game,type Action} from '@/lib/game';
const headers={'Cache-Control':'no-store'};
function identity(req:Request){const match=req.headers.get('cookie')?.match(/(?:^|; )holo_owner=([a-f0-9-]{36})/);return {owner:match?.[1]??crypto.randomUUID(),fresh:!match}}
function reply(data:unknown,owner:string,fresh:boolean,status=200){return Response.json(data,{status,headers:{...headers,...(fresh?{'Set-Cookie':`holo_owner=${owner}; Path=/; HttpOnly; SameSite=Lax; Max-Age=31536000${process.env.NODE_ENV==='production'?'; Secure':''}`}:{})}})}
function parse<T>(s:string){return JSON.parse(s) as T}
type GameRow={id:string;code:string;owner:string;guest:string|null;state:string;version:number};
async function validDeck(owner:string,d:Deck){let pool:string[]|undefined;if(d.poolId){const row=await database().prepare('SELECT data FROM pools WHERE id=? AND owner=?').bind(d.poolId,owner).first<{data:string}>();if(!row)throw Error('Sealed pool not found.');const sealed=parse<{cards:string[];size:number;side:Side}>(row.data);if(d.size!==sealed.size||d.side!==sealed.side)throw Error('Sealed decks must keep their pool’s side and format.');pool=sealed.cards}const err=validateDeck(d,pool);if(err)throw Error(err);if(typeof d.name!=='string'||!d.name.trim()||d.name.length>60)throw Error('Choose a deck name with 1–60 characters.');return d}
function view(row:GameRow,owner:string){const g=parse<Game>(row.state);const viewer=g.mode==='local'?g.active:row.owner===owner?0:1;return {id:row.id,code:row.code,version:row.version,viewer,game:publicGame(g,viewer)}}
export async function GET(req:Request){const {owner,fresh}=identity(req);try{const url=new URL(req.url),id=url.searchParams.get('game');if(id){const row=await database().prepare('SELECT * FROM games WHERE id=? AND (owner=? OR guest=?)').bind(id,owner,owner).first<GameRow>();if(!row)return reply({error:'Table not found.'},owner,fresh,404);return reply(view(row,owner),owner,fresh)}const db=database();const [decks,pools,games]=await Promise.all([db.prepare('SELECT data FROM decks WHERE owner=? ORDER BY updated DESC LIMIT 100').bind(owner).all<{data:string}>(),db.prepare('SELECT data FROM pools WHERE owner=? ORDER BY created DESC LIMIT 20').bind(owner).all<{data:string}>(),db.prepare('SELECT id,code,state FROM games WHERE owner=? OR guest=? ORDER BY updated DESC LIMIT 5').bind(owner,owner).all<{id:string;code:string;state:string}>()]);return reply({decks:decks.results.map(x=>parse(x.data)),pools:pools.results.map(x=>parse(x.data)),games:games.results.map(x=>{const g=parse<Game>(x.state);return {id:x.id,code:x.code,mode:g.mode,turn:g.turn,winner:g.winner,started:g.started}})},owner,fresh)}catch(e){console.error(e);return reply({error:'The holonet is temporarily unavailable. Try again in a moment.'},owner,fresh,503)}}
export async function POST(req:Request){const {owner,fresh}=identity(req);try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return reply({error:'Request origin does not match.'},owner,fresh,403);if(Number(req.headers.get('content-length'))>100000)return reply({error:'Request too large.'},owner,fresh,413);const b=await req.json() as Record<string,any>,db=database();
if(b.action==='saveDeck'){const d=await validDeck(owner,b.deck);let id=typeof d.id==='string'&&/^[a-f0-9-]{36}$/.test(d.id)?d.id:crypto.randomUUID();const prior=await db.prepare('SELECT owner FROM decks WHERE id=?').bind(id).first<{owner:string}>();if(prior&&prior.owner!==owner)throw Error('This deck belongs to another player.');const data={...d,id};await db.prepare('INSERT INTO decks (id,owner,data,updated) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated=excluded.updated WHERE decks.owner=excluded.owner').bind(id,owner,JSON.stringify(data),Date.now()).run();return reply({deck:data},owner,fresh)}
if(b.action==='openPacks'){const side:Side=b.side==='dark'?'dark':'light';const size=b.size===60?60:40;const packCount=size===60?8:6;const poolCards=sealedCards(side,size);const pool={id:crypto.randomUUID(),name:`${side==='light'?'Rebel':'Imperial'} sealed pool`,side,size,cards:poolCards,packs:packCount,created:Date.now()};await db.prepare('INSERT INTO pools (id,owner,data,created) VALUES (?,?,?,?)').bind(pool.id,owner,JSON.stringify(pool),Date.now()).run();return reply({pool},owner,fresh)}
if(b.action==='createGame'){const deck=await validDeck(owner,b.deck);const mode=['cpu','local','online'].includes(b.mode)?b.mode:'cpu';let opponent=deck.poolId?sealedOpponent(deck.side==='light'?'dark':'light',deck.size):starter(deck.side==='light'?'dark':'light',deck.size);if(mode==='local'&&b.otherDeck){opponent=await validDeck(owner,b.otherDeck);if(opponent.side===deck.side||opponent.size!==deck.size)throw Error('Both decks must use the same size and opposite sides.');if(!!opponent.poolId!==!!deck.poolId)throw Error('Both players must use the same open or sealed format.');}let game=createGame(deck,opponent,mode,b.difficulty==='cadet'?'cadet':'commander');if(mode==='cpu')game=cpuTurn(game);const id=crypto.randomUUID(),code=crypto.randomUUID().replaceAll('-','').slice(0,8).toUpperCase();const row={id,code,owner,guest:null,state:JSON.stringify(game),version:0};await db.prepare('INSERT INTO games (id,code,owner,guest,state,version,updated) VALUES (?,?,?,?,?,0,?)').bind(id,code,owner,null,row.state,Date.now()).run();return reply(view(row,owner),owner,fresh)}
if(b.action==='joinGame'){if(typeof b.code!=='string'||!/^[A-Z0-9]{8}$/.test(b.code.toUpperCase()))throw Error('Enter the 8-character table code.');const row=await db.prepare('SELECT * FROM games WHERE code=?').bind(b.code.toUpperCase()).first<GameRow>();if(!row)throw Error('No table found with that code.');if(row.owner===owner)return reply(view(row,owner),owner,fresh);if(row.guest===owner)return reply(view(row,owner),owner,fresh);if(row.guest)throw Error('This table already has two players.');const g=parse<Game>(row.state);if(g.mode!=='online')throw Error('This table is not an online game.');if(g.winner!==null)throw Error('This table has closed.');if(g.sealed&&!b.deck?.poolId)throw Error('This sealed table needs a deck built from your own sealed pool. Choose a matching saved sealed deck.');const d=b.deck?await validDeck(owner,b.deck):starter(g.players[1].side,g.players[0].hand.length+g.players[0].reserve.length as 40|60);if(!!d.poolId!==!!g.sealed)throw Error('Both players must use the same open or sealed format.');if(d.side!==g.players[1].side)throw Error(`This table needs a ${g.players[1].side} side deck.`);const size=g.players[0].hand.length+g.players[0].reserve.length;if(d.size!==size)throw Error(`This table uses ${size}-card decks.`);const prepared=createGame(starter(g.players[0].side,d.size),d,'online');g.players[1]=prepared.players[1];g.started=true;g.log.unshift('Your friend has joined. The battle begins.');const state=JSON.stringify(g);const result=await db.prepare('UPDATE games SET guest=?,state=?,version=version+1,updated=? WHERE id=? AND guest IS NULL AND version=?').bind(owner,state,Date.now(),row.id,row.version).run();if(!result.meta.changes)throw Error('This table changed. Please try again.');return reply(view({...row,guest:owner,state,version:row.version+1},owner),owner,fresh)}
if(b.action==='gameAction'){const row=await db.prepare('SELECT * FROM games WHERE id=? AND (owner=? OR guest=?)').bind(b.id,owner,owner).first<GameRow>();if(!row)throw Error('Table not found.');if(row.version!==b.version)return reply({error:'The table changed. Updating your view.',conflict:true},owner,fresh,409);let g=parse<Game>(row.state);const actor=g.mode==='local'?g.active:row.owner===owner?0:1;g=act(g,actor,b.move as Action);g=cpuTurn(g);const state=JSON.stringify(g);const result=await db.prepare('UPDATE games SET state=?,version=version+1,updated=? WHERE id=? AND version=?').bind(state,Date.now(),row.id,row.version).run();if(!result.meta.changes)return reply({error:'The table changed. Updating your view.',conflict:true},owner,fresh,409);return reply(view({...row,state,version:row.version+1},owner),owner,fresh)}
return reply({error:'Unknown operation.'},owner,fresh,400)
}catch(e){console.error(e);return reply({error:e instanceof Error?e.message:'Unable to complete that move.'},owner,fresh,400)}}
