import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {load} from '../native-proof/load-engine.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url));
const runtime=mod('runtime'),state=mod('state'),board=mod('board'),battle=mod('battle'),stats=mod('stat-modifiers'),armor=mod('armor-equipment'),combat=mod('combat-modifiers'),defense=mod('defense');
const rules={...mod('premiere-rules').premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true};
const clone=x=>JSON.parse(JSON.stringify(x));
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/armor-results.json',import.meta.url)));
const observed=name=>{const row=oracle.find(r=>r.name===name);assert.ok(row,name);return row};
function fresh(){return runtime.createMatch('armor',60,['light','dark'].map(side=>({side,cards:[...(side==='light'?['1_129','1_132','1_21','1_157','1_105','1_155','1_6']:['5_109','5_109','1_195','1_186','101_5','1_168','1_267','1_201','1_284']),...Array(60).fill(side==='light'?'1_28':'1_194')].slice(0,60)})),rules)}
function pull(m,side,bp,zone='table',location){const c=Object.values(m.cards).find(c=>c.owner===side&&c.blueprint===bp&&c.zone==='reserve');assert.ok(c,bp);state.moveCard(m,c.id,zone);if(location)c.location=location;return c.id}
function prompt(m){const p=runtime.prompt(m,rules,'dark');return p&&runtime.prompt(m,rules,p.side)}
const ids=m=>prompt(m).choices.map(c=>c.id);
function step(m,id){const before=clone(m);const r=runtime.applyCommand(clone(m),rules,prompt(m).side,{revision:m.revision,choice:id},()=>0);assert.deepEqual(m,before);state.assertState(r);for(const side of ['light','dark'])assert.deepEqual(runtime.project(r,rules,side),runtime.project(clone(r),rules,side));return r}
function seek(m,f){for(let n=0;n<500;n++){if(f(m))return m;const cs=ids(m);m=step(m,cs.includes('pass')?'pass':cs.includes('skip-destiny')?'skip-destiny':cs[0])}throw Error('unreached boundary')}
const boundary=(m,kind)=>seek(m,x=>x.stack.at(-1)?.event?.kind===kind);
const priority=(m,side)=>prompt(m).side===side?m:step(m,'pass');
const phase=(m,side,phase)=>seek(m,x=>x.turn.side===side&&x.turn.phase===phase&&x.stack.length===1&&prompt(x).side===side);
function fixture(){let m=fresh();const site=pull(m,'light','1_129');m.locations.push(site);const host=pull(m,'dark','1_194','table',site),other=pull(m,'dark','1_194','table',site),hero=pull(m,'light','1_21','table',site),device=pull(m,'dark','5_109','hand');for(const side of ['light','dark'])for(let i=0;i<12;i++)state.moveCard(m,m.players[side].reserve.at(-1),'force');m=phase(runtime.startTurns(m,rules),'dark','deploy');return{m,site,host,other,hero,device}}
const deploy=f=>boundary(step(f.m,'attach:'+f.device+':'+f.host),'deployed');
const values=(m,id)=>({armor:stats.characterAttribute(m,id,'armor'),defense:defense.defenseValue(m,id),power:board.power(m,id),immunity:combat.attritionImmunity(m,id)});
test('Mandalorian Armor deploys for 3 Force and supplies all three continuous effects',()=>{const f=fixture(),before=f.m.players.dark.force.length,m=deploy(f);assert.equal(before-m.players.dark.force.length,3);assert.equal(m.cards[f.device].attachedTo,f.host);assert.deepEqual(values(m,f.host),{armor:5,defense:5,power:3,immunity:3});assert.equal(board.forfeit(m,f.host),2);assert.equal(mod('ability').ability(m,f.host),1);assert.equal(m.data.armorEquipment[0].mode,'define');assert.deepEqual({name:'deployment',spent:before-m.players.dark.force.length,values:values(m,f.host)},observed('deployment'))});
test('deployment permits own aliens and Imperials, excludes both Vader personas, droids and opponents',()=>{const f=fixture();const alien=pull(f.m,'dark','1_195','table',f.site),droid=pull(f.m,'dark','1_186','table',f.site),vaders=['101_5','1_168'].map(bp=>pull(f.m,'dark',bp,'table',f.site));const actions=ids(f.m);assert.ok(actions.includes('attach:'+f.device+':'+alien));for(const id of [droid,...vaders,f.hero])assert.ok(!actions.includes('attach:'+f.device+':'+id));for(const id of vaders)assert.deepEqual({name:'excluded-'+f.m.cards[id].blueprint,available:actions.includes('attach:'+f.device+':'+id)},observed('excluded-'+f.m.cards[id].blueprint))});
test('insufficient Force omits deployment and a forged choice is rejected atomically',()=>{const f=fixture();while(f.m.players.dark.force.length>2)state.moveCard(f.m,f.m.players.dark.force[0],'used');assert.ok(!ids(f.m).includes('attach:'+f.device+':'+f.host));assert.throws(()=>step(f.m,'attach:'+f.device+':'+f.host),/choice/i)});
test('uniqueness excludes another armor while on table and its per-turn allowance survives cancellation',()=>{const f=fixture(),second=pull(f.m,'dark','5_109','hand');let m=phase(deploy(f),'dark','deploy');assert.ok(!ids(m).some(id=>id.startsWith('attach:'+second+':')));state.moveCard(m,f.device,'lost');assert.ok(!ids(m).some(id=>id.startsWith('attach:'+second+':')))});
test('canceled attachment has no armor, power or immunity grant',()=>{const f=fixture();let m=step(f.m,'attach:'+f.device+':'+f.host);const r=m.stack.find(x=>x.kind==='resolution'&&x.action.handler==='equipment:attach');r.cancelled=true;m=phase(m,'dark','deploy');assert.equal(m.cards[f.device].zone,'lost');assert.deepEqual(values(m,f.host),{armor:0,defense:1,power:1,immunity:0})});
test('departed and returned target invalidates pending deployment',()=>{const f=fixture();let m=step(f.m,'attach:'+f.device+':'+f.host);state.moveCard(m,f.host,'hand');state.moveCard(m,f.host,'table');m.cards[f.host].location=f.site;m=phase(m,'dark','deploy');assert.equal(m.cards[f.device].zone,'lost');assert.equal(stats.characterAttribute(m,f.host,'armor'),0)});
for(const preexisting of [false,true])test('official AR p28 '+(preexisting?'existing armor is reset and unmodifiable':'new armor is a modifiable definition'),()=>{const f=fixture();if(preexisting)stats.addStatModifier(f.m,f.site,f.host,'armor','define',4);let m=deploy(f);stats.addStatModifier(m,f.site,f.host,'armor','add',2);assert.equal(stats.characterAttribute(m,f.host,'armor'),preexisting?5:7);assert.equal(m.data.armorEquipment[0].mode,preexisting?'reset':'define');m=clone(m);assert.equal(stats.characterAttribute(m,f.host,'armor'),preexisting?5:7)});
test('zero defined armor still counts as existing, but additive-only armor does not create a value',()=>{for(const defined of [false,true]){const f=fixture();stats.addStatModifier(f.m,f.site,f.host,'armor',defined?'define':'add',0);const m=deploy(f);assert.equal(m.data.armorEquipment[0].mode,defined?'reset':'define')}});
test('classification is made at resolution after responses, not when deployment is initiated',()=>{const f=fixture();let m=step(f.m,'attach:'+f.device+':'+f.host);stats.addStatModifier(m,f.site,f.host,'armor','define',4);m=boundary(m,'deployed');assert.equal(m.data.armorEquipment[0].mode,'reset')});
test('a reset stays a reset when an earlier definition expires',()=>{const f=fixture();stats.addStatModifier(f.m,f.site,f.host,'armor','define',4);let m=deploy(f);m.turn.number++;stats.addStatModifier(m,f.site,f.host,'armor','add',2);assert.equal(stats.characterAttribute(m,f.host,'armor'),5)});
test('later reset wins over a definition and restores it when the reset expires',()=>{const f=fixture();let m=deploy(f);stats.addStatModifier(m,f.site,f.host,'armor','add',2,{duration:'source'});stats.addStatModifier(m,f.site,f.host,'armor','reset',3);assert.equal(stats.characterAttribute(m,f.host,'armor'),3);m.turn.number++;assert.equal(stats.characterAttribute(m,f.host,'armor'),7)});
test('armor transfer costs 3, moves all benefits and records the new target attribute context',()=>{const f=fixture();let m=phase(deploy(f),'dark','deploy');stats.addStatModifier(m,f.site,f.other,'armor','define',4);const before=m.players.dark.force.length;m=boundary(step(m,'device-transfer:'+f.device+':'+f.other),'transferred');assert.equal(before-m.players.dark.force.length,3);assert.deepEqual(values(m,f.host),{armor:0,defense:1,power:1,immunity:0});stats.addStatModifier(m,f.site,f.other,'armor','add',2);assert.deepEqual(values(m,f.other),{armor:5,defense:5,power:3,immunity:3});assert.equal(m.data.armorEquipment.length,1);assert.equal(m.data.armorEquipment[0].mode,'reset');assert.deepEqual({name:'transfer',spent:before-m.players.dark.force.length,old:values(m,f.host),new:values(m,f.other)},observed('transfer'))});
test('canceled transfer preserves the prior bearer and all benefits',()=>{const f=fixture();let m=step(phase(deploy(f),'dark','deploy'),'device-transfer:'+f.device+':'+f.other);m.stack.find(x=>x.kind==='resolution'&&x.action.handler==='equipment:attach').cancelled=true;m=phase(m,'dark','deploy');assert.equal(m.cards[f.device].attachedTo,f.host);assert.equal(stats.characterAttribute(m,f.host,'armor'),5);assert.equal(stats.characterAttribute(m,f.other,'armor'),0)});
test('transfer target leaving and returning does not rebind a pending action',()=>{const f=fixture();let m=step(phase(deploy(f),'dark','deploy'),'device-transfer:'+f.device+':'+f.other);state.moveCard(m,f.other,'hand');state.moveCard(m,f.other,'table');m.cards[f.other].location=f.site;m=phase(m,'dark','deploy');assert.equal(m.cards[f.device].attachedTo,f.host);assert.equal(stats.characterAttribute(m,f.host,'armor'),5)});
test('armor and its benefits follow bearer movement and expire on source departure',()=>{const f=fixture();let m=deploy(f);const site=pull(m,'light','1_132');m.locations.push(site);board.moveWithAttachments(m,f.host,site);assert.equal(m.cards[f.device].location,site);assert.equal(stats.characterAttribute(m,f.host,'armor'),5);state.moveCard(m,f.device,'hand');assert.deepEqual(values(m,f.host),{armor:0,defense:1,power:1,immunity:0});assert.deepEqual({name:'departure',values:values(m,f.host)},observed('departure'));state.moveCard(m,f.device,'table');m.cards[f.device].attachedTo=f.host;m.cards[f.device].location=site;assert.equal(stats.characterAttribute(m,f.host,'armor'),0);assert.throws(()=>armor.assertArmorEquipment(m),/original attachment/)});
test('host departure loses attached armor and prevents grants leaking to a returning physical character',()=>{const f=fixture();let m=deploy(f);mod('table').loseFromTable(m,[f.host]);m=seek(m,x=>x.cards[f.host].zone==='lost');assert.equal(m.cards[f.device].zone,'lost');state.moveCard(m,f.host,'table');m.cards[f.host].location=f.site;assert.equal(stats.characterAttribute(m,f.host,'armor'),0)});
for(const attrition of [2,3])test('battle damage respects armor immunity threshold '+attrition,()=>{const f=fixture();let m=phase(deploy(f),'dark','battle');m=boundary(step(m,'battle:'+f.site),'battle-destiny-complete');battle.battle(m).destiny.light=attrition;battle.battle(m).destiny.dark=0;m=boundary(m,'battle-damage');assert.equal(battle.battle(m).attritionProtected.some(ref=>ref.id===f.host),attrition<3);assert.equal(battle.battle(m).power.dark,4)});
for(const total of [5,6])test('lightsaber compares armor defense at '+total,()=>{const f=fixture();let m=deploy(f);const saber=pull(m,'light','1_157');m.cards[saber].attachedTo=f.hero;m.cards[saber].location=f.site;m=phase(m,'light','battle');for(const id of [...m.players.light.reserve])state.moveCard(m,id,'hand');for(const bp of [total===5?'1_28':'1_155','1_105']){const c=Object.values(m.cards).find(c=>c.owner==='light'&&c.blueprint===bp&&c.zone==='hand');state.moveCard(m,c.id,'reserve')}m=boundary(step(m,'battle:'+f.site),'battle-weapons');m=boundary(step(priority(m,'light'),'saber:fire:'+saber+':'+f.host),'weapon-fired');assert.equal(battle.battle(m).saberShots[0].total,total);assert.equal(battle.battle(m).hits.includes(f.host),total>5);assert.equal(board.forfeit(m,f.host),total>5?0:2);assert.deepEqual({name:'hit-'+total,hit:battle.battle(m).hits.includes(f.host),forfeit:board.forfeit(m,f.host)},observed('hit-'+total))});
test('armor registry survives save/load, rejects forged provenance and remains private',()=>{const f=fixture(),m=deploy(f);armor.assertArmorEquipment(clone(m));for(const mutate of [p=>p.mode='add',p=>p.turn=999,p=>p.source.id=f.hero,p=>p.target.version=999]){const bad=clone(m);mutate(bad.data.armorEquipment[0]);assert.throws(()=>armor.assertArmorEquipment(bad))}for(const side of ['light','dark'])assert.ok(!JSON.stringify(runtime.project(m,rules,side)).includes('armorEquipment'))});
for(const canceled of [false,true])test('Comlink armor react '+(canceled?'returns armor to hand without a grant':'grants protection before the battle starts'),()=>{const f=fixture();const com=pull(f.m,'dark','1_201');f.m.cards[com].attachedTo=f.other;f.m.cards[com].location=f.site;let m=phase(f.m,'light','battle');const before=m.players.dark.force.length;m=step(m,'battle:'+f.site);m=priority(m,'dark');const choice='attach:'+f.device+':'+f.host+':react:via:'+com;assert.ok(ids(m).includes(choice));m=step(m,choice);if(canceled)m.stack.find(x=>x.kind==='resolution'&&x.action.handler==='equipment:attach').cancelled=true;m=boundary(m,'battle-weapons');assert.equal(before-m.players.dark.force.length,3);assert.equal(m.cards[f.device].zone,canceled?'hand':'table');assert.equal(stats.characterAttribute(m,f.host,'armor'),canceled?0:5);assert.ok(mod('ground').usage(m).reacted.includes(f.device))});

for(const existing of [false,true])for(const add of [0,2,-2])test('executed GEMP comparison with explicit official-rule exception '+existing+' '+add,()=>{
 const f=fixture();if(existing)stats.addStatModifier(f.m,f.site,f.host,'armor','define',4);const m=deploy(f);stats.addStatModifier(m,f.site,f.host,'armor','add',add);
 const native={name:'query-'+existing+'-'+add,values:values(m,f.host)},reference=observed(native.name);
 if(!existing&&add!==0){
  // AR p28 explicitly uses Mandalorian Armor as the modifiable-definition
  // example. Pinned GEMP Card5_109 always installs ResetArmorModifier.
  assert.deepEqual(reference.values,{armor:5,defense:5,power:3,immunity:3});
  assert.deepEqual(native.values,{armor:5+add,defense:5+add,power:3,immunity:3});
 }else assert.deepEqual(native,reference);
});
