import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {load} from '../native-proof/load-engine.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url));
const runtime=mod('runtime'),state=mod('state'),board=mod('board'),battle=mod('battle');
const bacta=mod('bacta'),table=mod('table'),persona=mod('persona');
const rules={...mod('premiere-rules').premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true};
const clone=x=>JSON.parse(JSON.stringify(x));
function fresh(){return runtime.createMatch('bacta',60,['light','dark'].map(side=>({side,cards:[...(side==='light'?['3_32','3_32','1_12','8_5','3_9','3_9','3_60','3_59','1_129','1_132','1_19','1_19','1_100','1_152','1_6','1_5','1_31','1_40']:['1_284','1_168','1_324','13_86','1_267','1_317','1_317','3_86','3_86']),...Array(60).fill(side==='light'?'1_28':'1_194')].slice(0,60)})),rules)}
function pull(m,side,bp,zone='table',location){const c=Object.values(m.cards).find(c=>c.owner===side&&c.blueprint===bp&&c.zone==='reserve');assert.ok(c,bp);state.moveCard(m,c.id,zone);if(location)c.location=location;return c.id}
function prompt(m){const p=runtime.prompt(m,rules,'dark');return p&&runtime.prompt(m,rules,p.side)}
const ids=m=>prompt(m).choices.map(c=>c.id);
function step(m,id){const before=clone(m);const r=runtime.applyCommand(clone(m),rules,prompt(m).side,{revision:m.revision,choice:id},()=>0);assert.deepEqual(m,before);state.assertState(r);for(const side of ['light','dark'])assert.deepEqual(runtime.project(r,rules,side),runtime.project(clone(r),rules,side));return r}
function seek(m,f){for(let n=0;n<600;n++){if(f(m))return m;const cs=ids(m);m=step(m,cs.includes('pass')?'pass':cs.includes('skip-destiny')?'skip-destiny':cs[0])}throw Error('unreached boundary')}
const boundary=(m,kind)=>seek(m,x=>x.stack.at(-1)?.event?.kind===kind);
const priority=(m,side)=>prompt(m).side===side?m:step(m,'pass');
const phase=(m,side,phase)=>seek(m,x=>x.turn.side===side&&x.turn.phase===phase&&x.stack.length===1&&prompt(x).side===side);

function fixture(side='light',mode='same'){
 let m=fresh();const opposite=side==='light'?'dark':'light',site=pull(m,'light','1_129'),adj=pull(m,'light','1_132');m.locations.push(site,adj);
 const target=pull(m,side,side==='light'?'1_28':'1_194','table',site),second=pull(m,side,side==='light'?'1_28':'1_194','table',site),droid=pull(m,side,side==='light'?'3_9':'3_86','table',mode==='adjacent'?adj:site);
 const enemies=[];for(let i=0;i<10;i++)enemies.push(pull(m,opposite,opposite==='light'?'1_28':'1_194','table',site));
 for(const s of ['light','dark'])for(let i=0;i<10;i++)state.moveCard(m,m.players[s].reserve.at(-1),'force');
 m=phase(runtime.startTurns(m,rules),opposite,'battle');return{m,side,opposite,site,adj,target,second,droid,enemies};
}
function damage(f,hit=true){let m=boundary(step(f.m,'battle:'+f.site),'battle-damage');if(hit)battle.battle(m).hits.push(f.target);return priority(m,f.side)}
const offer=(m,f)=>ids(m).find(id=>id.startsWith('fx:'+f.droid+':'));
const pending=(m,f)=>priority(boundary(step(m,'forfeit:'+f.target),'about-to-forfeit'),f.side);
const finish=m=>boundary(m,'forfeited-to-used');

function setup(n=0){const f=fixture();state.moveCard(f.m,f.droid,'hand');if(n>0){state.moveCard(f.m,f.droid,'table');f.m.cards[f.droid].location=f.site}if(n>1)pull(f.m,'light','3_9','table',f.adj);f.tank=pull(f.m,'light','3_32');return f}
const saveId=f=>'bacta:save:'+f.tank+':'+f.target;
const recoverId=f=>'bacta:recover:'+f.tank+':'+f.target;
function lost(f){return priority(boundary(step(damage(f,false),'forfeit:'+f.target),'forfeited'),'light')}
function saved(f){return boundary(step(lost(f),saveId(f)),'card-stacked')}
function withLuke(n=0){const f=setup(n);state.moveCard(f.m,f.target,'hand');f.target=pull(f.m,'light','1_19','table',f.site);return f}
for(const n of [0,1,2])test('Bacta patient recovery with '+n+' cumulative FX-7 droids',()=>{const f=withLuke(n);let m=saved(f);assert.equal(m.cards[f.target].zone,'stacked');assert.equal(m.cards[f.target].stackedOn,f.tank);m=phase(m,'light','deploy');const force=m.players.light.force.length;assert.ok(ids(m).includes(recoverId(f)));m=boundary(step(m,recoverId(f)),'card-to-hand');assert.equal(m.cards[f.target].zone,'hand');assert.equal(force-m.players.light.force.length,Math.max(0,3-2*n))});
test('Bacta deployment costs four and observes unique play restrictions',()=>{const f=setup();state.moveCard(f.m,f.tank,'hand');const other=pull(f.m,'light','3_32','hand');let m=phase(f.m,'light','deploy'),force=m.players.light.force.length;m=boundary(step(m,'bacta:deploy:'+f.tank),'deployed');assert.equal(force-m.players.light.force.length,4);m=phase(m,'light','deploy');assert.ok(!ids(m).includes('bacta:deploy:'+other))});
test('decline leaves target lost; droids and Force loss never offer a patient',()=>{const f=setup();let m=lost(f);assert.ok(ids(m).includes(saveId(f)));m=boundary(step(m,'pass'),'battle-damage');assert.equal(m.cards[f.target].zone,'lost');for(const kind of ['force-lost','forfeited-to-used'])assert.deepEqual(bacta.bactaActions(m,{kind:'window',timing:'response',event:{kind,card:f.target}},'light'),[]);const c=pull(m,'light','1_5','lost');assert.deepEqual(bacta.bactaActions(m,{kind:'window',timing:'response',event:{kind:'character-lost',card:c}},'light'),[])});
test('ordinary table loss offers a patient with original Lost identity',()=>{const f=setup();let m=f.m;table.loseFromTable(m,[f.target]);runtime.openWindow(m,'response','light',{kind:'character-lost',card:f.target});assert.ok(ids(m).includes(saveId(f)));m=boundary(step(m,saveId(f)),'card-stacked');assert.equal(m.cards[f.target].zone,'stacked')});
test('patient is inactive, public, outside Life Force, and still counts for uniqueness',()=>{const f=withLuke(),m=saved(f);const duplicate=pull(m,'light','1_19','hand');assert.equal(persona.canEnterTable(m,duplicate),false);assert.ok(!battle.members(m,'light').includes(f.target));for(const side of ['light','dark']){const v=runtime.project(m,rules,side);assert.ok(v.game?.table?.some(c=>c.id===f.target)||v.table?.some(c=>c.id===f.target));}assert.equal(state.lifeForce(m,'light'),m.players.light.reserve.length+m.players.light.force.length+m.players.light.used.length+m.players.light.destiny.length)});
test('one patient prevents saving a second loss',()=>{const f=setup();let m=saved(f);m=priority(boundary(m,'battle-damage'),'light');m=priority(boundary(step(m,'forfeit:'+f.second),'forfeited'),'light');assert.ok(!ids(m).some(id=>id.startsWith('bacta:save:')))});
for(const stage of ['opportunity','pending','removal'])test('patient cannot reuse a Lost visit after departure at '+stage,()=>{const f=setup();let m=lost(f);if(stage!=='opportunity')m=step(m,saveId(f));if(stage==='removal')m=boundary(m,'about-to-remove-just-lost');state.moveCard(m,f.target,'hand');state.moveCard(m,f.target,'lost');if(stage==='opportunity')assert.ok(!ids(m).includes(saveId(f)));else{m=seek(m,x=>!x.stack.some(q=>q.kind==='resolution'&&q.action.handler.startsWith('bacta:')));assert.equal(m.cards[f.target].zone,'lost')}});
for(const stage of ['pending','removal'])test('departed Tank cannot receive a patient at '+stage,()=>{const f=setup();let m=step(lost(f),saveId(f));if(stage==='removal')m=boundary(m,'about-to-remove-just-lost');state.moveCard(m,f.tank,'hand');state.moveCard(m,f.tank,'table');m=seek(m,x=>!x.stack.some(q=>q.kind==='resolution'&&q.action.handler.startsWith('bacta:')));assert.equal(m.cards[f.target].zone,'lost')});
test('attachments remain Lost while patient moves to Tank',()=>{const f=setup(),gun=pull(f.m,'light','1_152');f.m.cards[gun].attachedTo=f.target;f.m.cards[gun].location=f.site;let m=saved(f);assert.equal(m.cards[gun].zone,'lost');assert.equal(m.cards[f.target].zone,'stacked')});
test('losing Tank disposes patient with owner-controlled Lost ordering',()=>{const f=withLuke();let m=saved(f);assert.throws(()=>state.moveCard(m,f.tank,'lost'));table.loseFromTable(m,[f.tank]);assert.equal(m.cards[f.target].zone,'leaving');m=step(m,'place-lost:'+f.target);assert.equal(m.cards[f.target].zone,'lost');assert.equal(m.cards[f.tank].zone,'lost');assert.equal(persona.canEnterTable(m,pull(m,'light','1_19','hand')),true)});
test('canceled recovery still spends cost and phase allowance',()=>{const f=withLuke();let m=phase(saved(f),'light','deploy');const before=m.players.light.force.length;m=step(m,recoverId(f));m=seek(m,x=>x.stack.at(-2)?.action?.handler==='bacta:recover'&&!x.stack.at(-2)?.awaitingResponses);m.stack.at(-2).cancelled=true;m=phase(m,'light','deploy');assert.equal(m.cards[f.target].zone,'stacked');assert.equal(before-m.players.light.force.length,3);assert.ok(!ids(m).includes(recoverId(f)));m.turn.number++;assert.ok(ids(m).includes(recoverId(f)))});
test('saving is not retrieval and FX reductions do not require the same location',()=>{const f=withLuke(2);pull(f.m,'dark','13_86');let m=saved(f);assert.equal(bacta.bactaCost(m,f.tank,f.target),0);state.moveCard(m,f.droid,'hand');assert.equal(bacta.bactaCost(m,f.tank,f.target),1);assert.ok(!ids(m).some(x=>x.startsWith('plans:')))});
test('stacked relation and pending save survive refresh and reject corruption',()=>{const f=setup(),m=saved(f);rules.validate(clone(m));for(const change of [x=>x.cards[f.target].stackedOn=f.site,x=>x.cards[f.target].stackedOn=f.target,x=>x.cards[f.target].zone='hand']){const bad=clone(m);change(bad);assert.throws(()=>{state.assertState(bad);rules.validate(bad)})}});
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/bacta-results.json',import.meta.url)));
for(const row of oracle)test('executed GEMP patient lifecycle '+row.name+(row.name==='asterisk'?' (official AR p138 exception)':''),()=>{const f=withLuke(row.name==='one-fx'?1:row.name==='two-fx'?2:0);if(['droid','asterisk'].includes(row.name)){state.moveCard(f.m,f.target,'hand');f.target=pull(f.m,'light',row.name==='droid'?'1_5':'1_12','table',f.site)}let gun;if(row.name==='attachments'){gun=pull(f.m,'light','1_152');f.m.cards[gun].attachedTo=f.target;f.m.cards[gun].location=f.site}let m=damage(f,false);const before=battle.battle(m).damage.light;m=priority(boundary(step(m,'forfeit:'+f.target),'forfeited'),'light');const offered=ids(m).includes(saveId(f));if(offered&&row.name!=='skip')m=boundary(step(m,saveId(f)),'card-stacked');const stacked=m.cards[f.target].zone==='stacked',lost=m.cards[f.target].zone==='lost',paid=before-battle.battle(m).damage.light,gunLost=!!gun&&m.cards[gun].zone==='lost';let cost=-1,hand=false;if(stacked){m=phase(m,'light','deploy');const force=m.players.light.force.length;m=boundary(step(m,recoverId(f)),'card-to-hand');cost=force-m.players.light.force.length;hand=m.cards[f.target].zone==='hand'}if(row.name==='asterisk')assert.equal(row.cost,1,'Preserve the observed reference discrepancy');assert.deepEqual({name:row.name,offered,stacked,lost,paid,cost,hand,gunLost,inactive:stacked},row.name==='asterisk'?{...row,cost:0}:row)});

test('asterisk patient deploy value is zero under the official Bacta exception',()=>{const f=setup();state.moveCard(f.m,f.target,'hand');f.target=pull(f.m,'light','1_12','table',f.site);let m=phase(saved(f),'light','deploy');assert.equal(bacta.bactaCost(m,f.tank,f.target),0);const force=m.players.light.force.length;m=boundary(step(m,recoverId(f)),'card-to-hand');assert.equal(m.players.light.force.length,force)});
test('losing Tank during paid recovery cannot move its lost patient into hand',()=>{const f=withLuke();let m=phase(saved(f),'light','deploy');m=step(m,recoverId(f));m=seek(m,x=>x.stack.at(-2)?.action?.handler==='bacta:recover'&&!x.stack.at(-2)?.awaitingResponses);table.loseFromTable(m,[f.tank]);m=step(m,'place-lost:'+f.target);m=phase(m,'light','deploy');assert.equal(m.cards[f.target].zone,'lost');assert.equal(m.cards[f.tank].zone,'lost');assert.equal(m.data.bactaUses.length,1)});
test('opposing FX-10 and inactive FX-7 do not reduce Bacta X',()=>{const f=withLuke();pull(f.m,'dark','3_86','table',f.site);assert.equal(bacta.bactaCost(f.m,f.tank,f.target),3)});
