// Playwright 1.62.1 / Chromium 1234; isolated projection and command fixtures.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {chromium} from 'playwright';
import {load} from '../native-proof/load-engine.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url));
const runtime=mod('runtime'),state=mod('state');
const rules={...mod('premiere-rules').premiereRules,supports:()=>true,starting:undefined,setupComplete:()=>true};
function fixture(){let m=runtime.createMatch('bacta-browser-fixture',60,['light','dark'].map(side=>({side,cards:[...(side==='light'?['3_32','1_19','1_129']:['1_284']),...Array(60).fill(side==='light'?'1_28':'1_194')].slice(0,60)})),rules);const take=bp=>Object.values(m.cards).find(c=>c.blueprint===bp).id,tank=take('3_32'),patient=take('1_19'),site=take('1_129');state.moveCard(m,site,'table');m.locations.push(site);state.moveCard(m,tank,'table');state.moveCard(m,patient,'stacked');m.cards[patient].stackedOn=tank;for(let i=0;i<5;i++)state.moveCard(m,m.players.light.reserve.at(-1),'force');m=runtime.startTurns(m,rules);for(let i=0;i<200;i++){const p=runtime.prompt(m,rules,'light');if(m.turn.side==='light'&&m.turn.phase==='deploy'&&p.choices.some(c=>c.id.startsWith('bacta:recover')))break;m=runtime.applyCommand(m,rules,p.side,{revision:m.revision,choice:'pass'})}return m}
const origin=process.env.NATIVE_UI_ORIGIN||'http://localhost:5173',out=process.env.NATIVE_UI_OUTPUT||'/private/tmp/swccg-bacta-browser';fs.mkdirSync(out,{recursive:true});
assert.equal(JSON.parse(fs.readFileSync(new URL('../../node_modules/playwright/package.json',import.meta.url))).version,'1.62.1');
const browser=await chromium.launch({headless:true}),errors=[];
try{for(const [width,height] of [[1440,1000],[834,1112],[390,844]]){let m=fixture();const context=await browser.newContext({viewport:{width,height}});await context.route('**/api/matches/**',async route=>{const body=route.request().postDataJSON();if(body?.operation==='command'){m=runtime.applyCommand(m,rules,'light',{revision:body.revision,choice:body.choice});for(let n=0;n<60&&m.stack.some(f=>f.kind==='resolution'&&f.action.handler.startsWith('bacta:'));n++){const p=runtime.prompt(m,rules,'light');m=runtime.applyCommand(m,rules,p.side,{revision:m.revision,choice:'pass'})}}await route.fulfill({json:{id:m.id,mode:'pvp',side:'light',rules:m.rules,deckSize:60,revision:m.revision,serverTime:Date.now(),waitingForOpponent:false,created:0,updated:0,game:runtime.project(m,rules,'light')}})});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/matches/'+m.id+'?progress-report');await page.getByText('PATIENT · INACTIVE',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:out+'/patient-'+width+'.png',fullPage:true});await page.getByRole('button',{name:'Inspect Luke Skywalker',exact:true}).click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');if(width<640)await page.getByRole('button',{name:'Actions',exact:false}).click();await page.getByRole('button',{name:/Bacta Tank · return Luke Skywalker to hand/}).click();await page.getByText('PATIENT · INACTIVE',{exact:true}).waitFor({state:'hidden'});await page.reload();await page.locator('.native-player').first().waitFor();assert.equal(await page.getByText('PATIENT · INACTIVE',{exact:true}).count(),0);assert.ok(Object.values(m.cards).some(c=>c.blueprint==='1_19'&&c.zone==='hand'));await context.close();}assert.deepEqual(errors,[]);console.log('Patient display, inspection, recovery and refresh passed at 1440, 834 and 390px.');}finally{await browser.close()}
