import test from 'node:test';
import assert from 'node:assert/strict';
import {pull,state,rules,runtime,clone,ids,step,seek,priority,load} from './vessels-fixture.mjs';
import {battleAdditionFixture as fixture,addition} from './battle-interrupts-fixture.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url)),policy=mod('battle-destiny'),board=mod('board');
const resolve=(m,card)=>seek(m,x=>x.cards[card].zone!=='playing');
for(const [mode,key,amount] of [['skywalkers','skywalkers',2],['strong','strong',1],['vader','strong',2],['warrior','courage',1],['leia','courage',2],['nowhere','nowhere',1]])test(mode+' adds actual battle draws, survives JSON recovery and follows Used/Lost destination',()=>{
 const f=fixture(mode),before=policy.battleDrawPolicy(f.m,'light').count,force=f.m.players.light.force.length;const action=addition(f.m,f[key],amount);assert.ok(ids(f.m).includes(action));let m=step(f.m,action);m=resolve(clone(m),f[key]);assert.equal(policy.battleDrawPolicy(m,'light').count,before+amount);assert.equal(m.players.light.force.length,force-(mode==='nowhere'?1:0));assert.equal(m.cards[f[key]].zone,mode==='nowhere'?'used':'lost');
});
test('ordinary warrior can draw added destiny without four ability',()=>{const f=fixture('warrior');assert.equal(policy.battleDrawPolicy(f.m,'light').count,0);const m=resolve(step(f.m,addition(f.m,f.courage)),f.courage);assert.equal(policy.battleDrawPolicy(m,'light').count,1);});
test('Skywalkers is weapons-only and targets participating Luke and Leia',()=>{const f=fixture();assert.ok(addition(f.m,f.skywalkers));f.m.data.battle.departed=[f.leia];assert.equal(addition(f.m,f.skywalkers),undefined);f.m.data.battle.departed=[];f.m.data.battle.stage='power';assert.equal(addition(f.m,f.skywalkers),undefined);});
test('Out Of Nowhere requires enemy initiation and cannot be delayed to weapons',()=>{const own=fixture('nowhere',true);assert.equal(addition(own.m,own.nowhere),undefined);const f=fixture('nowhere');f.m=priority(seek(f.m,m=>m.stack.at(-1)?.event?.kind==='battle-weapons'),'light');assert.equal(addition(f.m,f.nowhere),undefined);});
test('Out Of Nowhere checks modified maneuver',()=>{const f=fixture('nowhere');mod('stat-modifiers').addStatModifier(f.m,f.ywing,f.ywing,'maneuver','reset',3);assert.equal(addition(f.m,f.nowhere),undefined);});
test('a canceled paid Out Of Nowhere keeps its Force cost and creates no bonus',()=>{const f=fixture('nowhere'),force=f.m.players.light.force.length;let m=step(f.m,addition(f.m,f.nowhere));m=seek(m,x=>x.stack.at(-2)?.action?.handler==='battle-add:play'&&!x.stack.at(-2).awaitingResponses);m.stack.at(-2).cancelled=true;m=resolve(m,f.nowhere);assert.equal(m.players.light.force.length,force-1);assert.equal(m.cards[f.nowhere].zone,'lost');assert.equal(m.data.battle.drawModifiers,undefined);});
test('optional bonus remains after a target leaves during responses and after resolution',()=>{const f=fixture();let m=step(f.m,addition(f.m,f.skywalkers));state.moveCard(m,f.leia,'lost');m=resolve(m,f.skywalkers);assert.equal(policy.battleDrawPolicy(m,'light').count,2);state.moveCard(m,f.leia,'table');m.cards[f.leia].location=f.remote;assert.equal(policy.battleDrawPolicy(m,'light').count,2);});
test('same title additions are not cumulative while different titles combine',()=>{const f=fixture('vader'),second=pull(f.m,'light','1_116','hand');let m=priority(resolve(step(f.m,addition(f.m,f.strong)),f.strong),'light');m=priority(resolve(step(m,addition(m,second)),second),'light');assert.equal(policy.battleDrawPolicy(m,'light').count,2);state.moveCard(m,f.leia,'table');m.cards[f.leia].location=f.site;mod('battle').syncBattle(m);m=resolve(step(m,addition(m,f.skywalkers)),f.skywalkers);assert.equal(policy.battleDrawPolicy(m,'light').count,5);});
test('unique Interrupt turn allowance is consumed even by canceled play',()=>{const f=fixture(),second=pull(f.m,'light','1_110','hand');let m=step(f.m,addition(f.m,f.skywalkers));m.stack.find(x=>x.action?.handler==='battle-add:play').cancelled=true;m=priority(resolve(m,f.skywalkers),'light');assert.ok(!ids(m).some(id=>id.startsWith('battle-add:'+second+':')));});
test('Warrior’s Courage excludes attacking and non-alone characters, including a supporting droid',()=>{const own=fixture('warrior',true);assert.equal(addition(own.m,own.courage),undefined);const f=fixture('warrior');state.moveCard(f.m,f.droid,'table');f.m.cards[f.droid].location=f.site;mod('battle').syncBattle(f.m);assert.equal(addition(f.m,f.courage),undefined);});
test('Leia permits separate one- and two-destiny courage choices',()=>{const f=fixture('leia');assert.ok(addition(f.m,f.courage,1));assert.ok(addition(f.m,f.courage,2));});
test('Force Is Strong uses current Imperial ability and honors Vader persona',()=>{const f=fixture('strong');mod('ability').addAbilityModifier(f.m,f.pilot,f.pilot,'reset',2);assert.equal(addition(f.m,f.strong),undefined);mod('ability').addAbilityModifier(f.m,f.pilot,f.pilot,'add',1);assert.equal(addition(f.m,f.strong),undefined);});
test('physical limits and ability requirements still constrain the scheduled additions',()=>{const f=fixture();let m=resolve(step(f.m,addition(f.m,f.skywalkers)),f.skywalkers);policy.addBattleDrawModifier(m,f.site,'light','limit',1);assert.deepEqual(policy.battleDrawPolicy(m,'light'),{ordinary:3,minimum:0,count:3,limit:1});policy.addBattleDrawModifier(m,f.site,'light','ability',9);assert.equal(policy.battleDrawPolicy(m,'light').count,0);});
test('Boring Conversation cancels Skywalkers before its addition',()=>{const f=fixture();let m=priority(step(f.m,addition(f.m,f.skywalkers)),'dark');const cancel=ids(m).find(id=>id.startsWith('scomp:play:'+f.boring+':cancel'));assert.ok(cancel);m=resolve(step(m,cancel),f.boring);assert.equal(m.cards[f.skywalkers].zone,'lost');assert.equal(m.data.battle.drawModifiers,undefined);});
test('Skywalkers cancels Imperial Barrier without needing Luke or Leia in battle',()=>{const f=fixture('warrior');f.m.turn.phase='deploy';f.m.data.battle.stage='complete';f.m.stack=[{kind:'window',serial:++f.m.serial,timing:'phase',priority:'light',passes:0,completed:[]}];f.m.turn.side='light';const troop=pull(f.m,'light','1_28','hand');let m=step(f.m,'deploy:'+troop+':'+f.site);m=priority(seek(m,x=>x.stack.at(-1)?.event?.kind==='deployed'),'dark');const barrier=ids(m).find(id=>id.startsWith('barrier:'+f.barrier));assert.ok(barrier);m=priority(step(m,barrier),'light');const cancel=ids(m).find(id=>id.startsWith('scomp:play:'+f.skywalkers+':cancel'));assert.ok(cancel);m=resolve(step(m,cancel),f.skywalkers);assert.equal(m.cards[f.barrier].zone,'lost');assert.equal(m.cards[f.skywalkers].zone,'lost');assert.equal(mod('ground').barred(m,troop),false);});
test('Leia adds power only to other Rebels present with her at a Death Star site',()=>{const f=fixture();const troop=pull(f.m,'light','1_28','table',f.remote);state.moveCard(f.m,f.leia,'table');f.m.cards[f.leia].location=f.remote;assert.equal(board.power(f.m,troop),2);assert.equal(board.power(f.m,f.leia),3);f.m.cards[f.leia].location=f.site;assert.equal(board.power(f.m,troop),1);});
test('Leia immunity and continuous bonus disappear with blanked game text',()=>{const f=fixture('leia'),immunity=mod('combat-modifiers');assert.equal(immunity.attritionImmunityValues(f.m,f.leia).lessThan,2);mod('game-text').suppressGameText(f.m,f.leia,f.leia);assert.equal(immunity.attritionImmunityValues(f.m,f.leia).lessThan,0);});
for(const change of ['window','amount','target'])test('tampered battle addition '+change+' is rejected after save',()=>{const f=fixture(),m=step(f.m,addition(f.m,f.skywalkers)),p=m.stack.find(x=>x.action?.handler==='battle-add:play').action.payload;if(change==='window')p.window=-1;if(change==='amount')p.amount=9;if(change==='target')p.targets[1]=p.targets[0];assert.throws(()=>rules.validate(m),/battle addition|Skywalkers/);});
test('paid addition is absent when no Force remains',()=>{const f=fixture('nowhere');for(const id of [...f.m.players.light.force])state.moveCard(f.m,id,'used');assert.ok(!ids(f.m).some(id=>id.startsWith('battle-add:'+f.nowhere+':')));});
for(const cap of [null,1])test('scheduled additions produce physical battle draws through power resolution, cap '+cap,()=>{const f=fixture();let m=resolve(step(f.m,addition(f.m,f.skywalkers)),f.skywalkers);if(cap!==null)policy.addBattleDrawModifier(m,f.site,'light','limit',cap);for(let i=0;i<300&&!m.data.battle.totalsReady;i++){const choices=ids(m);m=step(clone(m),choices.find(id=>id==='draw-destiny')??choices.find(id=>id==='pass')??choices[0]);}assert.equal(m.data.battle.totalsReady,true);assert.equal(m.data.battle.destinyResults.light.draws.length,cap??3);});
test('computer prefers the larger Leia addition and avoids a redundant same-title play',()=>{const cpu=mod('computer'),f=fixture('leia');let v=runtime.project(f.m,rules,'light');v.prompt.choices=v.prompt.choices.filter(c=>c.id.startsWith('battle-add:')||c.id==='pass');assert.equal(cpu.chooseComputerAction(v,'light'),addition(f.m,f.courage,2));const g=fixture('vader'),second=pull(g.m,'light','1_116','hand');let m=priority(resolve(step(g.m,addition(g.m,g.strong)),g.strong),'light');v=runtime.project(m,rules,'light');v.prompt.choices=v.prompt.choices.filter(c=>c.id.startsWith('battle-add:'+second+':')||c.id==='pass');assert.equal(cpu.chooseComputerAction(v,'light'),'pass');});
const {default:fs}=await import('node:fs');
const observations=JSON.parse(fs.readFileSync(new URL('./gemp/battle-interrupt-results.json',import.meta.url)));
for(const row of observations)test('executed GEMP battle Interrupt comparison '+row.mode,()=>{
 if(row.mode==='leia-text'){const f=fixture(),troop=pull(f.m,'light','1_28','table',f.remote);state.moveCard(f.m,f.leia,'table');f.m.cards[f.leia].location=f.remote;assert.deepEqual({mode:row.mode,leiaPower:board.power(f.m,f.leia),troopPower:board.power(f.m,troop),immunity:mod('combat-modifiers').attritionImmunityValues(f.m,f.leia).lessThan},row);return;}
 const mode=row.mode.startsWith('sky')?'skywalkers':row.mode==='strong-vader'?'vader':row.mode==='warrior-droid'?'warrior':row.mode==='nowhere-own'?'nowhere':row.mode,f=fixture(mode,row.mode==='nowhere-own');
 if(row.mode==='warrior-droid'){state.moveCard(f.m,f.droid,'table');f.m.cards[f.droid].location=f.site;mod('battle').syncBattle(f.m);}
 const card=f[mode==='skywalkers'?'skywalkers':mode==='vader'||mode==='strong'?'strong':mode==='nowhere'?'nowhere':'courage'],a=addition(f.m,card,mode==='leia'?2:undefined),before=policy.battleDrawPolicy(f.m,'light').count,force=f.m.players.light.force.length;let m=f.m;
 if(a){m=step(m,a);if(row.mode==='sky-leia-leaves')state.moveCard(m,f.leia,'lost');if(row.mode==='sky-canceled'){m=priority(m,'dark');m=step(m,ids(m).find(id=>id.startsWith('scomp:play:'+f.boring+':cancel')));}m=resolve(m,card);}
 assert.deepEqual({mode:row.mode,before,after:policy.battleDrawPolicy(m,'light').count,offered:!!a,forcePaid:force-m.players.light.force.length,lost:m.cards[card].zone==='lost',used:m.cards[card].zone==='used'},row);
});
test('battle Interrupt oracle receipt binds executed source and observations',async()=>{const {createHash}=await import('node:crypto'),p=JSON.parse(fs.readFileSync(new URL('./gemp/battle-interrupt-provenance.json',import.meta.url)));for(const [f,sha]of Object.entries(p.files))assert.equal(createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+f,import.meta.url))).digest('hex'),sha);assert.equal(observations.length,p.observations);});
