import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {load} from '../native-proof/load-engine.mjs';
const module=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url));
const runtime=module('runtime'),state=module('state'),stats=module('ability'),board=module('board'),combat=module('battle'),mods=module('combat-modifiers');
const {premiereRules}=module('premiere-rules');
const rules={...premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true};
const clone=x=>JSON.parse(JSON.stringify(x)),other=s=>s==='light'?'dark':'light';
function fresh(beginner=false){return runtime.createMatch('battle-courage',60,['light','dark'].map(side=>({side,cards:[...(side==='light'?['5_41','5_41',beginner?'101_2':'1_19','1_109','1_129','1_124','9_24','1_21','1_4']:['5_141','5_141',beginner?'101_5':'1_168','1_267','1_284','1_285','4_103','9_109','1_171']),...Array(60).fill(side==='light'?'1_28':'1_194')].slice(0,60)})),rules)}
function pull(m,side,bp,zone='table',site){const c=Object.values(m.cards).find(c=>c.owner===side&&c.blueprint===bp&&c.zone==='reserve');assert.ok(c,'fixture '+bp);state.moveCard(m,c.id,zone);if(site)m.cards[c.id].location=site;return c.id}
function prompt(m){const p=runtime.prompt(m,rules,'dark');return p&&runtime.prompt(m,rules,p.side)}
const ids=m=>prompt(m).choices.map(c=>c.id);
function step(m,id){const before=clone(m),r=runtime.applyCommand(clone(m),rules,prompt(m).side,{revision:m.revision,choice:id},()=>0);assert.deepEqual(m,before);state.assertState(r);for(const s of ['dark','light'])assert.deepEqual(runtime.project(r,rules,s),runtime.project(clone(r),rules,s));return r}
function seek(m,predicate){for(let n=0;n<900;n++){if(predicate(m))return m;const p=prompt(m);assert.ok(p,'ended too soon');m=step(m,p.choices.some(c=>c.id==='pass')?'pass':p.choices.some(c=>c.id==='skip-destiny')?'skip-destiny':p.choices[0].id)}throw Error('boundary not reached')}
function phase(m,p='battle',side='dark'){if(m.status==='setup')m=runtime.startTurns(m,rules);return seek(m,x=>x.turn.side===side&&x.turn.phase===p&&x.stack.length===1)}
const priority=(m,side)=>prompt(m).side===side?m:step(m,'pass');
const boundary=(m,kind)=>seek(m,x=>x.stack.at(-1)?.event?.kind===kind);
function fixture(beginner=false){let m=fresh(beginner);const site=pull(m,'light','1_129');m.locations.push(site);const hero={},card={},copy={},sense={},troop={};for(const side of ['light','dark']){hero[side]=pull(m,side,side==='light'?(beginner?'101_2':'1_19'):(beginner?'101_5':'1_168'),'table',site);card[side]=pull(m,side,side==='light'?'5_41':'5_141','hand');copy[side]=pull(m,side,side==='light'?'5_41':'5_141','hand');sense[side]=pull(m,side,side==='light'?'1_109':'1_267','hand');troop[side]=pull(m,side,side==='light'?'1_28':'1_194','hand');for(let i=0;i<8;i++)state.moveCard(m,m.players[side].reserve.at(-1),'force')}m=phase(m);return{m,site,hero,card,copy,sense,troop}}
const start=f=>boundary(step(f.m,'battle:'+f.site),'battle-weapons');
const play=(m,f,side)=>step(priority(m,side),'duel-interrupt:battle:'+f.card[side]+':'+f.hero[side]);
const snapshot=(m,f,side,name)=>({name,ability:stats.ability(m,f.hero[side]),power:board.power(m,f.hero[side]),battleAbility:stats.abilityForBattleDestiny(m,f.hero[side]),immunity:mods.attritionImmunity(m,f.hero[side]),sourceLost:m.cards[f.card[side]].zone==='lost'});
for(const side of ['light','dark'])for(const change of [false,true])test(side+' battle Interrupt resolves current ability, cancels immunity and excludes only destiny ability '+change,()=>{const f=fixture();let m=play(start(f),f,side);if(change)stats.addAbilityModifier(m,f.site,f.hero[side],'reset',2.5);m=boundary(m,'battle-weapons');const expected=side==='light'?4:6;assert.deepEqual(snapshot(m,f,side,side+'-'+(change?'ability-change':'normal')),{name:side+'-'+(change?'ability-change':'normal'),ability:change?2.5:expected,power:(side==='light'?3:6)+(change?2.5:expected),battleAbility:0,immunity:0,sourceLost:true});assert.ok(board.presence(m,side,f.site));m=priority(m,side);assert.ok(!ids(m).some(id=>id.startsWith('duel-interrupt:battle:'+f.copy[side])));const ref=JSON.parse(fs.readFileSync(new URL('./gemp/battle-courage-results.json',import.meta.url)));assert.deepEqual(snapshot(m,f,side,side+'-'+(change?'ability-change':'normal')),ref.find(r=>r.name===side+'-'+(change?'ability-change':'normal')))});
for(const side of ['light','dark'])test(side+' cannot trade nonexistent immunity on the beginner persona',()=>{const f=fixture(true);let m=priority(start(f),side);assert.ok(!ids(m).some(id=>id.startsWith('duel-interrupt:battle:')));assert.throws(()=>play(m,f,side),/Illegal/)});
test('battle function is restricted to ordinary weapons opportunities and participating targets',()=>{const f=fixture();assert.ok(!ids(f.m).some(id=>id.startsWith('duel-interrupt:battle:')));let m=start(f);assert.ok(ids(m).includes('duel-interrupt:battle:'+f.card.dark+':'+f.hero.dark));m=boundary(m,'battle-destiny-before');assert.ok(!ids(m).some(id=>id.startsWith('duel-interrupt:battle:')))});
test('Sense cancels all three battle effects but does not refund unique play',()=>{const f=fixture();let m=start(f);const zero=pull(m,'light','1_124','hand');state.moveCard(m,zero,'reserve');m=play(m,f,'dark');m=step(m,'cancel:play:'+f.sense.light+':'+f.card.dark+':'+f.hero.light);m=boundary(m,'battle-weapons');assert.equal(board.power(m,f.hero.dark),6);assert.equal(stats.abilityForBattleDestiny(m,f.hero.dark),6);assert.equal(mods.attritionImmunity(m,f.hero.dark),5);m=priority(m,'dark');assert.ok(!ids(m).some(id=>id.startsWith('duel-interrupt:battle:'+f.copy.dark)))});
for(const mode of ['leave','return'])test('target '+mode+' cannot acquire the original pending trade',()=>{const f=fixture();let m=play(start(f),f,'dark');state.moveCard(m,f.hero.dark,'hand');if(mode==='return'){state.moveCard(m,f.hero.dark,'table');m.cards[f.hero.dark].location=f.site}m=seek(m,x=>x.cards[f.card.dark].zone==='lost');assert.equal(mods.combatPowerBonus(m,f.hero.dark),0)});
test('resolved trade lasts through phase changes, but expires next turn or target reentry',()=>{const f=fixture();let m=boundary(play(start(f),f,'dark'),'battle-weapons');stats.addAbilityModifier(m,f.site,f.hero.dark,'reset',2);assert.equal(board.power(m,f.hero.dark),12);assert.equal(stats.ability(m,f.hero.dark),2);m.turn.phase='move';assert.equal(board.power(m,f.hero.dark),12);m.turn.number++;assert.equal(board.power(m,f.hero.dark),6);assert.equal(mods.attritionImmunity(m,f.hero.dark),5);const g=fixture();m=boundary(play(start(g),g,'dark'),'battle-weapons');state.moveCard(m,g.hero.dark,'hand');state.moveCard(m,g.hero.dark,'table');m.cards[g.hero.dark].location=g.site;assert.equal(board.power(m,g.hero.dark),6);assert.equal(stats.abilityForBattleDestiny(m,g.hero.dark),6)});
function damage(f,n){mods.addCombatModifier(f.m,f.site,f.hero.dark,'power-add',10);let m=boundary(start(f),'battle-destiny-complete');combat.battle(m).destiny.light=n;combat.battle(m).destiny.dark=0;return boundary(m,'battle-damage')}
test('immunity permits passing unpaid attrition, but never unpaid battle damage or a hit',()=>{const f=fixture();let m=damage(f,4);assert.equal(combat.damagePending(m,'dark'),false);assert.ok(combat.battle(m).attritionProtected.some(r=>r.id===f.hero.dark));combat.battle(m).hits.push(f.hero.dark);assert.equal(combat.damagePending(m,'dark'),true);combat.battle(m).hits=[];combat.battle(m).damageLedger.dark.base=3;assert.equal(combat.damagePending(m,'dark'),true)});
test('initial total, not shrinking attrition, determines immunity',()=>{const f=fixture();state.moveCard(f.m,f.troop.dark,'table');f.m.cards[f.troop.dark].location=f.site;let m=damage(f,5);assert.equal(combat.battle(m).attritionProtected.some(r=>r.id===f.hero.dark),false);m=step(priority(m,'dark'),'forfeit:'+f.troop.dark);m=boundary(m,'battle-damage');assert.ok(combat.battle(m).attrition.dark<5);assert.equal(combat.damagePending(m,'dark'),true)});
test('immune characters may be voluntarily forfeited and credit both balances',()=>{const f=fixture();let m=damage(f,2);assert.equal(combat.damagePending(m,'dark'),false);assert.ok(ids(priority(m,'dark')).includes('forfeit:'+f.hero.dark));m=step(priority(m,'dark'),'forfeit:'+f.hero.dark);m=seek(m,x=>x.cards[f.hero.dark].zone==='lost');assert.equal(combat.battle(m).attrition.dark,0)});
test('immunity changes after damage begins cannot rewrite the frozen status',()=>{const f=fixture();let m=damage(f,4);mods.addCombatModifier(m,f.site,f.hero.dark,'immunity-cancel',1);assert.equal(mods.attritionImmunity(m,f.hero.dark),0);assert.equal(combat.damagePending(m,'dark'),false);const g=fixture();m=damage(g,5);mods.addCombatModifier(m,g.site,g.hero.dark,'immunity-full',1);assert.equal(combat.damagePending(m,'dark'),true)});
test('immunity cancellation overrides every grant and source/turn lifetimes are separate',()=>{const f=fixture(),m=f.m,id=f.hero.dark;mods.addCombatModifier(m,f.card.dark,id,'immunity-less-than',7);mods.addCombatModifier(m,f.card.light,id,'immunity-less-than',8);assert.equal(mods.attritionImmunity(m,id),8);mods.addCombatModifier(m,f.card.light,id,'immunity-full',1);assert.equal(mods.attritionImmunity(m,id),Infinity);mods.addCombatModifier(m,f.site,id,'immunity-cancel',1,{duration:'source'});assert.equal(mods.attritionImmunity(m,id),0);m.turn.number++;assert.equal(mods.attritionImmunity(m,id),0);m.locations=[];for(const h of Object.values(f.hero))delete m.cards[h].location;state.moveCard(m,f.site,'hand');assert.equal(mods.attritionImmunity(m,id),5)});
test('power additions clamp after all bonuses and noncumulative copies do not double',()=>{const f=fixture(),m=f.m,id=f.hero.dark;mods.addCombatModifier(m,f.card.dark,id,'power-add',2);mods.addCombatModifier(m,f.copy.dark,id,'power-add',2);assert.equal(board.power(m,id),8);mods.addCombatModifier(m,f.card.light,id,'power-add',-20);assert.equal(board.power(m,id),0);mods.addCombatModifier(m,f.copy.dark,id,'power-add',2,{cumulative:true});assert.equal(mods.combatPowerBonus(m,id),-16)});
test('malformed saved combat modifiers and protected snapshots are rejected',()=>{const f=fixture();let m=boundary(play(start(f),f,'dark'),'battle-weapons');for(const patch of [{kind:'invented'},{amount:null},{turn:999},{duration:'forever'},{cumulative:'yes'},{target:{id:f.hero.dark,zone:'table',version:999}}]){const bad=clone(m);Object.assign(bad.data.combatModifiers[0],patch);assert.throws(()=>prompt(bad),/combat|reference/)}m=damage(f,4);const bad=clone(m);combat.battle(bad).attritionProtected.push(clone(combat.battle(bad).attritionProtected[0]));assert.throws(()=>prompt(bad),/attrition/)});

for(const side of ['light','dark'])test(side+' immunity removed during responses does not undo initiated power/ability results',()=>{const f=fixture();let m=play(start(f),f,side);mods.addCombatModifier(m,f.site,f.hero[side],'immunity-cancel',1);m=boundary(m,'battle-weapons');const rows=JSON.parse(fs.readFileSync(new URL('./gemp/battle-courage-results.json',import.meta.url)));assert.deepEqual(snapshot(m,f,side,side+'-immunity-gone'),rows.find(r=>r.name===side+'-immunity-gone'))});
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/battle-courage-results.json',import.meta.url)));
for(const row of oracle.filter(r=>r.name.startsWith('printed-')&&!r.name.startsWith('printed-company-')))test('executed GEMP '+row.name,()=>{
 const bp=row.name.slice(8),light=['1_4','1_19','3_3','1_21','4_1','9_24'].includes(bp),side=light?'light':'dark';
 const m=runtime.createMatch('immunity-query',60,['light','dark'].map(s=>({side:s,cards:[...(s===side?[bp]:[]),...(s==='light'?['1_129','1_4']:[]),...Array(60).fill(s==='light'?'1_28':'1_194')].slice(0,60)})),rules);
 const site=pull(m,'light','1_129');m.locations.push(site);const id=pull(m,side,bp,'table',site);let value=mods.attritionImmunity(m,id);assert.deepEqual({name:row.name,immunity:Number.isFinite(value)?value:'all'},row);
 if(['4_103','9_24'].includes(bp)){pull(m,'light',bp==='4_103'?'1_4':'1_28','table',site);assert.equal(mods.attritionImmunity(m,id),oracle.find(r=>r.name==='printed-company-'+bp).immunity)}
});
for(const n of [4,5])test('executed GEMP immunity remains frozen against '+n+' attrition',()=>{
 const f=fixture();let m=damage(f,n);const row=oracle.find(r=>r.name==='frozen-'+n),protectedNow=()=>combat.battle(m).attritionProtected.some(ref=>ref.id===f.hero.dark);
 assert.equal(combat.battle(m).attrition.dark,row.attrition);assert.equal(protectedNow(),row.before>n);mods.addCombatModifier(m,f.site,f.hero.dark,'immunity-cancel',1);assert.equal(protectedNow(),row.after>n);assert.equal(combat.damagePending(m,'dark'),!(row.after>n));
});
for(const side of ['light','dark'])test('executed GEMP '+side+' unavailable without immunity',()=>{const f=fixture(true),m=priority(start(f),side);assert.deepEqual({name:side+'-no-immunity',available:ids(m).some(id=>id.startsWith('duel-interrupt:battle:'))},oracle.find(r=>r.name===side+'-no-immunity'))});
test('returning during damage neither inherits protection nor rejoins the battle',()=>{const f=fixture();let m=damage(f,4);const ref=combat.battle(m).attritionProtected.find(r=>r.id===f.hero.dark);state.moveCard(m,f.hero.dark,'hand');state.moveCard(m,f.hero.dark,'table');m.cards[f.hero.dark].location=f.site;assert.equal(module('identity').sameCard(m,ref),false);assert.equal(combat.members(m,'dark').includes(f.hero.dark),false);assert.equal(combat.damagePending(m,'dark'),false)});
