import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
import {assertBionicOutcome,assertWeaponTotalEvidence,assertDisarmOutcome,readGempMatch,replayGempMatch} from './gemp-match-replay.mjs';
const record=()=>readGempMatch(new URL('./gemp/complete-matches/bionic-battle.json.gz',import.meta.url));
const cards=r=>Object.fromEntries(Object.entries(r.decks).flatMap(([owner,list])=>list.map((blueprint,i)=>[owner+'-'+(i+1),{blueprint,owner}])));
test('ordinary complete match binds both rearmings and subsequent required Hand loss',()=>{
 const r=record(),map=cards(r),rearms=r.trace.flatMap((x,i)=>x.bionicOutcome?[assertBionicOutcome(r.trace,i,map,r.final)]:[]);assert.equal(rearms.length,2);
 const i=r.trace.findIndex(x=>x.disarmOutcome?.attachedBefore.some(id=>map[id].blueprint==='5_12')),p=assertDisarmOutcome(r.trace,i,map,r.final);assert.equal(p.target,rearms[0].target);assert.ok(p.outcome.state.players.light.lost.includes(rearms[0].source));
});
for(const mode of ['answer','label','source','source-owner','phase','turn-owner','target','target-owner','not-disarmed','target-type','missing-outcome','outcome-source','outcome-target','early','late','state','attachment-list','retained-effect','missing-hand','still-disarmed','force','used','crossed-action'])test('complete-match rearming rejects '+mode,()=>{
 const r=record(),map=cards(r),i=r.trace.findIndex(x=>x.bionicOutcome),row=r.trace[i],p=assertBionicOutcome(r.trace,i,map,r.final),o=row.bionicOutcome,after=r.trace[o.afterDecision+1].state;
 if(mode==='answer')row.answer='missing';if(mode==='label')row.parameters.actionText[row.parameters.actionId.indexOf(row.answer)]='Draw card';if(mode==='source')map[p.source].blueprint='1_152';if(mode==='source-owner')map[p.source].owner='dark';if(mode==='phase')row.state.phase='control';if(mode==='turn-owner')row.state.side='dark';if(mode==='target')row.semantic.target='dark-40';if(mode==='target-owner')map[p.target].owner='dark';if(mode==='not-disarmed')row.state.table.find(c=>c.id===p.target).disarmed=false;if(mode==='target-type')map[p.target].blueprint='1_152';if(mode==='missing-outcome')delete row.bionicOutcome;if(mode==='outcome-source')o.source='light-1';if(mode==='outcome-target')o.card='dark-40';if(mode==='early')o.afterDecision=i;if(mode==='late')o.afterDecision=r.trace.length;if(mode==='state')o.state.turn++;if(mode==='attachment-list')o.attachedBefore=[];if(mode==='retained-effect'){after.players.dark.lost=after.players.dark.lost.filter(id=>!p.effects.includes(id));o.state=structuredClone(after);}if(mode==='missing-hand'){after.table=after.table.filter(c=>c.id!==p.source);o.state=structuredClone(after);}if(mode==='still-disarmed'){after.table.find(c=>c.id===p.target).disarmed=true;o.state=structuredClone(after);}if(mode==='force'){after.players.light.force.unshift('light-1');o.state=structuredClone(after);}if(mode==='used'){after.players.light.used.reverse();o.state=structuredClone(after);}if(mode==='crossed-action')r.trace[i+1].semantic={kind:'draw'};
 assert.throws(()=>assertBionicOutcome(r.trace,i,map,r.final));
});
test('observed firing totals include single and two-draw Hand bonuses',()=>{
 const r=record(),map=cards(r),totals=r.trace.flatMap((x,i)=>x.weaponTotal?[assertWeaponTotalEvidence(r.trace,i,map)]:[]);assert.ok(totals.some(t=>t.hands.length&&t.draws.length===1));assert.ok(totals.some(t=>t.hands.length&&t.draws.length===2));for(const t of totals)assert.equal(t.total,t.draws.reduce((a,b)=>a+b,0)+(t.hands.length?1:0));
});
for(const mode of ['answer','text','missing-total','weapon','user','target','target-answer','target-observation','target-blueprint','side','draw-card-owner','draw-value','draw-count','hands','total','crossed-action'])test('weapon total evidence rejects '+mode,()=>{
 const r=record(),map=cards(r),i=r.trace.findIndex(x=>x.weaponTotal?.hands.length&&x.weaponTotal.draws.length===2),row=r.trace[i],e=assertWeaponTotalEvidence(r.trace,i,map),f=r.trace.findLastIndex((x,j)=>j<i&&x.semantic?.kind==='fire'),target=r.trace.slice(f+1,i).find(x=>x.semantic?.kind==='fire-target');
 if(mode==='answer')row.answer='0';if(mode==='text')row.text='Choose Battle action';if(mode==='missing-total')delete row.weaponTotal;if(mode==='weapon')e.weapon='dark-1';if(mode==='user')e.user='light-50';if(mode==='target')e.targets=[];if(mode==='target-answer')target.answer='missing';if(mode==='target-observation')target.fireTarget.referenceCardId='missing';if(mode==='target-blueprint')target.fireTarget.blueprint='1_21';if(mode==='side')row.semantic.side='light';if(mode==='draw-card-owner')map[e.cards[0]].owner='dark';if(mode==='draw-value')e.draws[0]++;if(mode==='draw-count'){e.cards.pop();e.draws.pop();}if(mode==='hands')e.hands=[];if(mode==='total')e.total=null;if(mode==='crossed-action')r.trace[i-1].semantic={kind:'draw'};
 assert.throws(()=>assertWeaponTotalEvidence(r.trace,i,map));
});
test('complete native match reproduces victory and every observed weapon total',()=>{
 const r=replayGempMatch(record());assert.equal(r.commands,2233);assert.equal(r.checkpoints,228);assert.equal(r.state.turn.number,33);assert.deepEqual(r.state.result,{winner:'light',loser:'dark',reason:'life-force'});assert.equal(r.transcript.filter(c=>c.choice.startsWith('attach:')).length,2);
});
test('a fabricated numeric total cannot pass a full native replay',()=>{const r=record(),row=r.trace.find(x=>x.weaponTotal?.hands.length);row.weaponTotal.total++;assert.throws(()=>replayGempMatch(r),/Actual weapon total differs/);});
test('Disarmed-again evidence rejects retaining the protected Hand',()=>{const r=record(),map=cards(r),i=r.trace.findIndex(x=>x.disarmOutcome?.attachedBefore.some(id=>map[id].blueprint==='5_12')),row=r.trace[i],o=row.disarmOutcome,after=r.trace[o.afterDecision+1].state,hand=o.attachedBefore.find(id=>map[id].blueprint==='5_12');after.players.light.lost=after.players.light.lost.filter(id=>id!==hand);o.state=structuredClone(after);assert.throws(()=>assertDisarmOutcome(r.trace,i,map,r.final),/must lose Bionic Hand/);});
test('full-match receipts bind source, profiles, unchanged production bytes and the separate discrepancy',()=>{
 const p=JSON.parse(fs.readFileSync(new URL('./gemp/bionic-match-provenance.json',import.meta.url))),bytes=f=>fs.readFileSync(new URL('../../'+f,import.meta.url)),hash=b=>createHash('sha256').update(b).digest('hex'),r=record();
 assert.equal(hash(bytes(p.fixture)),p.sha256);assert.equal(hash(gunzipSync(bytes(p.fixture))),p.jsonSha256);assert.equal(hash(bytes(p.harness)),p.harnessSha256);assert.equal(hash(bytes(p.profile)),p.profileSha256);assert.equal(hash(fs.readFileSync(new URL('./gemp/NativeEngineBionicMatchOracleTests.java',import.meta.url))),p.harnessSha256);assert.equal(p.referenceDecisions,r.trace.length);assert.equal(p.unchangedProductionFiles,6820);assert.equal(p.productionFilesChanged,0);assert.equal(p.junitTests,1);
 for(const field of ['fixture','harness'])assert.equal(hash(bytes(p.discrepancy[field])),p.discrepancy[field+'Sha256']);
 const d=readGempMatch(new URL('../../'+p.discrepancy.fixture,import.meta.url)),row=d.trace[p.discrepancy.referenceDecision],e=row.weaponTotal,map=cards(d);assert.equal(d.finished,true);assert.equal(e.total,p.discrepancy.actualTotal);assert.equal(e.draws.reduce((a,b)=>a+b,0)+1,p.discrepancy.printedRuleTotal);assert.equal(e.hands.length,1);const hands=row.state.table.filter(c=>map[c.id].blueprint==='5_12');assert.equal(hands.length,2);assert.equal(new Set(hands.map(c=>c.attachedTo)).size,2);assert.equal(hands.find(c=>c.id===e.hands[0]).attachedTo,e.user);
});
