import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {fixture,handReady,attach,rearmed,totalReady,mod,deploy,boundary,finish,runtime,rules,state,priority,step,seek,pull} from './bionic-hand-fixture.mjs';
import {ids,clone} from './noble-fixture.mjs';
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/bionic-hand-results.json',import.meta.url)));
const total=m=>mod('destiny').currentDestinyTotal(m,m.stack.find(f=>f.action?.handler==='destiny:total-finish').action.payload);
for(const row of oracle)test('Bionic Hand executed GEMP comparison '+[row.weapon,row.mode].filter(Boolean).join(' '),()=>{
 if(row.mode==='transfer'){const f=rearmed(),host=pull(f.m,'light','1_28','table',f.site);mod('disarmed-state').setDisarmed(f.m,host,true);if(row.canceled)mod('game-text').suppressGameText(f.m,f.dark,f.hand);assert.equal(row.transferable,true,'Pinned GEMP query is permissive; this is a documented discrepancy, not conformance.');assert.ok(!ids(f.m).includes('device-transfer:'+f.hand+':'+host));return;}
 if(row.weapon){const f=totalReady(row.weapon),m=f.m;assert.equal(total(m),row.before);
  if(['leave','return'].includes(row.mode)){state.moveCard(m,f.hand,'hand');if(row.mode==='return'){state.moveCard(m,f.hand,'table');m.cards[f.hand].attachedTo=f.target;m.cards[f.hand].location=f.site;}}
  if(['cancel','weapon-cancel'].includes(row.mode))mod('game-text').suppressGameText(m,f.light,row.mode==='cancel'?f.hand:f.weapon);
  assert.equal(total(m),row.after);assert.equal(mod('board').power(m,f.target),row.power);assert.equal(mod('bionic-hand').protectedDevice(m,f.hand),row.protected);const done=boundary(clone(m),'weapon-fired');assert.equal(row.weapon==='saber'?done.data.battle.saberShots[0].total:done.data.battle.shots[0].total,row.after);return;
 }
 if(row.mode==='rearmed'){const f=handReady(),before=f.m.players.light.force.length,m=finish(step(f.m,attach(f)));assert.equal(before-m.players.light.force.length,row.cost);assert.equal(mod('disarmed-state').isDisarmed(m,f.target),row.disarmed);assert.equal(m.cards[f.card].zone==='lost',row.effectLost);assert.equal(mod('board').power(m,f.target),row.power);assert.equal(mod('bionic-hand').protectedDevice(m,f.hand),row.protected);return;}
 if(row.mode==='disarmed-again'){const f=rearmed();f.m=finish(step(f.m,'equip:'+f.spare+':'+f.target));f.m.turn.phase='control';f.m.turn.side='dark';f.m.stack[0].priority='dark';const m=finish(step(f.m,'disarm:deploy:'+f.second+':'+f.target));assert.equal(mod('disarmed-state').isDisarmed(m,f.target),row.disarmed);assert.equal(m.cards[f.hand].zone==='lost',row.handLost);assert.equal(m.cards[f.spare].zone==='lost',row.gunLost);assert.equal(mod('board').power(m,f.target),row.power);return;}
 const f=handReady();if(row.mode==='effect-leaves')mod('table').returnToHand(f.m,[f.card]);if(row.mode==='effect-canceled')mod('game-text').suppressGameText(f.m,f.dark,f.card);if(row.mode==='character-leaves')mod('table').returnToHand(f.m,[f.target]);assert.equal(mod('disarmed-state').isDisarmed(f.m,f.target),row.disarmed);rules.validate(f.m);
});
test('Disarmed status is recorded before weapon-loss responses and survives serialization',()=>{const f=fixture(),m=boundary(step(f.m,deploy(f)),'about-to-lose');assert.equal(mod('disarmed-state').isDisarmed(m,f.target),true);rules.validate(clone(m));assert.equal(mod('disarmed-state').isDisarmed(clone(m),f.target),true);});
test('Bionic Hand is unavailable before actual disarming and on opponent characters',()=>{const f=fixture();f.m.turn.phase='deploy';f.m.turn.side='light';f.m.stack[0].priority='light';assert.ok(!ids(f.m).includes(attach(f)));mod('disarmed-state').setDisarmed(f.m,f.dark,true);assert.ok(!ids(f.m).includes('attach:'+f.hand+':'+f.dark));});
test('Bionic Hand requires two Force and ordinary Deploy timing',()=>{const f=handReady();while(f.m.players.light.force.length>1)state.moveCard(f.m,f.m.players.light.force[0],'used');assert.ok(!ids(f.m).includes(attach(f)));f.m.turn.phase='control';assert.ok(!ids(f.m).includes(attach(f)));});
test('required rearming cancels every attached disarming Effect before response and allows weapons again',()=>{const f=handReady();state.moveCard(f.m,f.second,'table');f.m.cards[f.second].attachedTo=f.target;f.m.cards[f.second].location=f.site;let m=seek(step(f.m,attach(f)),x=>x.stack.at(-1)?.handler==='table:lost-order');assert.equal(mod('disarmed-state').isDisarmed(m,f.target),false);assert.equal(m.cards[f.card].zone,'leaving');assert.equal(m.cards[f.second].zone,'leaving');m=finish(clone(m));assert.equal(m.cards[f.second].zone,'lost');assert.ok(ids(priority(m,'light')).includes('equip:'+f.spare+':'+f.target));});
test('canceled Hand deployment loses its card without rearming',()=>{const f=handReady(),m=step(f.m,attach(f));m.stack.find(x=>x.action?.handler==='equipment:attach').cancelled=true;const done=finish(m);assert.equal(done.cards[f.hand].zone,'lost');assert.equal(mod('disarmed-state').isDisarmed(done,f.target),true);});
test('changed physical host invalidates Hand deployment',()=>{const f=handReady(),m=step(f.m,attach(f));mod('table').returnToHand(m,[f.target]);state.moveCard(m,f.target,'table');m.cards[f.target].location=f.site;const done=finish(m);assert.equal(done.cards[f.hand].zone,'lost');assert.equal(mod('disarmed-state').isDisarmed(done,f.target),false);});
test('Hand cannot transfer even with canceled text and another Disarmed character',()=>{const f=rearmed(),host=pull(f.m,'light','1_28','table',f.site);mod('disarmed-state').setDisarmed(f.m,host,true);mod('game-text').suppressGameText(f.m,f.dark,f.hand);assert.ok(!ids(f.m).includes('device-transfer:'+f.hand+':'+host));const attempt=mod('attachment').attachmentAttempt(f.m,f.hand,host);assert.equal(mod('attachment').validAttachmentAttempt(f.m,attempt),false);});
test('host loss still loses the protected Hand and resets Disarmed status',()=>{const f=rearmed();mod('disarmed-state').setDisarmed(f.m,f.target,true);mod('table').loseFromTable(f.m,[f.target]);const m=finish(f.m);assert.equal(m.cards[f.hand].zone,'lost');assert.equal(mod('disarmed-state').isDisarmed(m,f.target),false);});
for(const field of ['duplicate','stale','noncharacter','malformed'])test('saved Disarmed status rejects '+field,()=>{const f=handReady(),refs=f.m.data.disarmedCharacters;if(field==='duplicate')refs.push({...refs[0]});if(field==='stale')refs[0].version--;if(field==='noncharacter')refs[0]=mod('identity').referenceCard(f.m,f.device);if(field==='malformed')f.m.data.disarmedCharacters={};assert.throws(()=>rules.validate(f.m));});
for(const field of ['host','weapon','initial','missing'])test('saved live character-weapon total rejects '+field,()=>{const f=totalReady(),p=f.m.stack.find(x=>x.action?.handler==='destiny:total-finish').action.payload;if(field==='host')p.characterWeapon.context.host=f.dark;if(field==='weapon')p.characterWeapon.context.weapon=f.dg;if(field==='initial')p.characterWeapon.initial=2;if(field==='missing')delete p.characterWeapon;assert.throws(()=>rules.validate(f.m));});
test('full production admission remains closed',()=>assert.equal(mod('premiere-rules').premiereRules.supports('5_12'),false));
test('all failed weapon draws stay null even with the Hand bonus',()=>{const f=rearmed();f.m=finish(step(f.m,'equip:'+f.spare+':'+f.target));f.m.turn.phase='battle';f.m.stack[0].priority='light';f.m=priority(boundary(step(f.m,'battle:'+f.site),'battle-weapons'),'light');for(const id of [...f.m.players.light.reserve])state.moveCard(f.m,id,'hand');const m=boundary(step(f.m,'fire:'+f.spare+':'+f.dark),'weapon-fired');assert.equal(m.data.battle.shots[0].total,null);assert.equal(m.data.battle.shots[0].hit,false);});
test('two copies do not double a noncumulative Hand power or total bonus',()=>{const f=totalReady(),extra=pull(f.m,'light','5_12','table',f.site);f.m.cards[extra].attachedTo=f.target;assert.equal(mod('board').power(f.m,f.target),2);assert.equal(total(f.m),4);});
test('only the original firing user supplies the Hand bonus after a weapon moves',()=>{const f=totalReady();f.m.cards[f.weapon].attachedTo=f.dark;assert.equal(total(f.m),4);state.moveCard(f.m,f.hand,'hand');const extra=pull(f.m,'light','5_12','table',f.site);f.m.cards[extra].attachedTo=f.dark;assert.equal(total(f.m),3);});
for(const field of ['actor','source','target','window','payment'])test('saved required Bionic action rejects '+field,()=>{const f=handReady();let m=seek(step(f.m,attach(f)),m=>m.stack.some(x=>x.action?.handler==='bionic:rearm'));const r=m.stack.find(x=>x.action?.handler==='bionic:rearm');if(field==='actor')r.actor='dark';if(field==='source')r.action.source=f.card;if(field==='target')r.action.payload.target=mod('identity').referenceCard(m,f.device);if(field==='window')r.action.payload.window=-1;if(field==='payment')r.action.payment={light:1};assert.throws(()=>rules.validate(m));});
test('Bionic receipt binds the executed harness, observations and unchanged production source',async()=>{const {createHash}=await import('node:crypto'),p=JSON.parse(fs.readFileSync(new URL('./gemp/bionic-hand-provenance.json',import.meta.url)));for(const [file,hash] of [[p.harness,p.harnessSha256],[p.results,p.resultsSha256]])assert.equal(createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+file,import.meta.url))).digest('hex'),hash);assert.equal(p.junitTests,4);assert.equal(p.observations,oracle.length);assert.equal(p.productionFilesChanged,0);assert.equal(p.productionFilesCompared,6820);});
test('public weapon total uses live modifiers without exposing continuation payloads',()=>{const f=totalReady('saber');let view=rules.view(f.m,'light',0).weaponDestiny;assert.deepEqual(view,{weapon:f.weapon,side:'light',draws:[3,3],total:7,modifier:1});mod('game-text').suppressGameText(f.m,f.light,f.hand);view=rules.view(f.m,'dark',0).weaponDestiny;assert.deepEqual(view,{weapon:f.weapon,side:'light',draws:[3,3],total:6,modifier:0});});
test('character weapon firing in a creature attack receives the same total bonus',async()=>{const {fixture:creatureFixture,deploy:deployCreature,attack}=await import('./ground-creature-fixture.mjs');const f=deployCreature(creatureFixture('light',{light:['5_12','1_109']}));const user=pull(f.m,'light','1_28','table',f.site),gun=pull(f.m,'light','1_152','table',f.site),hand=pull(f.m,'light','5_12','table',f.site);f.m.cards[gun].attachedTo=user;f.m.cards[hand].attachedTo=user;let m=priority(boundary(attack(f,'assault','light'),'attack-weapons'),'light');const die=pull(m,'light','1_109','hand');state.moveCard(m,die,'reserve');m=boundary(step(m,ids(m).find(id=>id.startsWith('creature-weapon:fire:'))),'destiny-total');assert.equal(total(m),4);m=boundary(clone(m),'weapon-fired');assert.equal(m.data.creatureShots.at(-1).total,4);});

test('computer rearms a character using an offered Hand deployment',()=>{const f=handReady(),view=runtime.project(f.m,rules,'light');assert.equal(mod('computer').chooseComputerAction(view,'light'),attach(f));});
