import test from 'node:test';
import assert from 'node:assert/strict';
import {load} from '../native-proof/load-engine.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url));
const runtime=mod('runtime'),state=mod('state'),board=mod('board'),capture=mod('captives'),table=mod('table'),identity=mod('identity'),occupancy=mod('occupancy');
const rules={...mod('premiere-rules').premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true};
const clone=x=>JSON.parse(JSON.stringify(x));
function fresh(){let m=runtime.createMatch('captives',60,['light','dark'].map(side=>({side,cards:[...(side==='light'?['1_129','1_132','1_19','1_19','1_152','1_40','1_149']:['1_284','1_168','1_194','1_194','1_310','1_302']),...Array(60).fill(side==='light'?'1_28':'1_194')].slice(0,60)})),rules);const pull=(side,bp,location,host)=>{const c=Object.values(m.cards).find(c=>c.owner===side&&c.blueprint===bp&&c.zone==='reserve');assert.ok(c,bp);state.moveCard(m,c.id,'table');if(location)c.location=location;if(host)c.attachedTo=host;return c.id};const site=pull('light','1_129'),adj=pull('light','1_132'),prison=pull('dark','1_284');m.locations.push(site,adj,prison);const target=pull('light','1_19',site),gun=pull('light','1_152',site,target),device=pull('light','1_40',site,target),escort=pull('dark','1_194',site),other=pull('dark','1_194',site);m=runtime.startTurns(m,rules);return {m,site,adj,prison,target,gun,device,escort,other};}
function valid(m){state.assertState(m);rules.validate(m);for(const side of ['light','dark'])assert.deepEqual(runtime.project(m,rules,side),runtime.project(clone(m),rules,side));return m;}
function prompt(m){let p=runtime.prompt(m,rules,'light');return p&&runtime.prompt(m,rules,p.side);}
function step(m,id){const p=prompt(m),result=runtime.applyCommand(m,rules,p.side,{revision:m.revision,choice:id},()=>0);return valid(result);}
function seek(m,predicate){for(let n=0;n<300;n++){if(predicate(m))return m;const choices=prompt(m).choices.map(c=>c.id);m=step(m,choices.includes('pass')?'pass':choices[0]);}throw Error('Boundary not reached');}
function seize(f){capture.captureCharacter(f.m,f.target,{kind:'escort',id:f.escort});valid(f.m);return f;}

test('capture retains inactive attachments, identity and uniqueness, without active presence or actions',()=>{const f=fresh(),refs=[f.target,f.gun,f.device].map(id=>identity.referenceCard(f.m,id));seize(f);assert.equal(f.m.cards[f.target].zone,'captive');for(const id of [f.gun,f.device]){assert.equal(f.m.cards[id].zone,'inactive');assert.equal(f.m.cards[id].attachedTo,f.target);}assert.equal(board.presence(f.m,'light',f.site),false);assert.equal(occupancy.unitsAt(f.m,f.site).some(c=>c.id===f.target),false);assert.equal(mod('game-text').gameTextActive(f.m,f.target),false);assert.equal(mod('persona').canEnterTable(f.m,Object.values(f.m.cards).find(c=>c.blueprint==='1_19'&&c.zone==='reserve').id),false);for(const ref of refs)assert.equal(identity.cardVersion(f.m,ref.id),ref.version);assert.equal(state.publicState(f.m,'dark').table.filter(c=>[f.target,f.gun,f.device].includes(c.id)).length,3);});
test('one escort cannot seize a second captive; nonwarrior and remote characters cannot escort',()=>{const f=seize(fresh()),second=Object.values(f.m.cards).find(c=>c.blueprint==='1_28'&&c.zone==='reserve');state.moveCard(f.m,second.id,'table');second.location=f.site;assert.equal(capture.captureDestinations(f.m,second.id).some(d=>d.kind==='escort'&&d.id===f.escort),false);board.moveWithAttachments(f.m,f.other,f.adj);assert.equal(capture.captureDestinations(f.m,second.id).some(d=>d.kind==='escort'),false);assert.throws(()=>capture.captureCharacter(f.m,second.id,{kind:'escort',id:f.escort}));});
test('escort landspeed movement carries captive and inactive attachments without changing their instances',()=>{const f=seize(fresh()),refs=[f.target,f.gun,f.device].map(id=>identity.referenceCard(f.m,id));board.moveWithAttachments(f.m,f.escort,f.adj);for(const ref of refs){assert.equal(f.m.cards[ref.id].location,f.adj);assert.ok(identity.sameCard(f.m,ref));}valid(f.m);});
test('escort loss suspends a real Light release choice that survives serialization and rallies attachments',()=>{const f=seize(fresh());table.loseFromTable(f.m,[f.escort]);valid(f.m);assert.equal(f.m.cards[f.target].zone,'captive');const p=prompt(f.m);assert.equal(p.side,'light');assert.ok(p.choices.some(c=>c.id==='captives:rally'));const m=step(clone(f.m),'captives:rally');for(const id of [f.target,f.gun,f.device])assert.equal(m.cards[id].zone,'table');assert.equal(m.cards[f.gun].attachedTo,f.target);assert.equal(m.cards[f.escort].zone,'lost');assert.equal(m.cards[f.target].captivity,undefined);});
test('release escape returns only captive to Used and loses retained attachments with real Lost ordering',()=>{const f=seize(fresh());table.loseFromTable(f.m,[f.escort]);let m=step(f.m,'captives:escape');m=seek(m,x=>[f.gun,f.device].every(id=>x.cards[id].zone==='lost'));assert.equal(m.cards[f.target].zone,'used');assert.equal(m.players.light.used[0],f.target);});
test('capture escape loses attachments but does not leave a phantom captive',()=>{const f=fresh();capture.captureCharacter(f.m,f.target,{kind:'escape'});valid(f.m);const m=seek(f.m,x=>x.cards[f.target].zone==='used');assert.equal(capture.captives(m).length,0);for(const id of [f.gun,f.device])assert.equal(m.cards[id].zone,'lost');});
test('captives occupy passenger capacity in addition to their escort and follow the carrier',()=>{const f=fresh();const ship=Object.values(f.m.cards).find(c=>c.blueprint==='1_310');state.moveCard(f.m,ship.id,'table');ship.location=f.site;f.m.cards[f.escort].attachedTo=ship.id;f.m.cards[f.escort].aboardRole='driver';seize(f);assert.equal(capture.captivePassengers(f.m,ship.id).length,1);const second=Object.values(f.m.cards).find(c=>c.blueprint==='1_194'&&c.zone==='reserve');state.moveCard(f.m,second.id,'table');second.location=f.site;second.attachedTo=ship.id;second.aboardRole='passenger';valid(f.m);assert.equal(occupancy.roleAvailable(f.m,ship.id,f.other,'passenger'),false);board.moveWithAttachments(f.m,ship.id,f.adj);valid(f.m);assert.equal(f.m.cards[f.target].location,f.adj);});
test('whole-carrier loss loses captive and attachments together; no release or rally choice',()=>{const f=fresh(),ship=Object.values(f.m.cards).find(c=>c.blueprint==='1_310');state.moveCard(f.m,ship.id,'table');ship.location=f.site;f.m.cards[f.escort].attachedTo=ship.id;f.m.cards[f.escort].aboardRole='driver';seize(f);const victims=table.loseFromTable(f.m,[ship.id]);assert.ok(victims.includes(f.target));assert.equal(f.m.stack.some(x=>x.handler==='captives:release'),false);valid(f.m);const m=seek(f.m,x=>victims.every(id=>x.cards[id].zone==='lost'));assert.equal(capture.captives(m).length,0);});
test('imprisonment is unlimited and release must rally, with no automatic release from mere control',()=>{const f=fresh();board.moveWithAttachments(f.m,f.target,f.prison);capture.captureCharacter(f.m,f.target,{kind:'prison',id:f.prison});const other=Object.values(f.m.cards).find(c=>c.blueprint==='1_28'&&c.zone==='reserve');state.moveCard(f.m,other.id,'table');other.location=f.prison;capture.captureCharacter(f.m,other.id,{kind:'prison',id:f.prison});valid(f.m);assert.equal(capture.schedulePrisonRelease(f.m),false);capture.releaseCaptive(f.m,f.target);assert.equal(prompt(f.m).choices.some(c=>c.id==='captives:escape'),false);const m=step(f.m,'captives:rally');assert.equal(m.cards[f.target].zone,'table');assert.equal(m.cards[other.id].zone,'captive');});
test('site destruction explicitly loses imprisoned captives and their inactive attachments',()=>{const f=fresh();board.moveWithAttachments(f.m,f.target,f.prison);capture.captureCharacter(f.m,f.target,{kind:'prison',id:f.prison});const victims=table.siteLossCards(f.m,f.prison,'none');assert.ok(victims.includes(f.target));table.loseSiteCards(f.m,victims);valid(f.m);const m=seek(f.m,x=>victims.every(id=>x.cards[id].zone==='lost'));assert.equal(capture.captives(m).length,0);});
for(const corrupt of ['dark-captive','orphan-attachment','duplicate-escort','bad-site','orphan-release','active-captivity'])test('reject malformed persisted captivity: '+corrupt,()=>{const f=seize(fresh()),m=clone(f.m);if(corrupt==='dark-captive')m.cards[f.target].owner='dark';if(corrupt==='orphan-attachment')delete m.cards[f.gun].attachedTo;if(corrupt==='duplicate-escort'){const c=Object.values(m.cards).find(c=>c.blueprint==='1_28'&&c.zone==='reserve');state.moveCard(m,c.id,'captive');c.location=f.site;c.captivity={escort:f.escort};}if(corrupt==='bad-site')m.cards[f.target].location=f.adj;if(corrupt==='orphan-release')m.cards[f.target].captivity={release:true,imprisoned:false};if(corrupt==='active-captivity')m.cards[f.target].zone='table';assert.throws(()=>valid(m));});

test('ordinary Move commands deliver a captive to prison and take custody again without using Force or a regular move',()=>{const f=seize(fresh());board.moveWithAttachments(f.m,f.escort,f.prison);let m=seek(f.m,x=>x.turn.side==='dark'&&x.turn.phase==='move'&&x.stack.length===1&&prompt(x).side==='dark');const before=m.players.dark.force.length;let choice=prompt(m).choices.find(c=>c.id==='captives:deliver:'+f.target+':'+f.escort);assert.ok(choice);m=step(m,choice.id);m=seek(m,x=>x.stack.length===1&&prompt(x).side==='dark');assert.deepEqual(m.cards[f.target].captivity,{prison:f.prison});assert.equal(m.players.dark.force.length,before);assert.equal(mod('ground').usage(m).moved.includes(f.escort),false);choice=prompt(m).choices.find(c=>c.id==='captives:take:'+f.target+':'+f.escort);assert.ok(choice);m=step(m,choice.id);m=seek(m,x=>x.stack.length===1);assert.deepEqual(m.cards[f.target].captivity,{escort:f.escort});});
test('released captive joins an ongoing battle even in damage, preserving previously calculated losses',()=>{const f=seize(fresh()),ally=Object.values(f.m.cards).find(c=>c.blueprint==='1_28'&&c.zone==='reserve');state.moveCard(f.m,ally.id,'table');ally.location=f.site;state.moveCard(f.m,f.m.players.dark.reserve.at(-1),'force');let m=seek(f.m,x=>x.turn.side==='dark'&&x.turn.phase==='battle'&&x.stack.length===1&&prompt(x).side==='dark');m=step(m,'battle:'+f.site);m=seek(m,x=>x.stack.at(-1)?.event?.kind==='battle-damage');const b=mod('battle').battle(m),before=clone(b.damageLedger);capture.releaseCaptive(m,f.target);m=step(m,'captives:rally');assert.ok(mod('participation').battleMembers(m,'light').includes(f.target));assert.deepEqual(mod('battle').battle(m).damageLedger,before);});
test('captivity does not erase a character’s current-turn movement or weapon-use limits',()=>{const f=fresh();mod('ground').record(f.m).moved.push(f.target);mod('weapon-state').useWeapon(f.m,f.gun,f.target);seize(f);capture.releaseCaptive(f.m,f.target);const m=step(f.m,'captives:rally');assert.ok(mod('ground').usage(m).moved.includes(f.target));assert.equal(mod('weapon-state').canUseWeapon(m,f.device,f.target),false);});

const fs=await import('node:fs'),crypto=await import('node:crypto');
const reference=JSON.parse(fs.readFileSync(new URL('./gemp/captives-results.json',import.meta.url)));
for(const row of reference)test('unchanged GEMP captive lifecycle: '+row.name,()=>{
 const f=fresh();if(row.name==='capture-imprisonment'||row.name==='prison-release')board.moveWithAttachments(f.m,f.target,f.prison);
 if(row.name==='carrier-lost'){const ship=Object.values(f.m.cards).find(c=>c.blueprint==='1_310');state.moveCard(f.m,ship.id,'table');ship.location=f.site;f.m.cards[f.escort].attachedTo=ship.id;f.m.cards[f.escort].aboardRole='driver';}
 capture.captureCharacter(f.m,f.target,row.name==='capture-escape'?{kind:'escape'}:['capture-imprisonment','prison-release'].includes(row.name)?{kind:'prison',id:f.prison}:{kind:'escort',id:f.escort});
 if(row.name.startsWith('release-')){table.loseFromTable(f.m,[f.escort]);f.m=step(f.m,'captives:'+row.name.slice(8));}
 if(row.name==='prison-release'){capture.releaseCaptive(f.m,f.target);f.m=step(f.m,'captives:rally');}
 if(row.name==='carrier-lost')table.loseFromTable(f.m,[Object.values(f.m.cards).find(c=>c.blueprint==='1_310').id]);
 const m=seek(f.m,x=>x.stack.length===1),t=m.cards[f.target],g=m.cards[f.gun],d=m.cards[f.device];valid(m);
 assert.deepEqual({name:row.name,captive:t.zone==='captive',imprisoned:!!t.captivity&&'prison' in t.captivity,active:t.zone==='table',weaponActive:g.zone==='table',deviceActive:d.zone==='table',weaponAttached:g.attachedTo===t.id,deviceAttached:d.attachedTo===t.id,used:t.zone==='used',lost:t.zone==='lost',weaponLost:g.zone==='lost',deviceLost:d.zone==='lost'},row);
});
test('capture evidence binds the unchanged reference and retains full admission gate',()=>{const p=JSON.parse(fs.readFileSync(new URL('./gemp/captives-provenance.json',import.meta.url)));assert.equal(p.productionFilesCompared,6820);assert.equal(p.productionFilesChanged,0);assert.equal(reference.length,7);assert.equal(new Set(reference.map(x=>x.name)).size,7);for(const [file,hash]of Object.entries(p.files))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+file,import.meta.url))).digest('hex'),hash);assert.equal(mod('premiere-rules').premiereRules.supports('2_142'),false);});
