// Controlled captive component fixtures, not a claim of a complete capture game.
import assert from 'node:assert/strict';
import {load} from '../native-proof/load-engine.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url));
const runtime=mod('runtime'),state=mod('state'),capture=mod('captives'),table=mod('table'),board=mod('board');
export const rules={...mod('premiere-rules').premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true};
function fresh(){let m=runtime.createMatch('captives',60,['light','dark'].map(side=>({side,cards:[...(side==='light'?['1_129','1_132','1_19','1_19','1_152','1_40','1_149']:['1_284','1_168','1_194','1_194','1_310','1_302']),...Array(60).fill(side==='light'?'1_28':'1_194')].slice(0,60)})),rules);const pull=(side,bp,location,host)=>{const c=Object.values(m.cards).find(c=>c.owner===side&&c.blueprint===bp&&c.zone==='reserve');assert.ok(c,bp);state.moveCard(m,c.id,'table');if(location)c.location=location;if(host)c.attachedTo=host;return c.id};const site=pull('light','1_129'),adj=pull('light','1_132'),prison=pull('dark','1_284');m.locations.push(site,adj,prison);const target=pull('light','1_19',site),gun=pull('light','1_152',site,target),device=pull('light','1_40',site,target),escort=pull('dark','1_194',site),other=pull('dark','1_194',site);m=runtime.startTurns(m,rules);return {m,site,adj,prison,target,gun,device,escort,other};}
export const decks=()=>['light','dark'].map(side=>({side,cards:Object.values(fresh().m.cards).filter(c=>c.owner===side).map(c=>c.blueprint)}));
export function captiveFixtures(){return ['rally','escape','prison'].map(mode=>{const f=fresh();capture.captureCharacter(f.m,f.target,{kind:'escort',id:f.escort});if(mode==='prison'){board.moveWithAttachments(f.m,f.escort,f.prison);for(let n=0;n<300;n++){let p=runtime.prompt(f.m,rules,'light');p=runtime.prompt(f.m,rules,p.side);if(f.m.turn.phase==='move'&&f.m.turn.side==='dark'&&f.m.stack.length===1&&p.side==='dark')break;f.m=runtime.applyCommand(f.m,rules,p.side,{revision:f.m.revision,choice:p.choices.some(c=>c.id==='pass')?'pass':p.choices[0].id},()=>0);}}else table.loseFromTable(f.m,[f.escort]);const choice=mode==='prison'?'captives:deliver:'+f.target+':'+f.escort:'captives:'+mode;let p=runtime.prompt(f.m,rules,'light');p=runtime.prompt(f.m,rules,p.side);assert.ok(p.choices.some(c=>c.id===choice));return {id:mode,start:f.m,choice,side:p.side,target:f.target,gun:f.gun,device:f.device,escort:f.escort};});}
