import test from 'node:test';
import assert from 'node:assert/strict';
import {pull,state,rules,clone,ids,step,seek,priority,settled,load} from './vessels-fixture.mjs';
import {compactorFixture as fixture,escapeFixture,play,scompOffer} from './compactor-fixture.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url)),board=mod('board'),ground=mod('ground');
const choose=m=>seek(m,x=>x.stack.at(-1)?.handler==='compactor:choose');
for(const own of [false,true])test('Flyboy relocates all participating characters in '+(own?'own':'opposing')+' initiated battle without Force or regular movement',()=>{
 const f=escapeFixture(own),before=f.m.players.light.force.length;ground.record(f.m).moved.push(f.troop);assert.ok(ids(f.m).includes(play(f.flyboy)));const m=settled(step(clone(f.m),play(f.flyboy)));assert.equal(m.cards[f.troop].location,f.compactor);assert.equal(m.cards[f.droid].location,f.compactor);assert.equal(m.cards[f.enemy].location,f.remote);assert.equal(m.players.light.force.length,before);assert.deepEqual(ground.usage(m).moved,[f.troop]);assert.equal(m.cards[f.flyboy].zone,'used');assert.equal(m.data.battle.stage,'complete');assert.ok(!m.data.battle.cancelled);
});
test('Flyboy carries attachments and leaves the carrier behind',()=>{const f=escapeFixture(false,true),host=pull(f.m,'light','1_149','table',f.remote);f.m.cards[f.troop].attachedTo=host;f.m.cards[f.troop].aboardRole='passenger';const gun=pull(f.m,'light','1_152','table',f.remote);f.m.cards[gun].attachedTo=f.troop;const m=settled(step(f.m,play(f.flyboy)));assert.equal(m.cards[f.troop].attachedTo,undefined);assert.equal(m.cards[f.troop].aboardRole,undefined);assert.equal(m.cards[gun].location,f.compactor);assert.equal(m.cards[gun].attachedTo,f.troop);assert.equal(m.cards[host].location,f.remote);});
test('Flyboy targets original characters only, excludes immobile guards and barred units',()=>{const f=escapeFixture();const guard=pull(f.m,'light','1_26','table',f.remote);f.m.data.battle.participants.light.push(guard);ground.record(f.m).barriers[f.droid]=f.m.turn.number;let m=step(f.m,play(f.flyboy));const arrival=pull(m,'light','1_28','table',f.remote);m.data.battle.participants.light.push(arrival);m=seek(m,x=>x.cards[f.flyboy].zone==='used');assert.equal(m.cards[f.troop].location,f.compactor);for(const id of [guard,f.droid,arrival])assert.equal(m.cards[id].location,f.remote);});
test('Flyboy revalidates physical targets and destination through save/reload',()=>{const f=escapeFixture();let m=step(f.m,play(f.flyboy));state.moveCard(m,f.troop,'hand');state.moveCard(m,f.troop,'table');m.cards[f.troop].location=f.remote;m=seek(clone(m),x=>x.cards[f.flyboy].zone==='used');assert.equal(m.cards[f.troop].location,f.remote);assert.equal(m.cards[f.droid].location,f.compactor);});
test('Flyboy has no offer at the Trash Compactor or outside battle initiation',()=>{const f=fixture('light');assert.ok(!ids(f.m).includes(play(f.flyboy)));const g=escapeFixture();g.m.data.battle.site=g.compactor;assert.equal(mod('compactor').compactorActions(g.m,g.m.stack.at(-1),'light').length,0);});
test('canceled Flyboy loses its card and leaves the characters in place',()=>{const f=escapeFixture();let m=step(f.m,play(f.flyboy));m.stack.find(x=>x.action?.handler==='compactor:play').cancelled=true;m=seek(m,x=>x.cards[f.flyboy].zone==='lost');assert.equal(m.cards[f.troop].location,f.remote);});
test('Trash Compactor allows Light deployment without icons/presence but retains other restrictions',()=>{const f=fixture('light'),troop=pull(f.m,'light','1_28','hand');assert.ok(board.deploymentPayment(f.m,troop,f.compactor));assert.equal(board.deploymentPayment(f.m,f.passenger,f.compactor),null);assert.equal(board.deploymentPayment(f.m,f.luke,f.compactor),null);const m=settled(step(f.m,'deploy:'+troop+':'+f.compactor));assert.equal(m.cards[troop].location,f.compactor);assert.equal(board.drainAmount(m,'light',f.compactor),1);assert.equal(board.drainAmount(m,'dark',f.compactor),0);mod('game-text').suppressGameText(m,f.compactor,f.compactor);assert.equal(board.drainAmount(m,'light',f.compactor),0);});
test('crushing an empty compactor is legal and uses a Lost Interrupt',()=>{const f=fixture();assert.ok(ids(f.m).includes(play(f.crush)));const m=settled(step(f.m,play(f.crush)));assert.equal(m.cards[f.crush].zone,'lost');assert.ok(m.locations.includes(f.compactor));});
test('Dark chooses successive crushing roots across both owners, with serialized before/after loss windows',()=>{const f=fixture(),light=pull(f.m,'light','1_28','table',f.compactor),dark=pull(f.m,'dark','1_194','table',f.compactor);let m=choose(step(f.m,play(f.crush)));assert.equal(m.stack.at(-1).side,'dark');assert.deepEqual(new Set(ids(m)),new Set(['crush:'+light,'crush:'+dark]));m=step(clone(m),'crush:'+light);assert.equal(m.stack.at(-1).event.allCards,true);assert.equal(m.cards[light].zone,'table');m=seek(m,x=>x.stack.at(-1)?.event?.kind==='cards-lost');assert.equal(m.cards[light].zone,'lost');assert.equal(m.cards[dark].zone,'table');m=choose(m);assert.deepEqual(ids(m),['crush:'+dark]);m=settled(step(clone(m),'crush:'+dark));assert.deepEqual(m.players.light.lost,[light]);assert.deepEqual(m.players.dark.lost,[f.crush,dark]);});
test('host attachments leave simultaneously and owner chooses Lost order before next crushing target',()=>{const f=fixture(),host=pull(f.m,'light','1_28','table',f.compactor),gun=pull(f.m,'light','1_152','table',f.compactor);f.m.cards[gun].attachedTo=host;const dark=pull(f.m,'dark','1_194','table',f.compactor);let m=choose(step(f.m,play(f.crush)));m=seek(step(m,'crush:'+host),x=>x.stack.at(-1)?.handler==='table:lost-order');assert.equal(m.stack.at(-1).side,'light');assert.equal(m.cards[host].zone,'leaving');assert.equal(m.cards[gun].zone,'leaving');assert.equal(m.cards[dark].zone,'table');m=step(clone(m),'place-lost:'+host);m=choose(m);assert.deepEqual(ids(m),['crush:'+dark]);assert.deepEqual(m.players.light.lost,[gun,host]);});
test('crush includes arrivals during play responses and ignores cards arriving after target selection',()=>{const f=fixture();let m=step(f.m,play(f.crush));const first=pull(m,'light','1_28','table',f.compactor);m=choose(m);const later=pull(m,'light','1_28','table',f.compactor);m=settled(step(m,'crush:'+first));assert.equal(m.cards[first].zone,'lost');assert.equal(m.cards[later].zone,'table');});
test('crush cannot affect another location and does not directly target Effects',()=>{const f=fixture(),host=pull(f.m,'light','1_28','table',f.compactor),effect=pull(f.m,'light','1_53','table',f.compactor),away=pull(f.m,'dark','1_194','table',f.remote);f.m.cards[effect].attachedTo=host;let m=choose(step(f.m,play(f.crush)));assert.deepEqual(ids(m),['crush:'+host]);m=settled(step(m,'crush:'+host));assert.equal(m.cards[effect].zone,'lost');assert.equal(m.cards[away].zone,'table');});
test('Boring Conversation cancels Scomp without any character or Scomp link',()=>{const f=fixture('light');const site=pull(f.m,'dark','1_285','table');f.m.locations.push(site);pull(f.m,'light','2_14','table',site);let m=priority(step(f.m,scompOffer(f.m,f.scomp,'peek')),'dark');assert.ok(scompOffer(m,f.boring,'cancel'));m=settled(step(m,scompOffer(m,f.boring,'cancel')));assert.equal(m.cards[f.boring].zone,'used');assert.equal(m.cards[f.scomp].zone,'lost');});
test('Scomp cancels Boring Conversation and preserves the original Scomp action',()=>{const f=fixture('light');const site=pull(f.m,'dark','1_285','table');f.m.locations.push(site);pull(f.m,'light','2_14','table',site);const second=pull(f.m,'light','1_108','hand');let m=priority(step(f.m,scompOffer(f.m,f.scomp,'peek')),'dark');m=priority(step(m,scompOffer(m,f.boring,'cancel')),'light');m=step(m,scompOffer(m,second,'cancel'));m=seek(m,x=>x.stack.at(-1)?.handler==='scomp:peek');assert.equal(m.cards[f.boring].zone,'lost');assert.equal(m.cards[second].zone,'used');m=settled(step(m,'scomp:finish'));assert.equal(m.cards[f.scomp].zone,'used');});
test('Scomp cancels crushing before victims are selected',()=>{const f=fixture();const site=pull(f.m,'dark','1_285','table');f.m.locations.push(site);pull(f.m,'light','2_14','table',site);const troop=pull(f.m,'light','1_28','table',f.compactor);let m=priority(step(f.m,play(f.crush)),'light');m=settled(step(m,scompOffer(m,f.scomp,'cancel')));assert.equal(m.cards[f.crush].zone,'lost');assert.equal(m.cards[f.scomp].zone,'used');assert.equal(m.cards[troop].zone,'table');});
test('Imperial Code Cylinder cancels Flyboy and prevents relocation',()=>{const f=escapeFixture();const site=pull(f.m,'dark','1_285','table');f.m.locations.push(site);state.moveCard(f.m,f.pilot,'table');f.m.cards[f.pilot].location=site;let m=priority(step(f.m,play(f.flyboy)),'dark');m=step(m,scompOffer(m,f.cylinder,'cancel'));m=seek(m,x=>x.cards[f.cylinder].zone==='used');assert.equal(m.cards[f.flyboy].zone,'lost');assert.equal(m.cards[f.troop].location,f.remote);});
for(const mode of ['window','destination','target'])test('saved relocation rejects tampered '+mode,()=>{const f=escapeFixture(),m=step(f.m,play(f.flyboy)),p=m.stack.find(x=>x.action?.handler==='compactor:play').action.payload;if(mode==='window')p.window=-1;else if(mode==='destination')p.destination=mod('identity').referenceCard(m,f.site);else p.targets.push(p.targets[0]);assert.throws(()=>rules.validate(m),/compactor|relocation/);});
test('Flyboy relocation remains free even with an empty Force Pile',()=>{const f=escapeFixture();for(const id of [...f.m.players.light.force])state.moveCard(f.m,id,'used');const m=settled(step(f.m,play(f.flyboy)));assert.equal(m.cards[f.troop].location,f.compactor);assert.equal(m.players.light.force.length,0);});
test('lost destination prevents relocation without redirecting the original targets',()=>{const f=escapeFixture();let m=step(f.m,play(f.flyboy));m.locations=m.locations.filter(id=>id!==f.compactor);state.moveCard(m,f.compactor,'hand');m=seek(m,x=>x.cards[f.flyboy].zone==='used');assert.equal(m.cards[f.troop].location,f.remote);assert.equal(m.cards[f.droid].location,f.remote);});
test('a remaining immobile guard keeps battle alive after other characters relocate',()=>{const f=escapeFixture(),guard=pull(f.m,'light','1_26','table',f.remote);f.m.data.battle.participants.light.push(guard);const m=seek(step(f.m,play(f.flyboy)),x=>x.cards[f.flyboy].zone==='used');assert.equal(m.cards[guard].location,f.remote);assert.notEqual(m.data.battle.stage,'complete');assert.equal(m.cards[f.troop].location,f.compactor);assert.ok(!ids(m).includes('battle-premature-end'));});
test('crushing loss opens Kintan response before the next chosen root',()=>{const f=fixture(),troop=pull(f.m,'light','1_28','table',f.compactor),enemy=pull(f.m,'dark','1_194','table',f.compactor),kintan=pull(f.m,'dark','1_254','hand');state.moveCard(f.m,f.passenger,'lost');let m=choose(step(f.m,play(f.crush)));m=priority(seek(step(m,'crush:'+troop),x=>x.stack.at(-1)?.event?.kind==='cards-lost'),'dark');assert.ok(ids(m).includes('revival:kintan:'+kintan));m=step(m,'revival:kintan:'+kintan);m=choose(m);assert.equal(m.cards[f.passenger].zone,'hand');assert.equal(m.cards[enemy].zone,'table');});
test('computer uses visible crushing advantage and passes when its own cards outweigh enemies',()=>{const f=fixture(),cpu=mod('computer');const troop=pull(f.m,'light','1_28','table',f.compactor);let v=mod('runtime').project(f.m,rules,'dark');v.prompt.choices=v.prompt.choices.filter(c=>c.id===play(f.crush)||c.id==='pass');assert.equal(cpu.chooseComputerAction(v,'dark'),play(f.crush));pull(f.m,'dark','1_194','table',f.compactor);state.moveCard(f.m,f.pilot,'table');f.m.cards[f.pilot].location=f.compactor;v=mod('runtime').project(f.m,rules,'dark');v.prompt.choices=v.prompt.choices.filter(c=>c.id===play(f.crush)||c.id==='pass');assert.notEqual(cpu.chooseComputerAction(v,'dark'),play(f.crush));});
test('crushing decision rejects a duplicate target after reload',()=>{const f=fixture();pull(f.m,'light','1_28','table',f.compactor);const m=choose(step(f.m,play(f.crush)));m.stack.at(-1).payload.targets.push(m.stack.at(-1).payload.targets[0]);assert.throws(()=>rules.validate(m),/compactor/);});
const {default:fs}=await import('node:fs');
const observations=JSON.parse(fs.readFileSync(new URL('./gemp/compactor-results.json',import.meta.url)));
for(const row of observations)test('executed GEMP compactor comparison '+row.kind+(row.ownBattle??''),()=>{
 if(row.kind==='relocate'){const f=escapeFixture(row.ownBattle),gun=pull(f.m,'light','1_152','table',f.remote);f.m.cards[gun].attachedTo=f.troop;const before=f.m.players.light.force.length,m=settled(step(f.m,play(f.flyboy)));assert.deepEqual({kind:row.kind,ownBattle:row.ownBattle,troopMoved:m.cards[f.troop].location===f.compactor,droidMoved:m.cards[f.droid].location===f.compactor,weaponAttached:m.cards[gun].attachedTo===f.troop,forcePaid:before-m.players.light.force.length,regularMove:ground.usage(m).moved.includes(f.troop),used:m.cards[f.flyboy].zone==='used'},row);}
 else if(row.kind==='crush'){const f=fixture(),troop=pull(f.m,'light','1_28','table',f.compactor),enemy=pull(f.m,'dark','1_194','table',f.compactor),gun=pull(f.m,'light','1_152','table',f.compactor);f.m.cards[gun].attachedTo=troop;let m=choose(step(f.m,play(f.crush)));const actorChooses=m.stack.at(-1).side==='dark';m=settled(step(m,'crush:'+troop));assert.deepEqual({kind:row.kind,actorChooses,attachmentsLost:m.cards[gun].zone==='lost',enemyLost:m.cards[enemy].zone==='lost',interruptLost:m.cards[f.crush].zone==='lost',locationRemains:m.locations.includes(f.compactor)},row);}
 else {const f=fixture('light'),site=pull(f.m,'dark','1_285','table');f.m.locations.push(site);pull(f.m,'light','2_14','table',site);let m=priority(step(f.m,scompOffer(f.m,f.scomp,'peek')),'dark');m=settled(step(m,scompOffer(m,f.boring,'cancel')));assert.deepEqual({kind:row.kind,boringUsed:m.cards[f.boring].zone==='used',scompLost:m.cards[f.scomp].zone==='lost'},row);}
});
test('compactor oracle receipt binds executed source and observations',async()=>{const {createHash}=await import('node:crypto'),p=JSON.parse(fs.readFileSync(new URL('./gemp/compactor-provenance.json',import.meta.url)));for(const [f,sha]of Object.entries(p.files))assert.equal(createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+f,import.meta.url))).digest('hex'),sha);assert.equal(observations.length,p.observations);});
