import test from 'node:test';
import assert from 'node:assert/strict';
import * as fns from './alternatives-fixture.mjs';
const {chooseComputerAction}=fns.mod('computer'),clone=x=>JSON.parse(JSON.stringify(x));
function choose(view,side='light'){const before=clone(view),id=chooseComputerAction(view,side);assert.deepEqual(view,before);assert.equal(chooseComputerAction(clone(view),side),id);assert.ok(view.prompt.choices.some(c=>c.id===id));return id;}
const cpu=m=>choose(fns.runtime.project(m,fns.rules,'light'));
function view(choices){return {status:'playing',turn:{side:'dark',phase:'control'},table:[],locations:[],players:{light:{hand:[],lost:[],destiny:[],lifeForce:20,counts:{reserve:10,force:5}}},rules:{},prompt:{side:'light',timing:'response',mandatory:false,choices:choices.map(id=>({id,label:id}))}};}
const card=(id,blueprint,owner,location)=>({id,blueprint,owner,...(location?{location}:{}),zone:'table'});
test('CPU releases captured crew through real legal Alternatives action and resumes after serialization',()=>{const f=fns.fixture();let m=fns.releaseReady(f);const id=cpu(m);assert.match(id,new RegExp('^alternatives:.*:release:'+f.ship+':'+f.bay+'$'));m=fns.step(m,id);m=fns.done(clone(m));for(const id of f.characters){assert.equal(m.cards[id].zone,'table');assert.equal(m.cards[id].location,f.bay);}fns.rules.validate(m);});
test('CPU pays to cancel unfavorable space battle but keeps favorable/equal battles',()=>{const f=fns.fixture({capture:false}),m=fns.battleReady(f),v=fns.runtime.project(m,fns.rules,'light'),id='alternatives:'+f.alt+':battle:'+f.site;v.prompt.choices=v.prompt.choices.filter(c=>c.id===id||c.id==='pass');const values=v.rules.values.sites[f.site];values.dark.power=20;values.light.defendingPower=3;assert.equal(choose(v),id);values.light.defendingPower=20;assert.equal(choose(v),'pass');values.light.defendingPower=25;assert.equal(choose(v),'pass');const force=m.players.light.force.length;const result=fns.seek(fns.done(fns.step(m,id)),x=>fns.mod('battle').battle(x)?.stage==='complete');assert.equal(result.players.light.force.length,force-3);assert.equal(fns.mod('battle').battle(result).cancelled,true);});
test('CPU counters Besieged deployment through a real response and preserves trapped crew',()=>{const f=fns.fixture();let m=fns.phase(f.m,'dark','deploy');m=fns.step(m,'besieged:deploy:'+f.effect+':'+f.ship);m=fns.seek(m,x=>fns.ids(x).includes('alternatives:'+f.alt+':deployment:'+f.effect));const v=fns.runtime.project(m,fns.rules,'light');v.prompt.choices=v.prompt.choices.filter(c=>!c.id.includes(':release:'));const id=choose(v);assert.match(id,/:deployment:/);m=fns.done(fns.step(m,id));assert.equal(m.cards[f.effect].zone,'lost');assert.equal(m.cards[f.ship].zone,'inactive');});
test('CPU cancels active Besieged for crew protection when no safe release is offered',()=>{const f=fns.fixture();let m=fns.priority(fns.seek(fns.deployEffect(f),x=>x.stack.length===1),'light');const v=fns.runtime.project(m,fns.rules,'light');v.prompt.choices=v.prompt.choices.filter(c=>!c.id.includes(':release:'));const id=choose(v);assert.match(id,/:effect:/);m=fns.done(fns.step(m,id));assert.equal(m.cards[f.effect].zone,'lost');for(const id of f.characters)assert.equal(m.cards[id].zone,'inactive');});
test('CPU ranks safe useful offered docking bays and refuses a visibly losing release',()=>{const v=view(['alternatives:i:release:s:occupied','alternatives:i:release:s:safe','alternatives:i:release:s:risk','pass']);v.table=[card('safe','1_129','light'),card('occupied','1_129','light'),card('risk','1_285','dark'),{...card('crew','1_28','light'),zone:'inactive'},card('garrison','1_28','light','occupied')];v.rules.capturedShips=[{id:'s',crew:['crew']}];v.rules.values={characters:{},sites:{safe:{dark:{power:0},light:{power:0}},occupied:{dark:{power:0},light:{power:1}},risk:{dark:{power:20},light:{power:0}}}};assert.equal(choose(v),'alternatives:i:release:s:safe');v.prompt.choices=v.prompt.choices.filter(c=>c.id.includes(':risk')||c.id==='pass');assert.equal(choose(v),'pass');});
test('CPU Alternatives choice depends only on own projection and offered actions',()=>{const f=fns.fixture(),m=fns.releaseReady(f),first=cpu(m),changed=clone(m);changed.players.dark.reserve.reverse();changed.players.light.reserve.reverse();assert.equal(cpu(changed),first);const v=fns.runtime.project(m,fns.rules,'light');v.prompt.choices=v.prompt.choices.filter(c=>!c.id.startsWith('alternatives:'));assert.ok(!choose(v).startsWith('alternatives:'));});
