import test from 'node:test';
import assert from 'node:assert/strict';
import {mod,runtime,rules,state,clone,pull,step,seek,ids,priority} from './prisoner-fixture.mjs';
import {controlFixture} from './control-station-fixture.mjs';
const travel=mod('vessel-travel'),executor=mod('executor-sites'),refresh=m=>{for(const side of ['light','dark'])assert.deepEqual(runtime.project(m,rules,side),runtime.project(clone(m),rules,side));};
const route=f=>'voyage:hyperspace:'+f.ship+':'+f.to;
const finish=m=>seek(m,x=>!x.stack.some(f=>f.kind==='resolution'&&f.action.handler.startsWith('voyage:')));
test('Control Station grants Light a paid regular Executor move during Dark move phase',()=>{
 const f=controlFixture(),darkForce=f.m.players.dark.force.length,lightForce=f.m.players.light.force.length;
 assert.ok(!ids(f.m).includes(route(f)));assert.equal(travel.vesselRoutes(f.m,f.ship).length,0);
 let m=priority(f.m,'light');assert.ok(ids(m).includes(route(f)));m=step(m,route(f));refresh(m);m=finish(m);
 assert.equal(m.cards[f.ship].owner,'dark');assert.equal(m.cards[f.ship].location,f.to);assert.equal(m.players.dark.force.length,darkForce);assert.equal(m.players.light.force.length,lightForce-1);assert.ok(mod('ground').usage(m).moved.includes(f.ship));assert.equal(travel.vesselTravelActions(m,{timing:'phase'},'light').some(a=>a.source===f.ship),false);refresh(m);
});
test('Control Station permission belongs to Light even when Executor was stolen by Light',()=>{const f=controlFixture({stolen:true});assert.ok(!ids(f.m).includes(route(f)));let m=priority(f.m,'light');assert.ok(ids(m).includes(route(f)));m=finish(step(m,route(f)));assert.equal(m.cards[f.ship].location,f.to);assert.equal(m.cards[f.ship].owner,'light');refresh(m);});
test('Only active Light control during Dark move phase restricts ordinary Dark movement',()=>{for(const mode of ['uncontrolled','contested','canceled','other-phase']){const f=controlFixture({controlled:mode!=='uncontrolled'});if(mode==='contested')pull(f.m,'dark','1_194','table',f.station);if(mode==='canceled')mod('game-text').suppressGameText(f.m,f.rebel,f.station);if(mode==='other-phase')f.m.turn.phase='battle';assert.equal(executor.executorMovementController(f.m,f.ship),undefined,mode);assert.ok(travel.vesselRoutes(f.m,f.ship).length,mode);assert.equal(travel.vesselTravelActions(f.m,{timing:'phase'},'light').some(a=>a.source===f.ship),false,mode);}});
test('Controller does not bypass one regular move, insufficient Light Force, or movement barriers',()=>{for(const mode of ['used','force','barred']){const f=controlFixture();if(mode==='used')mod('ground').record(f.m).moved.push(f.ship);if(mode==='force')for(const id of [...f.m.players.light.force])state.moveCard(f.m,id,'used');if(mode==='barred')mod('ground').record(f.m).barriers[f.ship]=f.m.turn.number;assert.equal(travel.vesselTravelActions(f.m,{timing:'phase'},'light').some(a=>a.source===f.ship),false,mode);refresh(f.m);}});
test('Controller text, control and exact instance are revalidated during the pending move',()=>{for(const mode of ['text','control','instance']){const f=controlFixture();let m=step(priority(f.m,'light'),route(f));if(mode==='text')mod('game-text').suppressGameText(m,f.rebel,f.station);if(mode==='control')pull(m,'dark','1_194','table',f.station);if(mode==='instance'){state.moveCard(m,f.rebel,'hand');m.locations=m.locations.filter(id=>id!==f.station);state.moveCard(m,f.station,'hand');state.moveCard(m,f.station,'table');m.locations.splice(2,0,f.station);state.moveCard(m,f.rebel,'table');m.cards[f.rebel].location=f.station;}m=finish(m);assert.equal(m.cards[f.ship].location,f.from,mode);refresh(m);}});
test('Movement continuation rejects forged controller, payer and actor',()=>{const f=controlFixture(),pending=step(priority(f.m,'light'),route(f));for(const mutate of [r=>r.action.payload.controller=mod('identity').referenceCard(f.m,f.theatre),r=>r.actor='dark',r=>r.action.payment={dark:1}]){const bad=clone(pending),r=bad.stack.find(f=>f.kind==='resolution'&&f.action.handler==='voyage:begin');mutate(r);assert.throws(()=>runtime.project(bad,rules,'light'));}});
test('Imperial leader grants power for each named Executor site, not Launch Bay',()=>{const f=controlFixture({controlled:false}),base=mod('occupancy').vesselPower(f.m,f.ship);state.moveCard(f.m,f.leader,'table');f.m.cards[f.leader].location=f.station;assert.equal(executor.executorControlPowerBonus(f.m,f.ship),3);assert.equal(mod('occupancy').vesselPower(f.m,f.ship),base+3);const bay=pull(f.m,'dark','4_165');f.m.locations.push(bay);mod('ship-sites').registerShipSite(f.m,bay,f.ship);assert.equal(executor.executorControlPowerBonus(f.m,f.ship),3);mod('game-text').suppressGameText(f.m,f.ship,f.leader);assert.equal(executor.executorControlPowerBonus(f.m,f.ship),3);mod('game-text').suppressGameText(f.m,f.ship,f.station);assert.equal(executor.executorControlPowerBonus(f.m,f.ship),0);refresh(f.m);});
test('Control Station power condition tracks leader departure and unrelated ships',()=>{const f=controlFixture({controlled:false});state.moveCard(f.m,f.leader,'table');f.m.cards[f.leader].location=f.theatre;assert.equal(executor.executorControlPowerBonus(f.m,f.ship),0);f.m.cards[f.leader].location=f.station;assert.equal(executor.executorControlPowerBonus(f.m,f.ship),3);state.moveCard(f.m,f.leader,'hand');assert.equal(executor.executorControlPowerBonus(f.m,f.ship),0);assert.equal(executor.executorControlPowerBonus(f.m,f.rebel),0);});

test('Loss of Light control in the moving response stops the hull after spending its regular move',()=>{const f=controlFixture();let m=step(priority(f.m,'light'),route(f));m=seek(m,x=>x.stack.at(-1)?.event?.kind==='vessel-moving');assert.ok(mod('ground').usage(m).moved.includes(f.ship));pull(m,'dark','1_194','table',f.station);m=finish(m);assert.equal(m.cards[f.ship].location,f.from);assert.ok(mod('ground').usage(m).moved.includes(f.ship));refresh(m);});
