import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {load} from '../native-proof/load-engine.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url));
const runtime=mod('runtime'),state=mod('state'),board=mod('board'),battle=mod('battle');
const bacta=mod('bacta'),table=mod('table'),persona=mod('persona'),costs=mod('deploy-costs');
const rules={...mod('premiere-rules').premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true};
const clone=x=>JSON.parse(JSON.stringify(x));
function fresh(){return runtime.createMatch('deploy-costs',60,['light','dark'].map(side=>({side,cards:[...(side==='light'?['1_11','1_21','4_2','5_5','101_2','1_91','3_32','3_32','1_12','8_5','3_9','3_9','3_60','3_59','1_129','1_132','1_19','1_19','1_100','1_152','1_6','1_5','1_31','1_40']:['4_116','4_116','5_99','1_284','1_168','1_324','13_86','1_267','1_317','1_317','3_86','3_86']),...Array(60).fill(side==='light'?'1_28':'1_194')].slice(0,60)})),rules)}
function pull(m,side,bp,zone='table',location){const c=Object.values(m.cards).find(c=>c.owner===side&&c.blueprint===bp&&c.zone==='reserve');assert.ok(c,bp);state.moveCard(m,c.id,zone);if(location)c.location=location;return c.id}
function prompt(m){const p=runtime.prompt(m,rules,'dark');return p&&runtime.prompt(m,rules,p.side)}
const ids=m=>prompt(m).choices.map(c=>c.id);
function step(m,id){const before=clone(m);const r=runtime.applyCommand(clone(m),rules,prompt(m).side,{revision:m.revision,choice:id},()=>0);assert.deepEqual(m,before);state.assertState(r);for(const side of ['light','dark'])assert.deepEqual(runtime.project(r,rules,side),runtime.project(clone(r),rules,side));return r}
function seek(m,f){for(let n=0;n<600;n++){if(f(m))return m;const cs=ids(m);m=step(m,cs.includes('pass')?'pass':cs.includes('skip-destiny')?'skip-destiny':cs[0])}throw Error('unreached boundary')}
const boundary=(m,kind)=>seek(m,x=>x.stack.at(-1)?.event?.kind===kind);
const priority=(m,side)=>prompt(m).side===side?m:step(m,'pass');
const phase=(m,side,phase)=>seek(m,x=>x.turn.side===side&&x.turn.phase===phase&&x.stack.length===1&&prompt(x).side===side);

function fixture(side='light',mode='same'){
 let m=fresh();const opposite=side==='light'?'dark':'light',site=pull(m,'light','1_129'),adj=pull(m,'light','1_132');m.locations.push(site,adj);
 const target=pull(m,side,side==='light'?'1_28':'1_194','table',site),second=pull(m,side,side==='light'?'1_28':'1_194','table',site),droid=pull(m,side,side==='light'?'3_9':'3_86','table',mode==='adjacent'?adj:site);
 const enemies=[];for(let i=0;i<10;i++)enemies.push(pull(m,opposite,opposite==='light'?'1_28':'1_194','table',site));
 for(const s of ['light','dark'])for(let i=0;i<10;i++)state.moveCard(m,m.players[s].reserve.at(-1),'force');
 m=phase(runtime.startTurns(m,rules),opposite,'battle');return{m,side,opposite,site,adj,target,second,droid,enemies};
}
function damage(f,hit=true){let m=boundary(step(f.m,'battle:'+f.site),'battle-damage');if(hit)battle.battle(m).hits.push(f.target);return priority(m,f.side)}
const offer=(m,f)=>ids(m).find(id=>id.startsWith('fx:'+f.droid+':'));
const pending=(m,f)=>priority(boundary(step(m,'forfeit:'+f.target),'about-to-forfeit'),f.side);
const finish=m=>boundary(m,'forfeited-to-used');


function setup(lab=true,bad=true){const f=fixture();if(lab){f.lab=pull(f.m,'light','3_60');f.m.locations.push(f.lab)}if(bad)f.bad=pull(f.m,'dark','4_116');return f}
for(const bp of ['1_19','101_2','1_11','1_21','4_2','5_5','5_99'])for(const zone of ['hand','lost','table'])test('global deploy value '+bp+' '+zone,()=>{const f=setup(false),side=bp==='5_99'?'dark':'light',id=pull(f.m,side,bp,zone,zone==='table'?f.site:undefined);const base=board.printed(f.m,id,'deploy');assert.equal(costs.deployValue(f.m,id),base+2);state.moveCard(f.m,f.bad,'lost');assert.equal(costs.deployValue(f.m,id),base)});
test('duplicate automatic copies do not stack and non-persona characters are unaffected',()=>{const f=setup();pull(f.m,'dark','4_116');const luke=pull(f.m,'light','1_19','hand');assert.equal(costs.deployValue(f.m,luke),5);assert.equal(costs.deployValue(f.m,f.target),1)});
test('Bad Feeling deploys free and successful cancellation removes the global modifier',()=>{const f=setup(false);state.moveCard(f.m,f.bad,'hand');let m=phase(f.m,'dark','deploy'),force=m.players.dark.force.length;m=boundary(step(m,'deploy-effect:'+f.bad),'deployed');assert.equal(m.players.dark.force.length,force);const luke=pull(m,'light','1_19','hand');assert.equal(costs.deployValue(m,luke),5);table.loseFromTable(m,[f.bad]);assert.equal(costs.deployValue(m,luke),3)});
test('canceled Effect deployment never turns on cost or play restrictions',()=>{const f=setup(false);state.moveCard(f.m,f.bad,'hand');let m=phase(f.m,'dark','deploy');m=step(m,'deploy-effect:'+f.bad);m.stack.find(q=>q.kind==='resolution'&&q.action.handler==='deploy-effect:deploy').cancelled=true;m=phase(m,'dark','deploy');assert.equal(m.cards[f.bad].zone,'lost');assert.equal(costs.deployValue(m,pull(m,'light','1_19','hand')),3)});
test('ordinary character deployment pays the same global value',()=>{const f=setup(false),luke=pull(f.m,'light','101_2','hand');let m=phase(f.m,'light','deploy'),force=m.players.light.force.length;m=boundary(step(m,'deploy:'+luke+':'+f.site),'deployed');assert.equal(force-m.players.light.force.length,6)});
test('Bacta recovery uses global modifiers but not deployment-only site discounts',()=>{const f=setup(),tank=pull(f.m,'light','3_32'),luke=pull(f.m,'light','1_19','stacked');f.m.cards[luke].stackedOn=tank;assert.equal(bacta.bactaCost(f.m,tank,luke),3);state.moveCard(f.m,f.droid,'hand');assert.equal(bacta.bactaCost(f.m,tank,luke),5);let m=phase(f.m,'light','deploy'),force=m.players.light.force.length;m=boundary(step(m,'bacta:recover:'+tank+':'+luke),'card-to-hand');assert.equal(force-m.players.light.force.length,5)});
test('Bad Feeling prohibits actual Interrupt offering and accepts it once source leaves',()=>{const f=setup(false),card=pull(f.m,'light','1_91','hand');let m=phase(f.m,'light','battle');m=step(m,'battle:'+f.site);m=priority(m,'light');assert.ok(!ids(m).some(id=>id.includes(card)));assert.equal(persona.canPlayCard(m,card),false);state.moveCard(m,f.bad,'lost');assert.equal(persona.canPlayCard(m,card),true);assert.ok(ids(m).some(id=>id.includes(card)))});
test('Med Lab discounts first successful medical deployment anywhere; second pays printed',()=>{const f=setup(true,false);state.moveCard(f.m,f.droid,'hand');const second=pull(f.m,'light','3_9','hand');let m=phase(f.m,'light','deploy'),force=m.players.light.force.length;m=boundary(step(m,'deploy:'+f.droid+':'+f.site),'deployed');assert.equal(m.players.light.force.length,force);assert.equal(costs.medicalDeployReduction(m,second),0);m=phase(m,'light','deploy');m=boundary(step(m,'deploy:'+second+':'+f.adj),'deployed');assert.equal(force-m.players.light.force.length,2)});
test('medical allowance is not spent by a retired deployment',()=>{const f=setup(true,false);state.moveCard(f.m,f.droid,'hand');const second=pull(f.m,'light','3_9','hand');let m=phase(f.m,'light','deploy');m=step(m,'deploy:'+f.droid+':'+f.site);const index=m.stack.findIndex(q=>q.kind==='resolution'&&q.action.handler==='ground:deploy');runtime.retireAction(m,index,m.stack[index].action.id,m.stack[index+1].serial);state.moveCard(m,f.droid,'lost');m=phase(m,'light','deploy');assert.equal(costs.medicalDeployReduction(m,second),2)});
test('Med Lab deployed after an earlier medical droid still has its allowance',()=>{const f=setup(false,false);state.moveCard(f.m,f.droid,'hand');const second=pull(f.m,'light','3_9','hand');let m=phase(f.m,'light','deploy');m=boundary(step(m,'deploy:'+f.droid+':'+f.site),'deployed');const lab=pull(m,'light','3_60','hand');m=phase(m,'light','deploy');const choice=ids(m).find(id=>id.startsWith('site:'+lab+':'));assert.ok(choice);m=step(m,choice);m=phase(m,'light','deploy');assert.equal(costs.medicalDeployReduction(m,second),2)});
test('ordinary droids and dark medical droids do not consume or receive the Light discount',()=>{const f=setup(true,false),threepio=pull(f.m,'light','1_6','hand'),dark=pull(f.m,'dark','3_86','hand');assert.equal(costs.medicalDeployReduction(f.m,threepio),0);assert.equal(costs.medicalDeployReduction(f.m,dark),0);let m=phase(f.m,'light','deploy');m=boundary(step(m,'deploy:'+threepio+':'+f.site),'deployed');assert.equal(costs.medicalDeployReduction(m,f.droid),2)});
test('Lab discount renews next turn, survives refresh, and records original observer',()=>{const f=setup(true,false);state.moveCard(f.m,f.droid,'hand');let m=phase(f.m,'light','deploy');m=boundary(step(m,'deploy:'+f.droid+':'+f.site),'deployed');m=clone(m);assert.equal(costs.medicalDeployReduction(m,f.droid),0);m.turn.number++;assert.equal(costs.medicalDeployReduction(m,f.droid),2)});
for(const mode of ['imperial','alien','contested','empty'])test('Med Lab drain condition '+mode,()=>{const f=setup(true,false);if(mode!=='empty')pull(f.m,'dark',mode==='alien'?'5_99':'1_194','table',f.lab);if(mode==='contested')pull(f.m,'light','1_28','table',f.lab);assert.equal(board.drainAmount(f.m,'dark',f.lab),mode==='imperial'?2:1)});
test('actual drain at Med Lab loses two Force under Imperial control',()=>{const f=setup(true,false);pull(f.m,'dark','1_194','table',f.lab);let m=phase(f.m,'dark','control');m=step(m,'drain:'+f.lab);m=seek(m,x=>x.stack.at(-1)?.handler==='ground:force-loss');assert.equal(m.stack.at(-1).payload.remaining,2)});
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/deploy-cost-results.json',import.meta.url)));
for(const row of oracle)test('executed deploy-cost oracle '+row.name,()=>{
 if(row.name.startsWith('query-')){const [,bp,zone]=row.name.split('-'),f=setup(false),id=pull(f.m,bp==='5_99'?'dark':'light',bp,zone,zone==='table'?f.site:undefined);const on=costs.deployValue(f.m,id);state.moveCard(f.m,f.bad,'hand');assert.deepEqual({name:row.name,on,off:costs.deployValue(f.m,id)},row);return}
 if(row.name.startsWith('drain-')){const mode=row.name.slice(6),f=setup(true,false);if(mode!=='empty')pull(f.m,'dark',mode==='alien'?'5_99':'1_194','table',f.lab);if(mode==='contested')pull(f.m,'light','1_28','table',f.lab);assert.deepEqual({name:row.name,amount:board.drainAmount(f.m,'dark',f.lab)},row);return}
 if(row.name.startsWith('patient-')){const count=Number(row.name.slice(8)),f=setup(),tank=pull(f.m,'light','3_32'),hero=pull(f.m,'light','1_19','stacked');f.m.cards[hero].stackedOn=tank;if(count===0)state.moveCard(f.m,f.droid,'hand');if(count===2)pull(f.m,'light','3_9','table',f.adj);let m=phase(f.m,'light','deploy'),before=m.players.light.force.length;m=boundary(step(m,'bacta:recover:'+tank+':'+hero),'card-to-hand');assert.deepEqual({name:row.name,cost:before-m.players.light.force.length},row);return}
 if(row.name==='medical'){const f=setup(true,false);state.moveCard(f.m,f.droid,'hand');const second=pull(f.m,'light','3_9','hand');let m=phase(f.m,'light','deploy'),before=m.players.light.force.length;m=boundary(step(m,'deploy:'+f.droid+':'+f.site),'deployed');const first=before-m.players.light.force.length;m=phase(m,'light','deploy');before=m.players.light.force.length;m=boundary(step(m,'deploy:'+second+':'+f.lab),'deployed');assert.deepEqual({name:row.name,first,second:before-m.players.light.force.length},row);return}
 if(row.name==='deployment'){const f=setup(false);state.moveCard(f.m,f.bad,'hand');let m=phase(f.m,'dark','deploy'),before=m.players.dark.force.length;m=boundary(step(m,'deploy-effect:'+f.bad),'deployed');const effectCost=before-m.players.dark.force.length,hero=pull(m,'light','101_2','hand');m=phase(m,'light','deploy');before=m.players.light.force.length;m=boundary(step(m,'deploy:'+hero+':'+f.site),'deployed');assert.deepEqual({name:row.name,effectCost,heroCost:before-m.players.light.force.length},row);return}
 if(row.name==='play-ban'){const f=setup(false),card=pull(f.m,'light','1_91','hand');let m=phase(f.m,'light','battle');m=priority(step(m,'battle:'+f.site),'light');const blocked=!ids(m).some(id=>id.includes(card));state.moveCard(m,f.bad,'hand');assert.deepEqual({name:row.name,blocked,allowed:ids(m).some(id=>id.includes(card))},row);return}
 assert.fail('Unmapped oracle observation');
});
test('initiated deployment retains its paid cost when the global provider leaves',()=>{const f=setup(false),hero=pull(f.m,'light','101_2','hand');let m=phase(f.m,'light','deploy'),before=m.players.light.force.length;m=step(m,'deploy:'+hero+':'+f.site);state.moveCard(m,f.bad,'lost');m=boundary(m,'deployed');assert.equal(before-m.players.light.force.length,6);assert.equal(costs.deployValue(m,hero),4)});
test('Med Lab availability is restricted to active locations',()=>{const f=setup(true,false);assert.equal(costs.medicalDeployReduction(f.m,f.droid),2);f.m.locations=f.m.locations.filter(id=>id!==f.lab);assert.equal(costs.medicalDeployReduction(f.m,f.droid),0)});
