import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
import {assertDisarmOutcome,readGempMatch,replayGempMatch} from './gemp-match-replay.mjs';
const record=()=>readGempMatch(new URL('./gemp/complete-matches/disarm-battle.json.gz',import.meta.url));
const cards=r=>Object.fromEntries(Object.entries(r.decks).flatMap(([owner,list])=>list.map((blueprint,i)=>[owner+'-'+(i+1),{blueprint,owner}])));
for(const [kind,side] of [['disarm-deploy','dark'],['disarm-deploy','light'],['evazan','dark']])test('full-game evidence binds '+side+' '+kind+' targeting and immediate losses',()=>{
 const r=record(),i=r.trace.findIndex(x=>x.semantic?.kind===kind&&x.semantic.side===side),p=assertDisarmOutcome(r.trace,i,cards(r),r.final);assert.equal(p.operation,kind==='evazan');if(kind==='disarm-deploy')assert.equal(p.weapons.length,side==='dark'?3:1);else assert.equal(p.target,'light-25');
});
for(const mode of ['answer','label','source','source-owner','phase','target','observation-card','observation-blueprint','observation-answer','observation-boundary','target-type','same-side','no-gun','no-own-gun','missing-outcome','outcome-source','outcome-target','outcome-early','outcome-late','attachment-list','outcome-state','missing-weapon','missing-effect','refunded-force','crossed-action'])test('disarming full-game evidence rejects '+mode,()=>{
 const r=record(),i=r.trace.findIndex(x=>x.semantic?.kind==='disarm-deploy'),row=r.trace[i],map=cards(r),o=row.disarmOutcome,p=assertDisarmOutcome(r.trace,i,map,r.final),after=r.trace[o.afterDecision+1].state;
 if(mode==='answer')row.answer='missing';if(mode==='label')row.parameters.actionText[row.parameters.actionId.indexOf(row.answer)]='Draw card';if(mode==='source')map[row.semantic.card].blueprint='1_194';if(mode==='source-owner')map[row.semantic.card].owner='light';if(mode==='phase')row.state.phase='battle';if(mode==='target')row.semantic.target='dark-21';if(mode==='observation-card')row.targetObservation.card='dark-21';if(mode==='observation-blueprint')row.targetObservation.blueprint='1_194';if(mode==='observation-answer')row.targetObservation.referenceCardId='missing';if(mode==='observation-boundary')row.targetObservation.afterDecision=i+2;if(mode==='target-type')map[p.target].blueprint='1_152';if(mode==='same-side')map[p.target].owner='dark';if(mode==='no-gun')row.state.table=row.state.table.filter(c=>!p.weapons.includes(c.id));if(mode==='no-own-gun')row.state.table=row.state.table.filter(c=>!(map[c.id].owner==='dark'&&map[c.id].blueprint==='1_317'));if(mode==='missing-outcome')delete row.disarmOutcome;if(mode==='outcome-source')o.source='dark-1';if(mode==='outcome-target')o.card='light-26';if(mode==='outcome-early')o.afterDecision=i;if(mode==='outcome-late')o.afterDecision=r.trace.length;if(mode==='attachment-list')o.attachedBefore=[];if(mode==='outcome-state')o.state.turn++;if(mode==='missing-weapon'){after.players.light.lost=after.players.light.lost.filter(id=>id!==p.weapons[0]);o.state=structuredClone(after);}if(mode==='missing-effect'){after.table=after.table.filter(c=>c.id!==p.source);o.state=structuredClone(after);}if(mode==='refunded-force'){after.players.dark.force.push('dark-4');o.state=structuredClone(after);}if(mode==='crossed-action')r.trace[i+2].semantic={kind:'draw'};
 assert.throws(()=>assertDisarmOutcome(r.trace,i,map,r.final));
});
for(const mode of ['source','location','self','old-trigger','wrong-trigger','not-lost','attachment-retained'])test('Evazan complete-game evidence rejects '+mode,()=>{
 const r=record(),i=r.trace.findIndex(x=>x.semantic?.kind==='evazan'),row=r.trace[i],map=cards(r),p=assertDisarmOutcome(r.trace,i,map,r.final),after=r.trace[row.disarmOutcome.afterDecision+1].state;
 if(mode==='source')map[p.source].blueprint='1_194';if(mode==='location')row.state.table.find(c=>c.id===p.source).location='light-18';if(mode==='self')row.semantic.target=p.source;if(mode==='old-trigger')r.trace[i-1].semantic={kind:'draw'};if(mode==='wrong-trigger')row.text='Choose Control action or Pass';if(mode==='not-lost'){after.players.light.lost=after.players.light.lost.filter(id=>id!==p.target);row.disarmOutcome.state=structuredClone(after);}if(mode==='attachment-retained'){const id=p.attached[0],side=map[id].owner;after.players[side].lost=after.players[side].lost.filter(c=>c!==id);row.disarmOutcome.state=structuredClone(after);}
 assert.throws(()=>assertDisarmOutcome(r.trace,i,map,r.final));
});
test('complete Disarmed and Evazan match reproduces victory without state correction',()=>{const r=replayGempMatch(record());assert.equal(r.commands,2730);assert.equal(r.checkpoints,258);assert.equal(r.state.turn.number,44);assert.deepEqual(r.state.result,{winner:'light',loser:'dark',reason:'life-force'});assert.equal(r.transcript.filter(c=>c.choice.startsWith('disarm:deploy:')).length,2);assert.equal(r.transcript.filter(c=>c.choice.startsWith('disarm:operate:')).length,1);});
test('full-match receipt binds the executed source, exact decks and reference bytes',()=>{
 const p=JSON.parse(fs.readFileSync(new URL('./gemp/disarm-match-provenance.json',import.meta.url))),bytes=f=>fs.readFileSync(new URL('../../'+f,import.meta.url)),hash=b=>createHash('sha256').update(b).digest('hex'),r=record();
 assert.equal(hash(bytes(p.fixture)),p.sha256);assert.equal(hash(gunzipSync(bytes(p.fixture))),p.jsonSha256);assert.equal(hash(bytes(p.harness)),p.harnessSha256);assert.equal(hash(bytes(p.profile)),p.profileSha256);assert.equal(hash(fs.readFileSync(new URL('./gemp/NativeEngineDisarmMatchOracleTests.java',import.meta.url))),p.harnessSha256);assert.equal(p.referenceDecisions,r.trace.length);assert.equal(p.unchangedProductionFiles,6820);assert.equal(p.productionFilesChanged,0);assert.equal(p.junitTests,1);assert.equal(r.finished,true);
});
