import test from 'node:test';
import assert from 'node:assert/strict';
import {load} from '../native-proof/load-engine.mjs';
import {fixture,deploy,operate,boundary,finish,runtime,rules,state,priority,step,seek,pull} from './disarm-fixture.mjs';
import {ids,clone} from './noble-fixture.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url));
for(const side of ['light','dark'])for(const turn of ['light','dark'])test(side+' Disarmed deploys in '+turn+' Control and loses weapons before operation',()=>{
 const f=fixture(side,turn),before=mod('board').power(f.m,f.target);let m=boundary(step(f.m,deploy(f)),'disarmed');assert.equal(m.cards[f.gun].zone,'lost');assert.equal(m.cards[f.card].attachedTo,f.target);assert.equal(mod('board').power(m,f.target),Math.max(0,before-1));assert.equal(m.players[side].force.length,f.m.players[side].force.length);assert.equal(m.cards[f.device].zone,'table');m=priority(m,'dark');assert.ok(ids(m).includes(operate(f)));m=boundary(step(clone(m),operate(f)),'cards-lost');assert.equal(m.cards[f.target].zone,'lost');assert.equal(m.cards[f.card].zone,'lost');
});
for(const mode of ['no-own-gun','no-target-gun'])test('Disarmed cannot deploy without both armed characters '+mode,()=>{const f=fixture('dark','dark',mode);assert.ok(!ids(f.m).includes(deploy(f)));});
test('deployment outside Control is illegal',()=>{const f=fixture();f.m.turn.phase='deploy';assert.ok(!ids(f.m).includes(deploy(f)));});
test('simultaneous weapon Lost ordering precedes the disarmed trigger and survives reload',()=>{const f=fixture('dark','light','two-weapons');let m=seek(step(f.m,deploy(f)),x=>x.stack.at(-1)?.handler==='table:lost-order');assert.deepEqual(new Set(ids(m)),new Set(['place-lost:'+f.gun,'place-lost:'+f.spare]));assert.ok(!m.stack.some(x=>x.event?.kind==='disarmed'));m=boundary(step(clone(m),'place-lost:'+f.gun),'disarmed');assert.deepEqual(m.players.light.lost.slice(0,2),[f.spare,f.gun]);assert.ok(ids(priority(m,'dark')).includes(operate(f)));});
test('carry restriction prevents offered deployment and transfer, then disappears with Effect',()=>{const f=fixture();let m=finish(step(f.m,deploy(f)));m.turn.phase='deploy';m.turn.side='light';m.stack[0].priority='light';assert.ok(!ids(m).some(id=>id.startsWith('equip:')&&id.endsWith(':'+f.target)));assert.equal(mod('weapon-carrying').canCarryWeapon(m,f.target),false);mod('table').loseFromTable(m,[f.card]);assert.equal(mod('weapon-carrying').canCarryWeapon(m,f.target),true);assert.ok(ids(m).includes('equip:'+f.spare+':'+f.target));});
test('Disarmed is immune to Alter while playing and on table',()=>{const f=fixture(),alter=pull(f.m,'light','1_71','hand');let m=step(f.m,deploy(f));m=priority(m,'light');assert.ok(!ids(m).some(id=>id.startsWith('cancel:play:'+alter+':'+f.card+':')));m=finish(m);m.turn.phase='control';m.stack[0].priority='light';assert.ok(!ids(m).some(id=>id.startsWith('cancel:play:'+alter+':'+f.card+':')));});
test('Evazan may operate on friendly characters but CPU declines that choice',()=>{const f=fixture('light'),m=priority(boundary(step(f.m,deploy(f)),'disarmed'),'dark');assert.ok(ids(m).includes(operate(f)));const view=runtime.project(m,rules,'dark');view.prompt.choices=view.prompt.choices.filter(c=>[operate(f),'pass'].includes(c.id));assert.equal(mod('computer').chooseComputerAction(view,'dark'),'pass');});
test('CPU operates on an enemy and plays Disarmed',()=>{const f=fixture();assert.equal(mod('computer').chooseComputerAction(runtime.project(f.m,rules,'dark'),'dark'),deploy(f));const m=priority(boundary(step(f.m,deploy(f)),'disarmed'),'dark'),v=runtime.project(m,rules,'dark');v.prompt.choices=v.prompt.choices.filter(c=>[operate(f),'pass'].includes(c.id));assert.equal(mod('computer').chooseComputerAction(v,'dark'),operate(f));});
test('a removed and returned target cannot inherit a pending operation',()=>{const f=fixture();let m=priority(boundary(step(f.m,deploy(f)),'disarmed'),'dark');m=step(m,operate(f));mod('table').returnToHand(m,[f.target]);state.moveCard(m,f.target,'table');m.cards[f.target].location=f.site;m=finish(m);assert.equal(m.cards[f.target].zone,'table');});
test('source departure does not cancel an operation already initiated',()=>{const f=fixture();let m=step(priority(boundary(step(f.m,deploy(f)),'disarmed'),'dark'),operate(f));mod('table').returnToHand(m,[f.evazan]);m=boundary(m,'cards-lost');assert.equal(m.cards[f.target].zone,'lost');});
test('a canceled operation cannot repeat in the same response window',()=>{const f=fixture();let m=priority(boundary(step(f.m,deploy(f)),'disarmed'),'dark');const serial=m.stack.at(-1).serial;m=step(m,operate(f));m.stack.find(x=>x.action?.handler==='disarm:operate').cancelled=true;m=seek(m,x=>x.stack.at(-1)?.serial===serial);m=priority(m,'dark');assert.ok(!ids(m).includes(operate(f)));assert.equal(m.cards[f.target].zone,'table');});
for(const mode of ['actor','target','window','source','payment'])test('saved operation rejects invalid '+mode,()=>{const f=fixture();const m=step(priority(boundary(step(f.m,deploy(f)),'disarmed'),'dark'),operate(f)),r=m.stack.find(x=>x.action?.handler==='disarm:operate');if(mode==='actor')r.actor='light';if(mode==='target')r.action.payload.target.id=f.evazan;if(mode==='window')r.action.payload.window=-1;if(mode==='source')r.action.payload.source.id=f.target;if(mode==='payment')r.action.payment={dark:1};assert.throws(()=>rules.validate(m));});

test('real weapon hit offers Evazan and operation ends a battle when its last enemy is lost',()=>{const f=fixture();f.m.turn.phase='battle';f.m.stack[0].priority='dark';let m=boundary(step(f.m,'battle:'+f.site),'battle-weapons');m=priority(m,'dark');m=boundary(step(m,'fire:'+f.dg+':'+f.target),'hit');assert.equal(m.stack.at(-1).event.targetRef.id,f.target);m=priority(m,'dark');assert.ok(ids(m).includes(operate(f)));m=boundary(step(m,operate(f)),'cards-lost');assert.equal(m.cards[f.target].zone,'lost');m=seek(m,x=>x.data.battle.stage==='complete');assert.equal(m.data.battle.premature,true);});
test('a previous hit cannot target a returned physical card',()=>{const f=fixture();runtime.openWindow(f.m,'response','dark',{kind:'hit',target:f.target,weapon:f.dg});mod('table').returnToHand(f.m,[f.target]);state.moveCard(f.m,f.target,'table');f.m.cards[f.target].location=f.site;assert.ok(!ids(f.m).includes(operate(f)));});
test('no operation on self, distant characters, noncharacters or suppressed text',()=>{for(const mode of ['self','distant','noncharacter','suppressed']){const f=fixture();if(mode==='distant')f.m.cards[f.evazan].location=f.remote;if(mode==='suppressed')mod('game-text').suppressGameText(f.m,f.dark,f.evazan);runtime.openWindow(f.m,'response','dark',{kind:'hit',target:mode==='self'?f.evazan:mode==='noncharacter'?f.gun:f.target,weapon:f.dg});assert.ok(!ids(f.m).some(id=>id.startsWith('disarm:operate:')));}});
test('weapon-loss response cannot remove a new physical weapon instance',()=>{const f=fixture();let m=boundary(step(f.m,deploy(f)),'about-to-lose');assert.equal(m.stack.at(-1).event.allCards,true);state.moveCard(m,f.gun,'hand');state.moveCard(m,f.gun,'table');m.cards[f.gun].attachedTo=f.dark;m.cards[f.gun].location=f.site;m=boundary(m,'disarmed');assert.equal(m.cards[f.gun].zone,'table');assert.equal(m.cards[f.gun].attachedTo,f.dark);});

test('normal Evazan deployment and pilot power use the shared vessel rules',()=>{const f=fixture('dark','dark','normal',{light:['1_127'],dark:['1_302']});state.moveCard(f.m,f.evazan,'hand');const planet=pull(f.m,'light','1_127','table');f.m.locations.unshift(planet);const ship=pull(f.m,'dark','1_302','table',planet),before=mod('board').power(f.m,ship);f.m.turn.phase='deploy';f.m.stack[0].priority='dark';const force=f.m.players.dark.force.length;const m=finish(step(f.m,'vessel:aboard:'+f.evazan+':'+ship+':pilot'));assert.equal(m.cards[f.evazan].attachedTo,ship);assert.equal(m.cards[f.evazan].aboardRole,'pilot');assert.equal(force-m.players.dark.force.length,2);assert.equal(mod('board').power(m,ship)-before,2);});

const fs=await import('node:fs'),{createHash}=await import('node:crypto');
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/disarm-results.json',import.meta.url)));
for(const row of oracle)test('executed GEMP Disarmed/Evazan comparison '+[row.side,row.turn,row.mode].filter(Boolean).join(' '),()=>{
 if(row.mode==='pilot'){
  const f=fixture('dark','dark','normal',{light:['1_127'],dark:['1_302']});state.moveCard(f.m,f.evazan,'hand');const planet=pull(f.m,'light','1_127','table');f.m.locations.unshift(planet);const ship=pull(f.m,'dark','1_302','table',planet),before=mod('board').power(f.m,ship),force=f.m.players.dark.force.length;f.m.turn.phase='deploy';f.m.stack[0].priority='dark';const m=finish(step(f.m,'vessel:aboard:'+f.evazan+':'+ship+':pilot'));assert.equal(force-m.players.dark.force.length,row.cost);assert.equal(mod('board').power(m,ship)-before,row.bonus);return;
 }
 const f=fixture(row.side??'dark',row.turn??'dark',row.mode);
 if(row.mode==='no-target-gun'){assert.equal(ids(f.m).includes(deploy(f)),row.offered);return;}
 let m;
 if(['hit','source-left','decline'].includes(row.mode)){
  f.m.turn.phase='battle';f.m.stack[0].priority='dark';m=priority(boundary(step(f.m,'battle:'+f.site),'battle-weapons'),'dark');m=priority(boundary(step(m,'fire:'+f.dg+':'+f.target),'hit'),'dark');assert.equal(ids(m).includes(operate(f)),row.operable);
  if(row.mode==='decline')m=boundary(step(m,'pass'),'battle-weapons');
  else {m=step(m,operate(f));if(row.mode==='source-left')mod('table').returnToHand(m,[f.evazan]);m=boundary(m,'cards-lost');}
  assert.equal(m.cards[f.target].zone==='lost',row.patientLost);assert.equal(m.cards[f.gun].zone==='lost',row.gunLost);return;
 }
 m=priority(boundary(step(f.m,deploy(f)),'disarmed'),'dark');
 const observed={cost:f.m.players[f.side].force.length-m.players[f.side].force.length,power:mod('board').power(m,f.target),gunLost:m.cards[f.gun].zone==='lost',spareLost:m.cards[f.spare].zone==='lost',deviceRetained:m.cards[f.device].attachedTo===f.light,operable:ids(m).includes(operate(f))};
 assert.deepEqual(observed,Object.fromEntries(Object.keys(observed).map(k=>[k,row[k]])));
 m=boundary(step(m,operate(f)),'cards-lost');assert.equal(m.cards[f.target].zone==='lost',row.patientLost);assert.equal(m.cards[f.card].zone==='lost',row.effectLost);
});
test('Disarmed receipt binds the executed source and results',()=>{const p=JSON.parse(fs.readFileSync(new URL('./gemp/disarm-provenance.json',import.meta.url))),hash=file=>createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+file,import.meta.url))).digest('hex');assert.equal(hash(p.harness),p.harnessSha256);assert.equal(hash(p.results),p.resultsSha256);assert.equal(p.observations,oracle.length);assert.equal(p.productionFilesChanged,0);assert.equal(p.junitTests,4);});
for(const field of ['weapons','lost'])test('saved disarm continuation requires its '+field+' group',()=>{const f=fixture();let m=boundary(step(f.m,deploy(f)),field==='weapons'?'about-to-lose':'cards-lost');const r=m.stack.find(x=>x.action?.handler===(field==='weapons'?'disarm:weapons':'disarm:disarmed'));delete r.action.payload[field];assert.throws(()=>rules.validate(m),/Missing disarm/);});
test('production admission stays closed for the new cards',()=>{for(const bp of ['1_48','1_214','1_172'])assert.equal(mod('premiere-rules').premiereRules.supports(bp),false);});

test('weapon transfer is withheld for a disarmed host',()=>{const f=fixture();let m=finish(step(f.m,deploy(f)));const bearer=pull(m,'light','1_28','table',f.site);state.moveCard(m,f.spare,'table');m.cards[f.spare].attachedTo=bearer;m.cards[f.spare].location=f.site;m.turn.phase='deploy';m.turn.side='light';m.stack[0].priority='light';const choice='transfer:'+f.spare+':'+f.target;assert.ok(!ids(m).includes(choice));mod('table').loseFromTable(m,[f.card]);assert.ok(ids(m).includes(choice));});
test('a carrying restriction acquired during attachment responses prevents completion',()=>{const f=fixture();f.m.turn.phase='deploy';f.m.turn.side='light';f.m.stack[0].priority='light';let m=step(f.m,'equip:'+f.spare+':'+f.target);state.moveCard(m,f.card,'table');m.cards[f.card].attachedTo=f.target;m.cards[f.card].location=f.site;m=finish(m);assert.equal(m.cards[f.spare].zone,'lost');assert.notEqual(m.cards[f.spare].attachedTo,f.target);});
test('multiple active Disarmed cards do not stack their power reduction',()=>{const f=fixture('dark','dark','normal',{dark:['1_214']}),other=pull(f.m,'dark','1_214','table',f.site);const before=mod('board').power(f.m,f.target);f.m.cards[other].attachedTo=f.target;state.moveCard(f.m,f.card,'table');f.m.cards[f.card].attachedTo=f.target;f.m.cards[f.card].location=f.site;assert.equal(mod('board').power(f.m,f.target),Math.max(0,before-1));});
