import test from 'node:test';
import assert from 'node:assert/strict';
import {pull,state,rules,runtime,clone,ids,step,seek,priority,settled,load} from './vessels-fixture.mjs';
import {setup,service,drain,link} from './droid-service-fixture.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url)),svc=mod('droid-service'),ground=mod('ground'),scomp=mod('scomp');
const offer=(m,card,mode)=>ids(m).find(id=>id.startsWith('scomp:play:'+card+':'+mode));
const decision=m=>seek(m,x=>x.stack.at(-1)?.handler==='ground:force-loss');
const peek=m=>seek(m,x=>x.stack.at(-1)?.handler==='scomp:peek');
for(const side of ['light','dark']){
 test(side+' service deploys only on opponent locations, persists and records deployment',()=>{
  const f=setup(side),own=side==='light'?f.site:f.remote,enemy=side==='light'?f.remote:f.site;
  assert.ok(!ids(f.m).includes('service:deploy:'+f.effect+':'+own));let m=settled(step(f.m,'service:deploy:'+f.effect+':'+enemy));assert.equal(m.cards[f.effect].attachedTo,enemy);assert.equal(m.cards[f.effect].zone,'table');rules.validate(clone(m));assert.ok(m.data.deployments.some(d=>d.card.id===f.effect));
 });
 test(side+' opponent control automatically cancels the service Effect',()=>{
  const f=setup(side),enemy=side==='light'?'dark':'light',site=side==='light'?f.remote:f.site;pull(f.m,enemy,enemy==='light'?'1_28':'1_194','table',site);const m=settled(step(f.m,'service:deploy:'+f.effect+':'+site));assert.equal(m.cards[f.effect].zone,'lost');
 });
 test(side+' canceled service deployment never attaches or grants credit',()=>{const f=setup(side),site=side==='light'?f.remote:f.site;let m=step(f.m,'service:deploy:'+f.effect+':'+site);m.stack.find(x=>x.action?.handler==='service:deploy').cancelled=true;m=settled(m);assert.equal(m.cards[f.effect].zone,'lost');assert.equal(svc.serviceActive(m,side),false);});
 for(const zone of ['hand','reserve','force','used','destiny'])test(side+' droid from '+zone+' satisfies Force loss by forfeit value through saved decisions',()=>{
  const f=service(setup(side),side),droid=side==='light'?f.droid:pull(f.m,side,'2_101','hand');state.moveCard(f.m,droid,zone);ground.queueForceLoss(f.m,{side,remaining:5,source:f.effect,site:null,reductionUsed:false});let m=decision(f.m),credit=svc.forceLossCredit(m,droid);assert.ok(credit>1);m=step(clone(m),zone==='hand'?'lose-hand:'+droid:'lose:'+zone);assert.equal(m.cards[droid].zone,'lost');const r=m.stack.find(x=>x.action?.handler==='ground:force-loss');assert.equal(r.action.payload.ledger.paid,credit);assert.equal(m.stack.at(-1).event.card,droid);
 });
 test(side+' non-droids and suppressed service pay ordinary one-card loss',()=>{const f=service(setup(side),side),d=side==='light'?f.droid:pull(f.m,side,'2_101','hand');assert.equal(svc.forceLossCredit(f.m,f.card),1);mod('game-text').suppressGameText(f.m,f.effect,f.effect);assert.equal(svc.forceLossCredit(f.m,d),1);});
 test(side+' service credit caps at remaining loss, including irreducible card costs',()=>{const f=service(setup(side),side),d=side==='light'?f.droid:pull(f.m,side,'2_101','hand');ground.queueForceLoss(f.m,{side,remaining:1,source:f.effect,site:null,reductionUsed:false,ledger:mod('loss').lossLedger(1,'effect',true)});let m=decision(f.m);m=step(m,'lose-hand:'+d);assert.equal(m.stack.find(x=>x.action?.handler==='ground:force-loss').action.payload.ledger.paid,1);});
 test(side+' droid service allows drain cancellation without an R-unit or Scomp link',()=>{const f=drain(side);assert.ok(offer(f.m,f.card,'drain'));const m=settled(step(clone(f.m),offer(f.m,f.card,'drain')));assert.equal(m.cards[f.card].zone,'used');assert.deepEqual(m.players[side].lost,[]);});
 test(side+' any previous support Interrupt play, including canceled play, consumes the granted allowance',()=>{const f=drain(side);mod('persona').recordCardPlay(f.m,f.card);assert.equal(offer(f.m,f.card,'drain'),undefined);f.m.turn.number++;assert.ok(offer(f.m,f.card,'drain'));});
 test(side+' cancellation itself can be canceled and source removal after initiation does not undo it',()=>{
  const f=drain(side);let m=step(f.m,offer(f.m,f.card,'drain'));state.moveCard(m,f.droid,'lost');mod('table').loseFromTable(m,[f.effect]);m=settled(m);assert.equal(m.cards[f.card].zone,'used');
  const g=drain(side);m=step(g.m,offer(g.m,g.card,'drain'));m.stack.find(x=>x.action?.handler==='scomp:play').cancelled=true;m=settled(m);assert.equal(m.cards[g.card].zone,'lost');
 });
 for(const pile of ['light','dark'])test(side+' privately inspects '+pile+' Reserve then reshuffles on acknowledgement',()=>{
  const f=link(side,pile);let m=peek(step(f.m,offer(f.m,f.card,'peek')?.replace(/:(light|dark)$/,':'+pile)));const before=[...m.players[pile].reserve];assert.deepEqual(scomp.scompView(m,side).peek.map(c=>c.id),before);assert.deepEqual(scomp.scompView(m,side==='light'?'dark':'light'),{});m=settled(step(clone(m),'scomp:finish'));assert.equal(m.cards[f.card].zone,'used');assert.deepEqual([...m.players[pile].reserve].sort(),before.sort());assert.equal(scomp.scompView(m,side).peek,undefined);
 });
 test(side+' normal inspection needs its actual Scomp-link character and is not once per turn',()=>{const f=link(side);mod('persona').recordCardPlay(f.m,f.card);assert.ok(offer(f.m,f.card,'peek'));state.moveCard(f.m,f.unit,'lost');assert.equal(offer(f.m,f.card,'peek'),undefined);});
 test(side+' initiated inspection survives eligible character leaving',()=>{const f=link(side);let m=step(f.m,offer(f.m,f.card,'peek'));state.moveCard(m,f.unit,'lost');m=peek(m);assert.ok(scomp.scompView(m,side).peek.length);});
 test(side+' tampered drain continuation is rejected',()=>{const f=drain(side),m=step(f.m,offer(f.m,f.card,'drain'));m.stack.find(x=>x.action?.handler==='scomp:play').action.payload.actionId='wrong';assert.throws(()=>rules.validate(m),/response binding/);});
}
test('Imperial Code Cylinder cancels pending Scomp Link Access at a Death Star Scomp link',()=>{const f=link('light');state.moveCard(f.m,f.pilot,'table');f.m.cards[f.pilot].location=f.remote;const ic=pull(f.m,'dark','1_250','hand');let m=priority(step(f.m,offer(f.m,f.card,'peek')),'dark');assert.ok(offer(m,ic,'cancel'));m=settled(step(m,offer(m,ic,'cancel')));assert.equal(m.cards[f.card].zone,'lost');assert.equal(m.cards[ic].zone,'used');});
for(const side of ['light','dark'])test(side+' losing droid from hand pays battle damage but never attrition',()=>{
 const f=service(setup(side,'battle'),side),enemy=side==='light'?'dark':'light';pull(f.m,side,side==='light'?'1_28':'1_194','table',f.site);pull(f.m,enemy,enemy==='light'?'1_28':'1_194','table',f.site);if(side==='dark'){f.m.cards[f.effect].attachedTo=f.planet;f.m.cards[f.effect].location=f.planet;}const d=side==='light'?f.droid:pull(f.m,side,'2_101','hand');let m=priority(seek(step(f.m,'battle:'+f.site),x=>x.stack.at(-1)?.event?.kind==='battle-damage'),side);const b=m.data.battle;b.damage[side]=8;b.initialDamage[side]=8;b.damageLedger[side]=mod('loss').lossLedger(8,'battle');b.attrition[side]=3;b.initialAttrition[side]=3;const credit=svc.forceLossCredit(m,d);m=seek(step(clone(m),'battle-lose-hand:'+d),x=>x.cards[d].zone==='lost');assert.equal(mod('battle').battleDamage(m,side),8-credit);assert.equal(m.data.battle.attrition[side],3);rules.validate(clone(m));
});
test('full rules projection retains private inspection after other view providers',()=>{const f=link();const m=peek(step(f.m,offer(f.m,f.card,'peek').replace(/:(light|dark)$/,':light')));assert.equal(rules.view(m,'light',0).peek.length,m.players.light.reserve.length);assert.equal(rules.view(m,'dark',0).peek.length,0);});
test('saved inspection rejects a changed pile or owner',()=>{const f=link();const m=peek(step(f.m,offer(f.m,f.card,'peek').replace(/:(light|dark)$/,':light'))),bad=clone(m);bad.stack.at(-1).payload.inspection.side='dark';assert.throws(()=>rules.validate(bad),/peek|Reserve|owner/i);const changed=clone(m);changed.players.light.reserve.reverse();assert.throws(()=>rules.validate(changed),/peek|Reserve/i);});
test('whole Reserve inspection includes a bottom insert privately and reshuffles it without firing',()=>{const f=link(),insert=pull(f.m,'light','1_42','hand');state.insertCard(f.m,insert,'dark',()=>0);mod('reserve-inserts').insertsIn(f.m,'dark')[0].position=f.m.players.dark.reserve.length;let m=peek(step(f.m,offer(f.m,f.card,'peek').replace(/:(light|dark)$/,':dark')));assert.deepEqual(rules.view(m,'light',0).peekInserts.map(c=>c.id),[insert]);assert.deepEqual(rules.view(m,'dark',0).peekInserts,[]);m=settled(step(clone(m),'scomp:finish'));assert.equal(mod('reserve-inserts').insertsIn(m,'dark')[0].revealed,false);assert.equal(m.cards[insert].zone,'table');});
const {default:fs}=await import('node:fs'),oracle=JSON.parse(fs.readFileSync(new URL('./gemp/droid-service-results.json',import.meta.url)));
for(const row of oracle)test('executed GEMP droid service comparison '+JSON.stringify(row),()=>{const side=row.dark?'dark':'light',f=drain(side);let m;if(row.kind==='drain-cancel'){m=settled(step(f.m,offer(f.m,f.card,'drain')));assert.deepEqual({kind:row.kind,dark:row.dark,interruptUsed:m.cards[f.card].zone==='used',cardsLost:m.players[side].lost.length},row);}else{state.moveCard(f.m,f.droid,'hand');m=decision(f.m);m=settled(step(m,'lose-hand:'+f.droid));assert.deepEqual({kind:row.kind,dark:row.dark,droidLost:m.cards[f.droid].zone==='lost',cardsLost:m.players[side].lost.length},row);}});
test('droid service receipt binds executed source and observations',async()=>{const {createHash}=await import('node:crypto'),p=JSON.parse(fs.readFileSync(new URL('./gemp/droid-service-provenance.json',import.meta.url)));for(const [f,sha]of Object.entries(p.files))assert.equal(createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+f,import.meta.url))).digest('hex'),sha);assert.equal(oracle.length,p.observations);});
test('zero and fractional droid forfeit credit never invents a minimum one or fractional card payment',()=>{const f=service(setup()),def=mod('definitions').cardDefinition(f.m,f.droid),printed=def.stats.forfeit;try{for(const [value,credit]of [['0',0],['2.5',2]]){def.stats.forfeit=value;assert.equal(svc.forceLossCredit(f.m,f.droid),credit);const m=clone(f.m);ground.queueForceLoss(m,{side:'light',remaining:5,source:f.effect,site:null,reductionUsed:false});let paid=decision(m);paid=step(paid,'lose-hand:'+f.droid);assert.equal(paid.stack.find(x=>x.action?.handler==='ground:force-loss').action.payload.ledger.paid,credit);assert.equal(paid.cards[f.droid].zone,'lost');}}finally{def.stats.forfeit=printed;}});
test('droid credit projection exposes only the viewing player’s hand',()=>{const f=service(setup()),view=rules.view(f.m,'light',0);assert.equal(view.forceLossCredits[f.droid],4);assert.equal(rules.view(f.m,'dark',0).forceLossCredits[f.droid],undefined);assert.deepEqual(Object.keys(view.forceLossCredits),f.m.players.light.hand);});
