import test from 'node:test';
import assert from 'node:assert/strict';
import {load} from '../native-proof/load-engine.mjs';
import {fixture,play,choosing,finish,runtime,rules,state,pull,step,seek,priority,prompt,ordinary} from './effect-search-fixture.mjs';
import {decks as preparationDecks,playing,advance,rules as setupRules} from './preparation-starting-fixture.mjs';
const mod=name=>load(new URL('../../lib/native-engine/'+name+'.ts',import.meta.url));
const bp=side=>side==='light'?'6_77':'6_160';
export const decks=(options={})=>preparationDecks(options).map(d=>({...d,cards:d.cards.map(c=>['9_51','9_139'].includes(c)?bp(d.side):c)}));
for(const side of ['dark','light']){
 test(side+' paid search keeps inspection private, reveals exact Effect, shuffles, and uses Interrupt',()=>{const f=fixture({side});let m=choosing(play(f));assert.equal(m.players[side].force.length,2);assert.ok(runtime.project(m,rules,side).rules.effectSearch.cards.length);assert.equal(runtime.project(m,rules,f.opponent).rules.effectSearch,null);assert.ok(prompt(m).choices.some(c=>c.id==='effect-search:take:'+f.target));m=step(m,'effect-search:take:'+f.target);for(const s of [side,f.opponent])assert.deepEqual(runtime.project(m,rules,s).rules.effectSearch.cards.map(c=>c.id),[f.target]);m=finish(m);assert.equal(m.cards[f.target].zone,'hand');assert.equal(m.cards[f.source].zone,'used');assert.equal(runtime.project(m,rules,side).rules.effectSearch,null);assert.ok(!prompt(priority(m,side)).choices.some(c=>c.id==='effect-search:play:'+f.copy));});
 test(side+' failed search is verified by opponent and stops same-title searches this turn',()=>{const f=fixture({side,empty:true});let m=choosing(play(f));assert.deepEqual(prompt(m).choices.map(c=>c.id),['effect-search:not-found']);m=step(m,'effect-search:not-found');assert.equal(prompt(m).side,f.opponent);assert.equal(runtime.project(m,rules,side).rules.effectSearch,null);assert.ok(runtime.project(m,rules,f.opponent).rules.effectSearch.cards.length);m=finish(step(m,'effect-search:verified'));assert.equal(m.cards[f.source].zone,'used');assert.equal(m.data.failedSearches[0].blueprint,bp(side));state.moveCard(m,f.target,'reserve');assert.equal(mod('search-policy').canSearch(m,{blueprint:bp(side),side,owner:side,pile:'reserve',function:'effect-search:upload'}),false);});
 test(side+' insufficient Force and empty Reserve cannot initiate',()=>{const f=fixture({side,amount:2});assert.ok(!prompt(f.m).choices.some(c=>c.id==='effect-search:play:'+f.source));while(f.m.players[side].reserve.length)state.moveCard(f.m,f.m.players[side].reserve[0],'hand');assert.deepEqual(mod('effect-search').effectSearchActions(f.m,f.m.stack.at(-1),side),[]);});
 test(side+' actual Sense cancels search after payment without revealing Reserve',()=>{const f=fixture({side});let m=seek(play(f),x=>prompt(x).choices.some(c=>c.id.startsWith('cancel:play:'+f.sense+':')));const id=prompt(m).choices.find(c=>c.id.startsWith('cancel:play:'+f.sense+':')).id;const die=pull(m,f.opponent,f.opponent==='light'?'1_28':'1_194','hand');state.moveCard(m,die,'reserve');m=finish(step(m,id));assert.equal(m.cards[f.source].zone,'lost');assert.equal(m.cards[f.target].zone,'reserve');assert.equal(m.players[side].force.length,2);assert.equal(m.data.failedSearches,undefined);});
}
for(const first of ['light','dark'])for(const size of [40,60])for(const effects of [true,false])test(`${first} first ${size}: one-Effect Starting Interrupt, effects ${effects}`,()=>{let m=runtime.createMatch('effect-start',size,decks({size,first,effects}),setupRules);m=playing(m);assert.equal(m.status,'playing');for(const side of ['dark','light']){assert.equal(m.cards[side+'-2'].zone,'lost');assert.equal(m.players[side].hand.length,8);assert.equal(m.players[side].reserve.length,size-10-(effects?1:0));assert.equal(Object.values(m.cards).filter(c=>c.owner===side&&c.zone==='table'&&['4_21','4_134'].includes(c.blueprint)).length,effects?1:0);}assert.equal(m.turn.side,first);});
test('mixed Starting Interrupt providers resolve independently with their own limits',()=>{const ds=decks();ds[0].cards[1]='9_139';ds[0].cards[3]='6_147';let m=playing(runtime.createMatch('mixed-start',60,ds,setupRules));assert.equal(m.cards['dark-3'].zone,'table');assert.equal(m.cards['dark-4'].zone,'table');assert.equal(m.cards['light-3'].zone,'table');assert.notEqual(m.cards['light-4'].zone,'table');});
test('reveal target moved away and returned is not taken as the old physical instance',()=>{const f=fixture();let m=step(choosing(play(f)),'effect-search:take:'+f.target);state.moveCard(m,f.target,'hand');state.moveCard(m,f.target,'reserve');m=finish(m);assert.equal(m.cards[f.target].zone,'reserve');assert.equal(m.cards[f.source].zone,'used');});
for(const corruption of ['owner','target','payment','handler'])test('saved Effect search rejects '+corruption,()=>{const f=fixture();let m=corruption==='payment'?play(f):step(choosing(play(f)),'effect-search:take:'+f.target);const r=m.stack.find(x=>x.action?.handler==='effect-search:'+(corruption==='payment'?'play':'take'));if(corruption==='owner')r.actor=f.opponent;if(corruption==='target')r.action.payload.target=mod('identity').referenceCard(m,f.sense);if(corruption==='payment')r.action.payment.light=2;if(corruption==='handler')r.action.handler='effect-search:bogus';assert.throws(()=>rules.validate(m));});
test('computer chooses actual paid search and never mutates its projected input',()=>{const f=fixture(),v=runtime.project(f.m,rules,'light'),copy=structuredClone(v);assert.equal(mod('computer').chooseComputerAction(v,'light'),'effect-search:play:'+f.source);assert.deepEqual(v,copy);});
test('production admission remains closed',()=>{for(const id of ['6_77','6_160'])assert.equal(mod('premiere-rules').premiereRules.supports(id),false);});
const {seeded}=await import('./match-runner.mjs');
for(const size of [40,60])test(size+' card native game with search Interrupts reaches Life Force victory',t=>{
 const ds=decks({size,copies:2});for(const d of ds)d.cards[4]=bp(d.side);
 let m=runtime.createMatch('effect-search-full-'+size,size,ds,setupRules),entropy=seeded(11),searched=0;
 for(let n=0;n<18000&&m.status!=='finished';n++){
  let side='dark',v=runtime.project(m,setupRules,side);if(!v.prompt?.choices.length){side='light';v=runtime.project(m,setupRules,side);}
  const choice=mod('computer').chooseComputerAction(v,side);assert.notEqual(choice,'concede');assert.ok(v.prompt.choices.some(c=>c.id===choice));if(choice.startsWith('effect-search:play:'))searched++;
  m=runtime.applyCommand(JSON.parse(JSON.stringify(m)),setupRules,side,{revision:m.revision,choice},entropy);
 }
 assert.equal(m.status,'finished');assert.equal(m.result.reason,'life-force');if(size===40)assert.ok(searched>0);t.diagnostic('Completed turn '+m.turn.number+', '+m.revision+' commands, '+searched+' paid searches.');
});
const fs=await import('node:fs'),{createHash}=await import('node:crypto');
const read=name=>JSON.parse(fs.readFileSync(new URL('./gemp/'+name,import.meta.url)));
for(const row of read('effect-starting-results.json'))test('GEMP one-Effect setup '+JSON.stringify([row.first,row.effects,row.dark,row.light]),()=>{
 let m=runtime.createMatch('oracle',60,decks({first:row.first,effects:row.effects}),setupRules);for(const side of ['dark','light'])m=runtime.applyCommand(m,setupRules,side,{revision:m.revision,choice:'select:'+side+'-1'},()=>42);m=runtime.applyCommand(m,setupRules,'dark',{revision:m.revision,choice:'reveal'},()=>42);
 let p=runtime.prompt(m,setupRules,runtime.prompt(m,setupRules,'dark').side);m=runtime.applyCommand(m,setupRules,p.side,{revision:m.revision,choice:p.choices[0].id},()=>42);
 for(const side of ['dark','light'])m=runtime.applyCommand(m,setupRules,side,{revision:m.revision,choice:row[side]?'starting-select:'+side+'-2':'starting-decline'},()=>42);
 m=runtime.applyCommand(m,setupRules,'dark',{revision:m.revision,choice:'starting-reveal'},()=>42);m=playing(m);assert.equal(m.turn.side,row.first);assert.deepEqual((m.data.preparationStarts??[]).map(id=>m.cards[id].owner),row.lostOrder);
 assert.deepEqual(Object.values(m.cards).filter(c=>c.zone==='table'&&['4_21','4_134'].includes(c.blueprint)).map(c=>c.blueprint).sort(),row.table);
 for(const side of ['dark','light'])assert.deepEqual({reserve:m.players[side].reserve.length,hand:m.players[side].hand.length,lost:m.players[side].lost.map(id=>m.cards[id].blueprint)},row.piles[side]);
});
for(const row of read('effect-search-results.json'))test('GEMP USED search '+row.side+' empty='+row.empty,()=>{const f=fixture(row);let m=choosing(play(f));if(row.empty)m=step(step(m,'effect-search:not-found'),'effect-search:verified');else m=step(m,'effect-search:take:'+f.target);m=finish(m);assert.equal(5-m.players[row.side].force.length,row.cost);assert.equal(m.cards[f.source].zone,'used');assert.equal(m.cards[f.target].zone,'hand');if(row.empty)assert.ok(row.trace.some(x=>x.text.toLowerCase().includes('verify')));});
test('Effect search receipt binds actual source, observations and unchanged GEMP production',()=>{const p=read('effect-search-provenance.json');for(const [name,hash]of Object.entries(p.files))assert.equal(createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+name,import.meta.url))).digest('hex'),hash);assert.equal(p.productionFilesCompared,6820);assert.equal(p.productionFilesChanged,0);assert.equal(p.startingBranches,read('effect-starting-results.json').length);assert.equal(p.usedBranches,read('effect-search-results.json').length);});
