import test from 'node:test';
import assert from 'node:assert/strict';
import {mod,runtime,rules,state,clone,pull,phase,step,seek,ids} from './prisoner-fixture.mjs';
const ships=mod('ship-sites'),board=mod('board');
const refresh=m=>{for(const side of ['light','dark'])assert.deepEqual(runtime.project(m,rules,side),runtime.project(clone(m),rules,side));};
function fixture(){const decks=['light','dark'].map(side=>({side,cards:[...(side==='dark'?['4_161','4_161','4_167','4_165','1_168','9_109','1_289']:['1_129']),...Array(60).fill(side==='dark'?'1_194':'1_28')].slice(0,60)}));let m=runtime.createMatch('executor-site',60,decks,rules);const system=pull(m,'dark','1_289');m.locations.push(system);const site=pull(m,'dark','4_161','hand');for(const s of ['light','dark'])for(let i=0;i<8;i++)state.moveCard(m,m.players[s].reserve.at(-1),'force');m=phase(runtime.startTurns(m,rules),'dark','deploy');return {m,site,system};}
function deploy(m,site,host='EXECUTOR'){const choice=ids(m).find(id=>id.startsWith('ship-site:deploy:'+site+':'+host+':'));assert.ok(choice);return seek(step(m,choice),x=>x.cards[site].zone==='table');}
test('Holotheatre deploys without Executor and retains independent site grouping after serialized refresh',()=>{let {m,site}=fixture();m=deploy(m,site);assert.equal(ships.relatedShip(m,site),undefined);assert.equal(ships.shipSiteGroup(m,site),'ship-persona:EXECUTOR');assert.equal(board.system(m,site),undefined);assert.deepEqual(ships.shipSitesView(m).shipSites[site],{persona:'EXECUTOR'});assert.equal(mod('location-icons').forceIcons(m,site,'dark'),1);refresh(m);const duplicate=pull(m,'dark','4_161','hand');m=phase(m,'dark','deploy');assert.ok(!ids(m).some(id=>id.startsWith('ship-site:deploy:'+duplicate+':')));});
for(const departure of ['lost','hand','used','out'])test('unique site and residents survive related hull departure: '+departure,()=>{let {m,site,system}=fixture();m=deploy(m,site);const hull=pull(m,'dark','4_167','table',system),resident=pull(m,'dark','1_194','table',site);assert.equal(ships.relatedShip(m,site),hull);const table=mod('table');if(departure==='lost')table.loseFromTable(m,[hull]);if(departure==='hand')table.returnToHand(m,[hull]);if(departure==='used')table.placeInUsedFromTable(m,hull);if(departure==='out')table.placeOutFromTable(m,hull);assert.equal(m.cards[site].zone,'table');assert.equal(m.cards[resident].zone,'table');assert.equal(m.cards[hull].zone,departure);assert.equal(ships.relatedShip(m,site),undefined);refresh(m);if(departure!=='out'){state.moveCard(m,hull,'table');m.cards[hull].location=system;assert.equal(ships.relatedShip(m,site),hull);refresh(m);}});
test('unique Holotheatre and nonunique Launch Bay share board group but only bay is lost with Executor',()=>{let {m,site,system}=fixture();m=deploy(m,site);const hull=pull(m,'dark','4_167','table',system),bay=pull(m,'dark','4_165','hand');m=phase(m,'dark','deploy');m=deploy(m,bay,hull);assert.equal(board.adjacent(m,site,bay),true);const resident=pull(m,'dark','1_194','table',site),bayResident=pull(m,'dark','1_194','table',bay);mod('table').loseFromTable(m,[hull]);m=seek(m,x=>!x.stack.some(f=>f.kind==='decision'&&f.handler==='table:lost-order'));assert.equal(m.cards[site].zone,'table');assert.equal(m.cards[resident].zone,'table');assert.equal(m.cards[bay].zone,'lost');assert.equal(m.cards[bayResident].zone,'lost');assert.equal(ships.shipSiteGroup(m,site),'ship-persona:EXECUTOR');refresh(m);});
test('Holotheatre adds generation separately from icons for Vader and Emperor, including canceled character text',()=>{let {m,site}=fixture();m=deploy(m,site);const base=board.generation(m,'dark'),vader=pull(m,'dark','1_168','table',site);assert.equal(board.generation(m,'dark'),base+1);const emperor=pull(m,'dark','9_109','table',site);assert.equal(board.generation(m,'dark'),base+2);assert.equal(mod('location-icons').forceIcons(m,site,'dark'),1);mod('game-text').suppressGameText(m,site,vader);assert.equal(board.generation(m,'dark'),base+2);state.moveCard(m,emperor,'hand');assert.equal(board.generation(m,'dark'),base+1);mod('game-text').suppressGameText(m,vader,site);assert.equal(board.generation(m,'dark'),base);refresh(m);});
test('Holotheatre errata adds a Light drain bonus; actual drain still requires control and active text',()=>{let {m,site}=fixture();m=deploy(m,site);assert.equal(board.drainAmount(m,'light',site),2);assert.equal(board.controls(m,'light',site),false);const rebel=pull(m,'light','1_28','table',site);assert.equal(board.drainAmount(m,'light',site),2);const trooper=pull(m,'dark','1_194','table',site);assert.equal(board.drainAmount(m,'light',site),2);assert.equal(board.controls(m,'light',site),false);state.moveCard(m,trooper,'hand');mod('game-text').suppressGameText(m,rebel,site);assert.equal(board.drainAmount(m,'light',site),1);refresh(m);});
test('unique site deploy continuation rejects a fabricated physical host or persona',()=>{const {m,site,system}=fixture();const pending=step(m,ids(m).find(id=>id.startsWith('ship-site:deploy:'+site+':')));for(const corrupt of [p=>p.persona='FALCON',p=>{p.host=mod('identity').referenceCard(m,system);},p=>delete p.persona,p=>p.index=10000]){const bad=clone(pending),r=bad.stack.find(f=>f.kind==='resolution'&&f.action.handler==='ship-site:deploy');corrupt(r.action.payload);assert.throws(()=>runtime.project(bad,rules,'dark'));}refresh(pending);});
test('Holotheatre is a starting location without a hull; a nonunique Launch Bay is not',()=>{
 const setupRules={...rules,starting:{...mod('premiere-setup').premiereSetup,ordinarySetup:()=>true},setupComplete:m=>m.setup?.stage==='complete'};
 const decks=['light','dark'].map(side=>({side,cards:[...(side==='dark'?['4_161','4_165']:['1_129']),...Array(60).fill(side==='dark'?'1_194':'1_28')].slice(0,60)}));
 let m=runtime.createMatch('executor-start',60,decks,setupRules);
 const view=runtime.project(m,setupRules,'dark');assert.deepEqual(view.setup.candidates.map(c=>c.blueprint),['4_161']);assert.deepEqual(view.setup.candidates[0].forceIcons,{dark:1,light:0});
 for(const side of ['dark','light']){const candidate=runtime.project(m,setupRules,side).setup.candidates[0];m=runtime.applyCommand(clone(m),setupRules,side,{revision:m.revision,choice:'select:'+candidate.id},()=>42);}
 for(let i=0;i<8&&m.status==='setup';i++){const p=runtime.prompt(m,setupRules,'dark'),own=runtime.prompt(m,setupRules,p.side);m=runtime.applyCommand(clone(m),setupRules,p.side,{revision:m.revision,choice:own.choices[0].id},()=>42);}
 assert.equal(m.status,'playing');const site=m.locations.find(id=>m.cards[id].blueprint==='4_161');assert.ok(site);assert.equal(ships.relatedShip(m,site),undefined);for(const side of ['dark','light'])assert.deepEqual(runtime.project(m,setupRules,side),runtime.project(clone(m),setupRules,side));
});
test('Holotheatre does not inherit Launch Bay landing, discount or capture destination text',()=>{
 let {m,site,system}=fixture();m=deploy(m,site);const hull=pull(m,'dark','4_167','table',system),bay=mod('launch-bay');
 assert.equal(bay.launchBay(m,site),false);assert.equal(bay.launchBayPermission(m,'dark',site),false);assert.deepEqual(ships.captureDestinations(m,hull),[hull]);
});
