import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {load} from '../native-proof/load-engine.mjs';
const runtime=load(new URL('../../lib/native-engine/runtime.ts',import.meta.url));
const state=load(new URL('../../lib/native-engine/state.ts',import.meta.url));
const combat=load(new URL('../../lib/native-engine/battle.ts',import.meta.url));
const {premiereRules}=load(new URL('../../lib/native-engine/premiere-rules.ts',import.meta.url));
const manifest=JSON.parse(fs.readFileSync(new URL('../../data/native-proof/manifest.json',import.meta.url)));
// Component-only boards. Production admission stays closed.
const rules={...premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true,resolve:(m,r,c)=>{if(r.action.handler==='probe:done')m.data.observed=r.action.payload;else premiereRules.resolve(m,r,c)}};
const clone=x=>JSON.parse(JSON.stringify(x));
function fresh(extra={}){return runtime.createMatch('interrupt-test',60,manifest.decks.map(d=>({side:d.side,cards:[...(extra[d.side]??[]),...d.main].slice(0,60)})),rules)}
function pull(m,side,bp,zone='table',site){const c=Object.values(m.cards).find(c=>c.owner===side&&c.blueprint===bp&&c.zone==='reserve');assert.ok(c,'fixture '+bp);state.moveCard(m,c.id,zone);if(site)m.cards[c.id].location=site;return c.id}
function location(m,side,bp){const id=pull(m,side,bp);m.locations.push(id);return id}
function force(m,side,n){for(let i=0;i<n;i++)state.moveCard(m,m.players[side].reserve.at(-1),'force')}
function prompt(m){const p=runtime.prompt(m,rules,'dark');return p&&runtime.prompt(m,rules,p.side)}
const ids=m=>prompt(m).choices.map(c=>c.id);
function step(m,id,side=prompt(m).side){const before=clone(m),r=runtime.applyCommand(clone(m),rules,side,{revision:m.revision,choice:id},()=>0);assert.deepEqual(m,before);state.assertState(r);for(const s of ['dark','light'])assert.deepEqual(runtime.project(r,rules,s),runtime.project(clone(r),rules,s));return r}
function seek(m,predicate){for(let n=0;n<900;n++){if(predicate(m))return m;const p=prompt(m);assert.ok(p,'ended too soon');m=step(m,p.choices.some(c=>c.id==='pass')?'pass':p.choices.some(c=>c.id==='skip-destiny')?'skip-destiny':p.choices[0].id)}throw Error('boundary not reached')}
function phase(m,p='deploy'){if(m.status==='setup')m=runtime.startTurns(m,rules);return seek(m,x=>x.turn.phase===p&&x.stack.length===1)}
function settle(m){return seek(m,x=>x.stack.length===1||x.stack.at(-1)?.kind==='decision')}
function priority(m,side){if(prompt(m).side!==side)m=step(m,'pass');assert.equal(prompt(m).side,side);return m}
function topDestiny(m,side,bp){const id=pull(m,side,bp,'hand');state.moveCard(m,id,'reserve');return id}

const farm=load(new URL('../../lib/native-engine/farm-devices.ts',import.meta.url));
const activation=load(new URL('../../lib/native-engine/activation.ts',import.meta.url));
const identity=load(new URL('../../lib/native-engine/identity.ts',import.meta.url));
const destiny=load(new URL('../../lib/native-engine/destiny.ts',import.meta.url));
function base(vapor=false){let m=fresh({light:['1_37','1_37','1_41','2_14','1_129'],dark:['1_194']});const site=location(m,'light','1_132'),remote=location(m,'dark','1_284'),hydro=pull(m,'light','1_37','table');m.cards[hydro].attachedTo=site;if(vapor){const v=pull(m,'light','1_41','table');m.cards[v].attachedTo=site;}m=phase(m,'control');m=seek(m,x=>x.turn.side==='light'&&x.turn.phase==='activate'&&x.stack.length===1&&x.stack[0].timing==='phase');return {m,site,remote,hydro};}
const offered=m=>farm.farmDeviceActions(m,m.stack.at(-1),'light').map(a=>a.id);
function activate(m){m=priority(m,'light');m=step(m,'core:activate');return seek(m,x=>x.stack.at(-1)?.event?.kind==='force-activated'||x.stack.length===1);}
for(const vapor of [false,true])test('Hydroponics converts the first '+(vapor?'two activations with Vaporator':'activation only')+', preserving order and refresh',()=>{
 let {m,hydro}=base(vapor);const initial=m.players.light.hand.length;
 for(let n=1;n<=3;n++){const top=m.players.light.reserve[0];m=activate(m);assert.equal(activation.activatedThisPhase(m,'light'),n);assert.equal(m.turn.activated,n);
  if(n<= (vapor?2:1)){assert.deepEqual(offered(m),['hydroponics:'+hydro]);m=priority(clone(m),'light');m=step(m,'hydroponics:'+hydro);m=seek(m,x=>x.cards[top].zone==='hand');assert.equal(offered(m).length,0);}else assert.equal(offered(m).length,0);
  m=settle(m);
 }
 assert.equal(m.players.light.hand.length-initial,vapor?2:1);assert.equal(m.players.light.force.length,vapor?1:2);
});
test('declining the first activation does not prevent the second with a Vaporator',()=>{let {m,hydro}=base(true);m=settle(activate(m));m=activate(m);assert.deepEqual(offered(m),['hydroponics:'+hydro]);});
test('multiple Stations offer a choice but cannot draw the same activated card twice',()=>{let {m,hydro,site}=base();const second=pull(m,'light','1_37','table');m.cards[second].attachedTo=site;m=activate(m);assert.equal(offered(m).length,2);m=priority(m,'light');m=step(m,'hydroponics:'+second);m=seek(m,x=>x.players.light.hand.length===1);assert.equal(offered(m).length,0);assert.equal(m.cards[hydro].zone,'table');});
test('a pending Hydroponics action survives source loss and draws the current Force top',()=>{let {m,hydro}=base();m=activate(m);m=priority(m,'light');m=step(m,'hydroponics:'+hydro);state.moveCard(m,hydro,'lost');const replacement=m.players.light.reserve.at(-1);state.moveCard(m,replacement,'force');m=seek(clone(m),x=>x.cards[replacement].zone==='hand');assert.equal(m.players.light.force.length,1);});
test('canceling a Station response consumes its opportunity without drawing',()=>{let {m,hydro}=base();m=activate(m);m=priority(m,'light');m=step(m,'hydroponics:'+hydro);m.stack.find(f=>f.action?.handler==='farm:draw').cancelled=true;m=settle(m);assert.equal(offered(m).length,0);assert.equal(m.players.light.hand.length,0);});
test('moving Force to hand and back does not reopen the departed activation instance',()=>{let {m}=base();m=activate(m);const card=m.players.light.force[0];state.moveCard(m,card,'hand');state.moveCard(m,card,'force');assert.equal(offered(m).length,0);});
test('card placement on Force is not activation; empty Reserve makes no event',()=>{let {m}=base();const count=activation.activatedThisPhase(m,'light');state.moveCard(m,m.players.light.reserve[0],'force');assert.equal(activation.activatedThisPhase(m,'light'),count);for(const id of [...m.players.light.reserve])state.moveCard(m,id,'used');assert.equal(runtime.activateOneForce(m,'light'),false);assert.equal(m.stack.length,1);});
test('activation count resets each phase and turn, including old saves',()=>{let {m}=base();m=settle(activate(m));assert.equal(activation.activatedThisPhase(m,'light'),1);delete m.data.activation;assert.equal(activation.activatedThisPhase(m,'light'),1);m=settle(activate(m));assert.equal(activation.activatedThisPhase(m,'light'),2);m=seek(m,x=>x.turn.phase==='control'&&x.stack.length===1);assert.equal(activation.activatedThisPhase(m,'light'),0);runtime.activateOneForce(m,'light');assert.equal(activation.activatedThisPhase(m,'light'),1);assert.equal(offered(m).length,0);m=settle(m);m=seek(m,x=>x.turn.number===4&&x.stack.length===1);assert.equal(activation.activatedThisPhase(m,'light'),0);});
for(const change of ['wrong-phase','wrong-side','canceled-text','covered','no-host'])test('Hydroponics excludes '+change,()=>{let {m,hydro}=base(true);if(change==='wrong-phase')m=seek(m,x=>x.turn.phase==='control'&&x.stack.length===1);if(change==='canceled-text')m.data.canceledGameText=[identity.referenceCard(m,hydro)];if(change==='covered')m.cards[hydro].coveredBy=m.cards[hydro].attachedTo;if(change==='no-host')delete m.cards[hydro].attachedTo;runtime.activateOneForce(m,change==='wrong-side'?'dark':'light');assert.equal(offered(m).length,0);});
for(const bp of ['1_37','1_41'])test('farm deployment '+bp+' costs 1 Force, attaches, records arrival and cannot transfer',()=>{let {m,site,remote}=base();const card=bp==='1_37'?pull(m,'light',bp,'hand'):pull(m,'light',bp,'hand');force(m,'light',2);m=seek(m,x=>x.turn.phase==='deploy'&&x.stack.length===1);m=priority(m,'light');assert.ok(ids(m).includes('farm-deploy:'+card+':'+site));assert.ok(!ids(m).includes('farm-deploy:'+card+':'+remote));const before=m.players.light.force.length;m=step(m,'farm-deploy:'+card+':'+site);m=seek(m,x=>x.cards[card].zone==='table');assert.equal(m.players.light.force.length,before-1);assert.equal(m.cards[card].attachedTo,site);assert.equal(m.data.deployments.at(-1).card.id,card);m=settle(m);assert.ok(!ids(m).some(id=>id.includes('transfer:'+card)));assert.ok(m.data.cardPlays.cards.some(c=>c.card===card));});
test('farm deployment revalidates the target instance and pays on cancellation',()=>{for(const mode of ['target-reentry','cancel']){let {m,site}=base();const card=pull(m,'light','1_37','hand');force(m,'light',2);m=seek(m,x=>x.turn.phase==='deploy'&&x.stack.length===1);m=priority(m,'light');m=step(m,'farm-deploy:'+card+':'+site);if(mode==='cancel')m.stack.find(f=>f.action?.handler==='farm:deploy').cancelled=true;else{for(const c of Object.values(m.cards).filter(c=>c.attachedTo===site))state.moveCard(m,c.id,'lost');const locations=[...m.locations];m.locations=m.locations.filter(id=>id!==site);state.moveCard(m,site,'hand');state.moveCard(m,site,'table');m.locations=locations;}m=settle(clone(m));assert.equal(m.cards[card].zone,'lost');assert.equal(m.players.light.used.length,1);}});
test('R2 activation opens the same Station response without spending generation allowance',()=>{let {m,site,hydro}=base();const link=location(m,'light','1_129');m.locations=[site,link,...m.locations.filter(id=>id!==site&&id!==link)];const r2=pull(m,'light','2_14','table',link),source=pull(m,'dark','1_251','playing');topDestiny(m,'dark','1_194');destiny.drawDestiny(m,'dark',source,'probe',{id:'done',label:'done',handler:'probe:done',payload:{}});m=seek(m,x=>x.stack.at(-1)?.event?.kind==='destiny-drawn');m=priority(m,'light');assert.ok(ids(m).includes('r2:'+r2+':activate'));m=step(m,'r2:'+r2+':activate');m=seek(m,x=>x.stack.at(-1)?.event?.kind==='force-activated');assert.equal(m.turn.activated,0);assert.equal(activation.activatedThisPhase(m,'light'),1);assert.deepEqual(offered(m),['hydroponics:'+hydro]);m=priority(m,'light');m=step(m,'hydroponics:'+hydro);m=seek(m,x=>!!x.data.observed);assert.equal(m.players.light.hand.length,1);m=settle(m);m=activate(m);assert.equal(activation.activatedThisPhase(m,'light'),2);assert.equal(offered(m).length,0);assert.equal(m.turn.activated,1);});
test('saved activation and pending response reject corrupt identities and counters',()=>{let {m,hydro}=base();m=activate(m);m=priority(m,'light');m=step(m,'hydroponics:'+hydro);for(const mutation of [x=>x.data.activation.counts.light=-1,x=>x.stack.find(f=>f.event?.kind==='force-activated').event.card.zone='hand',x=>x.stack.find(f=>f.action?.handler==='farm:draw').action.payload.window++,x=>x.stack.find(f=>f.event?.kind==='force-activated').event.count=100]){const bad=clone(m);mutation(bad);assert.throws(()=>prompt(bad));}});
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/farm-results.json',import.meta.url)));
for(const expected of oracle)test('executed GEMP parity: '+expected.name,()=>{
 if(expected.name.startsWith('deploy-')){const bp=expected.name==='deploy-hydro'?'1_37':'1_41';let {m,site}=base();const card=pull(m,'light',bp,'hand');force(m,'light',2);m=seek(m,x=>x.turn.phase==='deploy'&&x.stack.length===1);m=priority(m,'light');const before=m.players.light.force.length;m=step(m,'farm-deploy:'+card+':'+site);m=settle(m);assert.equal(before-m.players.light.force.length,expected.cost);return;}
 let {m,hydro,site}=base(['vapor','decline-first'].includes(expected.name));if(expected.name==='two-stations'){const second=pull(m,'light','1_37','table');m.cards[second].attachedTo=site;}
 const hand=m.players.light.hand.length,forceBefore=m.players.light.force.length;let offers=0,draws=0;
 for(let i=0;i<3;i++){m=activate(m);if(offered(m).includes('hydroponics:'+hydro)){offers++;if(!(expected.name==='decline-first'&&i===0)){draws++;m=priority(m,'light');m=step(m,'hydroponics:'+hydro);}}m=settle(m);}
 assert.deepEqual({name:expected.name,hand:m.players.light.hand.length-hand,force:m.players.light.force.length-forceBefore,offers,draws},expected);
});
test('drawing the final Life Force into hand ends the match; activation alone does not',()=>{let {m,hydro}=base();for(const id of m.players.light.reserve.slice(1))state.moveCard(m,id,'hand');m=activate(m);assert.equal(m.status,'playing');m=priority(m,'light');m=step(m,'hydroponics:'+hydro);m=seek(m,x=>x.status==='finished');assert.deepEqual(m.result,{winner:'dark',loser:'light',reason:'life-force'});});
test('activation identity and Force order remain private during the response',()=>{let {m}=base();m=activate(m);const card=m.players.light.force[0];for(const side of ['dark','light']){const view=runtime.project(m,rules,side);assert.ok(!JSON.stringify(view).includes('"'+card+'"'));assert.equal(view.players.light.counts.force,1);}});
import crypto from 'node:crypto';
test('farm evidence identifies the exact executed harness and results',()=>{const p=JSON.parse(fs.readFileSync(new URL('./gemp/farm-provenance.json',import.meta.url)));for(const [file,hash] of [[p.harness,p.harnessSha256],[p.result,p.resultSha256]])assert.equal(crypto.createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+file,import.meta.url))).digest('hex'),hash);assert.equal(p.observations,oracle.length);assert.equal(p.junitTests,2);assert.equal(p.unchangedProductionFiles,6820);for(const bp of ['1_37','1_41'])assert.equal(premiereRules.supports(bp),false);});
