import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,ended,start,drawn,finish,bonus,pull,state,rules,step,seek,phase,priority,ids,clone,runtime,mod} from './fighter-trouble-fixture.mjs';
for(const mode of ['bonus','no-bonus','few','other-ship','suppressed','unpiloted','empty'])test('Post-battle fighter trouble '+mode,()=>{
 const f=fixture(mode),m0=ended(f),force=m0.players.dark.force.length;let m=step(m0,'fighter-trouble:play:'+f.card+':'+f.target);
 if(mode!=='empty'){m=drawn(m);assert.ok(!ids(priority(m,'light')).some(id=>id==='fighter-trouble:bonus:'+f.target));m=priority(m,'dark');assert.equal(ids(m).includes('fighter-trouble:bonus:'+f.target),!['other-ship','suppressed','unpiloted'].includes(mode));if(['bonus','few'].includes(mode))m=bonus(m,f);if(mode==='few'){m=seek(m,x=>x.stack.at(-1)?.event?.kind==='destiny-drawn');m=step(priority(m,'light'),'maneuver:'+f.few+':'+f.target);}}
 m=finish(clone(m),f);assert.equal(m.players.dark.force.length,force-1);assert.equal(m.cards[f.target].zone,['bonus','other-ship','unpiloted'].includes(mode)?'lost':'table');assert.equal(m.cards[f.card].zone,'lost');assert.equal(m.data.fighterTrouble.destiny,mode==='empty'?null:['bonus','few'].includes(mode)?7:5);assert.equal(m.data.battle.stage,'complete');rules.validate(m);
});
test('Jek deployment supplies named ship bonus and fallback without adding an ordinary draw',()=>{
 const f=fixture();assert.equal(f.deploymentCost,2);assert.equal(f.power,5);assert.equal(f.maneuver,5);let m=step(f.m,'battle:'+f.planet);m=seek(m,x=>x.stack.at(-1)?.event?.kind==='battle-weapons');assert.equal(mod('battle-destiny').battleDrawPolicy(m,'light').count,1);
});
test('Only battle-ended responses at systems allow the Interrupt, with an affordable cost',()=>{
 const f=fixture();assert.ok(!ids(f.m).some(id=>id.startsWith('fighter-trouble:')));const no=fixture('no-force');assert.ok(!ids(ended(no)).some(id=>id.startsWith('fighter-trouble:play')));let m=ended(f);m=seek(m,x=>x.stack.length===1);assert.ok(!ids(priority(m,'dark')).some(id=>id.startsWith('fighter-trouble:play')));
});
test('Red 6 optional bonus cannot be repeated in the same draw',()=>{const f=fixture();let m=bonus(drawn(start(f)),f);m=seek(m,x=>x.stack.at(-1)?.event?.kind==='destiny-drawn');assert.ok(!ids(priority(m,'dark')).includes('fighter-trouble:bonus:'+f.target));assert.equal(finish(m,f).data.fighterTrouble.destiny,7);});
test('A departed target is not lost by its original pending effect',()=>{const f=fixture();let m=start(f);mod('table').returnToHand(m,[f.target]);m=finish(m,f);assert.equal(m.cards[f.target].zone,'hand');assert.equal(m.data.fighterTrouble.departed,true);assert.equal(m.data.fighterTrouble.destiny,5);});
test('An initiated Red 6 bonus survives source departure',()=>{const f=fixture();let m=bonus(drawn(start(f)),f);mod('table').returnToHand(m,[f.target]);m=finish(m,f);assert.equal(m.data.fighterTrouble.destiny,7);assert.equal(m.cards[f.target].zone,'hand');});
test('Returned target cannot inherit the pending loss',()=>{const f=fixture();let m=bonus(drawn(start(f)),f);m=seek(m,x=>x.stack.at(-1)?.event?.kind==='about-to-lose'&&x.stack.at(-1).event.cause==='fighter-trouble');mod('table').returnToHand(m,[f.target]);state.moveCard(m,f.target,'table');m.cards[f.target].location=f.planet;m=finish(m,f);assert.equal(m.cards[f.target].zone,'table');assert.ok(!m.data.fighterTrouble.lost);});
test('Canceling the Interrupt preserves its cost and draws nothing',()=>{const f=fixture(),before=ended(f);let m=step(before,'fighter-trouble:play:'+f.card+':'+f.target);m.stack.find(x=>x.action?.handler==='fighter-trouble:play').cancelled=true;m=finish(m,f);assert.equal(m.players.dark.force.length,before.players.dark.force.length-1);assert.equal(m.cards[f.die].zone,'reserve');assert.equal(m.cards[f.target].zone,'table');});
test('Canceled Red 6 response is consumed without changing the draw',()=>{const f=fixture();let m=bonus(drawn(start(f)),f);m.stack.find(x=>x.action?.handler==='fighter-trouble:bonus').cancelled=true;m=finish(m,f);assert.equal(m.data.fighterTrouble.destiny,5);assert.equal(m.cards[f.target].zone,'table');});
test('Saved optional response rejects wrong source, window and draw bindings',()=>{const f=fixture(),m=bonus(drawn(start(f)),f);for(const edit of [p=>p.source.id=f.jek,p=>p.window++,p=>p.pendingId+='bad',p=>p.serial++]){const bad=clone(m);edit(bad.stack.find(x=>x.action?.handler==='fighter-trouble:bonus').action.payload);assert.throws(()=>rules.validate(bad));}});
test('Actual Sense cancellation stops the paid post-battle Interrupt',()=>{
 const f=fixture();let m=start(f);m=seek(m,x=>x.stack.at(-2)?.action?.handler==='fighter-trouble:play'&&!x.stack.at(-2).awaitingResponses);m=priority(m,'light');const die=pull(m,'light','1_28','hand');state.moveCard(m,die,'reserve');const choice=ids(m).find(id=>id.startsWith('cancel:play:'+f.sense+':'+f.card+':'));assert.ok(choice);m=step(m,choice);m=finish(m,f);assert.equal(m.cards[f.target].zone,'table');assert.equal(m.cards[f.die].zone,'reserve');m=seek(m,x=>x.cards[f.sense].zone==='used');assert.equal(m.cards[f.sense].zone,'used');
});
test('Losing the ship removes crew and its weapon without battle-loss credit',()=>{
 const f=fixture();const gun=pull(f.m,'light','1_158','table',f.planet);f.m.cards[gun].attachedTo=f.target;let m=ended(f);const damage=clone(m.data.battle.damage),attrition=clone(m.data.battle.attrition);m=bonus(drawn(step(m,'fighter-trouble:play:'+f.card+':'+f.target)),f);m=seek(m,x=>x.stack.at(-1)?.handler==='table:lost-order');m=finish(clone(m),f);assert.ok([f.target,f.jek,gun].every(id=>m.cards[id].zone==='lost'));assert.deepEqual(m.data.battle.damage,damage);assert.deepEqual(m.data.battle.attrition,attrition);
});
test('A second Interrupt can target another ship in the same completed-battle window',()=>{
 const f=fixture();let m=finish(bonus(drawn(start(f)),f),f);m=priority(m,'dark');assert.ok(ids(m).includes('fighter-trouble:play:'+f.second+':'+f.ywing));m=step(m,'fighter-trouble:play:'+f.second+':'+f.ywing);m=seek(m,x=>x.cards[f.second].zone==='lost');assert.equal(m.cards[f.second].zone,'lost');rules.validate(m);
});
test('Canceled battle does not emit a post-battle Interrupt window',()=>{
 const f=fixture();let m=step(f.m,'battle:'+f.planet);m.stack.find(x=>x.action?.handler==='battle:begin').cancelled=true;m=seek(m,x=>x.stack.length===1);assert.equal(m.data.battle.cancelled,true);assert.ok(!ids(priority(m,'dark')).some(id=>id.startsWith('fighter-trouble:play')));
});
test('Saved initiation rejects a forged post-battle window',()=>{const f=fixture(),bad=clone(start(f));bad.stack.find(x=>x.action?.handler==='fighter-trouble:play').action.payload.window++;assert.throws(()=>rules.validate(bad));});
test('A replacement draw gets its own optional Red 6 response and does not retain the old bonus',()=>{
 const f=fixture();let m=ended(f);const next=pull(m,'dark','1_317','hand');state.moveCard(m,f.die,'hand');state.moveCard(m,next,'reserve');state.moveCard(m,f.die,'reserve');m=bonus(drawn(step(m,'fighter-trouble:play:'+f.card+':'+f.target)),f);m=seek(m,x=>x.stack.at(-1)?.event?.kind==='destiny-drawn');const old=m.stack.at(-2);assert.equal(old.action.payload.draw.value,7);assert.equal(mod('destiny-response').cancelPendingDestiny(m,old,true),true);m=seek(m,x=>x.stack.at(-1)?.event?.kind==='destiny-drawn'&&x.stack.at(-1).event.card===next);assert.equal(m.stack.at(-2).action.payload.draw.value,3);m=finish(bonus(m,f),f);assert.equal(m.data.fighterTrouble.destiny,5);assert.equal(m.cards[f.target].zone,'table');assert.ok([f.die,next].every(id=>m.cards[id].zone==='used'));
});
test('A canceled current destiny cannot be increased by a pending Red 6 response',()=>{
 const f=fixture();let m=bonus(drawn(start(f)),f);const r=m.stack.find(x=>x.action?.handler==='destiny:finish');assert.equal(mod('destiny-response').cancelPendingDestiny(m,r),true);m=finish(m,f);assert.equal(m.data.fighterTrouble.destiny,null);assert.equal(m.cards[f.target].zone,'table');
});
for(const row of JSON.parse((await import('node:fs')).readFileSync(new URL('./gemp/fighter-trouble-results.json',import.meta.url))))test('Executed GEMP post-battle comparison '+row.mode,()=>{
 const f=fixture(row.mode);const armed=seek(step(f.m,'battle:'+f.planet),x=>x.stack.at(-1)?.event?.kind==='battle-weapons');const battleDraws=mod('battle-destiny').battleDrawPolicy(armed,'light').count;
 let m=ended(f);const offered=ids(m).includes('fighter-trouble:play:'+f.card+':'+f.target),before=m.players.dark.force.length;let bonusOffered=false,bonusUsed=false;
 if(offered){m=step(m,'fighter-trouble:play:'+f.card+':'+f.target);if(row.mode==='target-leaves')mod('table').returnToHand(m,[f.target]);if(row.mode!=='empty'){m=priority(drawn(m),'dark');bonusOffered=ids(m).includes('fighter-trouble:bonus:'+f.target);if(['bonus','few','bonus-source-leaves'].includes(row.mode)){m=bonus(m,f);bonusUsed=true;if(row.mode==='bonus-source-leaves')mod('table').returnToHand(m,[f.target]);}if(row.mode==='few'){m=seek(m,x=>x.stack.at(-1)?.event?.kind==='destiny-drawn');m=step(priority(m,'light'),'maneuver:'+f.few+':'+f.target);}}m=finish(m,f);}
 assert.deepEqual({mode:row.mode,battleDraws,destiny:m.data.fighterTrouble?.destiny??null,deploymentCost:f.deploymentCost,power:f.power,maneuver:f.maneuver,offered,bonusOffered,bonusUsed,cost:before-m.players.dark.force.length,shipLost:m.cards[f.target].zone==='lost',problemLost:m.cards[f.card].zone==='lost',drew:m.cards[f.die].zone==='used',fewUsed:m.cards[f.few].zone==='used'},row);
});
test('Saved general destiny retains the original fighter and owning Interrupt',()=>{
 const f=fixture(),m=drawn(start(f));for(const edit of [p=>p.next.payload.target=f.ywing,p=>p.next.payload.card=f.second,p=>p.next.payload.window++,p=>p.next.payload.targetRef.version++]){const bad=clone(m);edit(bad.stack.find(x=>x.action?.handler==='destiny:finish').action.payload);assert.throws(()=>rules.validate(bad));}
});
