import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {load} from '../native-proof/load-engine.mjs';
const module=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url));
const runtime=module('runtime'),state=module('state'),cancel=module('cancellation');
const {premiereRules}=module('premiere-rules');
const manifest=JSON.parse(fs.readFileSync(new URL('../../data/native-proof/manifest.json',import.meta.url)));
// Metadata-only characters supply printed ability in these isolated fixtures.
// Neither the fixture override nor these characters are admitted to full games.
const rules={...premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true};
const clone=x=>JSON.parse(JSON.stringify(x)),other=s=>s==='light'?'dark':'light';
const fresh=()=>runtime.createMatch('force-effects-test',60,manifest.decks.map(d=>({side:d.side,cards:[...(d.side==='light'?['102_1','102_1','1_71','1_109','1_109','1_21','4_2','9_24','1_113','1_113','1_113','1_124','1_105','1_129','1_115','1_115','1_28','1_28']:['102_6','102_6','1_234','1_267','1_267','9_109','1_238','1_238','1_238','101_4','1_207','101_5','1_262','1_262','1_194','1_194']),...Array(60).fill(d.side==='light'?'1_28':'1_194')].slice(0,60)})),rules);
function pull(m,side,bp,zone='table',site){const c=Object.values(m.cards).find(c=>c.owner===side&&c.blueprint===bp&&c.zone==='reserve');assert.ok(c,'fixture '+bp);state.moveCard(m,c.id,zone);if(site)m.cards[c.id].location=site;return c.id}
function location(m){const id=pull(m,'light','1_129');m.locations.push(id);return id}
function force(m,side,n){for(let i=0;i<n;i++)state.moveCard(m,m.players[side].reserve.at(-1),'force')}
function prompt(m){const p=runtime.prompt(m,rules,'dark');return p&&runtime.prompt(m,rules,p.side)}
const ids=m=>prompt(m).choices.map(c=>c.id);
function step(m,id){const before=clone(m),r=runtime.applyCommand(clone(m),rules,prompt(m).side,{revision:m.revision,choice:id},()=>0);assert.deepEqual(m,before);state.assertState(r);for(const s of ['dark','light'])assert.deepEqual(runtime.project(r,rules,s),runtime.project(clone(r),rules,s));return r}
function seek(m,predicate){for(let n=0;n<900;n++){if(predicate(m))return m;const p=prompt(m);assert.ok(p,'ended too soon');m=step(m,p.choices.some(c=>c.id==='pass')?'pass':p.choices[0].id)}throw Error('boundary not reached')}
function phase(m,side='dark',p='control'){if(m.status==='setup')m=runtime.startTurns(m,rules);return seek(m,x=>x.turn.side===side&&x.turn.phase===p&&x.stack.length===1)}
const settled=m=>seek(m,x=>x.stack.length===1),priority=(m,side)=>prompt(m).side===side?m:step(m,'pass');
function senseFixture(side='dark',mode='fallback',roll=0){let m=fresh();const enemy=other(side),site=location(m),hero=pull(m,side,side==='light'?'1_21':'101_5','table',site),source=pull(m,enemy,enemy==='light'?'102_1':'102_6'),sense=pull(m,side,side==='light'?'1_109':'1_267','hand'),target=pull(m,enemy,enemy==='light'?'1_115':'1_262','hand');let lower,second;
 if(mode==='fallback'||mode==='ties'){lower=pull(m,side,side==='light'?'1_28':'1_194','table',site);if(mode==='ties')second=pull(m,side,side==='light'?'1_28':'1_194','table',site)}
 if(mode==='multiple')second=pull(m,side,side==='light'?'4_2':'9_109','table',site);
 force(m,side,6);force(m,enemy,6);m=phase(m);const destiny=pull(m,side,side==='light'?(roll===0?'1_124':'1_109'):(roll===0?'101_4':'1_267'),'hand');state.moveCard(m,destiny,'reserve');m=priority(m,enemy);m=step(m,'shuffle:'+target+':'+enemy+':reserve');m=step(m,'cancel:play:'+sense+':'+target+':'+(second&&mode==='multiple'?second:hero));return{m,side,enemy,site,hero,second,lower,source,sense,target,destiny};}
function exclude(f,targets=[f.hero]){let m=step(f.m,'force-effect:exclude:'+f.source);for(const id of targets)m=step(m,'force-effect:select:'+id);return step(m,'force-effect:confirm')}
for(const side of ['dark','light'])for(const mode of ['fallback','none','ties','multiple'])test(side+' exclusion '+mode+' pays X, immediately retargets and survives serialized commands',()=>{
 const f=senseFixture(side,mode);const before=f.m.players[f.enemy].force.length;let m=exclude(f,mode==='multiple'?[f.hero,f.second]:[f.hero]);
 assert.equal(m.players[f.enemy].force.length,before-(mode==='multiple'?2:1));
 if(['fallback','ties'].includes(mode)){assert.equal(prompt(m).side,side);assert.equal(prompt(m).mandatory,true);assert.deepEqual(new Set(ids(m)),new Set([f.lower,...(mode==='ties'?[f.second]:[])].map(id=>'force-effect:target:'+id)));m=step(m,'force-effect:target:'+f.lower)}
 assert.ok(!m.stack.some(r=>r.kind==='resolution'&&r.action.handler==='force-effect:exclude'));m=priority(m,f.enemy);assert.ok(!ids(m).includes('force-effect:exclude:'+f.source));m=settled(m);assert.equal(m.cards[f.target].zone,['fallback','ties'].includes(mode)?'lost':'used');assert.equal(m.cards[f.sense].zone,'used');assert.equal(m.cards[f.destiny].zone,'used');assert.ok([f.hero,f.second].filter(Boolean).every(id=>m.cards[id].zone==='table'));
});
for(const side of ['light','dark'])test(side+' exclusion uses the replacement ability, not the excluded hero ability',()=>{const f=senseFixture(side,'fallback',3);let m=exclude(f);m=step(m,'force-effect:target:'+f.lower);m=settled(m);assert.equal(m.cards[f.target].zone,'used');assert.equal(m.cards[f.sense].zone,'used')});
test('excluding a different Jedi preserves the current highest target',()=>{const f=senseFixture('light','multiple');let m=exclude(f,[f.hero]);assert.equal(prompt(m).timing,'response');const r=m.stack.find(r=>r.kind==='resolution'&&r.action.handler==='cancel:play');assert.equal(r.action.payload.character,f.second);m=settled(m);assert.equal(m.cards[f.target].zone,'lost')});
test('selection toggles, respects available Force, and rejects empty confirmation',()=>{const f=senseFixture('light','multiple');let m=f.m;while(m.players.dark.force.length>1)state.moveCard(m,m.players.dark.force[0],'used');m=step(m,'force-effect:exclude:'+f.source);assert.ok(!ids(m).includes('force-effect:confirm'));m=step(m,'force-effect:select:'+f.hero);assert.ok(!ids(m).includes('force-effect:select:'+f.second));m=step(m,'force-effect:select:'+f.hero);assert.ok(ids(m).includes('force-effect:select:'+f.second));m=step(m,'force-effect:select:'+f.second);m=step(m,'force-effect:confirm');assert.equal(prompt(m).side,'light');assert.deepEqual(ids(m),['force-effect:target:'+f.hero])});
test('exclusions do not leak into a later Sense',()=>{const f=senseFixture('light','none');let m=settled(exclude(f));const second=pull(m,'light','1_109','hand');assert.deepEqual(cancel.highestAbilityCharacters(m,'light'),[f.hero]);const target=pull(m,'dark','1_262','hand');m=priority(m,'dark');m=step(m,'shuffle:'+target+':dark:reserve');assert.ok(ids(m).includes('cancel:play:'+second+':'+target+':'+f.hero))});
for(const side of ['light','dark'])test(side+' Effect deployment is free, unique and not active until it resolves',()=>{
 let m=fresh();const site=location(m),hero=pull(m,other(side),side==='dark'?'1_21':'101_5','table',site),source=pull(m,side,side==='light'?'102_1':'102_6','hand'),second=pull(m,side,side==='light'?'102_1':'102_6','hand'),alter=pull(m,other(side),side==='dark'?'1_71':'1_234','hand');force(m,side,4);m=phase(m,side,'deploy');m=step(m,'force-effect:deploy:'+source);assert.equal(m.cards[source].zone,'playing');const before=m.players[side].force.length;const alt=step(m,'cancel:play:'+alter+':'+source+':'+hero);assert.ok(!ids(alt).includes('force-effect:exclude:'+source));m=settled(m);assert.equal(m.cards[source].zone,'table');assert.equal(m.players[side].force.length,before);m=priority(m,side);assert.ok(!ids(m).includes('force-effect:deploy:'+second));assert.equal(m.data.cardPlays.cards.filter(p=>p.card===source).length,1);
});
test('forged saved exclusions and response bindings are rejected without mutation',()=>{
 const f=senseFixture();let m=step(f.m,'force-effect:exclude:'+f.source);for(const change of [p=>p.targetIndex=100,p=>p.actionId='forged',p=>p.windowSerial=0,p=>p.selected=[{id:f.hero,zone:'hand',version:1}]]){const bad=clone(m);change(bad.stack.at(-1).payload);assert.throws(()=>prompt(bad),/Force Effect|Jedi|reference/)}
 m=step(m,'force-effect:select:'+f.hero);m=step(m,'force-effect:confirm');const bad=clone(m);bad.stack.find(r=>r.kind==='resolution'&&r.action.handler==='cancel:play').action.payload.excluded[0].version=999;assert.throws(()=>prompt(bad),/reference/);
 for(const s of ['light','dark'])assert.ok(!JSON.stringify(runtime.project(m,rules,s)).includes('targetIndex'));
});
function assaultFixture(side='light',bonus=4){let m=fresh();const enemy=other(side),site=location(m),source=pull(m,enemy,enemy==='light'?'102_1':'102_6'),assault=pull(m,side,side==='light'?'1_113':'1_238','hand');for(let i=0;i<2;i++)pull(m,enemy,enemy==='dark'?'1_194':'1_28','table',site);force(m,side,8);force(m,enemy,8);m=phase(m,enemy);
 const draws=[pull(m,side,side==='light'?'1_113':'1_238','hand'),pull(m,side,side==='light'?'1_113':'1_238','hand')];for(const id of draws.reverse())state.moveCard(m,id,'reserve');let defense;
 if(bonus===null)for(const id of [...m.players[enemy].reserve])state.moveCard(m,id,'hand');else{defense=pull(m,enemy,enemy==='dark'?(bonus===0?'101_4':'1_207'):(bonus===0?'1_124':'1_105'),'hand');state.moveCard(m,defense,'reserve')}
 m=step(m,'drain:'+site);m=priority(m,side);m=step(m,'assault:play:'+assault);return{m,side,enemy,site,source,assault,defense,draws};}
for(const side of ['light','dark'])for(const bonus of [4,0,null])test(side+' Assault defensive destiny '+bonus+' comes from defender and adds to frozen power',()=>{const f=assaultFixture(side,bonus);const before=f.m.players[f.enemy].force.length;let m=step(f.m,'force-effect:boost:'+f.source);assert.equal(m.players[f.enemy].force.length,before-1);assert.ok(!ids(m).includes('force-effect:boost:'+f.source));m=seek(m,x=>x.stack.at(-1)?.event?.kind==='assault-result');const e=m.stack.at(-1).event;assert.equal(e.destiny,6);assert.equal(e.power,2);assert.equal(e.defensiveDestiny,bonus);assert.equal(e.defensiveTotal,2+(bonus??0));assert.equal(e.amount,bonus===4?0:4);assert.equal(e.loser,bonus===4?null:f.enemy);if(f.defense)assert.equal(m.cards[f.defense].zone,'used');m=seek(m,x=>x.cards[f.assault].zone==='lost'&&x.stack.length===1);assert.equal(m.cards[f.source].zone,'table')});
test('an initiated defensive bonus survives source loss but never adds a second draw',()=>{const f=assaultFixture();let m=step(f.m,'force-effect:boost:'+f.source);state.moveCard(m,f.source,'lost');m=seek(m,x=>x.stack.at(-1)?.event?.kind==='assault-result');assert.equal(m.stack.at(-1).event.defensiveDestiny,4);assert.equal(Object.values(m.data.destinySequences).filter(s=>s.category==='assault-defense').length,1)});
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/force-effects-results.json',import.meta.url)));
for(const row of oracle.filter(r=>!r.name.includes('-assault-')&&!r.name.includes('-production-return')))test('actual GEMP Force Effect comparison '+row.name,()=>{
 const [side,mode]=row.name.split('-'),f=senseFixture(side,mode==='fail'?'fallback':mode==='other'?'multiple':mode,mode==='fail'?3:0),before=f.m.players[f.enemy].force.length,drawsBefore=f.m.players[side].reserve.length;
 let m=exclude(f,mode==='multiple'?[f.hero,f.second]:[f.hero]);if(prompt(m).timing==='decision')m=step(m,'force-effect:target:'+f.lower);m=priority(m,f.enemy);assert.ok(!ids(m).includes('force-effect:exclude:'+f.source));m=settled(m);
 assert.deepEqual({name:row.name,targetLost:m.cards[f.target].zone==='lost',senseUsed:m.cards[f.sense].zone==='used',forceSpent:before-m.players[f.enemy].force.length,cardsDrawn:drawsBefore-m.players[side].reserve.length,reoffered:false},row);
});
for(const row of oracle.filter(r=>r.name.includes('-assault-')))test('actual GEMP defensive Assault comparison '+row.name,()=>{
 const [side,,value]=row.name.split('-'),bonus=value===''?null:Number(value),f=assaultFixture(side,bonus);let m=f.m;
 // Match the explicitly ordered GEMP attacking destiny: 3, then 1.
 const one=pull(m,side,side==='light'?'1_28':'1_194','hand');const top=m.players[side].reserve.shift();state.moveCard(m,one,'reserve');m.players[side].reserve.unshift(top);
 const before={light:m.players.light.lost.length,dark:m.players.dark.lost.length},values=[];m=step(m,'force-effect:boost:'+f.source);
 const observed=new Set();for(let i=0;i<600&&!(m.cards[f.assault].zone==='lost'&&m.stack.length===1);i++){const w=m.stack.at(-1);if(w.event?.kind==='destiny-draw-complete'&&!observed.has(w.serial)){observed.add(w.serial);values.push(w.event.value)}const p=prompt(m);m=step(m,p.choices.some(c=>c.id==='pass')?'pass':p.choices[0].id)}
 assert.deepEqual({name:row.name,draws:values,attackerLost:m.players[side].lost.length-before[side]-1,defenderLost:m.players[f.enemy].lost.length-before[f.enemy],interruptLost:m.cards[f.assault].zone==='lost'},row);
});
test('ability below 6 is not a Jedi and no Force means no optional exclusion',()=>{const f=senseFixture('light');let m=f.m;while(m.players.dark.force.length)state.moveCard(m,m.players.dark.force[0],'used');assert.ok(!ids(m).includes('force-effect:exclude:'+f.source));const otherFixture=senseFixture('dark');m=otherFixture.m;const r=m.stack.find(f=>f.kind==='resolution'&&f.action.handler==='cancel:play');r.action.payload.character=otherFixture.lower;r.action.payload.characterRef=module('identity').referenceCard(m,otherFixture.lower);assert.ok(!ids(m).includes('force-effect:exclude:'+otherFixture.source))});
test('a nested Alter can cancel Sense after retargeting without refunding the exclusion',()=>{const f=senseFixture('light');let m=exclude(f);m=step(m,'force-effect:target:'+f.lower);const alter=pull(m,'dark','1_234','hand');m=priority(m,'dark');const force=m.players.dark.force.length;m=step(m,'cancel:play:'+alter+':'+f.sense+':direct');m=settled(m);assert.equal(m.cards[f.sense].zone,'lost');assert.equal(m.cards[alter].zone,'used');assert.equal(m.cards[f.target].zone,'used');assert.equal(m.cards[f.destiny].zone,'reserve');assert.equal(m.players.dark.force.length,force)});
test('canceling boosted Assault preserves both payments and suppresses both draw groups',()=>{const f=assaultFixture();let m=step(f.m,'force-effect:boost:'+f.source);const hero=pull(m,'dark','101_5','table',f.site),sense=pull(m,'dark','1_267','hand'),zero=pull(m,'dark','101_4','hand');state.moveCard(m,zero,'reserve');m=priority(m,'dark');m=step(m,'cancel:play:'+sense+':'+f.assault+':'+hero);m=seek(m,x=>x.cards[sense].zone==='used');assert.equal(m.cards[f.assault].zone,'lost');assert.equal(m.cards[f.defense].zone,'reserve');assert.ok(f.draws.every(id=>m.cards[id].zone==='reserve'));assert.equal(m.players.dark.force.length,7);assert.equal(m.players.light.force.length,7)});
for(const side of ['light','dark'])for(const fallback of [true,false])test(side+' Alter can be retargeted while trying to cancel the exclusion Effect itself '+fallback,()=>{
 let m=fresh();const enemy=other(side),site=location(m),hero=pull(m,side,side==='light'?'1_21':'101_5','table',site),source=pull(m,enemy,enemy==='dark'?'102_6':'102_1'),alter=pull(m,side,side==='light'?'1_71':'1_234','hand');const lower=fallback?pull(m,side,side==='light'?'1_28':'1_194','table',site):undefined;force(m,enemy,4);m=phase(m);const zero=pull(m,side,side==='light'?'1_124':'101_4','hand');state.moveCard(m,zero,'reserve');m=priority(m,side);m=step(m,'cancel:play:'+alter+':'+source+':'+hero);m=exclude({m,source,hero});if(fallback)m=step(m,'force-effect:target:'+lower);m=settled(m);assert.equal(m.cards[alter].zone,'used');assert.equal(m.cards[source].zone,fallback?'lost':'table');assert.equal(m.cards[zero].zone,'used');assert.equal(m.players[enemy].force.length,3);
});
test('unrespondable exclusions still yield for each Force-use response before taking effect',()=>{
 const f=senseFixture('light','multiple'),original={automatic:rules.automatic,initiate:rules.initiate,resolve:rules.resolve};
 rules.automatic=(m,w)=>[...original.automatic(m,w),...(w.event?.kind==='force-used'?[{id:'probe:force:'+w.serial,handler:'probe:force',label:'Observe Force use',actor:'dark',payload:null}]:[])];
 rules.initiate=(m,r,...args)=>{if(r.action.handler!=='probe:force')original.initiate(m,r,...args)};
 rules.resolve=(m,r,...args)=>{if(r.action.handler==='probe:force')m.data.observedUses=(m.data.observedUses??0)+1;else original.resolve(m,r,...args)};
 try{let m=exclude(f,[f.hero,f.second]);assert.equal(m.stack.at(-1).event.kind,'force-used');assert.equal(m.stack.find(r=>r.kind==='resolution'&&r.action.handler==='cancel:play').action.payload.excluded,undefined);m=seek(m,x=>x.data.observedUses===2&&x.stack.at(-1)?.event===undefined&&x.stack.at(-2)?.action?.handler==='cancel:play');assert.equal(m.players.dark.force.length,4);assert.equal(m.stack.at(-2).action.payload.noCharacter,true);m=settled(m);assert.equal(m.cards[f.target].zone,'used')}finally{Object.assign(rules,original)}
});

for(const row of oracle.filter(r=>r.name.includes('-production-return')))test('documented GEMP production removal difference '+row.name,()=>{
 const side=row.name.split('-')[0],f=senseFixture(side,'none');let m=f.m;state.moveCard(m,f.hero,'hand');m=settled(m);
 const actual={name:row.name,senseUsed:m.cards[f.sense].zone==='used',targetLost:m.cards[f.target].zone==='lost',heroInHand:m.cards[f.hero].zone==='hand'};
 assert.equal(row.targetLost,true);assert.deepEqual(actual,{...row,targetLost:false});
});
