import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {load} from '../native-proof/load-engine.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url));
const runtime=mod('runtime'),state=mod('state'),board=mod('board'),battle=mod('battle');
const fx=mod('fx-droids');
const rules={...mod('premiere-rules').premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true};
const clone=x=>JSON.parse(JSON.stringify(x));
function fresh(){return runtime.createMatch('fx-droids',60,['light','dark'].map(side=>({side,cards:[...(side==='light'?['8_5','3_9','3_9','3_60','3_59','1_129','1_132','1_19','1_100','1_152','1_6','1_5','1_31','1_40']:['1_284','1_168','1_324','13_86','1_267','1_317','1_317','3_86','3_86']),...Array(60).fill(side==='light'?'1_28':'1_194')].slice(0,60)})),rules)}
function pull(m,side,bp,zone='table',location){const c=Object.values(m.cards).find(c=>c.owner===side&&c.blueprint===bp&&c.zone==='reserve');assert.ok(c,bp);state.moveCard(m,c.id,zone);if(location)c.location=location;return c.id}
function prompt(m){const p=runtime.prompt(m,rules,'dark');return p&&runtime.prompt(m,rules,p.side)}
const ids=m=>prompt(m).choices.map(c=>c.id);
function step(m,id){const before=clone(m);const r=runtime.applyCommand(clone(m),rules,prompt(m).side,{revision:m.revision,choice:id},()=>0);assert.deepEqual(m,before);state.assertState(r);for(const side of ['light','dark'])assert.deepEqual(runtime.project(r,rules,side),runtime.project(clone(r),rules,side));return r}
function seek(m,f){for(let n=0;n<600;n++){if(f(m))return m;const cs=ids(m);m=step(m,cs.includes('pass')?'pass':cs.includes('skip-destiny')?'skip-destiny':cs[0])}throw Error('unreached boundary')}
const boundary=(m,kind)=>seek(m,x=>x.stack.at(-1)?.event?.kind===kind);
const priority=(m,side)=>prompt(m).side===side?m:step(m,'pass');
const phase=(m,side,phase)=>seek(m,x=>x.turn.side===side&&x.turn.phase===phase&&x.stack.length===1&&prompt(x).side===side);

function fixture(side='light',mode='same'){
 let m=fresh();const opposite=side==='light'?'dark':'light',site=pull(m,'light','1_129'),adj=pull(m,'light','1_132');m.locations.push(site,adj);
 const target=pull(m,side,side==='light'?'1_28':'1_194','table',site),second=pull(m,side,side==='light'?'1_28':'1_194','table',site),droid=pull(m,side,side==='light'?'3_9':'3_86','table',mode==='adjacent'?adj:site);
 const enemies=[];for(let i=0;i<10;i++)enemies.push(pull(m,opposite,opposite==='light'?'1_28':'1_194','table',site));
 for(const s of ['light','dark'])for(let i=0;i<10;i++)state.moveCard(m,m.players[s].reserve.at(-1),'force');
 m=phase(runtime.startTurns(m,rules),opposite,'battle');return{m,side,opposite,site,adj,target,second,droid,enemies};
}
function damage(f,hit=true){let m=boundary(step(f.m,'battle:'+f.site),'battle-damage');if(hit)battle.battle(m).hits.push(f.target);return priority(m,f.side)}
const offer=(m,f)=>ids(m).find(id=>id.startsWith('fx:'+f.droid+':'));
const pending=(m,f)=>priority(boundary(step(m,'forfeit:'+f.target),'about-to-forfeit'),f.side);
const finish=m=>boundary(m,'forfeited-to-used');
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/fx-results.json',import.meta.url)));
const observed=name=>{const row=oracle.find(r=>r.name===name);assert.ok(row,name);return row};
for(const side of ['light','dark'])for(const mode of ['same','adjacent','skip','source-leaves'])test('FX forfeiture '+side+' '+mode,()=>{const f=fixture(side,mode);let m=damage(f);const before=battle.battle(m).damage[side],value=board.forfeit(m,f.target);m=pending(m,f);assert.equal(before-battle.battle(m).damage[side],Math.min(before,value));assert.equal(m.cards[f.target].zone,'table');const a=offer(m,f);assert.ok(a);if(mode==='skip'){m=step(m,'pass');m=boundary(m,'forfeited')}else{m=step(m,a);if(mode==='source-leaves')state.moveCard(m,f.droid,'hand');m=finish(m)}assert.deepEqual({name:side+'-'+mode,used:m.cards[f.target].zone==='used',lost:m.cards[f.target].zone==='lost',paid:before-battle.battle(m).damage[side]},observed(side+'-'+mode))});
test('declined or canceled FX replacement keeps default Lost destination',()=>{const f=fixture();let m=pending(damage(f),f);m=step(m,offer(m,f));m.stack.find(q=>q.kind==='resolution'&&q.action.handler==='fx:replace').cancelled=true;m=boundary(m,'forfeited');assert.equal(m.cards[f.target].zone,'lost');assert.equal(m.data.fxUses.length,1)});
test('unhit characters and hit droids cannot be saved by FX; empty windows auto-advance',()=>{for(const droid of [false,true]){const f=fixture();let m=damage(f,false);if(droid){f.target=f.droid;battle.battle(m).hits.push(f.target)}m=step(m,'forfeit:'+f.target);m=boundary(m,'forfeited');assert.equal(m.cards[f.target].zone,'lost');assert.equal(m.data.fxUses,undefined)}});
test('a distant droid and an opposing droid cannot offer replacement',()=>{for(const mode of ['distant','opponent']){const f=fixture();let m=damage(f);if(mode==='distant'){const site=pull(m,'dark','1_284');m.locations.push(site);m.cards[f.droid].location=site}else state.moveCard(m,f.droid,'hand');pull(m,'dark','3_86','table',f.site);m=boundary(step(m,'forfeit:'+f.target),'forfeited');assert.equal(m.data.fxUses,undefined)}});
test('the same FX instance may replace only one forfeiture each turn',()=>{const f=fixture();let m=pending(damage(f),f);m=finish(step(m,offer(m,f)));m=priority(boundary(m,'battle-damage'),'light');battle.battle(m).hits.push(f.second);m=boundary(step(m,'forfeit:'+f.second),'forfeited');assert.equal(m.cards[f.second].zone,'lost');assert.equal(m.data.fxUses.length,1)});
test('different FX copies may each replace a forfeiture',()=>{const f=fixture();const secondFX=pull(f.m,'light','3_9','table',f.site);let m=pending(damage(f),f);m=finish(step(m,offer(m,f)));m=priority(boundary(m,'battle-damage'),'light');battle.battle(m).hits.push(f.second);m=priority(boundary(step(m,'forfeit:'+f.second),'about-to-forfeit'),'light');assert.ok(!offer(m,f));m=finish(step(m,ids(m).find(id=>id.startsWith('fx:'+secondFX+':'))));assert.equal(m.cards[f.second].zone,'used');assert.equal(m.data.fxUses.length,2)});
test('FX initiation cannot open a nested replacement or place the target twice',()=>{const f=fixture(),otherFX=pull(f.m,'light','3_9','table',f.site);let m=pending(damage(f),f);m=step(m,offer(m,f));/* initiation responses do not expose the underlying replacement window */assert.ok(!ids(m).some(id=>id.startsWith('fx:'+otherFX+':')));m=finish(m);assert.equal(m.players.light.used.filter(id=>id===f.target).length,1);assert.equal(m.data.fxUses.length,1)});
test('attachment loss ordering finishes before placing the forfeited host in Used',()=>{const f=fixture();const gun=pull(f.m,'light','1_152'),belt=pull(f.m,'light','1_40');for(const id of [gun,belt]){f.m.cards[id].attachedTo=f.target;f.m.cards[id].location=f.site}let m=pending(damage(f),f);m=step(m,offer(m,f));m=seek(m,x=>x.stack.at(-1)?.handler==='table:lost-order');assert.equal(m.cards[f.target].zone,'leaving');assert.equal(m.cards[gun].zone,'leaving');assert.equal(m.cards[belt].zone,'leaving');assert.ok(!ids(m).includes('place-lost:'+f.target));m=clone(m);m=step(m,'place-lost:'+belt);m=finish(m);assert.equal(m.cards[f.target].zone,'used');assert.deepEqual(m.players.light.lost.slice(0,2),[gun,belt]);assert.equal(m.players.light.used[0],f.target)});
test('Used forfeiture does not open Old Ben or Delevar just-lost recovery, nor trigger Secret Plans',()=>{const f=fixture();pull(f.m,'light','1_100','hand');pull(f.m,'light','8_5','table',f.site);pull(f.m,'dark','13_86');let m=pending(damage(f),f);const force=m.players.light.force.length;m=finish(step(m,offer(m,f)));assert.ok(!ids(m).some(id=>/^(medic:|revival:old-ben|plans:)/.test(id)));assert.equal(m.players.light.force.length,force)});
for(const stage of ['before','pending','replaced'])test('forfeiture binds original target instance '+stage,()=>{const f=fixture();let m=pending(damage(f),f),before=battle.battle(m).damage.light;if(stage!=='before')m=step(m,offer(m,f));if(stage==='replaced')m=boundary(m,'forfeiture-destination-changed');state.moveCard(m,f.target,'hand');state.moveCard(m,f.target,'table');m.cards[f.target].location=f.site;m=seek(m,x=>!x.stack.some(q=>q.kind==='resolution'&&q.action.handler.startsWith('forfeiture:')));assert.equal(m.cards[f.target].zone,'table');assert.equal(battle.battle(m).damage.light,before)});
test('FX usage and the replacement window survive refresh and reject forged bindings',()=>{const f=fixture();const before=pending(damage(f),f),m=step(before,offer(before,f));for(const side of ['light','dark'])assert.deepEqual(runtime.project(m,rules,side),runtime.project(clone(m),rules,side));for(const mutate of [x=>x.data.fxUses[0].turn=999,x=>x.stack.find(f=>f.kind==='resolution'&&f.action.handler==='fx:replace').action.payload.target.id=f.second,x=>x.stack.find(f=>f.kind==='resolution'&&f.action.handler==='forfeiture:leave').action.payload.destination='hand']){const bad=clone(m);mutate(bad);assert.throws(()=>rules.validate(bad))}assert.ok(!JSON.stringify(runtime.project(m,rules,'light')).includes('fxUses'))});
test('official current FX erratum never offers replacement for ordinary non-forfeiture loss',()=>{const f=fixture();let m=damage(f);for(const kind of ['about-to-lose','character-lost','cards-lost'])assert.deepEqual(fx.fxActions(m,{kind:'window',timing:'response',event:{kind,card:f.target,site:f.site}},'light'),[])});
for(const side of ['light','dark'])test('FX ground deployment uses printed cost and zero ability '+side,()=>{const f=fixture(side);state.moveCard(f.m,f.droid,'hand');let m=phase(f.m,side,'deploy');const force=m.players[side].force.length;m=boundary(step(m,'deploy:'+f.droid+':'+f.site),'deployed');assert.equal(force-m.players[side].force.length,2);assert.equal(mod('ability').ability(m,f.droid),0)});

test('hit Talz can forfeit to Used as a cost and still restore another hit character',()=>{const f=fixture();const talz=pull(f.m,'light','1_31','table',f.site);let m=damage(f);battle.battle(m).hits.push(talz);const before=battle.battle(m).damage.light,value=board.forfeit(m,talz);m=priority(boundary(step(m,'rescue:'+talz+':'+f.target),'about-to-forfeit'),'light');m=finish(step(m,offer(m,f)));assert.equal(m.cards[talz].zone,'used');m=seek(m,x=>!battle.battle(x).hits.includes(f.target));assert.equal(m.cards[f.target].zone,'table');assert.equal(battle.battle(m).damage.light,Math.max(0,before-value))});
for(const mode of ['reentry','next-turn'])test('FX allowance renews for '+mode,()=>{const f=fixture();let m=pending(damage(f),f);m=finish(step(m,offer(m,f)));m=priority(boundary(m,'battle-damage'),'light');battle.battle(m).hits.push(f.second);if(mode==='reentry'){state.moveCard(m,f.droid,'hand');state.moveCard(m,f.droid,'table');m.cards[f.droid].location=f.site}else m.turn.number++;f.target=f.second;m=pending(m,f);assert.ok(offer(m,f));m=finish(step(m,offer(m,f)));assert.equal(m.cards[f.second].zone,'used')});
for(const side of ['light','dark'])test('actual blaster hit proceeds through FX forfeiture '+side,()=>{const f=fixture(side),gun=pull(f.m,f.opposite,side==='light'?'1_317':'1_152');f.m.cards[gun].attachedTo=f.enemies[0];f.m.cards[gun].location=f.site;const destiny=pull(f.m,f.opposite,side==='light'?'1_317':'1_100','hand');state.moveCard(f.m,destiny,'reserve');let m=priority(boundary(step(f.m,'battle:'+f.site),'battle-weapons'),f.opposite);m=boundary(step(m,'fire:'+gun+':'+f.target),'weapon-fired');assert.ok(battle.battle(m).hits.includes(f.target));m=priority(boundary(m,'battle-damage'),side);m=pending(m,f);m=finish(step(m,offer(m,f)));assert.equal(m.cards[f.target].zone,'used')});
