import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {load} from '../native-proof/load-engine.mjs';
const module=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url));
const runtime=module('runtime'),state=module('state'),stats=module('ability'),board=module('board'),combat=module('battle'),mods=module('combat-modifiers');
const {premiereRules}=module('premiere-rules');
const rules={...premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true};
const clone=x=>JSON.parse(JSON.stringify(x)),other=s=>s==='light'?'dark':'light';
function fresh(beginner=false){return runtime.createMatch('battle-courage',60,['light','dark'].map(side=>({side,cards:[...(side==='light'?['4_2','5_41','5_41',beginner?'101_2':'1_19','1_109','1_129','1_124','9_24','1_21','1_4']:['5_159','5_159','5_141','5_141',beginner?'101_5':'1_168','1_267','1_284','1_285','4_103','9_109','1_171']),...Array(60).fill(side==='light'?'1_28':'1_194')].slice(0,60)})),rules)}
function pull(m,side,bp,zone='table',site){const c=Object.values(m.cards).find(c=>c.owner===side&&c.blueprint===bp&&c.zone==='reserve');assert.ok(c,'fixture '+bp);state.moveCard(m,c.id,zone);if(site)m.cards[c.id].location=site;return c.id}
function prompt(m){const p=runtime.prompt(m,rules,'dark');return p&&runtime.prompt(m,rules,p.side)}
const ids=m=>prompt(m).choices.map(c=>c.id);
function step(m,id){const before=clone(m),r=runtime.applyCommand(clone(m),rules,prompt(m).side,{revision:m.revision,choice:id},()=>0);assert.deepEqual(m,before);state.assertState(r);for(const s of ['dark','light'])assert.deepEqual(runtime.project(r,rules,s),runtime.project(clone(r),rules,s));return r}
function seek(m,predicate){for(let n=0;n<900;n++){if(predicate(m))return m;const p=prompt(m);assert.ok(p,'ended too soon');m=step(m,p.choices.some(c=>c.id==='pass')?'pass':p.choices.some(c=>c.id==='skip-destiny')?'skip-destiny':p.choices[0].id)}throw Error('boundary not reached')}
function phase(m,p='battle',side='dark'){if(m.status==='setup')m=runtime.startTurns(m,rules);return seek(m,x=>x.turn.side===side&&x.turn.phase===p&&x.stack.length===1)}
const priority=(m,side)=>prompt(m).side===side?m:step(m,'pass');
const boundary=(m,kind)=>seek(m,x=>x.stack.at(-1)?.event?.kind===kind);
function fixture(beginner=true){let m=fresh(beginner);const site=pull(m,'light','1_129');m.locations.push(site);const hero={},card={},copy={},sense={},troop={};for(const side of ['light','dark']){hero[side]=pull(m,side,side==='light'?(beginner?'101_2':'1_19'):(beginner?'101_5':'1_168'),'table',site);card[side]=pull(m,side,side==='light'?'5_41':'5_141','hand');copy[side]=pull(m,side,side==='light'?'5_41':'5_141','hand');sense[side]=pull(m,side,side==='light'?'1_109':'1_267','hand');troop[side]=pull(m,side,side==='light'?'1_28':'1_194','hand');for(let i=0;i<8;i++)state.moveCard(m,m.players[side].reserve.at(-1),'force')}m=phase(m);return{m,site,hero,card,copy,sense,troop}}
const start=f=>boundary(step(f.m,'battle:'+f.site),'battle-weapons');

const rows=JSON.parse(fs.readFileSync(new URL('./gemp/immunity-results.json',import.meta.url)));
for(const row of rows.filter(r=>!r.name.startsWith('assault-')))test('executed GEMP immunity query '+row.name,()=>{
 const f=fixture(),m=f.m,mode=row.name;const id=mode==='yoda'?pull(m,'light','4_2','table',f.site):f.troop.dark;if(mode!=='yoda'){state.moveCard(m,id,'table');m.cards[id].location=f.site}
 const add=(kind,amount)=>mods.addCombatModifier(m,f.site,id,kind,amount);
 if(['less-add','less-subtract','less-zero','less-higher','exact-higher','equal','both-change','cap','cap-zero','both-cap','cancel','uncancelable'].includes(mode))add('immunity-less-than',mode==='less-higher'?5:3);
 if(['exact','exact-add','exact-negative','less-higher','exact-higher','equal','both-change','exact-cap','both-cap'].includes(mode))add('immunity-exact',mode==='exact-higher'||mode==='both-change'?4:3);
 if(['none-add','less-add','exact-add','both-change'].includes(mode))add('immunity-change',2);
 if(mode==='less-subtract')add('immunity-change',-1);if(['less-zero','exact-negative'].includes(mode))add('immunity-change',-5);
 if(mode==='full-cap')add('immunity-full',1);if(['cap','cap-zero','exact-cap','both-cap','full-cap'].includes(mode))add('immunity-limit',mode==='cap-zero'?0:2);
 if(['cancel','uncancelable'].includes(mode))add('immunity-cancel',1);if(mode.includes('uncancelable'))add('immunity-uncancelable',1);
 const v=mods.attritionImmunityValues(m,id);assert.deepEqual({name:mode,lessThan:Number.isFinite(v.lessThan)?v.lessThan:'all',exact:v.exact,hasAny:mods.hasAttritionImmunity(m,id)},row);mods.assertCombatModifiers(clone(m));
});
function assaultFixture(){const f=fixture();f.assault=pull(f.m,'dark','5_159','hand');f.copyAssault=pull(f.m,'dark','5_159','hand');state.moveCard(f.m,f.troop.dark,'table');f.m.cards[f.troop.dark].location=f.site;return f}
const initiated=f=>seek(step(f.m,'battle:'+f.site),m=>m.stack.at(-2)?.action?.handler==='battle:begin'&&!m.stack.at(-2).awaitingResponses&&m.stack.at(-1)?.kind==='window'&&m.stack.at(-1).event===undefined);
const assault=(m,f)=>step(priority(m,'dark'),'trooper-assault:'+f.assault);
const resolved=(m,f)=>seek(m,x=>['used','lost'].includes(x.cards[f.assault].zone));
for(const mode of ['normal','cancel-immunity','second','sense'])test('actual Trooper Assault '+mode,()=>{
 const f=assaultFixture();let m=assault(initiated(f),f);if(mode==='cancel-immunity')mods.addCombatModifier(m,f.site,f.troop.dark,'immunity-cancel',1);
 if(mode==='sense'){const zero=pull(m,'light','1_124','hand');state.moveCard(m,zero,'reserve');m=step(m,'cancel:play:'+f.sense.light+':'+f.assault+':'+f.hero.light)}
 m=resolved(m,f);if(mode==='second'){m=seek(m,x=>x.stack.at(-2)?.action?.handler==='battle:begin'&&x.stack.at(-1)?.kind==='window');m=step(priority(m,'dark'),'trooper-assault:'+f.copyAssault);m=seek(m,x=>x.cards[f.copyAssault].zone==='used')}
 const v=mods.attritionImmunity(m,f.troop.dark);assert.deepEqual({name:'assault-'+mode,power:board.power(m,f.troop.dark),immune:v===Infinity,sourceUsed:m.cards[f.assault].zone==='used',sourceLost:m.cards[f.assault].zone==='lost',otherPower:board.power(m,f.hero.dark)},rows.find(r=>r.name==='assault-'+mode));assert.equal(board.power(m,f.hero.dark),4);
});
test('only the battle initiation response offers Trooper Assault',()=>{const f=assaultFixture();assert.ok(!ids(f.m).includes('trooper-assault:'+f.assault));let m=priority(initiated(f),'dark');assert.ok(ids(m).includes('trooper-assault:'+f.assault));m=boundary(m,'battle-weapons');assert.ok(!ids(m).includes('trooper-assault:'+f.assault))});
test('without a participating trooper the Interrupt cannot be initiated',()=>{const f=assaultFixture();state.moveCard(f.m,f.troop.dark,'hand');const m=priority(initiated(f),'dark');assert.ok(!ids(m).includes('trooper-assault:'+f.assault));assert.throws(()=>assault(m,f),/Illegal/)});
test('recipients are collected on resolution, including a newly present trooper',()=>{const f=assaultFixture();let m=assault(initiated(f),f);const added=pull(m,'dark','1_194','table',f.site);state.moveCard(m,f.troop.dark,'hand');combat.syncBattle(m);m=resolved(m,f);assert.equal(board.power(m,added),3);assert.equal(mods.attritionImmunity(m,added),Infinity);assert.equal(mods.combatPowerBonus(m,f.troop.dark),0);const row=rows.find(r=>r.name==='assault-arrival');assert.deepEqual({name:row.name,power:board.power(m,f.troop.dark),immune:mods.attritionImmunity(m,f.troop.dark)===Infinity,sourceUsed:m.cards[f.assault].zone==='used',sourceLost:m.cards[f.assault].zone==='lost',otherPower:board.power(m,f.hero.dark),secondPower:board.power(m,added)},row)});
test('a removed trooper characteristic excludes a recipient, a granted characteristic includes one',()=>{const f=assaultFixture();let m=assault(initiated(f),f);const traits=module('characteristics');traits.changeCharacteristic(m,f.site,f.troop.dark,'STORMTROOPER','remove');traits.changeCharacteristic(m,f.site,f.hero.dark,'TROOPER','give');m=resolved(m,f);assert.equal(board.power(m,f.troop.dark),1);assert.equal(board.power(m,f.hero.dark),6)});
test('later arrivals and later gained trooper status cannot retroactively gain the resolved grant',()=>{const f=assaultFixture();let m=resolved(assault(initiated(f),f),f);const added=pull(m,'dark','1_194','table',f.site);module('characteristics').changeCharacteristic(m,f.site,f.hero.dark,'TROOPER','give');assert.equal(board.power(m,added),1);assert.equal(board.power(m,f.hero.dark),4)});
test('resolved group membership survives characteristic loss, but ends with its original table instance',()=>{const f=assaultFixture();let m=resolved(assault(initiated(f),f),f);module('characteristics').changeCharacteristic(m,f.site,f.troop.dark,'STORMTROOPER','remove');assert.equal(board.power(m,f.troop.dark),3);state.moveCard(m,f.troop.dark,'hand');state.moveCard(m,f.troop.dark,'table');m.cards[f.troop.dark].location=f.site;assert.equal(board.power(m,f.troop.dark),1)});
test('Used Interrupt grant survives source movement but expires on the next turn',()=>{const f=assaultFixture();let m=resolved(assault(initiated(f),f),f);state.moveCard(m,f.assault,'hand');assert.equal(board.power(m,f.troop.dark),3);m.turn.phase='draw';assert.equal(mods.attritionImmunity(m,f.troop.dark),Infinity);m.turn.number++;assert.equal(board.power(m,f.troop.dark),1);assert.equal(mods.hasAttritionImmunity(m,f.troop.dark),false)});
test('exact immunity is available to Focused Attack implied targeting',()=>{const f=fixture();mods.addCombatModifier(f.m,f.site,f.hero.dark,'immunity-exact',3);const m=priority(start(f),'dark');assert.ok(ids(m).includes('duel-interrupt:battle:'+f.card.dark+':'+f.hero.dark))});
for(const total of [2,3,4])test('exact immunity freezes only against attrition '+total,()=>{const f=fixture();mods.addCombatModifier(f.m,f.site,f.hero.dark,'immunity-exact',3);mods.addCombatModifier(f.m,f.site,f.hero.dark,'power-add',10);let m=boundary(start(f),'battle-destiny-complete');combat.battle(m).destiny.light=total;combat.battle(m).destiny.dark=0;m=boundary(m,'battle-damage');assert.equal(combat.damagePending(m,'dark'),total!==3);mods.addCombatModifier(m,f.site,f.hero.dark,'immunity-change',1);assert.equal(combat.damagePending(m,'dark'),total!==3)});
test('cancellation protection expires with source; caps choose lowest and additive duplicates remain noncumulative',()=>{const f=fixture(),m=f.m,id=f.hero.dark;mods.addCombatModifier(m,f.card.dark,id,'immunity-less-than',5);mods.addCombatModifier(m,f.card.dark,id,'immunity-change',2);mods.addCombatModifier(m,f.copy.dark,id,'immunity-change',2);assert.equal(mods.attritionImmunity(m,id),7);mods.addCombatModifier(m,f.card.light,id,'immunity-limit',4);mods.addCombatModifier(m,f.copy.light,id,'immunity-limit',3);assert.equal(mods.attritionImmunity(m,id),3);mods.addCombatModifier(m,f.card.dark,id,'immunity-cancel',1);mods.addCombatModifier(m,f.hero.light,id,'immunity-uncancelable',1,{duration:'source'});assert.equal(mods.attritionImmunity(m,id),3);state.moveCard(m,f.hero.light,'hand');assert.equal(mods.hasAttritionImmunity(m,id),false)});
test('saved modifier kinds, amounts and pending card identity are validated',()=>{const f=assaultFixture();let m=assault(initiated(f),f);const bad=clone(m);bad.stack.find(r=>r.action?.handler==='trooper-assault:play').action.payload.card=f.card.dark;assert.throws(()=>prompt(bad),/Assault/);m=resolved(m,f);for(const patch of [{kind:'immunity-limit',amount:-1},{kind:'immunity-exact',amount:null},{kind:'immunity-uncancelable',amount:2}]){const bad=clone(m);Object.assign(bad.data.combatModifiers[0],patch);assert.throws(()=>prompt(bad),/combat modifier/)};assert.ok(!JSON.stringify(runtime.project(m,rules,'light')).includes('combatModifiers'))});

test('Trooper Assault completes a battle with unprotected loss and protected survivors',()=>{const f=assaultFixture();state.moveCard(f.m,f.troop.light,'table');f.m.cards[f.troop.light].location=f.site;let m=resolved(assault(initiated(f),f),f);m=boundary(m,'battle-destiny-complete');combat.battle(m).destiny.light=7;combat.battle(m).destiny.dark=0;m=boundary(m,'battle-damage');const initial=combat.battle(m).attrition.dark;m=step(priority(m,'dark'),'forfeit:'+f.hero.dark);m=seek(m,x=>combat.battle(x)?.stage==='complete'&&x.stack.length===1);assert.deepEqual({name:'assault-complete-battle',initialAttrition:initial,vaderLost:m.cards[f.hero.dark].zone==='lost',trooperOnTable:m.cards[f.troop.dark].zone==='table',lukeOnTable:m.cards[f.hero.light].zone==='table',sourceUsed:m.cards[f.assault].zone==='used'},rows.find(r=>r.name==='assault-complete-battle'));assert.ok(combat.battle(m).attrition.dark>0);assert.equal(combat.battle(m).damage.dark,0)});
test('an initiated assault with no remaining trooper resolves to Used without a grant',()=>{const f=assaultFixture();let m=assault(initiated(f),f);state.moveCard(m,f.troop.dark,'hand');m=resolved(m,f);assert.equal(m.cards[f.assault].zone,'used');assert.equal((m.data.combatModifiers??[]).length,0)});
