import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {load} from '../native-proof/load-engine.mjs';
const runtime=load(new URL('../../lib/native-engine/runtime.ts',import.meta.url)),state=load(new URL('../../lib/native-engine/state.ts',import.meta.url)),inserts=load(new URL('../../lib/native-engine/reserve-inserts.ts',import.meta.url)),activation=load(new URL('../../lib/native-engine/activation.ts',import.meta.url));
const {premiereRules}=load(new URL('../../lib/native-engine/premiere-rules.ts',import.meta.url));
const {chooseComputerAction}=load(new URL('../../lib/native-engine/computer.ts',import.meta.url));
const manifest=JSON.parse(fs.readFileSync(new URL('../../data/native-proof/manifest.json',import.meta.url))),clone=x=>JSON.parse(JSON.stringify(x));
const rules={...premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true};
function prompt(m,r=rules){const p=runtime.prompt(m,r,'dark');return p&&runtime.prompt(m,r,p.side)}
function step(m,id,r=rules,side=prompt(m,r).side){const old=clone(m),next=runtime.applyCommand(clone(m),r,side,{revision:m.revision,choice:id},()=>0);assert.deepEqual(m,old);for(const s of ['light','dark'])assert.deepEqual(runtime.project(next,r,s),runtime.project(clone(next),r,s));return next}
function seek(m,condition,r=rules){for(let i=0;i<1200;i++){if(condition(m))return m;const p=prompt(m,r);assert.ok(p);m=step(m,p.mandatory?p.choices[0].id:'pass',r)}throw Error('Boundary not found')}
const event=m=>m.stack.at(-1)?.event;
function pull(m,side,bp,zone='hand'){const id=m.players[side].reserve.find(id=>m.cards[id].blueprint===bp);assert.ok(id,bp);state.moveCard(m,id,zone);return id}
function fixture(r=rules){let m=runtime.createMatch('insert-effects',60,manifest.decks.map(d=>({side:d.side,cards:[...(d.side==='light'?['1_42','1_42','1_72','1_71','1_2','1_22']:['1_208','1_208','1_234']),...d.main].slice(0,60)})),r);for(const side of ['light','dark']){const site=pull(m,side,side==='light'?'1_129':'1_284','table');m.locations.push(site)}const light=pull(m,'light','1_42'),dark=pull(m,'dark','1_208');m=runtime.startTurns(m,r);return {m,light,dark}}
function atPhase(m,side,phase,r=rules){return seek(m,x=>x.turn.side===side&&x.turn.phase===phase&&x.stack.length===1&&x.stack[0].timing==='phase'&&prompt(x,r).side===side,r)}
function deploy(f,side='dark',r=rules){let m=atPhase(f.m,side,'deploy',r);m=step(m,'insert:deploy:'+f[side],r);return seek(m,x=>inserts.isInserted(x,f[side])&&x.stack.length===1,r)}
function installed(r=rules){const f=fixture(r);state.insertCard(f.m,f.light,'dark',()=>0);inserts.insertsIn(f.m,'dark')[0].position=1;return f}
for(const side of ['light','dark'])test('real insert deployment '+side+' preserves hidden counts, immunity and once-per-game title limit',()=>{
 const f=fixture(),m=deploy(f,side),target=side==='light'?'dark':'light';assert.equal(inserts.insertsIn(m,target).length,1);assert.equal(m.cards[f[side]].zone,'table');assert.equal(runtime.project(m,rules,target).players[target].counts.reserve,null);assert.ok(m.data.insertPlays.includes(m.cards[f[side]].blueprint));
 const second=pull(m,side,side==='light'?'1_42':'1_208');state.moveCard(m,f[side],'lost');const next=atPhase(m,side,'deploy');assert.ok(!prompt(next).choices.some(c=>c.id==='insert:deploy:'+second));
});
for(const count of [0,1,2])test('insert deployment target size '+count,()=>{const f=fixture();for(const id of f.m.players.light.reserve.slice(count))state.moveCard(f.m,id,'used');const m=atPhase(f.m,'dark','deploy');assert.equal(prompt(m).choices.some(c=>c.id==='insert:deploy:'+f.dark),count>=2)});
test('late target depletion loses deployment without undoing its once-per-game use',()=>{const f=fixture();let m=atPhase(f.m,'dark','deploy');m=step(m,'insert:deploy:'+f.dark);for(const id of m.players.light.reserve.slice(1))state.moveCard(m,id,'used');m=seek(m,x=>x.stack.length===1);assert.equal(m.cards[f.dark].zone,'lost');assert.ok(m.data.insertPlays.includes('1_208'))});
test('Alter cannot target the insert during deployment or after insertion',()=>{const f=fixture();pull(f.m,'light','1_71');let m=atPhase(f.m,'dark','deploy');m=step(m,'insert:deploy:'+f.dark);assert.ok(!prompt(m).choices.some(c=>c.id.startsWith('cancel:')));m=seek(m,x=>inserts.isInserted(x,f.dark)&&x.stack.length===1);m=step(m,'pass');assert.ok(!prompt(m).choices.some(c=>c.id.includes(f.dark)&&c.id.startsWith('cancel:')))});
for(const count of [0,1,2])test('normal activation declares '+count+' and an exposed Tremor stops its remaining units',()=>{
 const f=installed();let m=atPhase(f.m,'dark','activate');assert.ok(!prompt(m).choices.some(c=>c.id==='core:activate'));m=step(m,'core:declare-activation');m=seek(m,x=>x.stack.at(-1)?.handler==='core:activation-amount');assert.ok(prompt(m).choices.some(c=>c.id==='core:activation-amount:'+count));m=step(m,'core:activation-amount:'+count);
 if(count){assert.equal(event(m)?.kind,'insert-revealed');assert.equal(m.turn.activated,1);assert.equal(m.cards[f.light].zone,'table');m=seek(m,x=>x.stack.length===1);assert.equal(m.cards[f.light].zone,'lost');assert.equal(activation.mayActivate(m,'dark'),false)}else m=seek(m,x=>x.stack.length===1);
 assert.equal(m.turn.activated,Math.min(count,1));assert.ok(!prompt(m).choices.some(c=>['core:activate','core:declare-activation'].includes(c.id)));
});
test('declared activation can continue through normal phase actions, but cannot be increased while an insert remains',()=>{
 const f=installed();inserts.insertsIn(f.m,'dark')[0].position=20;let m=atPhase(f.m,'dark','activate');m=step(m,'core:declare-activation');m=seek(m,x=>x.stack.at(-1)?.handler==='core:activation-amount');m=step(m,'core:activation-amount:1');assert.equal(event(m)?.kind,'activation-between');assert.equal(m.turn.activated,1);m=seek(m,x=>x.stack.length===1);assert.ok(!prompt(m).choices.some(c=>c.id==='core:declare-activation'||c.id==='core:activate'));assert.equal(runtime.project(m,rules,'light').activation.count,1);
});
test('card-effect activation is interrupted without counting as normal generation',()=>{const f=installed();runtime.activateForce(f.m,'dark',f.dark,3);runtime.openWindow(f.m,'response','light');let m=seek(f.m,x=>event(x)?.kind==='insert-revealed');assert.equal(m.players.dark.force.length,1);m=seek(m,x=>x.stack.length===1);assert.equal(m.players.dark.force.length,1);assert.equal(m.turn.activated,0);assert.equal(m.cards[f.light].zone,'lost')});
test('concession during reveal freezes the exact suspended activation',()=>{const f=installed();runtime.activateForce(f.m,'dark',f.dark,3);runtime.openWindow(f.m,'response','light');let m=seek(f.m,x=>event(x)?.kind==='insert-revealed');const before=clone(m);m=step(m,'concede',rules,'dark');assert.equal(m.result.winner,'light');assert.deepEqual(m.stack,before.stack);assert.deepEqual(m.players,before.players)});
test('CPU declares activation using only its projected options and unknown Reserve count',()=>{const f=installed(),m=atPhase(f.m,'dark','activate');assert.equal(chooseComputerAction(runtime.project(m,rules,'dark'),'dark'),'core:declare-activation');let n=step(m,'core:declare-activation');n=seek(n,x=>x.stack.at(-1)?.handler==='core:activation-amount');assert.equal(chooseComputerAction(runtime.project(n,rules,'dark'),'dark'),'core:activation-amount:'+Math.floor(n.turn.generation))});
const cancelling={...rules,actions:(m,w,side)=>[...rules.actions(m,w,side),...(w.event?.kind==='insert-revealed'&&side===w.event.side?[{id:'probe:cancel-insert',label:'Cancel revealed insert',handler:'probe:cancel-insert',payload:w.event.card,source:w.event.card}]:[])],resolve:(m,r,c)=>{if(r.action.handler==='probe:cancel-insert')state.moveCard(m,r.action.payload,'lost');else rules.resolve(m,r,c)},initiate:(m,r,c)=>{if(r.action.handler!=='probe:cancel-insert')rules.initiate(m,r,c)}};
function cancelReveal(m,r=cancelling){if(prompt(m,r).side!==event(m).side)m=step(m,'pass',r);m=step(m,'probe:cancel-insert',r);return m}
test('canceling a revealed insert restores the suspended card activation and suppresses its prohibition',()=>{const f=installed(cancelling);runtime.activateForce(f.m,'dark',f.dark,3);runtime.openWindow(f.m,'response','light');let m=seek(f.m,x=>event(x)?.kind==='insert-revealed',cancelling);m=cancelReveal(m);m=seek(m,x=>x.stack.length===1,cancelling);assert.equal(m.players.dark.force.length,3);assert.equal(activation.mayActivate(m,'dark'),true);assert.equal(m.cards[f.light].zone,'lost')});
test('canceling the last opposing insert permits more normal activation after the declaration completes',()=>{const f=installed(cancelling);let m=atPhase(f.m,'dark','activate',cancelling);m=step(m,'core:declare-activation',cancelling);m=seek(m,x=>x.stack.at(-1)?.handler==='core:activation-amount',cancelling);m=step(m,'core:activation-amount:1',cancelling);m=cancelReveal(m);m=seek(m,x=>x.stack.length===1,cancelling);assert.equal(m.turn.activated,1);if(prompt(m,cancelling).side!=='dark')m=step(m,'pass',cancelling);assert.ok(prompt(m,cancelling).choices.some(c=>c.id==='core:activate'));m=step(m,'core:activate',cancelling);m=seek(m,x=>x.stack.length===1,cancelling);assert.equal(m.turn.activated,2)});
for(const extra of [0,1,2])test('a variable activation may increase by '+extra+' after every opposing insert is canceled',()=>{const f=installed(cancelling);runtime.activateForce(f.m,'dark',f.dark,1,3);runtime.openWindow(f.m,'response','light');let m=seek(f.m,x=>event(x)?.kind==='insert-revealed',cancelling);m=cancelReveal(m);m=seek(m,x=>x.stack.at(-1)?.handler==='core:activation-extra',cancelling);assert.equal(prompt(m,cancelling).side,'dark');m=step(m,'core:activation-extra:'+extra,cancelling);m=seek(m,x=>x.stack.length===1,cancelling);assert.equal(m.players.dark.force.length,1+extra);assert.equal(m.turn.activated,0)});
test('variable activation cannot increase while another opposing insert remains',()=>{const f=installed(cancelling),second=pull(f.m,'light','1_42');state.insertCard(f.m,second,'dark',()=>0);const entries=inserts.insertsIn(f.m,'dark');entries.find(x=>x.card.id===f.light).position=1;entries.find(x=>x.card.id===second).position=10;runtime.activateForce(f.m,'dark',f.dark,1,3);runtime.openWindow(f.m,'response','light');let m=seek(f.m,x=>event(x)?.kind==='insert-revealed',cancelling);m=cancelReveal(m);m=seek(m,x=>x.stack.length===1,cancelling);assert.equal(m.players.dark.force.length,1);assert.ok(inserts.isInserted(m,second))});
test('adjacent insert results resolve in physical order before suspended activation continues',()=>{const f=installed(),second=pull(f.m,'light','1_42');state.insertCard(f.m,second,'dark',()=>0);for(const x of inserts.insertsIn(f.m,'dark'))x.position=1;const order=inserts.insertsIn(f.m,'dark').map(x=>x.card.id);runtime.activateForce(f.m,'dark',f.dark,3);runtime.openWindow(f.m,'response','light');let m=seek(f.m,x=>event(x)?.kind==='insert-revealed');assert.equal(event(m).card,order[0]);m=seek(step(m,'pass'),x=>event(x)?.kind==='insert-revealed'&&event(x).card===order[1]);m=seek(m,x=>x.stack.length===1);assert.equal(m.players.dark.force.length,1);assert.deepEqual(m.players.light.lost.slice(0,2),[order[1],order[0]])});
for(const first of ['light','dark'])test('turn player orders simultaneous inserts with '+first+' first',()=>{const f=fixture();state.insertCard(f.m,f.light,'dark',()=>0);state.insertCard(f.m,f.dark,'light',()=>0);for(const x of inserts.reserveInserts(f.m))x.position=0;let m=step(f.m,'pass');assert.equal(m.stack.at(-1).handler,'insert:order');assert.equal(prompt(m).side,'dark');m=step(m,'insert:first:'+f[first]);assert.equal(event(m).card,f[first]);m=seek(m,x=>x.stack.length===1);assert.equal(activation.mayActivate(m,'light'),false);assert.equal(activation.mayActivate(m,'dark'),false)});
test('insert restriction survives source retrieval but expires on the next turn',()=>{const f=installed();runtime.activateForce(f.m,'dark',f.dark,3);runtime.openWindow(f.m,'response','light');let m=seek(f.m,x=>x.cards[f.light].zone==='lost'&&x.stack.length===1);state.moveCard(m,f.light,'hand');assert.equal(activation.mayActivate(m,'dark'),false);m=atPhase(m,'light','activate');assert.equal(activation.mayActivate(m,'dark'),true)});
test('a last Life Force loss ends the game before its newly exposed insert can change the outcome',()=>{const f=installed();for(const id of f.m.players.dark.reserve.slice(1))state.moveCard(f.m,id,'hand');const r={...rules,actions:(m,w,s)=>[{id:'probe:last-loss',label:'Lose final Force',handler:'probe:last-loss',payload:null}],initiate:()=>{},resolve:(m,a,c)=>{if(a.action.handler==='probe:last-loss')state.moveTop(m,'dark','reserve','lost');else rules.resolve(m,a,c)}};let m=step(f.m,'probe:last-loss',r);m=seek(m,x=>x.status==='finished',r);assert.equal(m.result.winner,'light');assert.equal(m.cards[f.light].zone,'table');assert.equal(inserts.insertsIn(m,'dark')[0].revealed,false)});
test('corrupt declarations and reveal continuations reject before command mutation',()=>{const f=installed();let m=atPhase(f.m,'dark','activate');m=step(m,'core:declare-activation');m=seek(m,x=>x.stack.at(-1)?.handler==='core:activation-amount');m=step(m,'core:activation-amount:2');for(const change of [x=>x.side='light',x=>x.count=999,x=>x.remaining=.5,x=>x.turn=999,x=>x.done=true]){const bad=clone(m);change(bad.data.normalActivation);assert.throws(()=>prompt(bad));}for(const change of [x=>x.side='light',x=>x.ref.version++,x=>x.card='missing']){const bad=clone(m);change(bad.stack.find(f=>f.action?.handler==='insert:result').action.payload);assert.throws(()=>prompt(bad));}});
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/insert-timing-results.json',import.meta.url)));
for(const row of oracle)test('executed GEMP insert timing: '+JSON.stringify(row),()=>{
 const r=row.cancel?cancelling:rules,f=fixture(r),target=row.owner==='light'?'dark':'light';
 if(row.kind==='title-limit'){let m=deploy(f,row.owner,r);state.moveCard(m,f[row.owner],'hand');m=atPhase(m,target,'deploy',r);m=atPhase(m,row.owner,'deploy',r);assert.equal(prompt(m,r).choices.some(c=>c.id==='insert:deploy:'+f[row.owner]),row.again);return;}
 state.insertCard(f.m,f[row.owner],target,()=>0);inserts.insertsIn(f.m,target)[0].position=row.depth;runtime.activateForce(f.m,target,f[target],3);runtime.openWindow(f.m,'response','light');let m=seek(f.m,x=>event(x)?.kind==='insert-revealed',r);assert.deepEqual([m.players[target].force.length],row.revealedAt);if(row.cancel)m=cancelReveal(m,r);m=seek(m,x=>x.stack.length===1,r);assert.equal(m.players[target].force.length,row.activated);assert.equal(!activation.mayActivate(m,target),row.prohibited);assert.equal(m.players[row.owner].lost.includes(f[row.owner]),row.ownerLost);
});
test('insert timing receipt fingerprints both harnesses and results without opening admission',async()=>{const crypto=await import('node:crypto');const p=JSON.parse(fs.readFileSync(new URL('./gemp/insert-timing-provenance.json',import.meta.url)));for(const [file,hash]of Object.entries(p.files))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+file,import.meta.url))).digest('hex'),hash);assert.equal(p.observations,oracle.length);assert.equal(p.unchangedProductionFiles,6820);assert.equal(premiereRules.supports('1_42'),false);assert.equal(premiereRules.supports('1_208'),false)});

test('Stew bonus declares its text bound without leaking the short inserted Reserve count',()=>{
 const f=fixture();for(const bp of ['1_2','1_22']){const id=pull(f.m,'light',bp,'table');f.m.cards[id].location=f.m.locations.find(id=>f.m.cards[id].owner==='light');}
 const stew=pull(f.m,'light','1_72');for(const id of f.m.players.light.reserve.slice(3))state.moveCard(f.m,id,'used');state.insertCard(f.m,f.dark,'light',()=>0);inserts.insertsIn(f.m,'light')[0].position=3;
 let m=atPhase(f.m,'dark','control');if(prompt(m).side!=='light')m=step(m,'pass');m=step(m,'stew:play:'+stew);m=seek(m,x=>x.stack.at(-1)?.handler==='stew:amount');assert.equal(m.players.light.reserve.length,1);assert.ok(prompt(m).choices.some(c=>c.id==='stew:amount:2'));assert.equal(runtime.project(m,rules,'light').players.light.counts.reserve,null);m=step(m,'stew:amount:2');assert.equal(event(m)?.kind,'insert-revealed');m=seek(m,x=>x.stack.length===1);assert.equal(m.players.light.force.length,3);assert.equal(m.cards[f.dark].zone,'lost');assert.equal(m.cards[stew].zone,'lost');
});
test('a canceled pending reveal retires the insert without leaving a blocked Reserve',()=>{const f=installed();runtime.activateForce(f.m,'dark',f.dark,3);runtime.openWindow(f.m,'response','light');let m=seek(f.m,x=>event(x)?.kind==='insert-revealed');m.stack.find(f=>f.action?.handler==='insert:result').cancelled=true;m=seek(m,x=>x.stack.length===1);assert.equal(m.players.dark.force.length,3);assert.equal(m.cards[f.light].zone,'lost');assert.equal(inserts.insertsIn(m,'dark').length,0);assert.equal(activation.mayActivate(m,'dark'),true)});
