import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {load} from '../native-proof/load-engine.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url));
const runtime=mod('runtime'),state=mod('state'),inserts=mod('reserve-inserts'),peek=mod('reserve-peek'),{premiereRules}=mod('premiere-rules');
const manifest=JSON.parse(fs.readFileSync(new URL('../../data/native-proof/manifest.json',import.meta.url))),clone=x=>structuredClone(x);
const rules={...premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true};
function prompt(m){const p=runtime.prompt(m,rules,'dark');return p&&runtime.prompt(m,rules,p.side)}
function step(m,id){const before=clone(m),p=prompt(m),next=runtime.applyCommand(clone(m),rules,p.side,{revision:m.revision,choice:id},()=>0);assert.deepEqual(m,before);for(const s of ['light','dark'])assert.deepEqual(runtime.project(next,rules,s),runtime.project(clone(next),rules,s));return next}
function seek(m,check){for(let n=0;n<800;n++){if(check(m))return m;const p=prompt(m);assert.ok(p);m=step(m,p.mandatory?p.choices[0].id:'pass')}throw Error('Boundary missing')}
function pull(m,side,bp,zone='hand'){const id=m.players[side].reserve.find(id=>m.cards[id].blueprint===bp);assert.ok(id,bp);state.moveCard(m,id,zone);return id}
function fixture(destiny=0,adjacent=false,secondDepth=1){let m=runtime.createMatch('insert-response',60,manifest.decks.map(d=>({side:d.side,cards:[...(d.side==='light'?['4_16','1_42','1_109']:['5_149','1_267']),...d.main].slice(0,60)})),rules);for(const side of ['light','dark']){const site=pull(m,side,side==='light'?'1_129':'1_284','table');m.locations.push(site);const hero=pull(m,side,side==='light'?'101_2':'101_5','table');m.cards[hero].location=m.locations[0]}
 const anger=pull(m,'light','4_16'),second=pull(m,'light','1_42'),telepathy=pull(m,'dark','5_149'),lsSense=pull(m,'light','1_109'),dsSense=pull(m,'dark','1_267');
 state.insertCard(m,anger,'dark',()=>0);if(adjacent)state.insertCard(m,second,'dark',()=>0);const entries=inserts.insertsIn(m,'dark');entries.sort((a,b)=>a.card.id===anger?-1:b.card.id===anger?1:0);inserts.saveInserts(m,entries);for(const x of entries)x.position=x.card.id===second?secondDepth:1;
 const dsTop=m.players.dark.reserve.find(id=>Number(mod('board').cardDefinition(m,id).stats.destiny)===destiny),lsTop=m.players.light.reserve.find(id=>Number(mod('board').cardDefinition(m,id).stats.destiny)===0);assert.ok(dsTop);assert.ok(lsTop);const dummy=m.players.dark.reserve.find(id=>id!==dsTop);m.players.dark.reserve=[dummy,dsTop,...m.players.dark.reserve.filter(id=>![dummy,dsTop].includes(id))];m.players.light.reserve=[lsTop,...m.players.light.reserve.filter(id=>id!==lsTop)];
 m=runtime.startTurns(m,rules);runtime.activateForce(m,'dark',dsSense,1);runtime.openWindow(m,'response','light');m=seek(m,x=>x.stack.at(-1)?.event?.kind==='insert-revealed');return {m,anger,second,telepathy,lsSense,dsSense,dsTop,lsTop}}
function play(m,card,prefix){m=seek(m,x=>prompt(x).choices.some(c=>c.id.startsWith(prefix)&&c.id.includes(card)));return step(m,prompt(m).choices.find(c=>c.id.startsWith(prefix)&&c.id.includes(card)).id)}
function chain(f){let m=play(f.m,f.telepathy,'telepathy:play:');m=play(m,f.lsSense,'cancel:play:');return play(m,f.dsSense,'cancel:play:')}
for(const destiny of [0,6])for(const adjacent of [false,true])test('nested Sense draws beneath pending insert: destiny '+destiny+', adjacent '+adjacent,()=>{const f=fixture(destiny,adjacent);let m=chain(f),before=m.players.dark.reserve.length;m=seek(m,x=>x.cards[f.dsSense].zone==='used');assert.equal(m.players.dark.reserve.length,before-1);assert.equal(m.cards[f.dsTop].zone,'used');assert.equal(inserts.insertsIn(m,'dark')[0].revealed,true);assert.equal(m.cards[f.anger].zone,'table');assert.equal(inserts.insertsIn(m,'dark').find(x=>x.card.id===f.second)?.revealed,adjacent?false:undefined);m=seek(m,x=>x.stack.length===1);assert.equal(m.cards[f.telepathy].zone,destiny===0?'used':'lost');assert.equal(m.cards[f.lsSense].zone,destiny===0?'lost':'used');assert.equal(m.data.angerObligations?.length??0,destiny===0?0:1);assert.equal(m.cards[f.anger].zone,'lost');assert.equal(m.cards[f.second].zone,adjacent?'lost':'hand');assert.equal(inserts.insertsIn(m,'dark').length,0)});
test('an unrevealed exposed insert still blocks movement atomically',()=>{const f=fixture(),m=clone(f.m);inserts.insertsIn(m,'dark')[0].revealed=false;const before=clone(m);assert.throws(()=>state.moveTop(m,'dark','reserve','destiny'),/exposed insert/);assert.deepEqual(m,before)});

for(const to of ['force','hand','lost','used','destiny'])test('a valid response can move an ordinary card to '+to+' while the revealed insert stays on table',()=>{const f=fixture(),m=clone(f.m),top=m.players.dark.reserve[0],before=m.players.dark.reserve.length;state.moveTop(m,'dark','reserve',to);state.assertState(m);assert.equal(m.cards[top].zone,to);assert.equal(m.cards[f.anger].zone,'table');assert.equal(inserts.insertsIn(m,'dark')[0].revealed,true);assert.equal(m.players.dark.reserve.length,before-1);assert.ok(!m.players.dark[to].includes(f.anger))});
for(const depth of [2,4])test('a response exposes a later insert only after the original reveal finishes: depth '+depth,()=>{const f=fixture(0,true,depth);let m=chain(f);m=seek(m,x=>x.cards[f.dsSense].zone==='used');const second=inserts.insertsIn(m,'dark').find(x=>x.card.id===f.second);assert.equal(second.revealed,false);assert.equal(second.position,depth-2);assert.equal(m.cards[f.anger].zone,'table');m=seek(m,x=>x.stack.length===1);assert.equal(m.cards[f.anger].zone,'lost');assert.equal(m.cards[f.second].zone,depth===2?'lost':'table')});
test('ordinary top additions during a response do not erase the pending reveal or its bound cancellation',()=>{const f=fixture();let m=chain(f);const added=m.players.dark.force[0];state.moveCard(m,added,'reserve');const before=clone(m);assert.equal(inserts.insertsIn(m,'dark')[0].revealed,true);assert.equal(runtime.project(m,rules,'dark').inserts[0].card.id,f.anger);m=seek(m,x=>x.stack.length===1);assert.equal(m.cards[f.anger].zone,'lost');assert.equal(m.cards[added].zone,'used')});
test('concession during the nested response preserves every pending card and continuation',()=>{const f=fixture();const m=chain(f),before=clone(m);const done=step(m,'concede');assert.equal(done.status,'finished');assert.deepEqual(done.players,before.players);assert.deepEqual(done.stack,before.stack);assert.deepEqual(done.cards,before.cards)});
test('complete native admission stays closed',()=>assert.equal(premiereRules.supports('4_16'),false));

for(const adjacent of [false,true])test('a nested peek keeps the resolving insert separate from newly encountered inserts: '+adjacent,()=>{const f=fixture(0,adjacent),m=clone(f.m),snapshot=peek.peekReserve(m,'dark',3);assert.equal(snapshot.cards.length,3);assert.equal(snapshot.inserts.some(x=>x.id===f.anger),false);assert.equal(snapshot.inserts.length,adjacent?1:0);peek.assertReservePeek(m,clone(snapshot));peek.returnReservePeek(m,snapshot);state.assertState(m);assert.equal(inserts.insertsIn(m,'dark')[0].position,0);assert.equal(inserts.insertsIn(m,'dark')[0].revealed,true);if(adjacent)assert.equal(inserts.insertsIn(m,'dark')[1].position,3)});
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/insert-response-results.json',import.meta.url))),receipt=JSON.parse(fs.readFileSync(new URL('./gemp/insert-response-provenance.json',import.meta.url)));
for(const [index,row]of oracle.entries())test('executed insert response '+index+' with explicit ordinary-card adjudication',()=>{
 const f=fixture(row.destiny,row.adjacent);if(row.covered)state.moveCard(f.m,f.dsTop,'reserve');let m=chain(f),before=m.players.dark.reserve.length;const reveals=new Set([f.anger]);
 const watched=check=>x=>{if(x.stack.at(-1)?.event?.kind==='insert-revealed')reveals.add(x.stack.at(-1).event.card);return check(x)};
 m=seek(m,watched(x=>x.cards[f.dsSense].zone==='used'));const actual={kind:'sense-chain',destiny:row.destiny,adjacent:row.adjacent,covered:row.covered,darkOrdinaryDraws:before-m.players.dark.reserve.length,firstRemainedPendingDuringDraw:inserts.insertsIn(m,'dark').some(x=>x.card.id===f.anger&&x.revealed),secondStayedHiddenDuringDraw:row.adjacent?!inserts.insertsIn(m,'dark').find(x=>x.card.id===f.second).revealed:true};
 m=seek(m,watched(x=>['used','lost'].includes(x.cards[f.telepathy].zone)));Object.assign(actual,{lightSenseLost:m.cards[f.lsSense].zone==='lost',telepathyUsed:m.cards[f.telepathy].zone==='used',angerInDarkUsed:m.players.dark.used.includes(f.anger),angerInLightUsed:m.players.light.used.includes(f.anger),angerLost:m.cards[f.anger].zone==='lost',revealsAtTelepathyCompletion:reveals.size});
 if(row.covered)assert.deepEqual(actual,row);else{assert.ok(receipt.adjudication.differingObservationIndices.includes(index));assert.equal(actual.darkOrdinaryDraws,1);assert.equal(row.darkOrdinaryDraws,0);assert.equal(actual.firstRemainedPendingDuringDraw,true);assert.equal(row.firstRemainedPendingDuringDraw,false);assert.equal(actual.angerInDarkUsed,false);assert.equal(row.angerInDarkUsed,true);assert.equal(actual.secondStayedHiddenDuringDraw,true);assert.equal(actual.telepathyUsed,row.destiny===0)}
});
test('insert response evidence fingerprints the reference and explicit differences',async()=>{const crypto=await import('node:crypto');for(const[file,hash]of Object.entries(receipt.files))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+file,import.meta.url))).digest('hex'),hash);assert.equal(oracle.length,8);assert.equal(receipt.observations,8);assert.equal(receipt.adjudication.differingObservations,4);assert.equal(receipt.unchangedProductionFiles,6820)});
