import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {load} from '../native-proof/load-engine.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url));
const runtime=mod('runtime'),state=mod('state'),board=mod('board'),battle=mod('battle'),weapon=mod('weapon-state'),immunity=mod('combat-modifiers');
const rules={...mod('premiere-rules').premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true};
const clone=x=>JSON.parse(JSON.stringify(x));
function fresh(){return runtime.createMatch('sabers',60,['light','dark'].map(side=>({side,cards:[...(side==='light'?['1_155','1_155','1_157','1_21','9_24','1_19','1_19','1_152','1_31','1_6','1_105','1_115','1_115','1_109','1_129','1_132','1_124','1_109']:['1_262','1_262','1_324','1_168','101_5','1_267','1_267','1_317','1_284','1_285','1_317']),...Array(60).fill(side==='light'?'1_28':'1_194')].slice(0,60)})),rules)}
function pull(m,side,bp,zone='table',location){const c=Object.values(m.cards).find(c=>c.owner===side&&c.blueprint===bp&&c.zone==='reserve');assert.ok(c,bp);state.moveCard(m,c.id,zone);if(location)c.location=location;return c.id}
function prompt(m){const p=runtime.prompt(m,rules,'dark');return p&&runtime.prompt(m,rules,p.side)}
const ids=m=>prompt(m).choices.map(c=>c.id);
function step(m,id){const before=clone(m);const r=runtime.applyCommand(clone(m),rules,prompt(m).side,{revision:m.revision,choice:id},()=>0);assert.deepEqual(m,before);state.assertState(r);for(const s of ['dark','light'])assert.deepEqual(runtime.project(r,rules,s),runtime.project(clone(r),rules,s));return r}
function seek(m,f){for(let n=0;n<500;n++){if(f(m))return m;const p=prompt(m);assert.ok(p,'no prompt');const cs=p.choices.map(c=>c.id);m=step(m,cs.includes('pass')?'pass':cs.includes('skip-destiny')?'skip-destiny':cs[0])}throw Error('unreached boundary')}
const boundary=(m,kind)=>seek(m,x=>x.stack.at(-1)?.event?.kind===kind);
const priority=(m,side)=>prompt(m).side===side?m:step(m,'pass');
function fixture(bp='1_324',phase='battle',armed=true,siteBp='1_129'){
 let m=fresh();const side=bp==='1_324'?'dark':'light',site=pull(m,'light',siteBp);m.locations.push(site);
 const host=pull(m,side,side==='dark'?'1_168':'1_21','table',site),target=pull(m,side==='dark'?'light':'dark',side==='dark'?'1_19':'101_5','table',site),saber=pull(m,side,bp,armed?'table':'hand');
 if(armed){m.cards[saber].attachedTo=host;m.cards[saber].location=site}
 for(const s of ['light','dark'])for(let i=0;i<10;i++)state.moveCard(m,m.players[s].reserve.at(-1),'force');
 m=runtime.startTurns(m,rules);m=seek(m,x=>x.turn.side===side&&x.turn.phase===phase&&x.stack.length===1);return{m,side,site,host,target,saber};
}
function drawCards(f,values){const m=f.m;for(const id of [...m.players[f.side].reserve])state.moveCard(m,id,'hand');for(const v of [...values].reverse()){const bp=f.side==='dark'?({0:'1_285',1:'1_194',3:'1_317',5:'1_262'})[v]:({0:'1_124',1:'1_28',2:'1_155',3:'1_109',4:'1_105',5:'1_115'})[v];const c=Object.values(m.cards).find(c=>c.owner===f.side&&c.blueprint===bp&&c.zone==='hand');assert.ok(c,'draw '+v);state.moveCard(m,c.id,'reserve')}}
function fire(f,values){drawCards(f,values);let m=boundary(step(f.m,'battle:'+f.site),'battle-weapons');m=priority(m,f.side);m=step(m,'saber:fire:'+f.saber+':'+f.target);return boundary(m,'weapon-fired')}
for(const [bp,values,hit,zero] of [['1_324',[1,3],false,false],['1_324',[3,3],true,true],['1_324',[5],true,true],['1_157',[1,2],false,false],['1_157',[4,5],true,true],['1_155',[4,5],true,false]])test('two-destiny lightsaber '+bp+' '+values,()=>{const f=fixture(bp);const initial=board.forfeit(f.m,f.target);let m=fire(f,values);assert.equal(battle.battle(m).hits.includes(f.target),hit);assert.equal(board.forfeit(m,f.target),zero?0:initial);assert.equal(battle.battle(m).saberShots[0].draws.length,2);assert.equal(battle.battle(m).saberShots[0].total,values.reduce((a,b)=>a+b,0));m=boundary(m,'battle-weapons');assert.ok(!ids(priority(m,f.side)).some(x=>x.startsWith('saber:fire:'+f.saber)))});
test('location bonus applies independently to both weapon draws',()=>{const f=fixture('1_324','battle',true,'1_132');const m=fire(f,[1,3]);assert.equal(battle.battle(m).saberShots[0].total,6);assert.equal(board.forfeit(m,f.target),0)});
for(const bp of ['1_155','1_157','1_324'])test('deployment observes matching host and current cost '+bp,()=>{const f=fixture(bp,'deploy',false);const before=f.m.players[f.side].force.length,cost=bp==='1_155'?1:0;const a=ids(f.m).filter(id=>id.startsWith('saber:equip:'+f.saber));assert.deepEqual(a,['saber:equip:'+f.saber+':'+f.host]);const m=seek(step(f.m,a[0]),x=>x.cards[f.saber].zone==='table');assert.equal(m.cards[f.saber].attachedTo,f.host);assert.equal(before-m.players[f.side].force.length,cost)});
test('generic lightsaber transfer pays destination ability cost',()=>{const f=fixture('1_155','deploy');const troop=pull(f.m,'light','1_28','table',f.site);const before=f.m.players.light.force.length;const m=seek(step(f.m,'saber:equip:'+f.saber+':'+troop),x=>x.cards[f.saber].attachedTo===troop);assert.equal(before-m.players.light.force.length,6)});
test('generic deployment ability cost changes with current ability and insufficient Force suppresses action',()=>{const f=fixture('1_155','deploy',false);while(f.m.players.light.force.length>0)state.moveCard(f.m,f.m.players.light.force[0],'used');assert.ok(!ids(f.m).includes('saber:equip:'+f.saber+':'+f.host));mod('ability').addAbilityModifier(f.m,f.site,f.host,'add',2);assert.ok(ids(f.m).includes('saber:equip:'+f.saber+':'+f.host))});
test('forfeit reset survives source loss and next turn, expires on target departure',()=>{const f=fixture();let m=fire(f,[3,3]);state.moveCard(m,f.saber,'lost');m.turn.number++;assert.equal(board.forfeit(m,f.target),0);state.moveCard(m,f.target,'hand');state.moveCard(m,f.target,'table');m.cards[f.target].location=f.site;assert.equal(board.forfeit(m,f.target),7)});
test('Talz restores hit status and weapon forfeit reset together',()=>{const f=fixture();const talz=pull(f.m,'light','1_31','table',f.site);let m=boundary(fire(f,[3,3]),'battle-damage');m=step(priority(m,'light'),'rescue:'+talz+':'+f.target);m=seek(m,x=>!battle.battle(x).hits.includes(f.target));assert.equal(m.cards[talz].zone,'lost');assert.equal(board.forfeit(m,f.target),7)});
test('zero-forfeit hit still must be forfeited and pays neither loss balance',()=>{const f=fixture();let m=boundary(fire(f,[3,3]),'battle-damage');const b=battle.battle(m),damage=b.damage.light,attrition=b.attrition.light;m=step(priority(m,'light'),'forfeit:'+f.target);m=seek(m,x=>x.cards[f.target].zone==='lost');assert.equal(battle.battle(m).damage.light,damage);assert.equal(battle.battle(m).attrition.light,attrition)});
function drainFixture(bp='1_324'){const f=fixture(bp,'control');state.moveCard(f.m,f.target,'hand');return f}
function drainStart(f){return seek(step(f.m,'drain:'+f.site),m=>m.stack.at(-2)?.action?.handler==='ground:drain'&&!m.stack.at(-2).awaitingResponses&&m.stack.at(-1)?.event===undefined)}
for(const use of [false,true])test('Force-drain enhancement is optional '+use,()=>{const f=drainFixture();const base=board.drainAmount(f.m,f.side,f.site);let m=priority(drainStart(f),f.side);assert.ok(ids(m).includes('saber:drain:'+f.saber));if(use)m=step(m,'saber:drain:'+f.saber);m=seek(m,x=>x.stack.at(-1)?.handler==='ground:force-loss');assert.equal(m.stack.at(-1).payload.remaining,base+(use?1:0));assert.equal(!!m.data.weaponUse,use)});
test('using lightsaber for drain blocks a different weapon but allows the same saber in battle',()=>{const f=drainFixture();let m=step(priority(drainStart(f),f.side),'saber:drain:'+f.saber);m=boundary(m,'force-drain-enhanced');assert.equal(weapon.canUseWeapon(m,f.saber),true);const gun=pull(m,'dark','1_317');m.cards[gun].attachedTo=f.host;m.cards[gun].location=f.site;assert.equal(weapon.canUseWeapon(m,gun),false)});
test('a drain cannot use the same saber twice and generic duplicates are noncumulative',()=>{const f=drainFixture('1_155'),second=pull(f.m,'light','1_155'),troop=pull(f.m,'light','1_28','table',f.site);f.m.cards[second].attachedTo=troop;f.m.cards[second].location=f.site;const base=board.drainAmount(f.m,'light',f.site);let m=step(priority(drainStart(f),'light'),'saber:drain:'+f.saber);m=seek(m,x=>x.stack.at(-2)?.action?.handler==='ground:drain'&&x.stack.at(-1)?.event===undefined);m=priority(m,'light');assert.ok(!ids(m).includes('saber:drain:'+f.saber));m=step(m,'saber:drain:'+second);m=seek(m,x=>x.stack.at(-1)?.handler==='ground:force-loss');assert.equal(m.stack.at(-1).payload.remaining,base+1)});
test('Jedi Luke gains power and both immunity branches from an attached lightsaber',()=>{const f=fixture('1_155');const luke=pull(f.m,'light','9_24','table',f.site);f.m.cards[f.saber].attachedTo=luke;assert.equal(board.power(f.m,luke),8);assert.equal(immunity.attritionImmunity(f.m,luke),6);state.moveCard(f.m,f.host,'hand');assert.equal(immunity.attritionImmunity(f.m,luke),7);state.moveCard(f.m,f.saber,'hand');assert.equal(board.power(f.m,luke),6);assert.equal(immunity.attritionImmunity(f.m,luke),6)});
test('tampered shot and drain records are rejected and private reset registry stays private',()=>{const f=fixture();const m=fire(f,[3,3]);const bad=clone(m);bad.data.battle.saberShots[0].weapon=f.target;assert.throws(()=>prompt(bad),/lightsaber|destiny scope/);const b=clone(m);b.data.forfeitResets[0].value=-1;assert.throws(()=>prompt(b),/forfeit/);assert.ok(!JSON.stringify(runtime.project(m,rules,'light')).includes('forfeitResets'));const d=drainFixture();const dm=drainStart(d);dm.stack.at(-2).action.payload.saberBonus=[d.saber];assert.throws(()=>prompt(dm),/drain grants/)});
function initiated(f){drawCards(f,[3,3]);return step(priority(boundary(step(f.m,'battle:'+f.site),'battle-weapons'),f.side),'saber:fire:'+f.saber+':'+f.target)}
test('a canceled firing consumes usage but causes no draws, hit, or reset',()=>{const f=fixture();let m=initiated(f);m.stack.find(x=>x.action?.handler==='saber:fire').cancelled=true;m=boundary(m,'battle-weapons');assert.equal(battle.battle(m).saberShots[0].outcome,'canceled');assert.equal(battle.battle(m).saberShots[0].draws.length,0);assert.equal(board.forfeit(m,f.target),7);assert.ok(!ids(priority(m,f.side)).includes('saber:fire:'+f.saber+':'+f.target))});
test('preventing the about-to-hit result prevents the associated forfeit reset',()=>{const f=fixture();let m=boundary(initiated(f),'about-to-hit');assert.equal(board.forfeit(m,f.target),7);m.stack.find(x=>x.action?.handler==='saber:hit').cancelled=true;m=boundary(m,'weapon-fired');assert.equal(battle.battle(m).hits.includes(f.target),false);assert.equal(board.forfeit(m,f.target),7)});
test('emptying Reserve after firing initiation completes two failed draws without a hit',()=>{const f=fixture();let m=initiated(f);for(const id of [...m.players.dark.reserve])state.moveCard(m,id,'hand');m=boundary(m,'weapon-fired');assert.equal(battle.battle(m).saberShots[0].total,null);assert.equal(board.forfeit(m,f.target),7)});
test('one permitted physical draw leaves the second skipped and preserves the successful total',()=>{const f=fixture();let m=boundary(initiated(f),'about-to-draw-destiny');const shot=battle.battle(m).saberShots[0];mod('destiny-limits').setDestinyLimit(m,shot.scope,1);m=boundary(m,'weapon-fired');assert.equal(battle.battle(m).saberShots[0].total,3);assert.equal(battle.battle(m).saberShots[0].draws[1].skipped,'limit');assert.equal(m.players.dark.reserve.length,1)});
test('live target ability is compared after both draws and responses',()=>{const f=fixture();let m=boundary(initiated(f),'destiny-total');mod('ability').addAbilityModifier(m,f.site,f.target,'add',3);m=boundary(m,'weapon-fired');assert.equal(battle.battle(m).saberShots[0].defense,7);assert.equal(battle.battle(m).saberShots[0].outcome,'miss')});
test('deploying on an original host which departed and returned fails without refund',()=>{const f=fixture('1_155','deploy',false);let m=step(f.m,'saber:equip:'+f.saber+':'+f.host);const remaining=m.players.light.force.length;state.moveCard(m,f.host,'hand');state.moveCard(m,f.host,'table');m.cards[f.host].location=f.site;m=seek(m,x=>x.cards[f.saber].zone==='lost');assert.equal(m.players.light.force.length,remaining)});
test('nonempty drain response and weapon continuation remain available after round-trip serialization',()=>{const f=drainFixture();let m=priority(clone(drainStart(f)),f.side);assert.ok(ids(m).includes('saber:drain:'+f.saber));m=step(m,'saber:drain:'+f.saber);m=clone(boundary(m,'force-drain-enhanced'));m=seek(m,x=>x.stack.at(-1)?.handler==='ground:force-loss');assert.equal(m.stack.at(-1).payload.remaining,2)});
for(const cancel of [false,true])test('lightsaber deployment as a CZ-3 battle react, canceled '+cancel,()=>{const f=fixture('1_155','battle',false);pull(f.m,'light','1_6','table',f.site);f.m.turn.side='dark';f.m.stack[0].priority='dark';let m=seek(step(f.m,'battle:'+f.site),x=>x.stack.at(-2)?.action?.handler==='battle:begin'&&!x.stack.at(-2).awaitingResponses&&x.stack.at(-1)?.event===undefined);m=priority(m,'light');const choice='saber:equip:'+f.saber+':'+f.host+':react';assert.ok(ids(m).includes(choice));m=step(m,choice);if(cancel)m.stack.find(x=>x.action?.handler==='saber:equip').cancelled=true;m=seek(m,x=>x.cards[f.saber].zone===(cancel?'hand':'table'));assert.equal(m.cards[f.saber].attachedTo,cancel?undefined:f.host);assert.ok(mod('ground').usage(m).reacted.includes(f.saber))});
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/lightsaber-results.json',import.meta.url)));
for(const row of oracle)test('executed GEMP lightsaber comparison '+row.name,()=>{
 const match=/^(1_\d+)-(\d+)-(-?\d+)$/.exec(row.name);
 if(match){const f=fixture(match[1]);const values=[Number(match[2]),Number(match[3])].filter(v=>v>=0),before=f.m.players[f.side].force.length;const m=fire(f,values);assert.deepEqual({name:row.name,hit:battle.battle(m).hits.includes(f.target),forfeit:board.forfeit(m,f.target),spent:before-m.players[f.side].force.length-1},row);return}
 if(row.name.startsWith('deploy-')){const f=fixture(row.name.slice(7),'deploy',false),before=f.m.players[f.side].force.length;const m=seek(step(f.m,'saber:equip:'+f.saber+':'+f.host),x=>x.cards[f.saber].zone==='table');assert.deepEqual({name:row.name,spent:before-m.players[f.side].force.length},row);return}
 if(row.name.startsWith('luke-')){const f=fixture('1_155');const luke=pull(f.m,'light','9_24','table',f.site);f.m.cards[f.saber].attachedTo=luke;if(row.name==='luke-alone-armed')state.moveCard(f.m,f.host,'hand');assert.deepEqual({name:row.name,power:board.power(f.m,luke),immunity:immunity.attritionImmunity(f.m,luke)},row);return}
 if(row.name==='talz-restored'){const f=fixture();const talz=pull(f.m,'light','1_31','table',f.site);let m=boundary(fire(f,[3,3]),'battle-damage');m=seek(step(priority(m,'light'),'rescue:'+talz+':'+f.target),x=>!battle.battle(x).hits.includes(f.target));assert.deepEqual({name:row.name,forfeit:board.forfeit(m,f.target),talzLost:m.cards[talz].zone==='lost'},row);return}
 const dup=row.name==='drain-duplicates',f=drainFixture(dup?'1_155':'1_324');let second;if(dup){second=pull(f.m,'light','1_155');const troop=pull(f.m,'light','1_28','table',f.site);f.m.cards[second].attachedTo=troop;f.m.cards[second].location=f.site}let m=priority(drainStart(f),f.side);
 if(row.name!=='drain-skip'){m=step(m,'saber:drain:'+f.saber);if(dup){m=seek(m,x=>x.stack.at(-2)?.action?.handler==='ground:drain'&&x.stack.at(-1)?.event===undefined);m=step(priority(m,f.side),'saber:drain:'+second)}}
 m=seek(m,x=>x.stack.at(-1)?.handler==='ground:force-loss');assert.deepEqual({name:row.name,total:m.stack.at(-1).payload.remaining},row);
});

for(const bp of ['1_155','1_157','1_324'])test('empty Reserve does not prohibit lightsaber initiation: '+bp,()=>{
 const f=fixture(bp);drawCards(f,[]);const force=f.m.players[f.side].force.length,initialForfeit=board.forfeit(f.m,f.target);
 const m=fire(f,[]),shot=battle.battle(m).saberShots[0];
 assert.deepEqual(shot.draws.map(d=>d.value),[null,null]);assert.equal(shot.total,null);assert.equal(shot.outcome,'miss');
 assert.equal(board.forfeit(m,f.target),initialForfeit);assert.equal(battle.battle(m).hits.includes(f.target),false);
 assert.equal(m.players[f.side].force.length,force-1-(bp==='1_155'?1:0));
 assert.ok(battle.battle(m).fired.includes(f.saber));
});
