import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {load} from '../native-proof/load-engine.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url));
const runtime=mod('runtime'),state=mod('state'),board=mod('board'),battle=mod('battle'),stats=mod('stat-modifiers'),medics=mod('medics');
const rules={...mod('premiere-rules').premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true};
const clone=x=>JSON.parse(JSON.stringify(x));
function fresh(){return runtime.createMatch('medics',60,['light','dark'].map(side=>({side,cards:[...(side==='light'?['8_5','3_9','3_9','3_60','3_59','1_129','1_132','1_19','1_100','1_152','1_6','1_5']:['1_284','1_168','1_324','13_86','1_267','1_317','1_317']),...Array(60).fill(side==='light'?'1_28':'1_194')].slice(0,60)})),rules)}
function pull(m,side,bp,zone='table',location){const c=Object.values(m.cards).find(c=>c.owner===side&&c.blueprint===bp&&c.zone==='reserve');assert.ok(c,bp);state.moveCard(m,c.id,zone);if(location)c.location=location;return c.id}
function prompt(m){const p=runtime.prompt(m,rules,'dark');return p&&runtime.prompt(m,rules,p.side)}
const ids=m=>prompt(m).choices.map(c=>c.id);
function step(m,id){const before=clone(m);const r=runtime.applyCommand(clone(m),rules,prompt(m).side,{revision:m.revision,choice:id},()=>0);assert.deepEqual(m,before);state.assertState(r);for(const side of ['light','dark'])assert.deepEqual(runtime.project(r,rules,side),runtime.project(clone(r),rules,side));return r}
function seek(m,f){for(let n=0;n<600;n++){if(f(m))return m;const cs=ids(m);m=step(m,cs.includes('pass')?'pass':cs.includes('skip-destiny')?'skip-destiny':cs[0])}throw Error('unreached boundary')}
const boundary=(m,kind)=>seek(m,x=>x.stack.at(-1)?.event?.kind===kind);
const priority=(m,side)=>prompt(m).side===side?m:step(m,'pass');
const phase=(m,side,phase)=>seek(m,x=>x.turn.side===side&&x.turn.phase===phase&&x.stack.length===1&&prompt(x).side===side);
function fixture(noFX=false){let m=fresh();const site=pull(m,'light','1_129');m.locations.push(site);const medic=pull(m,'light','8_5','table',site),troop=pull(m,'light','1_28','table',site),second=pull(m,'light','1_28','table',site),fx=pull(m,'light','3_9',noFX?'hand':'table',noFX?undefined:site);for(let i=0;i<10;i++)pull(m,'dark','1_194','table',site);for(const side of ['light','dark'])for(let i=0;i<12;i++)state.moveCard(m,m.players[side].reserve.at(-1),'force');m=phase(runtime.startTurns(m,rules),'dark','battle');return{m,site,medic,troop,second,fx}}
const damage=f=>priority(boundary(step(f.m,'battle:'+f.site),'battle-damage'),'light');
const forfeit=(m,id)=>boundary(step(priority(m,'light'),'forfeit:'+id),'forfeited');
const recovery=(f,target=f.troop)=>'medic:recover:'+f.medic+':'+target;
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/delevar-results.json',import.meta.url)));
const observed=name=>{const row=oracle.find(r=>r.name===name);assert.ok(row,name);return row};
for(const mode of ['use','skip','self','no-fx','fx-lost','source-leaves','target-leaves'])test('executed Delevar recovery '+mode,()=>{
 const f=fixture(mode==='no-fx');let m=damage(f);const target=mode==='self'?f.medic:mode==='fx-lost'?f.fx:f.troop,before=battle.battle(m).damage.light,fv=board.forfeit(m,target);m=priority(forfeit(m,target),'light');const offered=ids(m).includes(recovery(f,target)),force=m.players.light.force.length;
 if(offered&&mode!=='skip'){m=step(m,recovery(f,target));if(mode==='source-leaves')state.moveCard(m,f.medic,'hand');if(mode==='target-leaves')state.moveCard(m,target,'hand');m=seek(m,x=>x.cards[target].zone==='used'||!x.stack.some(f=>f.kind==='resolution'&&f.action.handler.startsWith('medic:')))}
 assert.deepEqual({name:'recovery-'+mode,offered,used:m.cards[target].zone==='used',lost:m.cards[target].zone==='lost',paid:before-battle.battle(m).damage.light,forfeit:fv,forceSpent:force-m.players.light.force.length},observed('recovery-'+mode));
});
for(const mode of ['same','other','opponent','lab-hoth','lab-tatooine','away-hoth'])test('executed Delevar protection '+mode,()=>{
 const f=fixture();const m=f.m;let target=f.troop;const other=pull(m,'dark','1_284');m.locations.push(other);
 if(mode==='opponent')target=Object.values(m.cards).find(c=>c.owner==='dark'&&c.zone==='table'&&c.blueprint==='1_194').id;
 if(mode==='other')m.cards[f.medic].location=other;
 if(mode.includes('hoth')||mode.startsWith('lab')){const lab=pull(m,'light','3_60'),hoth=pull(m,'light','3_59');m.locations.push(lab,hoth);if(mode!=='away-hoth')m.cards[f.medic].location=lab;if(mode!=='lab-tatooine')m.cards[target].location=hoth;}
 stats.addStatModifier(m,other,target,'forfeit','add',-1);assert.deepEqual({name:'protection-'+mode,forfeit:board.forfeit(m,target)},observed('protection-'+mode));
});
test('Corporal Delevar can deploy for printed cost and establishes protection on arrival',()=>{const f=fixture();state.moveCard(f.m,f.medic,'hand');let m=phase(f.m,'light','deploy');stats.addStatModifier(m,f.site,f.troop,'forfeit','add',-1);assert.equal(board.forfeit(m,f.troop),1);const before=m.players.light.force.length;m=boundary(step(m,'deploy:'+f.medic+':'+f.site),'deployed');assert.equal(before-m.players.light.force.length,2);assert.equal(board.forfeit(m,f.troop),2);assert.equal(mod('characteristics').hasCharacteristic(m,f.medic,'SCOUT'),true)});
test('Echo docking bay and FX forfeiture components can deploy',()=>{const f=fixture();const site=pull(f.m,'light','3_59','hand');state.moveCard(f.m,f.fx,'hand');const m=phase(f.m,'light','deploy');assert.ok(ids(m).some(id=>id.startsWith('site:'+site+':')));assert.ok(ids(m).some(id=>id.startsWith('deploy:'+f.fx+':')))});
test('a different droid or adjacent FX does not satisfy with your FX droid',()=>{for(const kind of ['different','adjacent']){const f=fixture(true);if(kind==='different')pull(f.m,'light','1_6','table',f.site);else{const site=pull(f.m,'light','1_132');f.m.locations.push(site);state.moveCard(f.m,f.fx,'table');f.m.cards[f.fx].location=site}const m=priority(forfeit(damage(f),f.troop),'light');assert.ok(!ids(m).includes(recovery(f)))}});
test('once-per-turn recovery is spent at initiation, even if subsequently canceled',()=>{for(const canceled of [false,true]){const f=fixture();let m=step(priority(forfeit(damage(f),f.troop),'light'),recovery(f));if(canceled)m.stack.find(x=>x.kind==='resolution'&&x.action.handler==='medic:recover').cancelled=true;m=seek(m,x=>x.stack.at(-1)?.event?.kind==='battle-damage');m=priority(forfeit(m,f.second),'light');assert.ok(!ids(m).includes(recovery(f,f.second)));assert.equal(m.cards[f.troop].zone,canceled?'lost':'used')}});
test('declining the first recovery leaves the opportunity available for another forfeiture',()=>{const f=fixture();let m=priority(forfeit(damage(f),f.troop),'light');m=step(m,'pass');m=boundary(m,'battle-damage');m=priority(forfeit(m,f.second),'light');assert.ok(ids(m).includes(recovery(f,f.second)))});
test('recovery only moves its character; attached cards remain in Lost and payment is retained',()=>{const f=fixture();const gun=pull(f.m,'light','1_152');f.m.cards[gun].attachedTo=f.troop;f.m.cards[gun].location=f.site;let m=damage(f);const paid=battle.battle(m).damage.light;m=priority(forfeit(m,f.troop),'light');m=boundary(step(m,recovery(f)),'card-to-used');assert.equal(m.cards[f.troop].zone,'used');assert.equal(m.cards[gun].zone,'lost');assert.equal(battle.battle(m).damage.light,paid-2);assert.equal(m.players.light.used[0],f.troop);assert.ok(!battle.members(m,'light').includes(f.troop))});
test('recovery is placement, not Force retrieval, even under Secret Plans',()=>{const f=fixture();pull(f.m,'dark','13_86');let m=priority(forfeit(damage(f),f.troop),'light');const force=m.players.light.force.length;m=boundary(step(m,recovery(f)),'about-to-remove-just-lost');assert.ok(!ids(m).some(id=>id.startsWith('plans:')));m=boundary(m,'card-to-used');assert.equal(m.players.light.force.length,force);assert.equal(m.cards[f.troop].zone,'used')});
for(const during of ['opportunity','pending','removal'])test('old Lost identity cannot be reused after departure/return at '+during,()=>{const f=fixture();let m=priority(forfeit(damage(f),f.troop),'light');const ben=pull(m,'light','1_100','hand');if(during!=='opportunity')m=step(m,recovery(f));if(during==='removal')m=boundary(m,'about-to-remove-just-lost');state.moveCard(m,f.troop,'hand');state.moveCard(m,f.troop,'lost');if(during==='opportunity'){assert.ok(!ids(m).includes(recovery(f)));assert.ok(!ids(m).some(id=>id.startsWith('revival:old-ben:'+ben)))}else{m=seek(m,x=>!x.stack.some(f=>f.kind==='resolution'&&f.action.handler.startsWith('medic:')));assert.equal(m.cards[f.troop].zone,'lost')}});
test('recovering the last FX is allowed only if a second own FX remains with Delevar',()=>{const f=fixture();pull(f.m,'light','3_9','table',f.site);const m=priority(forfeit(damage(f),f.fx),'light');assert.ok(ids(m).includes(recovery(f,f.fx)))});
test('Delevar cannot use another site forfeiture, ordinary card loss, or a hand/Life Force loss',()=>{const f=fixture();const m=f.m;state.moveCard(m,f.troop,'lost');const ref=mod('identity').referenceCard(m,f.troop);const site=pull(m,'light','1_132');m.locations.push(site);for(const event of [{kind:'character-lost',card:f.troop,cardRef:ref,site:f.site},{kind:'force-lost',card:f.troop,cardRef:ref,site:f.site},{kind:'forfeited',card:f.troop,cardRef:ref,site}])assert.deepEqual(medics.medicActions(m,{kind:'window',timing:'response',event},'light'),[])});
test('usage and pending recovery survive serialization and reject forged references',()=>{const f=fixture();const m=step(priority(forfeit(damage(f),f.troop),'light'),recovery(f));medics.assertMedics(clone(m));for(const mutate of [x=>x.data.medicUses[0].turn=999,x=>x.data.medicUses[0].source.version=999,x=>x.stack.find(f=>f.kind==='resolution'&&f.action.handler==='medic:recover').action.payload.target.id=f.site]){const bad=clone(m);mutate(bad);assert.throws(()=>medics.assertMedics(bad))}for(const side of ['light','dark'])assert.ok(!JSON.stringify(runtime.project(m,rules,side)).includes('medicUses'))});
for(const late of [false,true])test('actual lightsaber forfeiture reset with Delevar '+(late?'arriving after hit':'already protecting'),()=>{const f=fixture();for(const c of Object.values(f.m.cards).filter(c=>c.zone==='table'&&c.owner==='dark'&&c.blueprint==='1_194'))state.moveCard(f.m,c.id,'hand');const vader=pull(f.m,'dark','1_168','table',f.site),saber=pull(f.m,'dark','1_324');f.m.cards[saber].attachedTo=vader;f.m.cards[saber].location=f.site;if(late)state.moveCard(f.m,f.medic,'hand');for(const id of [...f.m.players.dark.reserve])state.moveCard(f.m,id,'hand');for(let i=0;i<2;i++){const gun=Object.values(f.m.cards).find(c=>c.owner==='dark'&&c.blueprint==='1_317'&&c.zone==='hand');state.moveCard(f.m,gun.id,'reserve')}let m=priority(boundary(step(f.m,'battle:'+f.site),'battle-weapons'),'dark');m=boundary(step(m,'saber:fire:'+saber+':'+f.troop),'weapon-fired');if(late){state.moveCard(m,f.medic,'table');m.cards[f.medic].location=f.site}const protectedValue=board.forfeit(m,f.troop);state.moveCard(m,f.medic,'hand');assert.deepEqual({name:'saber-'+late,hit:battle.battle(m).hits.includes(f.troop),protected:protectedValue,after:board.forfeit(m,f.troop)},observed('saber-'+late))});
test('usage belongs to the original medic table instance and turn',()=>{const f=fixture();let m=boundary(step(priority(forfeit(damage(f),f.troop),'light'),recovery(f)),'card-to-used');m=boundary(m,'battle-damage');m=priority(forfeit(m,f.second),'light');const again=ids(m).includes(recovery(f,f.second));state.moveCard(m,f.medic,'hand');state.moveCard(m,f.medic,'table');m.cards[f.medic].location=f.site;const returned=ids(m).includes(recovery(f,f.second));m.turn.number++;assert.deepEqual({name:'usage',again,returned,nextTurn:ids(m).includes(recovery(f,f.second))},observed('usage'))});
