import test from 'node:test';
import assert from 'node:assert/strict';
import {mentorFixture as fixture,play} from './mentor-fixture.mjs';
import {pull,state,rules,runtime,clone,ids,step,seek,priority,load} from './vessels-fixture.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url)),policy=mod('battle-destiny');
const done=(m,id)=>seek(m,x=>x.cards[id].zone==='lost');
const search=m=>seek(m,x=>x.stack.at(-1)?.handler==='mentor:choose');
for(const mode of ['gift','gift-yoda','cocky','eye','eye-imperial'])test(mode+' printed battle mode adds destiny and persists through save',()=>{const f=fixture(mode),before=policy.battleDrawPolicy(f.m,f.side).count,id=f[mode.startsWith('eye')?'eye':mode==='cocky'?'cocky':'gift'];assert.ok(play(f));const m=done(clone(step(f.m,play(f))),id);assert.equal(policy.battleDrawPolicy(m,f.side).count,before+(f.side==='dark'?1:2));assert.equal(mod('battle-power').battlePowerBonus(m,f.side),mode==='eye'?1:0);});
test('Vader’s Eye adds total power without changing Vader and survives his departure',()=>{const f=fixture('eye'),original=mod('board').power(f.m,f.vader);let m=step(f.m,play(f));state.moveCard(m,f.vader,'lost');m=done(m,f.eye);assert.equal(mod('battle-power').battlePowerBonus(m,'dark'),1);assert.equal(mod('board').power(f.m,f.vader),original);});
test('Vader’s Eye excludes attacking, supported and low-ability Imperials',()=>{const f=fixture('eye-imperial');state.moveCard(f.m,f.passenger,'table');f.m.cards[f.passenger].location=f.site;mod('battle').syncBattle(f.m);assert.equal(play(f),undefined);state.moveCard(f.m,f.passenger,'hand');mod('ability').addAbilityModifier(f.m,f.pilot,f.pilot,'reset',2);assert.equal(play(f),undefined);f.m.data.battle.initiator='dark';assert.equal(play(f),undefined);});
test('Vader’s Eye power affects the actual power totals, not attrition',()=>{const f=fixture('eye');let m=done(step(f.m,play(f)),f.eye);m=seek(m,x=>x.data.battle.totalsReady);assert.equal(m.data.battle.power.dark,mod('board').power(m,f.vader)+1);assert.equal(m.data.battle.attrition.light,0);});
test('Gift searches privately, reveals exactly its choice, then shuffles and loses the Interrupt',()=>{const f=fixture(),before=f.m.players.light.force.length;let m=search(step(f.m,play(f)));assert.equal(m.players.light.force.length,before-1);const ls=runtime.project(m,rules,'light'),ds=runtime.project(m,rules,'dark');assert.ok(ls.rules.mentorSearch.cards.some(c=>c.id===f.saber));assert.equal(ds.rules.mentorSearch,null);assert.deepEqual(ds.prompt.choices,[]);m=step(clone(m),'mentor:take:'+f.saber);assert.deepEqual(runtime.project(m,rules,'dark').rules.mentorSearch.cards.map(c=>c.id),[f.saber]);m=done(m,f.gift);assert.equal(m.cards[f.saber].zone,'hand');assert.equal(runtime.project(m,rules,'dark').rules.mentorSearch,null);assert.equal(m.players.light.hand.includes(f.saber),true);});
test('failed Gift search requires opponent verification and records the same-function restriction',()=>{const f=fixture();state.moveCard(f.m,f.saber,'hand');let m=search(step(f.m,play(f)));assert.deepEqual(ids(m),['mentor:not-found']);m=step(clone(m),'mentor:not-found');assert.equal(m.stack.at(-1).side,'dark');assert.ok(runtime.project(m,rules,'dark').rules.mentorSearch.cards.length);m=done(step(clone(m),'mentor:verified'),f.gift);assert.equal(mod('search-policy').canSearch(m,{blueprint:'1_82',side:'light',owner:'light',pile:'reserve',function:'mentor:lightsaber'}),false);assert.equal(m.data.failedSearches.length,1);});
test('canceled Gift retains its Force cost without inspecting or shuffling Reserve',()=>{const f=fixture(),before=[...f.m.players.light.reserve],force=f.m.players.light.force.length;let m=priority(step(f.m,play(f)),'dark');const cancel=ids(m).find(id=>id.startsWith('scomp:play:'+f.boring+':cancel'));assert.ok(cancel);m=done(step(m,cancel),f.gift);assert.deepEqual(m.players.light.reserve,before);assert.equal(m.players.light.force.length,force-1);assert.equal(m.data.failedSearches,undefined);});
test('Gift cannot search an empty Reserve or pay with no Force',()=>{const f=fixture();for(const id of [...f.m.players.light.force])state.moveCard(f.m,id,'used');assert.ok(!ids(f.m).includes(play(f)));const g=fixture();for(const id of [...g.m.players.light.reserve])state.moveCard(g.m,id,'hand');assert.ok(!ids(g.m).includes(play(g)));});
test('Cocky loss removes its selected TIE while other participants continue the battle',()=>{const f=fixture('tie');let m=done(clone(step(f.m,play(f))),f.cocky);assert.equal(m.cards[f.tie].zone,'lost');assert.equal(m.cards[f.secondTie].zone,'table');assert.notEqual(m.data.battle.stage,'complete');assert.equal(m.data.battle.paid?.dark??0,0);});
test('Cocky is only a response to enemy space battle initiation',()=>{const f=fixture('tie',true);assert.ok(!ids(f.m).includes(play(f)));const g=fixture('tie');g.m=priority(seek(g.m,m=>m.stack.at(-1)?.event?.kind==='battle-weapons'),'light');assert.ok(!ids(g.m).includes(play(g)));});
test('Cocky does not hit TIE Scouts and cancellation preserves its target',()=>{const f=fixture('tie');state.moveCard(f.m,f.scout,'table');f.m.cards[f.scout].location=f.planet;mod('battle').syncBattle(f.m);assert.ok(!ids(f.m).some(id=>id==='mentor:play:'+f.cocky+':tie:'+f.scout));let m=priority(step(f.m,play(f)),'dark');m=done(step(m,ids(m).find(id=>id.startsWith('scomp:play:'+f.boring+':cancel'))),f.cocky);assert.equal(m.cards[f.tie].zone,'table');});
test('Cocky binds the original target instance through responses',()=>{const f=fixture('tie');let m=step(f.m,play(f));state.moveCard(m,f.tie,'hand');state.moveCard(m,f.tie,'table');m.cards[f.tie].location=f.planet;m=done(clone(m),f.cocky);assert.equal(m.cards[f.tie].zone,'table');});
test('computer selects opponent TIE loss and a useful private search',()=>{for(const mode of ['tie','search']){const f=fixture(mode),v=runtime.project(f.m,rules,'light');v.prompt.choices=v.prompt.choices.filter(c=>c.id===play(f)||c.id==='pass');assert.equal(mod('computer').chooseComputerAction(v,'light'),play(f));}});
for(const mode of ['target','window','power'])test('tampered saved '+mode+' rejects',()=>{const f=fixture(mode==='power'?'eye':'tie'),m=step(f.m,play(f)),p=m.stack.find(x=>x.action?.handler===(mode==='power'?'battle-add:play':'mentor:play')).action.payload;if(mode==='target')p.target=mod('identity').referenceCard(m,f.scout);else if(mode==='window')p.window=-1;else p.power=2;assert.throws(()=>rules.validate(m));});
for(const capital of [false,true])test('TIE Fighter deploys with its permanent pilot and correct capital discount: '+capital,()=>{const f=fixture();f.m.turn.side='dark';f.m.stack[0].priority='dark';if(capital)pull(f.m,'dark','1_302','table',f.planet);const before=f.m.players.dark.force.length;const m=seek(step(f.m,'vessel:deploy:'+f.tie+':'+f.planet),x=>x.stack.length===1);assert.equal(before-m.players.dark.force.length,capital?0:1);assert.equal(mod('occupancy').permanentAbility(m,f.tie),1);assert.equal(mod('occupancy').operational(m,f.tie),true);assert.equal(mod('piloting').vesselHyperspeed(m,f.tie),null);});
test('TIE discount does not apply at a related site',()=>{const f=fixture();pull(f.m,'dark','1_302','table',f.planet);assert.equal(mod('otsd-ships').otsdDeployModifier(f.m,f.tie,f.site),0);assert.equal(mod('otsd-ships').otsdDeployModifier(f.m,f.tie,f.planet),-1);});
test('search result is bound to its original Reserve instance',()=>{const f=fixture();let m=step(search(step(f.m,play(f))),'mentor:take:'+f.saber);state.moveCard(m,f.saber,'hand');state.moveCard(m,f.saber,'reserve');m=done(clone(m),f.gift);assert.equal(m.cards[f.saber].zone,'reserve');});
test('Gift is not free when a response empties Reserve after payment',()=>{const f=fixture(),force=f.m.players.light.force.length;let m=step(f.m,play(f));for(const id of [...m.players.light.reserve])state.moveCard(m,id,'hand');m=done(m,f.gift);assert.equal(m.players.light.force.length,force-1);assert.equal(m.data.failedSearches,undefined);});
test('a played Gift consumes its unique allowance across its alternate mode',()=>{const f=fixture('gift'),second=pull(f.m,'light','1_82','hand');let m=priority(done(step(f.m,play(f)),f.gift),'light');assert.ok(!ids(m).some(id=>id.startsWith('mentor:play:'+second)||id.startsWith('battle-add:'+second)));});
test('Vader’s Eye bonus is battle-scoped and same-title bonuses are not cumulative',()=>{const f=fixture('eye');let m=done(step(f.m,play(f)),f.eye);mod('battle-power').addBattlePower(m,f.eye,'dark',1,'vaders-eye');assert.equal(mod('battle-power').battlePowerBonus(m,'dark'),1);assert.equal(mod('board').power(m,f.vader),mod('board').power(f.m,f.vader));m=seek(m,x=>x.data.battle.stage==='complete');assert.equal(m.data.battle.powerModifiers.length,2);delete m.data.battle;assert.equal(mod('battle-power').battlePowerBonus(m,'dark'),0);});
test('mentor saved search rejects a forged non-lightsaber choice',()=>{const f=fixture(),m=search(step(f.m,play(f)));assert.throws(()=>step(m,'mentor:take:'+f.luke));});
const {default:fs}=await import('node:fs');
const observations=JSON.parse(fs.readFileSync(new URL('./gemp/mentor-results.json',import.meta.url)));
for(const row of observations)test('executed GEMP mentor comparison '+row.mode+(row.capital??''),()=>{
 if(row.mode==='deploy-tie'){const f=fixture();f.m.turn.side='dark';f.m.stack[0].priority='dark';if(row.capital)pull(f.m,'dark','1_302','table',f.planet);const before=f.m.players.dark.force.length,m=seek(step(f.m,'vessel:deploy:'+f.tie+':'+f.planet),x=>x.stack.length===1);assert.deepEqual({mode:row.mode,capital:row.capital,forcePaid:before-m.players.dark.force.length,ability:mod('occupancy').permanentAbility(m,f.tie)},row);}
 else if(row.mode==='search'){const f=fixture(),force=f.m.players.light.force.length;const m=done(step(search(step(f.m,play(f))),'mentor:take:'+f.saber),f.gift);assert.deepEqual({mode:row.mode,forcePaid:force-m.players.light.force.length,targetInHand:m.cards[f.saber].zone==='hand',interruptLost:m.cards[f.gift].zone==='lost'},row);}
 else if(row.mode==='tie'){const f=fixture('tie'),m=done(step(f.m,play(f)),f.cocky);assert.deepEqual({mode:row.mode,targetLost:m.cards[f.tie].zone==='lost',secondOnTable:m.cards[f.secondTie].zone==='table',interruptLost:m.cards[f.cocky].zone==='lost'},row);}
 else {const f=fixture(row.mode),before=policy.battleDrawPolicy(f.m,f.side).count,m=done(step(f.m,play(f)),f[f.side==='dark'?'eye':row.mode==='cocky'?'cocky':'gift']);assert.deepEqual({mode:row.mode,before,after:policy.battleDrawPolicy(m,f.side).count,powerBonus:mod('battle-power').battlePowerBonus(m,f.side),lost:true},row);}
});
test('mentor reference receipt binds executed source and observations',async()=>{const {createHash}=await import('node:crypto'),p=JSON.parse(fs.readFileSync(new URL('./gemp/mentor-provenance.json',import.meta.url)));for(const [f,sha]of Object.entries(p.files))assert.equal(createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+f,import.meta.url))).digest('hex'),sha);assert.equal(observations.length,p.observations);});
