import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {load} from '../native-proof/load-engine.mjs';
import {runtime,rules,state,pull,step,seek,priority,ids,clone} from './noble-fixture.mjs';
import {fixture,choice,decision,boundary,weapons} from './obi-wan-fixture.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url));
for(const own of [true,false])test('Obi-Wan offers once at battle initiation on either turn '+own,()=>{const f=fixture('move',own),before=f.m.players.light.force.length;assert.ok(ids(f.m).includes(choice(f)));let m=decision(step(f.m,choice(f)));assert.equal(before-m.players.light.force.length,1);assert.equal(m.stack.at(-1).side,'dark');assert.ok(ids(m).includes('obi:move:'+f.adj));m=boundary(step(clone(m),'obi:move:'+f.adj),'moved');assert.equal(m.cards[f.target].location,f.adj);assert.equal(m.players.dark.force.length,f.m.players.dark.force.length);m=weapons(m);assert.ok(!ids(m).some(id=>id.startsWith('obi:use:')));assert.ok(!mod('battle').members(m,'dark').includes(f.target));});
for(const mode of ['no-adj','barred','no-force','suppressed','ability'])test('Obi-Wan rejects ineligible '+mode,()=>{const f=fixture(mode);if(mode==='no-force')for(const id of [...f.m.players.light.force])state.moveCard(f.m,id,'used');if(mode==='suppressed')mod('game-text').suppressGameText(f.m,f.target,f.obi);if(mode==='ability')mod('ability').addAbilityModifier(f.m,f.obi,f.target,'add',1);assert.ok(!ids(f.m).includes(choice(f)));});
for(const mode of ['lose','guard','already-moved'])test('voluntary or mandatory loss resolves attachments and events '+mode,()=>{const f=fixture(mode);state.moveCard(f.m,f.gun,'table');f.m.cards[f.gun].attachedTo=f.target;f.m.cards[f.gun].location=f.site;let m=step(f.m,choice(f));if(mode==='lose')m=step(decision(m),'obi:lose');m=boundary(m,'about-to-lose');assert.deepEqual(new Set(m.stack.at(-1).event.cards),new Set([f.target,f.gun]));m=boundary(m,'cards-lost');assert.equal(m.cards[f.target].zone,'lost');assert.equal(m.cards[f.gun].zone,'lost');assert.equal(m.stack.at(-1).event.cause,'obi-wan');});
test('free movement carries attachments and consumes the regular move',()=>{const f=fixture();state.moveCard(f.m,f.gun,'table');f.m.cards[f.gun].attachedTo=f.target;f.m.cards[f.gun].location=f.site;let m=boundary(step(decision(step(f.m,choice(f))),'obi:move:'+f.adj),'moved');assert.equal(m.cards[f.gun].attachedTo,f.target);assert.equal(m.cards[f.gun].location,f.adj);assert.equal(mod('ground').canMove(m,f.target),false);});
test('last opposing participant departure ends battle without drawing battle destiny',()=>{const f=fixture();state.moveCard(f.m,f.second,'hand');let m=step(decision(step(f.m,choice(f))),'obi:move:'+f.adj);for(let n=0;n<200&&m.data.battle.stage!=='complete';n++){const cs=ids(m);m=step(m,cs.includes('battle-premature-end')?'battle-premature-end':cs.includes('pass')?'pass':cs[0]);}assert.equal(m.data.battle.stage,'complete');assert.equal(m.data.battle.premature,true);assert.equal(m.data.battle.destinyResults,undefined);});
test('source departure after payment does not undo the initiated action',()=>{const f=fixture();let m=step(f.m,choice(f));mod('table').returnToHand(m,[f.obi]);m=decision(m);m=boundary(step(m,'obi:move:'+f.adj),'moved');assert.equal(m.cards[f.target].location,f.adj);});
test('a returned physical target does not inherit the old action',()=>{const f=fixture();let m=step(f.m,choice(f));mod('table').returnToHand(m,[f.target]);state.moveCard(m,f.target,'table');m.cards[f.target].location=f.site;m=weapons(m);assert.equal(m.cards[f.target].zone,'table');assert.equal(m.cards[f.target].location,f.site);});
test('movement has its own response window and uses the selected route instance',()=>{const f=fixture();let m=step(decision(step(f.m,choice(f))),'obi:move:'+f.adj);assert.equal(m.stack.at(-2).action.handler,'obi:move');assert.equal(m.stack.at(-1).timing,'response');mod('table').returnToHand(m,[f.target]);state.moveCard(m,f.target,'table');m.cards[f.target].location=f.site;m=weapons(m);assert.equal(m.cards[f.target].location,f.site);});
for(const change of ['window','source','target','payment','actor'])test('saved Obi-Wan binding rejects '+change,()=>{const f=fixture(),m=step(f.m,choice(f)),r=m.stack.find(x=>x.action?.handler==='obi:use');if(change==='window')r.action.payload.window=-1;if(change==='source')r.action.payload.source.id=f.target;if(change==='target')r.action.payload.target.id=f.obi;if(change==='payment')r.action.payment.light=0;if(change==='actor')r.actor='dark';assert.throws(()=>rules.validate(m),/Obi-Wan/);});
test('normal Obi-Wan deployment pays five and supports Mentor with Luke',()=>{const f=fixture();state.moveCard(f.m,f.obi,'hand');f.m.data.battle.stage='complete';f.m.turn.number++;f.m.turn.side='light';f.m.turn.phase='deploy';f.m.stack=[{kind:'window',serial:++f.m.serial,timing:'phase',priority:'light',passes:0,completed:[]}];const before=f.m.players.light.force.length;let m=boundary(step(f.m,'deploy:'+f.obi+':'+f.site),'deployed');assert.equal(before-m.players.light.force.length,5);assert.equal(mod('combat-modifiers').attritionImmunity(m,f.obi),5);m=seek(m,x=>x.stack.length===1);pull(m,'light','101_2','table',f.site);m.turn.phase='battle';m.stack[0].priority='light';m=priority(boundary(step(m,'battle:'+f.site),'battle-weapons'),'light');assert.ok(ids(m).some(id=>id.startsWith('battle-add:'+f.gift+':2:')));});

test('computer uses the offered reaction and preserves the target with a free exit',()=>{const f=fixture(),cpu=mod('computer');const v=runtime.project(f.m,rules,'light');v.prompt.choices=v.prompt.choices.filter(c=>['pass',choice(f)].includes(c.id));assert.equal(cpu.chooseComputerAction(v,'light'),choice(f));const m=decision(step(f.m,choice(f)));assert.equal(cpu.chooseComputerAction(runtime.project(m,rules,'dark'),'dark'),'obi:move:'+f.adj);});
test('canceling the paid reaction preserves the target and consumes the use',()=>{const f=fixture();let m=step(f.m,choice(f));m.stack.find(x=>x.action?.handler==='obi:use').cancelled=true;m=weapons(m);assert.equal(m.cards[f.target].location,f.site);assert.equal(m.players.light.force.length,f.m.players.light.force.length-1);assert.equal(m.data.battle.obiWanUses.length,1);});
test('movement remains free when the opponent has no Force',()=>{const f=fixture();for(const id of [...f.m.players.dark.force])state.moveCard(f.m,id,'used');const m=boundary(step(decision(step(f.m,choice(f))),'obi:move:'+f.adj),'moved');assert.equal(m.cards[f.target].location,f.adj);assert.equal(m.players.dark.force.length,0);});
test('no new instance of a destination can inherit a pending move',()=>{const f=fixture();let m=step(decision(step(f.m,choice(f))),'obi:move:'+f.adj);const index=m.locations.indexOf(f.adj);m.locations.splice(index,1);state.moveCard(m,f.adj,'hand');state.moveCard(m,f.adj,'table');m.locations.splice(index,0,f.adj);m=weapons(m);assert.equal(m.cards[f.target].location,f.site);});
test('production admission stays closed for Obi-Wan and arbitrary decks',()=>assert.equal(mod('premiere-rules').premiereRules.supports('1_21'),false));
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/obi-wan-results.json',import.meta.url)));
for(const row of oracle)test('executed GEMP Obi-Wan comparison '+row.mode,()=>{
 const mode=row.mode==='ability-two'?'ability':row.mode,f=fixture(mode,row.mode==='own');
 if(row.mode==='deploy'){
  state.moveCard(f.m,f.obi,'hand');f.m.data.battle.stage='complete';f.m.turn.number++;f.m.turn.side='light';f.m.turn.phase='deploy';f.m.stack=[{kind:'window',serial:++f.m.serial,timing:'phase',priority:'light',passes:0,completed:[]}];const before=f.m.players.light.force.length,m=boundary(step(f.m,'deploy:'+f.obi+':'+f.site),'deployed');assert.equal(before-m.players.light.force.length,row.cost);assert.equal(mod('combat-modifiers').attritionImmunity(m,f.obi),row.immunity);return;
 }
 if(mode==='ability')mod('ability').addAbilityModifier(f.m,f.obi,f.target,'add',1);
 if(mode==='no-adj'||mode==='ability'){assert.equal(ids(f.m).includes(choice(f)),row.offered);return;}
 if(mode==='last')state.moveCard(f.m,f.second,'hand');
 if(['lose','attachments'].includes(mode)){state.moveCard(f.m,f.gun,'table');f.m.cards[f.gun].attachedTo=f.target;f.m.cards[f.gun].location=f.site;}
 assert.equal(ids(f.m).includes(choice(f)),row.offered);let m=step(f.m,choice(f));if(mode==='source-left')mod('table').returnToHand(m,[f.obi]);
 m=seek(m,x=>x.stack.at(-1)?.handler==='obi:choose'||x.stack.at(-1)?.event?.kind==='about-to-lose');assert.equal(m.stack.at(-1)?.handler==='obi:choose',row.choice);
 if(row.choice)m=step(m,mode==='lose'?'obi:lose':'obi:move:'+f.adj);
 m=boundary(m,row.lost?'cards-lost':'moved');
 assert.deepEqual({lightCost:f.m.players.light.force.length-m.players.light.force.length,darkCost:f.m.players.dark.force.length-m.players.dark.force.length,moved:m.cards[f.target].location===f.adj,lost:m.cards[f.target].zone==='lost',gunLost:m.cards[f.gun].zone==='lost',gunMoved:m.cards[f.gun].attachedTo===f.target&&m.cards[f.gun].location===f.adj},Object.fromEntries(['lightCost','darkCost','moved','lost','gunLost','gunMoved'].map(k=>[k,row[k]])));
});
test('GEMP receipt binds the executed source and observed results',()=>{const p=JSON.parse(fs.readFileSync(new URL('./gemp/obi-wan-provenance.json',import.meta.url))),hash=file=>createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+file,import.meta.url))).digest('hex');assert.equal(hash(p.harness),p.harnessSha256);assert.equal(hash(p.results),p.resultsSha256);assert.equal(p.observations,oracle.length);assert.equal(p.productionFilesChanged,0);assert.equal(p.junitTests,3);});

for(const [mode,bp,allowed] of [['open-source','1_149',true],['enclosed-source','1_151',false],['enclosed-target','1_309',false]])test('current presence respects '+mode,()=>{
 const side=mode==='enclosed-target'?'dark':'light',f=fixture('move',false,{[side]:[bp]}),host=pull(f.m,side,bp,'table',f.site),crew=side==='dark'?f.target:f.obi;f.m.cards[crew].attachedTo=host;f.m.cards[crew].aboardRole='passenger';mod('battle').syncBattle(f.m);assert.equal(ids(f.m).includes(choice(f)),allowed);rules.validate(f.m);
});
test('losing a character offers attachment Lost ordering before the loss response',()=>{const f=fixture('lose');state.moveCard(f.m,f.gun,'table');f.m.cards[f.gun].attachedTo=f.target;f.m.cards[f.gun].location=f.site;let m=step(decision(step(f.m,choice(f))),'obi:lose');m=seek(m,x=>x.stack.at(-1)?.handler==='table:lost-order');assert.deepEqual(new Set(ids(m)),new Set(['place-lost:'+f.target,'place-lost:'+f.gun]));m=boundary(step(clone(m),'place-lost:'+f.gun),'cards-lost');assert.deepEqual(m.players.dark.lost.slice(0,2),[f.target,f.gun]);assert.ok(!ids(priority(m,'dark')).includes('revival:kintan:'+f.kintan),'Kintan needs an opposing character loss');});
