import test from 'node:test';
import assert from 'node:assert/strict';
import {pull,state,rules,runtime,clone,ids,step,seek,priority,settled,load} from './vessels-fixture.mjs';
import {setup,drain,table,boundary} from './otsd-orders-fixture.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url)),orders=mod('otsd-orders');
const offer=(m,card,mode)=>ids(m).find(id=>id.startsWith('orders:play:'+card+':'+mode));
const search=m=>seek(m,x=>x.stack.at(-1)?.handler==='orders:choose');
for(const side of ['light','dark']){
 test(side+' USED drain cancellation requires a related controlled system and persists after refresh',()=>{const f=drain(side),before=f.m.players[side].reserve.length;assert.ok(offer(f.m,f.card,'drain'));let m=settled(step(clone(f.m),offer(f.m,f.card,'drain')));assert.equal(m.players[side].reserve.length,before);assert.equal(m.cards[f.card].zone,'used');assert.ok(mod('ground').usage(m).drained.includes(f.site));m=clone(f.m);state.moveCard(m,f.ship,'lost');assert.equal(offer(m,f.card,'drain'),undefined);});
 test(side+' LOST starfighter search pays cost before responses and preserves Lost order',()=>{
  const f=setup(side),ship=pull(f.m,side,side==='light'?'106_9':'106_15','lost'),unique=pull(f.m,side,side==='light'?'1_141':'1_300','lost'),before=f.m.players[side].force.length;const action=offer(f.m,f.card,'search');assert.ok(action);let m=step(f.m,action);
  if(side==='dark'){assert.equal(m.stack.some(x=>x.kind==='resolution'&&x.action.handler==='orders:play'&&x.awaitingResponses),true);m=seek(m,x=>x.stack.at(-1)?.handler==='ground:force-loss');m=step(m,'lose:force');}
  m=search(m);assert.equal(before-m.players[side].force.length,side==='light'?3:1);assert.ok(ids(m).includes('orders:take:'+ship));assert.ok(!ids(m).includes('orders:take:'+unique));const lost=m.players[side].lost.filter(id=>id!==ship);m=settled(step(clone(m),'orders:take:'+ship));assert.equal(m.cards[ship].zone,'hand');assert.equal(m.cards[f.card].zone,'lost');assert.deepEqual(m.players[side].lost,[f.card,...lost]);rules.validate(clone(m));
 });
 test(side+' canceled starfighter recovery never refunds its cost or returns a target',()=>{
  const f=setup(side),ship=pull(f.m,side,side==='light'?'106_9':'106_15','lost'),before=f.m.players[side].force.length;let m=step(f.m,offer(f.m,f.card,'search'));
  m=seek(m,x=>x.stack.at(-2)?.action?.handler==='orders:play'&&!x.stack.at(-2).awaitingResponses);m.stack.at(-2).cancelled=true;m=settled(m);assert.equal(m.cards[ship].zone,'lost');assert.equal(m.cards[f.card].zone,'lost');assert.equal(before-m.players[side].force.length,side==='light'?3:0);
 });
 test(side+' failed Lost search preserves pile order and records failed search identity',()=>{const f=setup(side);pull(f.m,side,side==='light'?'1_141':'1_300','lost');let m=search(step(f.m,offer(f.m,f.card,'search')));assert.deepEqual(ids(m),['orders:not-found']);const before=[...m.players[side].lost];m=settled(step(m,'orders:not-found'));assert.equal(m.data.failedSearches[0].function,'orders:starfighter');assert.deepEqual(m.players[side].lost,[f.card,...before]);});
 test(side+' named Assault cancellation retires only the original pending Interrupt',()=>{
  const f=drain(side),enemy=side==='light'?'dark':'light',assault=pull(f.m,enemy,enemy==='light'?'1_113':'1_238','hand');let m=priority(f.m,enemy);m=step(m,'assault:play:'+assault);m=seek(m,x=>x.stack.at(-2)?.action?.handler==='assault:play'&&!x.stack.at(-2).awaitingResponses);m=priority(m,side);const action=offer(m,f.card,'cancel');assert.ok(action);m=boundary(step(clone(m),action),'card-canceled');assert.equal(m.cards[assault].zone,'lost');assert.equal(m.stack.some(x=>x.kind==='resolution'&&x.action.handler==='core:canceled'),true);m=settled(m);assert.equal(m.cards[f.card].zone,'lost');assert.equal(m.players[side].lost.includes(assault),false);
 });
 test(side+' selected original starfighter cannot leave and return during reveal to inherit retrieval',()=>{const f=setup(side),ship=pull(f.m,side,side==='light'?'106_9':'106_15','lost');let m=search(step(f.m,offer(f.m,f.card,'search')));m=step(m,'orders:take:'+ship);state.moveCard(m,ship,'hand');state.moveCard(m,ship,'lost');m=settled(m);assert.equal(m.cards[ship].zone,'lost');});
}
const {default:fs}=await import('node:fs');
test('non-unique metadata includes restricted and diamond cards, while retaining their play limits',()=>{const identities=JSON.parse(fs.readFileSync(new URL('../../data/native-engine/identities.json',import.meta.url)));for(const [bp,row] of Object.entries(identities))assert.equal(row.nonUnique,row.uniqueness!=='UNIQUE',bp);});
for(const side of ['light','dark']){
 test(side+' restricted squadron cards are legal non-unique recovery targets',()=>{const f=setup(side),target=pull(f.m,side,side==='light'?'106_7':'106_10','lost');let m=search(step(f.m,offer(f.m,f.card,'search')));assert.ok(ids(m).includes('orders:take:'+target));m=settled(step(m,'orders:take:'+target));assert.equal(m.cards[target].zone,'hand');});
 test(side+' later effect responses cannot reopen named Interrupt cancellation',()=>{const f=drain(side),w={...f.m.stack.at(-1),event:{kind:'force-lost'}};assert.deepEqual(orders.ordersActions(f.m,w,side),[]);});
 test(side+' cancellation can itself be canceled without stopping the drain',()=>{const f=drain(side),before=f.m.players[side].reserve.length;let m=step(f.m,offer(f.m,f.card,'drain'));m.stack.find(x=>x.kind==='resolution'&&x.action.handler==='orders:play').cancelled=true;m=settled(m);assert.equal(m.cards[f.card].zone,'lost');assert.ok(m.players[side].reserve.length<before);});
 test(side+' saved named cancellation rejects an altered parent action identity',()=>{const f=drain(side);let m=step(f.m,offer(f.m,f.card,'drain'));m.stack.find(x=>x.kind==='resolution'&&x.action.handler==='orders:play').action.payload.actionId='different-drain';assert.throws(()=>rules.validate(m),/response binding/);});
}
test('Tarkin can lose a starfighter from hand as the cost and then recover that same card',()=>{const f=setup('dark'),target=pull(f.m,'dark','106_15','hand');pull(f.m,'dark','1_300','lost');let m=step(f.m,offer(f.m,f.card,'search'));m=seek(m,x=>x.stack.at(-1)?.handler==='ground:force-loss');assert.equal(m.stack.find(x=>x.kind==='resolution'&&x.action.handler==='orders:play').awaitingResponses,true);m=search(step(m,'lose-hand:'+target));assert.ok(ids(m).includes('orders:take:'+target));m=settled(step(m,'orders:take:'+target));assert.equal(m.cards[target].zone,'hand');});
test('Tarkin losing its last Life Force ends the game before recovery',()=>{const f=setup('dark');pull(f.m,'dark','106_15','lost');for(const pile of ['reserve','force','used'])for(const id of [...f.m.players.dark[pile]])state.moveCard(f.m,id,'hand');const last=f.m.players.dark.hand.find(id=>id!==f.card);state.moveCard(f.m,last,'force');let m=step(f.m,offer(f.m,f.card,'search'));m=seek(m,x=>x.stack.at(-1)?.handler==='ground:force-loss');m=step(m,'lose:force');assert.equal(m.status,'finished');assert.equal(m.result.winner,'light');});
test('It’s A Hit needs three available Force and never substitutes losing cards',()=>{const f=setup();pull(f.m,'light','106_9','lost');for(const id of f.m.players.light.force.slice(2))state.moveCard(f.m,id,'hand');assert.equal(offer(f.m,f.card,'search'),undefined);});
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/otsd-orders-results.json',import.meta.url)));
const life=(m,side)=>['reserve','force','used'].reduce((n,p)=>n+m.players[side][p].length,0);
for(const row of oracle)test('executed GEMP OTSD orders comparison '+JSON.stringify(row),()=>{
 const side=row.dark?'dark':'light';if(row.kind==='drain'){const f=drain(side),before=life(f.m,side),m=settled(step(f.m,offer(f.m,f.card,'drain')));assert.deepEqual({kind:'drain',dark:row.dark,lifeLost:before-life(m,side),interruptUsed:m.cards[f.card].zone==='used'},row);return;}
 const f=setup(side),target=pull(f.m,side,row.target,'lost'),beforeLife=life(f.m,side),beforeForce=f.m.players[side].force.length;let m=step(f.m,offer(f.m,f.card,'search'));if(side==='dark'){m=seek(m,x=>x.stack.at(-1)?.handler==='ground:force-loss');m=step(m,'lose:force');}m=search(m);m=settled(step(m,'orders:take:'+target));assert.deepEqual({kind:'recover',dark:row.dark,target:row.target,inHand:m.cards[target].zone==='hand',interruptLost:m.cards[f.card].zone==='lost',forceSpent:beforeForce-m.players[side].force.length,lifeLost:beforeLife-life(m,side)},row);
});
test('OTSD orders reference receipt retains executed test source and observations',async()=>{const {createHash}=await import('node:crypto');const p=JSON.parse(fs.readFileSync(new URL('./gemp/otsd-orders-provenance.json',import.meta.url)));for(const [f,sha]of Object.entries(p.files))assert.equal(createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+f,import.meta.url))).digest('hex'),sha);assert.equal(oracle.length,p.observations);});
