import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {load} from '../native-proof/load-engine.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url));
const runtime=mod('runtime'),state=mod('state'),inserts=mod('reserve-inserts'),identity=mod('identity'),activation=mod('activation'),peek=mod('reserve-peek');
const {premiereRules}=mod('premiere-rules'),rules={...premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true};
const manifest=JSON.parse(fs.readFileSync(new URL('../../data/native-proof/manifest.json',import.meta.url))),clone=x=>structuredClone(x);
const prompt=m=>{const p=runtime.prompt(m,rules,'dark');return p&&runtime.prompt(m,rules,p.side)};
function step(m,id){const before=clone(m),next=runtime.applyCommand(clone(m),rules,prompt(m).side,{revision:m.revision,choice:id},()=>0);assert.deepEqual(m,before);for(const side of ['light','dark'])assert.deepEqual(runtime.project(next,rules,side),runtime.project(clone(next),rules,side));return next;}
function seek(m,check){for(let n=0;n<500;n++){if(check(m))return m;const p=prompt(m);assert.ok(p);m=step(m,p.mandatory?p.choices[0].id:'pass')}throw Error('Missing boundary');}
function pull(m,side,bp,zone='hand'){const id=m.players[side].reserve.find(id=>m.cards[id].blueprint===bp);assert.ok(id,bp);state.moveCard(m,id,zone);return id;}
function fixture(owner='light',count=4,anger=false){let m=runtime.createMatch('pending-shuffle',60,manifest.decks.map(d=>({side:d.side,cards:[...(d.side==='light'?['1_42','4_16']:['1_208','5_149']),...d.main].slice(0,60)})),rules);
 for(const side of ['light','dark']){const site=pull(m,side,side==='light'?'1_129':'1_284','table');m.locations.push(site);}
 const target=owner==='light'?'dark':'light',card=pull(m,owner,owner==='dark'?'1_208':anger?'4_16':'1_42'),other=pull(m,'light',anger?'1_42':'4_16'),telepathy=pull(m,'dark','5_149');
 state.insertCard(m,card,target,()=>0);for(const id of m.players[target].reserve.slice(count+1))state.moveCard(m,id,'hand');inserts.insertsIn(m,target)[0].position=1;m=runtime.startTurns(m,rules);runtime.activateForce(m,target,card,1);runtime.openWindow(m,'response',owner);m=seek(m,x=>x.stack.at(-1)?.event?.kind==='insert-revealed');return {m,card,other,telepathy,owner,target};
}
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/pending-insert-shuffle-results.json',import.meta.url)));
for(const row of oracle.filter(x=>x.kind==='shuffle'))test('executed pending shuffle: '+JSON.stringify(row),()=>{
 const f=fixture(row.owner,row.count);let m=f.m;const ref=identity.referenceCard(m,f.card),before=[...m.players[f.target].reserve];state.shufflePile(m,f.target,'reserve',()=>0);state.assertState(m);assert.ok(identity.sameCard(m,ref));
 const entry=inserts.insertsIn(m,f.target)[0];assert.equal(entry.revealed,row.pendingAfterShuffle);assert.equal(!inserts.topInsert(m,f.target),row.topOrdinary);assert.equal(entry.position>0,row.buried);assert.deepEqual(new Set(m.players[f.target].reserve),new Set(before));
 if(row.cancel)m.stack.find(x=>x.action?.handler==='insert:result').cancelled=true;
 m=seek(m,x=>x.stack.length===1);assert.equal(m.players[f.owner].lost.includes(f.card),row.ownerLost);assert.equal(m.players[f.target].reserve.length,row.ordinaryRemaining);assert.equal(!activation.mayActivate(m,f.target),row.prohibited);assert.equal(inserts.insertsIn(m,f.target).length,0);
});
test('actual Telepathy can cancel an Anger insert buried by a response shuffle',()=>{const f=fixture('light',4,true);let m=f.m;state.shufflePile(m,'dark','reserve',()=>0);assert.ok(inserts.insertsIn(m,'dark')[0].position>0);m=seek(m,x=>prompt(x).choices.some(c=>c.id.startsWith('telepathy:play:')));m=step(m,prompt(m).choices.find(c=>c.id.startsWith('telepathy:play:')).id);m=seek(m,x=>x.stack.length===1);assert.equal(m.cards[f.card].zone,'lost');assert.equal(m.cards[f.telepathy].zone,'used');assert.deepEqual(m.data.angerObligations??[],[])});
test('a shuffle can put a later insert ahead of the resolving one, allowing a nested reveal',()=>{
 const f=fixture('light',4,true);let m=f.m;state.insertCard(m,f.other,'dark',()=>0);state.shufflePile(m,'dark','reserve',()=>0);
 // Same controlled post-shuffle order as GEMP: ordinary, second, ordinary, first.
 const entries=inserts.insertsIn(m,'dark');inserts.saveInserts(m,[{...entries.find(x=>x.card.id===f.other),position:1},{...entries.find(x=>x.card.id===f.card),position:2}]);
 runtime.activateForce(m,'dark',f.telepathy,1);runtime.openWindow(m,'response','light');m=seek(m,x=>x.stack.at(-1)?.event?.card===f.other);assert.equal(inserts.insertsIn(m,'dark').find(x=>x.card.id===f.card).revealed,true);assert.equal(m.stack.filter(x=>x.action?.handler==='insert:result').length,2);
 const row=oracle.find(x=>x.kind==='nested');assert.equal(row.parentPendingAtSecond,true);m=seek(m,x=>x.stack.length===1);assert.equal(m.cards[f.card].zone,'lost');assert.equal(m.cards[f.other].zone,'lost');assert.equal(m.data.angerObligations.length,1);assert.deepEqual(m.players.light.lost.slice(0,2),[f.card,f.other]);assert.deepEqual(row.order,['first','second']);
});
test('re-exposing an already revealed insert does not schedule its effect twice',()=>{const f=fixture('light',4,true);let m=f.m;state.shufflePile(m,'dark','reserve',()=>0);inserts.insertsIn(m,'dark')[0].position=1;runtime.activateForce(m,'dark',f.telepathy,1);runtime.openWindow(m,'response','light');m=seek(m,x=>x.players.dark.force.length===2);assert.equal(m.stack.filter(x=>x.action?.handler==='insert:result').length,1);m=seek(m,x=>x.stack.length===1);assert.equal(m.data.angerObligations.length,1);assert.equal(m.players.light.lost.filter(id=>id===f.card).length,1)});
test('revealed insert position follows top additions, removals, and returned peeks',()=>{const f=fixture(),m=f.m;state.shufflePile(m,f.target,'reserve',()=>0);const entry=inserts.insertsIn(m,f.target)[0],depth=entry.position;state.moveCard(m,m.players[f.target].hand[0],'reserve');assert.equal(entry.position,depth+1);state.moveTop(m,f.target,'reserve','used');assert.equal(entry.position,depth);entry.position=1;const inspected=peek.peekReserve(m,f.target,3);assert.equal(inspected.inserts.length,0);peek.returnReservePeek(m,inspected);assert.equal(entry.position,3);assert.equal(entry.revealed,true);state.assertState(m)});
test('conditional shuffle includes the pending insert in each equally likely legal physical order',()=>{const outcomes=new Set();for(let a=0;a<2;a++)for(let b=0;b<2;b++){const f=fixture('light',2),values=[a,b];state.shufflePile(f.m,'dark','reserve',()=>values.shift());const x=inserts.insertsIn(f.m,'dark')[0],order=[...f.m.players.dark.reserve];order.splice(x.position,0,f.card);outcomes.add(order.join(','));assert.ok(x.position>0);assert.equal(x.revealed,true)}assert.equal(outcomes.size,4)});
for(const entropy of [()=>-1,()=>{throw Error('entropy failed')}])test('invalid shuffle entropy leaves pending continuation and physical state untouched',()=>{const f=fixture(),before=clone(f.m);assert.throws(()=>state.shufflePile(f.m,f.target,'reserve',entropy));assert.deepEqual(f.m,before)});
test('concession freezes a shuffled pending insert and its continuation',()=>{const f=fixture();state.shufflePile(f.m,f.target,'reserve',()=>0);const before=clone(f.m),done=step(f.m,'concede');assert.deepEqual(done.stack,before.stack);assert.deepEqual(done.data.reserveInserts,before.data.reserveInserts);assert.deepEqual(done.players,before.players)});
test('pending shuffle reference evidence is fingerprinted and full admission stays closed',()=>{const p=JSON.parse(fs.readFileSync(new URL('./gemp/pending-insert-shuffle-provenance.json',import.meta.url)));for(const[file,hash]of Object.entries(p.files))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+file,import.meta.url))).digest('hex'),hash);assert.equal(p.observations,oracle.length);assert.equal(p.unchangedProductionFiles,6820);assert.equal(premiereRules.supports('4_16'),false)});

for(const mode of ['missing','duplicate'])test('recovery rejects a buried revealed insert with '+mode+' continuation',()=>{const f=fixture();state.shufflePile(f.m,f.target,'reserve',()=>0);const index=f.m.stack.findIndex(x=>x.action?.handler==='insert:result');if(mode==='missing')f.m.stack.splice(index,1);else f.m.stack.splice(index,0,clone(f.m.stack[index]));const before=clone(f.m);assert.throws(()=>prompt(f.m),/bound continuation/);assert.deepEqual(f.m,before)});
