import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {load} from '../native-proof/load-engine.mjs';
const runtime=load(new URL('../../lib/native-engine/runtime.ts',import.meta.url)),state=load(new URL('../../lib/native-engine/state.ts',import.meta.url)),inserts=load(new URL('../../lib/native-engine/reserve-inserts.ts',import.meta.url)),peek=load(new URL('../../lib/native-engine/reserve-peek.ts',import.meta.url));
const {premiereRules}=load(new URL('../../lib/native-engine/premiere-rules.ts',import.meta.url));
const manifest=JSON.parse(fs.readFileSync(new URL('../../data/native-proof/manifest.json',import.meta.url))),clone=x=>JSON.parse(JSON.stringify(x));
const rules={...premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true};
function prompt(m){const p=runtime.prompt(m,rules,'dark');return p&&runtime.prompt(m,rules,p.side)}
function step(m,id,side=prompt(m).side){const before=clone(m),next=runtime.applyCommand(clone(m),rules,side,{revision:m.revision,choice:id},()=>0);assert.deepEqual(m,before);for(const s of ['light','dark'])assert.deepEqual(runtime.project(next,rules,s),runtime.project(clone(next),rules,s));return next}
function seek(m,condition){for(let i=0;i<1500;i++){if(condition(m))return m;const p=prompt(m);assert.ok(p);m=step(m,p.mandatory?p.choices[0].id:'pass')}throw Error('Boundary not found')}
function pull(m,side,bp,zone='table'){const id=m.players[side].reserve.find(id=>m.cards[id].blueprint===bp);assert.ok(id,bp);state.moveCard(m,id,zone);return id}
function fixture(){let m=runtime.createMatch('peek',60,manifest.decks.map(d=>({side:d.side,cards:[...(d.side==='light'?['1_42','1_42','1_71','101_2']:['4_133','4_133','1_208']),...d.main].slice(0,60)})),rules);for(const side of ['light','dark']){const site=pull(m,side,side==='light'?'1_129':'1_284');m.locations.push(site);for(let i=0;i<5;i++)state.moveCard(m,m.players[side].reserve.at(-1),'force');}const path=pull(m,'dark','4_133','hand'),insert=pull(m,'light','1_42','hand');return {m:runtime.startTurns(m,rules),path,insert}}
function phase(m,phase='deploy',side='dark'){return seek(m,x=>x.turn.side===side&&x.turn.phase===phase&&x.stack.length===1&&prompt(x).side===side)}
function deployed(f){let m=phase(f.m);m=step(m,'dark-path:deploy:'+f.path);return seek(m,x=>x.stack.length===1)}
function begin(f,m=deployed(f)){m=phase(m);m=step(m,'dark-path:peek:'+f.path);return seek(m,x=>x.stack.at(-1)?.handler==='dark-path:select')}
function finish(m,first=0,second=1){const p=m.stack.at(-1).payload;const cards=p.inspection.cards.map(x=>x.id);m=step(m,'dark-path:lose:'+cards[first]);m=step(m,'dark-path:lose:'+cards[second]);return {m,cards}}
for(const depth of [1,2,3,5])for(const order of [[0,1],[1,0],[0,2],[2,0],[1,2],[2,1]])test('Dark Path returns the kept card above inserts: depth '+depth+', losses '+order,()=>{
 const f=fixture();let m=deployed(f);state.insertCard(m,f.insert,'dark',()=>0);inserts.insertsIn(m,'dark')[0].position=depth;const before=m.players.dark.reserve.slice(),life=state.lifeForce(m,'dark');m=begin(f,m);
 assert.deepEqual(runtime.project(m,rules,'dark').rules.peek.map(c=>c.id),before.slice(0,3));assert.equal(runtime.project(m,rules,'dark').rules.peekInserts.length,depth<3?1:0);assert.deepEqual(runtime.project(m,rules,'light').rules.peek,[]);assert.equal(inserts.insertsIn(m,'dark')[0].revealed,false);assert.throws(()=>step(m,prompt(m).choices[0].id,'light'),/Illegal/);
 const done=finish(m,...order);m=done.m;assert.deepEqual(m.players.dark.lost.slice(0,2),[before[order[1]],before[order[0]]]);assert.deepEqual(m.players.dark.reserve,before.filter((_,i)=>!order.includes(i)));assert.equal(state.lifeForce(m,'dark'),life-2);assert.equal(inserts.insertsIn(m,'dark')[0].position,Math.max(3,depth)-2);assert.equal(inserts.insertsIn(m,'dark')[0].revealed,false);assert.equal(m.stack.at(-1).event.kind,'cards-lost');
 m=seek(m,x=>x.stack.length===1);m=phase(m);assert.ok(!prompt(m).choices.some(x=>x.id==='dark-path:peek:'+f.path));
});
for(const count of [0,1,2,3])test('Dark Path short Reserve '+count,()=>{const f=fixture();let m=deployed(f);for(const id of m.players.dark.reserve.slice(count))state.moveCard(m,id,'used');m=phase(m);if(!count){assert.ok(!prompt(m).choices.some(x=>x.id==='dark-path:peek:'+f.path));return}m=begin(f,m);const before=m.players.dark.reserve.slice();if(count<3){assert.deepEqual(prompt(m).choices.map(c=>c.id),['dark-path:finish']);m=step(m,'dark-path:finish');assert.deepEqual(m.players.dark.reserve,before);assert.equal(m.players.dark.lost.length,0)}else{m=finish(m).m;assert.equal(m.players.dark.reserve.length,1);assert.equal(m.players.dark.lost.length,2)}});
test('multiple adjacent inserts retain their physical order below all returned cards',()=>{const f=fixture();let m=deployed(f);const second=pull(m,'light','1_42','hand');state.insertCard(m,f.insert,'dark',()=>0);state.insertCard(m,second,'dark',()=>0);const entries=inserts.insertsIn(m,'dark');entries[0].position=1;entries[1].position=2;const ids=entries.map(x=>x.card.id);m=begin(f,m);assert.deepEqual(runtime.project(m,rules,'dark').rules.peekInserts.map(x=>x.id),ids);m=finish(m,0,2).m;assert.deepEqual(inserts.insertsIn(m,'dark').map(x=>[x.card.id,x.position]),ids.map(id=>[id,1]));});
test('Macroscan restores three cards above a passed insert and keeps the inspection private',()=>{const f=fixture();let m=deployed(f);const macro=pull(m,'dark','1_224'),darkInsert=pull(m,'dark','1_208','hand');state.insertCard(m,darkInsert,'light',()=>0);inserts.insertsIn(m,'light')[0].position=1;m.data.nighttimeSites=[m.locations[0]];const before=m.players.light.reserve.slice();m=phase(m);m=step(m,'peek:'+macro);m=seek(m,x=>x.stack.at(-1)?.handler==='equipment:peek');assert.equal(runtime.project(m,rules,'dark').rules.peekInserts[0].id,darkInsert);assert.deepEqual(runtime.project(m,rules,'light').rules.peekInserts,[]);m=step(m,'keep');assert.deepEqual(m.players.light.reserve,before);assert.equal(inserts.insertsIn(m,'light')[0].position,3)});
test('peek snapshot rejects stale cards and forged insert omissions without mutation',()=>{const f=fixture();let m=deployed(f);state.insertCard(m,f.insert,'dark',()=>0);inserts.insertsIn(m,'dark')[0].position=1;m=begin(f,m);for(const mutate of [p=>p.inspection.inserts=[],p=>p.inspection.cards[0].version++,p=>p.inspection.side='light',p=>p.selected=['missing'],p=>p.selected=[p.inspection.cards[0].id,p.inspection.cards[1].id]]){const bad=clone(m);mutate(bad.stack.at(-1).payload);const before=clone(bad);assert.throws(()=>prompt(bad));assert.deepEqual(bad,before)}});
test('each Dark Path instance can act once per turn, and a new table visit has new use',()=>{const f=fixture();let m=deployed(f);const second=pull(m,'dark','4_133');m=finish(begin(f,m)).m;m=phase(m);assert.ok(prompt(m).choices.some(c=>c.id==='dark-path:peek:'+second));state.moveCard(m,f.path,'hand');state.moveCard(m,f.path,'table');assert.ok(prompt(m).choices.some(c=>c.id==='dark-path:peek:'+f.path));m=phase(m,'deploy','light');assert.ok(prompt(step(m,'pass')).choices.some(c=>c.id==='dark-path:peek:'+second));});
test('the initiated peek survives source departure, while cancellation consumes its use',()=>{for(const cancel of [false,true]){const f=fixture();let m=deployed(f);m=phase(m);m=step(m,'dark-path:peek:'+f.path);if(cancel)m.stack.find(x=>x.action?.handler==='dark-path:peek').cancelled=true;else state.moveCard(m,f.path,'lost');m=seek(m,x=>x.stack.at(-1)?.handler==='dark-path:select'||x.stack.length===1);assert.equal(m.stack.at(-1)?.handler==='dark-path:select',!cancel);if(cancel){m=phase(m);assert.ok(!prompt(m).choices.some(c=>c.id==='dark-path:peek:'+f.path))}}});
test('a kept card delays insert reveal until subsequent real activation',()=>{const f=fixture();let m=deployed(f);state.insertCard(m,f.insert,'dark',()=>0);inserts.insertsIn(m,'dark')[0].position=1;m=finish(begin(f,m),0,1).m;m=seek(m,x=>x.stack.length===1);runtime.activateForce(m,'dark',f.path,2);runtime.openWindow(m,'response','light');m=seek(m,x=>x.stack.at(-1)?.event?.kind==='insert-revealed');assert.equal(inserts.insertsIn(m,'dark')[0].position,0);assert.equal(m.cards[f.insert].zone,'table');m=seek(m,x=>x.stack.length===1);assert.equal(m.cards[f.insert].zone,'lost')});
test('no complete deck is admitted by adding Dark Path coverage',()=>assert.equal(premiereRules.supports('4_133'),false));
for(const choice of ['keep','to-force'])test('Electrobinoculars '+choice+' keeps inspection separate from actual insert exposure',()=>{const f=fixture();let m=deployed(f);const host=pull(m,'light','1_28'),bin=pull(m,'light','1_35'),insert=pull(m,'dark','1_208','hand');m.cards[host].location=m.locations[0];m.cards[bin].attachedTo=host;m.cards[bin].location=m.locations[0];state.insertCard(m,insert,'light',()=>0);inserts.insertsIn(m,'light')[0].position=1;m=seek(m,x=>x.stack.at(-1)?.timing==='phase'&&prompt(x).side==='light');m=step(m,'peek:'+bin);m=seek(m,x=>x.stack.at(-1)?.handler==='equipment:peek');const top=m.players.light.reserve[0];assert.deepEqual(runtime.project(m,rules,'light').rules.peek.map(c=>c.id),[top]);assert.deepEqual(runtime.project(m,rules,'light').rules.peekInserts,[]);assert.equal(inserts.insertsIn(m,'light')[0].revealed,false);m=step(m,choice);if(choice==='keep'){assert.equal(m.players.light.reserve[0],top);assert.equal(inserts.insertsIn(m,'light')[0].position,1)}else{assert.equal(m.players.light.force[0],top);assert.equal(m.stack.at(-1).event.kind,'insert-revealed');assert.equal(inserts.insertsIn(m,'light')[0].revealed,true)}});
test('Dark Path deployment can be canceled by the real Alter card',()=>{const f=fixture();const hero=pull(f.m,'light','101_2'),alter=pull(f.m,'light','1_71','hand');f.m.cards[hero].location=f.m.locations[0];let m=phase(f.m);const low=m.players.light.reserve.find(id=>Number(load(new URL('../../lib/native-engine/board.ts',import.meta.url)).cardDefinition(m,id).stats.destiny)===0);assert.ok(low);state.moveCard(m,low,'reserve');m=step(m,'dark-path:deploy:'+f.path);const a=prompt(m).choices.find(c=>c.id.startsWith('cancel:play:')&&c.id.includes(alter));assert.ok(a);m=step(m,a.id);m=seek(m,x=>x.cards[alter].zone==='used'&&x.stack.length===1);assert.equal(m.cards[f.path].zone,'lost');assert.ok(!prompt(m).choices.some(c=>c.id==='dark-path:peek:'+f.path))});
test('selected-card preview survives recovery and is never projected to the opponent',()=>{const f=fixture();let m=begin(f);const first=m.stack.at(-1).payload.inspection.cards[0].id;m=step(m,'dark-path:lose:'+first);assert.equal(runtime.project(clone(m),rules,'dark').rules.peekSelected[0].id,first);assert.equal(runtime.project(clone(m),rules,'light').rules.peekSelected,undefined);assert.equal(m.cards[first].zone,'reserve')});
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/reserve-peek-results.json',import.meta.url))),receipt=JSON.parse(fs.readFileSync(new URL('./gemp/reserve-peek-provenance.json',import.meta.url)));
for(const [index,row]of oracle.entries())test('executed GEMP peek observation '+index+' with explicit AR replacement adjudication',()=>{
 const f=fixture();let m=deployed(f),target=row.kind==='dark-path'?'dark':'light',insert=f.insert;
 if(row.kind!=='dark-path'){insert=pull(m,'dark','1_208','hand');m.data.nighttimeSites=[m.locations[0]];}
 if(row.depth>=0){state.insertCard(m,insert,target,()=>0);inserts.insertsIn(m,target)[0].position=row.depth;}
 if(row.kind==='dark-path')for(const id of m.players.dark.reserve.slice(row.count))state.moveCard(m,id,'used');
 let expectedDepth=row.depth;
 if(row.kind==='dark-path'){m=begin(f,m);if(row.count<3){m=step(m,'dark-path:finish');if(row.depth>=0)expectedDepth=Math.max(row.depth,row.count)}else{const lost=[0,1,2].filter(i=>i!==row.keep);m=finish(m,...lost).m;if(row.depth>=0)expectedDepth=Math.max(row.depth,3)-2;}assert.equal(m.players.dark.lost.length,row.lost)}
 else{const macro=pull(m,'dark','1_224');m=phase(m);m=step(m,'peek:'+macro);m=seek(m,x=>x.stack.at(-1)?.handler==='equipment:peek');assert.equal(runtime.project(m,rules,'dark').rules.peek.length,row.shown);m=step(m,'keep');expectedDepth=Math.max(row.depth,3)}
 const actual=inserts.insertsIn(m,target)[0]?.position??-1;assert.equal(actual,expectedDepth);if(receipt.adjudication.differingObservationIndices.includes(index))assert.notEqual(actual,row.insertDepth);else assert.equal(actual,row.insertDepth);if(row.depth>=0){assert.equal(m.cards[insert].zone,'table');assert.equal(inserts.insertsIn(m,target)[0].revealed,false)}
});
test('peek conformance receipt fingerprints executed sources and preserves explicit disagreements',async()=>{const crypto=await import('node:crypto');for(const[file,hash]of Object.entries(receipt.files))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+file,import.meta.url))).digest('hex'),hash);assert.equal(receipt.observations,oracle.length);assert.equal(receipt.adjudication.differingObservations,9);assert.equal(receipt.unchangedProductionFiles,6820)});
