import test from 'node:test';
import assert from 'node:assert/strict';
import {corridorFixture} from './main-corridor-fixture.mjs';
import {mod,runtime,rules,state,pull,phase,step,seek,ids,clone} from './prisoner-fixture.mjs';
const cards=mod('ship-sites');
function pending(){const f=corridorFixture({hull:true});f.bay=pull(f.m,'dark','4_165','hand');f.m=phase(f.m,'dark','deploy');return f;}
const choices=(f,m=f.m)=>ids(m).filter(id=>id.startsWith('ship-site:deploy:'+f.bay+':'+f.ship+':'));
test('Launch Bay deployment offers only either end of two existing Executor interiors',()=>{const f=pending(),first=f.m.locations.indexOf(f.theatre),last=f.m.locations.indexOf(f.corridor)+1;assert.deepEqual(choices(f).map(id=>Number(id.split(':').at(-1))),[first,last]);for(const id of choices(f)){const m=seek(step(f.m,id),x=>x.cards[f.bay].zone==='table');rules.validate(clone(m));assert.equal(mod('board').locationOrder(m,m.locations.filter(id=>cards.relatedShip(m,id)===f.ship)),true);}});
test('Unique interior deployment cannot appear beyond an existing exterior Launch Bay',()=>{const f=pending();f.m.locations=f.m.locations.filter(id=>id!==f.corridor);state.moveCard(f.m,f.corridor,'hand');state.moveCard(f.m,f.bay,'table');f.m.locations.push(f.bay);cards.registerShipSite(f.m,f.bay,f.ship);const offered=ids(f.m).filter(id=>id.startsWith('ship-site:deploy:'+f.corridor+':EXECUTOR:'));assert.equal(offered.length,2);assert.ok(!offered.some(id=>Number(id.split(':').at(-1))>f.m.locations.indexOf(f.bay)));for(const id of offered){const m=seek(step(f.m,id),x=>x.cards[f.corridor].zone==='table');rules.validate(m);}});
test('Ship-site resolution rechecks the selected position after legal row changes during responses',()=>{const f=pending();f.m.locations=f.m.locations.filter(id=>id!==f.corridor);state.moveCard(f.m,f.corridor,'hand');state.moveCard(f.m,f.bay,'table');f.m.locations.push(f.bay);cards.registerShipSite(f.m,f.bay,f.ship);const before=f.m.locations.indexOf(f.theatre),choice=ids(f.m).find(id=>id==='ship-site:deploy:'+f.corridor+':EXECUTOR:'+before);let m=step(f.m,choice);const a=m.locations.indexOf(f.theatre),b=m.locations.indexOf(f.bay);[m.locations[a],m.locations[b]]=[m.locations[b],m.locations[a]];rules.validate(m);m=seek(m,x=>x.cards[f.corridor].zone==='lost');assert.equal(m.cards[f.bay].zone,'table');assert.equal(m.cards[f.theatre].zone,'table');rules.validate(clone(m));});
