import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {load} from '../native-proof/load-engine.mjs';
const runtime=load(new URL('../../lib/native-engine/runtime.ts',import.meta.url)),state=load(new URL('../../lib/native-engine/state.ts',import.meta.url)),inserts=load(new URL('../../lib/native-engine/reserve-inserts.ts',import.meta.url)),ground=load(new URL('../../lib/native-engine/ground.ts',import.meta.url)),battle=load(new URL('../../lib/native-engine/battle.ts',import.meta.url));
const {premiereRules}=load(new URL('../../lib/native-engine/premiere-rules.ts',import.meta.url));
const manifest=JSON.parse(fs.readFileSync(new URL('../../data/native-proof/manifest.json',import.meta.url))),clone=x=>JSON.parse(JSON.stringify(x));
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/telepathy-results.json',import.meta.url))),receipt=JSON.parse(fs.readFileSync(new URL('./gemp/telepathy-provenance.json',import.meta.url)));
const observed=(kind,match=()=>true)=>{const row=oracle.find(r=>r.kind===kind&&match(r));assert.ok(row,'Missing executed observation: '+kind);return row};
const rules={...premiereRules,starting:undefined,supports:()=>true,setupComplete:()=>true};
function prompt(m,r=rules){const p=runtime.prompt(m,r,'dark');return p&&runtime.prompt(m,r,p.side)}
function step(m,id,r=rules,side=prompt(m,r).side){const before=clone(m),next=runtime.applyCommand(clone(m),r,side,{revision:m.revision,choice:id},()=>0);assert.deepEqual(m,before);for(const s of ['light','dark'])assert.deepEqual(runtime.project(next,r,s),runtime.project(clone(next),r,s));return next}
function seek(m,condition,r=rules){for(let i=0;i<1800;i++){if(condition(m))return m;const p=prompt(m,r);assert.ok(p);m=step(m,p.mandatory?p.choices[0].id:'pass',r)}throw Error('Boundary not found')}
function pull(m,side,bp,zone='hand'){const id=m.players[side].reserve.find(id=>m.cards[id].blueprint===bp);assert.ok(id,bp);state.moveCard(m,id,zone);return id}
function fixture(){let m=runtime.createMatch('telepathy',60,manifest.decks.map(d=>({side:d.side,cards:[...(d.side==='light'?['4_16','1_42','1_109','1_109','101_2']:['5_149','5_149','1_234']),...d.main].slice(0,60)})),rules);for(const side of ['light','dark']){const site=pull(m,side,side==='light'?'1_129':'1_284','table');m.locations.push(site);for(let i=0;i<8;i++)state.moveCard(m,m.players[side].reserve.at(-1),'force');}const anger=pull(m,'light','4_16'),telepathy=pull(m,'dark','5_149'),light=pull(m,'light','1_28','table'),dark=pull(m,'dark','1_194','table');m.cards[light].location=m.locations[0];m.cards[dark].location=m.locations[0];return {m:runtime.startTurns(m,rules),anger,telepathy,light,dark,site:m.locations[0]}}
function phase(m,phase='deploy',side='dark'){return seek(m,x=>x.turn.side===side&&x.turn.phase===phase&&x.stack.length===1&&prompt(x).side===side)}
function startInsert(f){let m=phase(f.m,'deploy','light');return step(m,'insert:deploy:'+f.anger)}
function reveal(f,phaseName='control'){let m=phase(f.m,phaseName);state.insertCard(m,f.anger,'dark',()=>0);inserts.insertsIn(m,'dark')[0].position=1;runtime.activateForce(m,'dark',f.dark,1);runtime.openWindow(m,'response','light');return seek(m,x=>x.stack.at(-1)?.event?.kind==='insert-revealed')}
function playTelepathy(m,id){m=seek(m,x=>prompt(x)?.side==='dark'&&prompt(x).choices.some(c=>c.id.startsWith('telepathy:play:')&&c.id.includes(id)));return step(m,prompt(m).choices.find(c=>c.id.startsWith('telepathy:play:')&&c.id.includes(id)).id)}
function armed(mode,count){const f=fixture();if(mode==='drain')state.moveCard(f.m,f.dark,'hand');let m=phase(f.m,mode==='battle'?'battle':'control','light');while(m.players.light.force.length>count+(mode==='battle'?1:0))state.moveTop(m,'light','force','used');while(m.players.light.force.length<count+(mode==='battle'?1:0))state.moveTop(m,'light','reserve','force');m=step(m,(mode==='battle'?'battle:':'drain:')+f.site);return {...f,m}}
for(const mode of ['insert','reveal'])test('real Telepathy cancels Anger '+mode+' and returns to Used',()=>{const f=fixture();let m=mode==='insert'?startInsert(f):reveal(f);m=playTelepathy(m,f.telepathy);m=seek(m,x=>x.cards[f.telepathy].zone==='used'&&x.stack.length===1);assert.equal(m.cards[f.anger].zone,'lost');assert.equal(inserts.insertsIn(m,'dark').length,0);assert.equal(m.cards[f.anger].zone==='lost',observed(mode,r=>!r.sense).angerLost);assert.equal(m.cards[f.telepathy].zone==='used',observed(mode,r=>!r.sense).telepathyUsed);assert.deepEqual(m.data.angerObligations??[],[]);assert.ok(!m.data.insertPlays?.includes('4_16'))});
test('Anger is immune to Alter and may be inserted again after leaving the table',()=>{const f=fixture(),alter=pull(f.m,'dark','1_234');let m=startInsert(f);assert.ok(!prompt(m).choices.some(c=>c.id.includes(alter)&&c.id.startsWith('cancel:')));m=seek(m,x=>inserts.isInserted(x,f.anger)&&x.stack.length===1);state.moveCard(m,f.anger,'hand');assert.ok(!prompt(m).choices.some(c=>c.id==='insert:deploy:'+f.anger));m=phase(m,'deploy','dark');m=phase(m,'deploy','light');assert.ok(prompt(m).choices.some(c=>c.id==='insert:deploy:'+f.anger));m=step(m,'insert:deploy:'+f.anger);m=seek(m,x=>inserts.isInserted(x,f.anger)&&x.stack.length===1);assert.equal(m.cards[f.anger].zone,'table')});
test('Telepathy cannot cancel another insert title',()=>{const f=fixture(),tremor=pull(f.m,'light','1_42');let m=phase(f.m,'deploy','light');m=step(m,'insert:deploy:'+tremor);assert.ok(!prompt(m).choices.some(c=>c.id.startsWith('telepathy:')))});
for(const stage of ['control','battle','draw'])test('Anger deadline after revealing in '+stage+' survives recovery and source retrieval',()=>{const f=fixture();let m=reveal(f,stage);m=seek(m,x=>x.cards[f.anger].zone==='lost'&&x.stack.length===1);assert.equal(m.data.angerObligations.length,1);state.moveCard(m,f.anger,'hand');const turn=m.turn.number;m=seek(m,x=>x.stack.at(-1)?.handler==='ground:force-loss');const loss=m.stack.at(-1).payload;const row=observed('deadline',r=>r.revealedDuring===stage.toUpperCase());assert.equal(loss.remaining,row.loss);assert.equal(m.turn.number-turn,row.turnsLater);assert.equal(m.turn.phase,'battle');assert.equal(m.turn.side,'dark');assert.equal(m.turn.number,turn+(stage==='control'?0:2));assert.equal(m.data.angerObligations.length,0)});
for(const cancel of [false,true])test('initiating a battle satisfies Anger, canceled='+cancel,()=>{const f=fixture();let m=reveal(f);m=seek(m,x=>x.cards[f.anger].zone==='lost'&&x.stack.length===1);m=phase(m,'battle');m=step(m,'battle:'+f.site);if(cancel)m.stack.find(x=>x.action?.handler==='battle:begin').cancelled=true;m=seek(m,x=>!x.data.angerObligations.length);assert.equal(m.data.angerObligations.length,0);m=seek(m,x=>x.turn.phase==='move'&&x.stack.length===1);assert.equal(m.players.dark.lost.length,cancel?observed('canceled-battle-satisfies').loss:0)});
for(const mode of ['battle','drain'])for(const count of [0,1,2,3])for(const choice of ['pay','cancel'])test('Telepathy '+mode+' with '+count+' Force, '+choice,()=>{
 const f=armed(mode,count);let m=playTelepathy(f.m,f.telepathy);m=seek(m,x=>x.stack.at(-1)?.handler==='telepathy:choose'||x.cards[f.telepathy].zone==='used');
 if(count>=2){assert.equal(prompt(m).side,'light');assert.deepEqual(prompt(m).choices.map(c=>c.id),['telepathy:pay','telepathy:cancel']);m=step(m,'telepathy:'+choice)}
 m=seek(m,x=>x.cards[f.telepathy].zone==='used');const paid=count>=2&&choice==='pay',row=observed(mode,r=>r.force===count&&r.pay===(choice==='pay'));assert.equal(m.players.light.force.length,row.forceRemaining);assert.equal(!paid,row.canceled);const parent=m.stack.find(x=>x.action?.handler===(mode==='battle'?'battle:begin':'ground:drain'));
 if(parent)assert.equal(parent.cancelled,!paid);
 if(!paid){const events=[];m=seek(m,x=>{if(x.stack.at(-1)?.event)events.push(x.stack.at(-1).event.kind);return x.stack.length===1});if(mode==='battle'){assert.equal(battle.battle(m).premature,true);assert.equal(battle.battle(m).cancelled,true);assert.equal(events.filter(x=>['battle-ending','battle-ended'].includes(x)).length,row.endingEventsAtObservation);assert.ok(!prompt(m).choices.some(c=>c.id==='battle:'+f.site));assert.equal(battle.battle(m).totalsReady,false)}else{assert.ok(ground.usage(m).drained.includes(f.site));assert.equal(m.players.dark.lost.length,0)}}
});
for(const mode of ['insert','reveal','battle','drain'])test('real Sense cancels Telepathy '+mode+' before its effect',()=>{const f=mode==='battle'||mode==='drain'?armed(mode,3):fixture();const hero=pull(f.m,'light','101_2','table'),sense=pull(f.m,'light','1_109');f.m.cards[hero].location=f.site;const low=f.m.players.light.reserve.find(id=>mDestiny(f.m,id)===0);assert.ok(low);state.moveCard(f.m,low,'reserve');let m=mode==='insert'?startInsert(f):mode==='reveal'?reveal(f):f.m;m=playTelepathy(m,f.telepathy);const option=prompt(m).choices.find(c=>c.id.startsWith('cancel:play:')&&c.id.includes(sense));assert.ok(option);m=step(m,option.id);m=seek(m,x=>x.cards[sense].zone==='used');assert.equal(m.cards[f.telepathy].zone,'lost');if(['insert','reveal'].includes(mode))assert.equal(m.cards[f.telepathy].zone==='lost',observed(mode,r=>r.sense).telepathyLost);if(mode==='battle'||mode==='drain')assert.equal(m.players.light.force.length,3);if(mode==='reveal'){m=seek(m,x=>x.stack.length===1);assert.equal(m.data.angerObligations.length,1)}});
function mDestiny(m,id){return Number(load(new URL('../../lib/native-engine/board.ts',import.meta.url)).cardDefinition(m,id).stats.destiny)}
test('a second unique Telepathy cannot be played in the same turn',()=>{const f=armed('drain',4),second=pull(f.m,'dark','5_149');let m=playTelepathy(f.m,f.telepathy);m=seek(m,x=>x.stack.at(-1)?.handler==='telepathy:choose');m=step(m,'telepathy:pay');m=seek(m,x=>x.cards[f.telepathy].zone==='used');for(let i=0;i<8&&m.stack.length>1;i++){assert.ok(!prompt(m).choices.some(c=>c.id.startsWith('telepathy:play:')&&c.id.includes(second)));m=step(m,prompt(m).mandatory?prompt(m).choices[0].id:'pass')}assert.equal(m.cards[second].zone,'hand');assert.equal(m.players.light.force.length,2)});
test('forged pending Telepathy bindings reject without mutation',()=>{const f=armed('drain',2);let m=playTelepathy(f.m,f.telepathy);m=seek(m,x=>x.stack.at(-1)?.handler==='telepathy:choose');for(const mutate of [p=>p.index++,p=>p.window++,p=>p.mode='reveal',p=>p.card=f.anger,p=>p.actionId='wrong']){const bad=clone(m);mutate(bad.stack.at(-1).payload);const before=clone(bad);assert.throws(()=>prompt(bad));assert.deepEqual(bad,before)}});
test('concession freezes an unresolved Telepathy decision',()=>{const f=armed('battle',2);let m=playTelepathy(f.m,f.telepathy);m=seek(m,x=>x.stack.at(-1)?.handler==='telepathy:choose');const stack=clone(m.stack),players=clone(m.players);m=step(m,'concede',rules,'light');assert.equal(m.result.winner,'dark');assert.deepEqual(m.stack,stack);assert.deepEqual(m.players,players)});
test('new card definitions do not open full native admission',()=>{assert.equal(premiereRules.supports('4_16'),false);assert.equal(premiereRules.supports('5_149'),false)});

test('executed Telepathy receipt fingerprints source, fixtures and all observations',async()=>{const crypto=await import('node:crypto');for(const[file,hash]of Object.entries(receipt.files))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+file,import.meta.url))).digest('hex'),hash);assert.equal(receipt.observations,oracle.length);assert.equal(oracle.length,24);assert.equal(receipt.unchangedProductionFiles,6820)});

test('presence loss after cancellation cannot reopen ordinary battle-end windows',()=>{const f=armed('battle',2);let m=playTelepathy(f.m,f.telepathy);m=seek(m,x=>x.stack.at(-1)?.handler==='telepathy:choose');m=step(m,'telepathy:cancel');state.moveCard(m,f.dark,'hand');const events=[];m=seek(m,x=>{if(x.stack.at(-1)?.event)events.push(x.stack.at(-1).event.kind);return x.stack.length===1});assert.equal(battle.battle(m).cancelled,true);assert.equal(events.some(x=>['battle-ending','battle-ended'].includes(x)),false);assert.ok(battle.battleHistory(m).participants.includes(f.light))});
