import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {load} from '../native-proof/load-engine.mjs';
import {runtime,rules,state,pull,step,seek,priority,ids,clone} from './noble-fixture.mjs';
import {fixture,settled,turn,cancel} from './wrong-turn-fixture.mjs';
const mod=n=>load(new URL('../../lib/native-engine/'+n+'.ts',import.meta.url)),costs=mod('deploy-costs'),board=mod('board');
const deploy=(m,id)=>settled(step(m,'deploy-effect:'+id));
test('Wrong Turn pays three, survives save, is unique and affects only opposing warriors',()=>{
 const f=fixture(),before=f.m.players.dark.force.length,m=deploy(f.m,f.wrong);
 assert.equal(before-m.players.dark.force.length,3);assert.equal(m.cards[f.wrong].zone,'table');assert.equal(m.cards[f.wrong].owner,'dark');
 assert.equal(costs.deployValue(m,f.hero),4);assert.equal(costs.deployValue(m,f.troop),2);assert.equal(costs.deployValue(m,f.droid),1);assert.equal(costs.deployValue(m,f.enemy),1);
 assert.ok(!ids(priority(clone(m),'dark')).includes('deploy-effect:'+f.second));assert.deepEqual(runtime.project(m,rules,'light'),runtime.project(clone(m),rules,'light'));
});
test('insufficient Force and another players deploy phase do not offer Wrong Turn',()=>{const f=fixture();while(f.m.players.dark.force.length>2)state.moveCard(f.m,f.m.players.dark.force[0],'used');assert.ok(!ids(f.m).includes('deploy-effect:'+f.wrong));assert.ok(!ids(turn(f.m,'light')).includes('deploy-effect:'+f.wrong));});
for(const zone of ['hand','reserve','used','lost','stacked','table'])test('warrior deploy attribute applies in '+zone,()=>{const f=fixture();state.moveCard(f.m,f.wrong,'table');state.moveCard(f.m,f.hero,zone);if(zone==='stacked'){state.moveCard(f.m,f.tank,'table');f.m.cards[f.hero].stackedOn=f.tank;}if(zone==='table')f.m.cards[f.hero].location=f.site;assert.equal(costs.deployValue(f.m,f.hero),4);state.moveCard(f.m,f.wrong,'lost');assert.equal(costs.deployValue(f.m,f.hero),3);});
test('independent providers combine, same title remains noncumulative',()=>{const f=fixture();for(const id of [f.wrong,f.second,f.bad])state.moveCard(f.m,id,'table');assert.equal(costs.deployValue(f.m,f.hero),6);state.moveCard(f.m,f.wrong,'lost');assert.equal(costs.deployValue(f.m,f.hero),6);state.moveCard(f.m,f.second,'lost');assert.equal(costs.deployValue(f.m,f.hero),5);});
test('warrior training changes the current deploy attribute dynamically',()=>{const f=fixture(),training=pull(f.m,'light','1_64','table');state.moveCard(f.m,f.wrong,'table');state.moveCard(f.m,f.droid,'table');f.m.cards[f.droid].location=f.site;f.m.cards[training].attachedTo=f.droid;f.m.cards[training].location=f.site;mod('equipment-state').recordEquipment(f.m).training[training]='warrior';assert.equal(costs.deployValue(f.m,f.droid),2);state.moveCard(f.m,training,'lost');assert.equal(costs.deployValue(f.m,f.droid),1);});
for(const mode of ['pending','table','countered'])test('real Skywalkers cancellation '+mode,()=>{
 const f=fixture(),before=f.m.players.dark.force.length;let m=step(f.m,'deploy-effect:'+f.wrong);if(mode!=='pending')m=settled(m);m=priority(m,'light');const choice=cancel(m,f.sky,mode==='pending'?'cancel':'table');assert.ok(choice);m=step(clone(m),choice);
 if(mode==='countered'){m=priority(m,'dark');const counter=cancel(m,f.boring,'cancel');assert.ok(counter);m=step(m,counter);}
 m=settled(m);assert.equal(before-m.players.dark.force.length,3);assert.equal(m.cards[f.wrong].zone,mode==='countered'?'table':'lost');assert.equal(m.cards[f.sky].zone,'lost');assert.equal(costs.deployValue(m,f.hero),mode==='countered'?4:3);if(mode==='countered')assert.equal(m.cards[f.boring].zone,'used');
});
test('paid warrior deployment retains cost when Skywalkers cancels the Effect after arrival',()=>{
 const f=fixture();let m=turn(deploy(f.m,f.wrong),'light'),before=m.players.light.force.length;m=settled(step(m,'deploy:'+f.troop+':'+f.site));assert.equal(before-m.players.light.force.length,2);m=priority(m,'light');m=settled(step(m,cancel(m,f.sky)));assert.equal(costs.deployValue(m,f.troop),1);assert.equal(before-m.players.light.force.length,2);
});
test('Bacta patient recovery uses combined global deploy value',()=>{const f=fixture();for(const id of [f.wrong,f.bad,f.tank])state.moveCard(f.m,id,'table');state.moveCard(f.m,f.hero,'stacked');f.m.cards[f.hero].stackedOn=f.tank;let m=turn(f.m,'light'),before=m.players.light.force.length;m=settled(step(m,'bacta:recover:'+f.tank+':'+f.hero));assert.equal(m.cards[f.hero].zone,'hand');assert.equal(before-m.players.light.force.length,6);});
for(const change of ['amount','payer','id'])test('saved deployment rejects altered '+change,()=>{const f=fixture(),m=step(f.m,'deploy-effect:'+f.wrong),a=m.stack.find(x=>x.action?.handler==='deploy-effect:deploy').action;if(change==='amount')a.payment.dark=0;if(change==='payer')a.payment.light=3;if(change==='id')a.id+=':forged';assert.throws(()=>rules.validate(m),/deployment Effect/);});
test('production admission remains closed',()=>assert.equal(mod('premiere-rules').premiereRules.supports('1_232'),false));
test('computer invests surplus Force in Wrong Turn, preserving deployment reserves',()=>{const f=fixture(),cpu=mod('computer'),view=()=>{const v=runtime.project(f.m,rules,'dark');v.prompt.choices=v.prompt.choices.filter(c=>['deploy-effect:'+f.wrong,'pass'].includes(c.id));return v;};assert.equal(cpu.chooseComputerAction(view(),'dark'),'deploy-effect:'+f.wrong);while(f.m.players.dark.force.length>4)state.moveCard(f.m,f.m.players.dark.force[0],'used');assert.equal(cpu.chooseComputerAction(view(),'dark'),'pass');});
test('free Rebel Trooper deployment remains free while its deploy attribute is modified',()=>{const f=fixture();state.moveCard(f.m,f.wrong,'table');pull(f.m,'light','101_2','table',f.site);let m=turn(f.m,'light'),before=m.players.light.force.length;assert.equal(costs.deployValue(m,f.troop),2);m=settled(step(m,'deploy:'+f.troop+':'+f.site));assert.equal(m.cards[f.troop].zone,'table');assert.equal(m.players.light.force.length,before);});
test('CZ-3 react pays the modified normal cost and stops the drain on arrival',()=>{const f=fixture();state.moveCard(f.m,f.wrong,'table');for(const id of [f.droid,f.enemy]){state.moveCard(f.m,id,'table');f.m.cards[id].location=f.site;}f.m.turn.phase='control';let m=step(f.m,'drain:'+f.site);m=priority(m,'light');const before=m.players.light.force.length,life=state.lifeForce(m,'light');assert.ok(ids(m).includes('react-deploy:'+f.troop+':'+f.site));m=settled(step(m,'react-deploy:'+f.troop+':'+f.site));assert.equal(m.cards[f.troop].zone,'table');assert.equal(before-m.players.light.force.length,2);assert.equal(state.lifeForce(m,'light'),life);});
const oracle=JSON.parse(fs.readFileSync(new URL('./gemp/wrong-turn-results.json',import.meta.url)));
for(const row of oracle)test('executed GEMP comparison '+row.mode,()=>{
 const f=fixture();let m=f.m,actual={mode:row.mode};
 if(row.mode.startsWith('attribute-')){const zone=row.mode.slice(10);state.moveCard(m,f.hero,zone);if(zone==='table')m.cards[f.hero].location=f.site;state.moveCard(m,f.wrong,'table');actual.on=costs.deployValue(m,f.hero);state.moveCard(m,f.bad,'table');actual.combined=costs.deployValue(m,f.hero);state.moveCard(m,f.wrong,'hand');actual.afterRemoval=costs.deployValue(m,f.hero);}
 else if(row.mode==='types'){state.moveCard(m,f.wrong,'table');Object.assign(actual,{warrior:costs.deployValue(m,f.troop),droid:costs.deployValue(m,f.droid),ownWarrior:costs.deployValue(m,f.enemy)});}
 else if(row.mode==='patient'){for(const id of [f.wrong,f.bad,f.tank])state.moveCard(m,id,'table');state.moveCard(m,f.hero,'stacked');m.cards[f.hero].stackedOn=f.tank;m=turn(m,'light');const before=m.players.light.force.length;m=settled(step(m,'bacta:recover:'+f.tank+':'+f.hero));assert.equal(m.cards[f.hero].zone,'hand');actual.cost=before-m.players.light.force.length;}
 else if(row.mode==='deployment'){const before=m.players.dark.force.length;m=deploy(m,f.wrong);actual.effectCost=before-m.players.dark.force.length;m=turn(m,'light');const light=m.players.light.force.length;m=settled(step(m,'deploy:'+f.troop+':'+f.site));assert.equal(m.cards[f.troop].zone,'table');actual.troopCost=light-m.players.light.force.length;}
 else {assert.ok(['pending','table','countered'].includes(row.mode));const before=m.players.dark.force.length;m=step(m,'deploy-effect:'+f.wrong);if(row.mode!=='pending')m=settled(m);m=priority(m,'light');m=step(m,cancel(m,f.sky,row.mode==='pending'?'cancel':'table'));if(row.mode==='countered'){m=priority(m,'dark');m=step(m,cancel(m,f.boring,'cancel'));}m=settled(m);Object.assign(actual,{cost:before-m.players.dark.force.length,wrongLost:m.cards[f.wrong].zone==='lost',heroDeploy:costs.deployValue(m,f.hero),skyLost:m.cards[f.sky].zone==='lost',boringUsed:m.cards[f.boring].zone==='used'});}
 assert.deepEqual(actual,row);
});
test('Wrong Turn reference receipt binds the executed harness and results',()=>{const receipt=JSON.parse(fs.readFileSync(new URL('./gemp/wrong-turn-provenance.json',import.meta.url))),hash=file=>createHash('sha256').update(fs.readFileSync(new URL('./gemp/'+file,import.meta.url))).digest('hex');assert.equal(receipt.harnessSha256,hash(receipt.harness));assert.equal(receipt.resultsSha256,hash(receipt.results));assert.equal(receipt.observations,oracle.length);assert.equal(receipt.junitTests,5);assert.equal(receipt.productionFilesCompared,6820);assert.equal(receipt.productionFilesChanged,0);});
