import test from 'node:test';import assert from 'node:assert/strict';
import {load} from './load-engine.mjs';
import {runPath,createScenario,step,ready,deploy,phase,card,pick,prompt,project,until,finish,losses,clone,assertMatch,fallback} from './character-paths.mjs';
const rules=load(new URL('../../lib/native-proof/desert-rules.ts',import.meta.url));
const chars=load(new URL('../../lib/native-proof/character-rules.ts',import.meta.url));
const paths=['farm-deploy','bay-deploy','barrier-luke','luke-first','trooper-first','adjacent-luke','raiders-1','raiders-2','raiders-3','raiders-4','raiders-5','raider-barrier'];
for(const path of paths)test(path+' completes with the authored pool and private projections',()=>{const {m}=runPath(path);assert.equal(m.engine,'native-proof-10');assert.equal(m.complete,true);assert.equal(m.turn.stage,'complete');assert.equal(Object.keys(m.cards).length,120);for(const side of ['light','dark'])assert.deepEqual(project(m,side).players[side==='light'?'dark':'light'].hand,[])});
test('Luke location cost and uniqueness; free deploy is legal with zero Force',()=>{const farm=runPath('farm-deploy').facts,bay=runPath('bay-deploy').facts;assert.equal(farm.lukeCost,3);assert.equal(bay.lukeCost,4);assert.equal(bay.forceBeforeFree,0);assert.equal(bay.forceAfterFree,0);assert.equal(bay.duplicateAvailable,false);let m=createScenario('luke-arrives');m.cards[m.locations[0]].blueprint='1_124';assert.equal(chars.characterCanDeploy(m,'101_2',m.locations[0]),false);assert.equal(chars.characterCanDeploy(m,'1_196',m.locations[0]),false)});
test('Luke forfeits for 5 before leaving; remaining warrior credit falls from 3 to 2',()=>{assert.deepEqual(runPath('luke-first').facts,{damage:7,attrition:3,trooperBefore:3,lukeForfeit:5,guardForfeit:1,trooperAfter:2,damageAfter:2,attritionAfter:0});assert.deepEqual(runPath('trooper-first').facts,{damageAfter:4,attritionAfter:0,remainingForfeit:3,lukeForfeit:5})});
test('adjacent support does not require Luke to participate in the battle',()=>{assert.deepEqual(runPath('adjacent-luke').facts,{trooperForfeit:3,force:0,lukeParticipates:false})});
test('Barrier permits free deployment outside battle, suspends Luke during it, then restores support',()=>{assert.deepEqual(runPath('barrier-luke').facts,{beforeForfeit:3,duringForfeit:2,afterLukeForfeit:5,canMove:false,lightLost:5})});
test('Raider thresholds apply personal bonuses and one noncumulative total bonus',()=>{assert.deepEqual([1,2,3,4,5].map(n=>runPath('raiders-'+n).facts.totalPower),[1,4,6,10,12]);assert.deepEqual(runPath('raider-barrier').facts,{outsideIndividual:2,totalPower:6,participants:3})});
test('splitting Raiders changes both groups and losses do not recalculate locked battle totals',()=>{
 let m=createScenario('tusken-band');for(let n=0;n<3;n++)m=ready(deploy(m,'1_196',m.locations[1]));assert.deepEqual(project(m,'dark').characterStudy.groups.map(g=>[g.raiders,g.bonus]),[[1,0],[3,0]]);m=phase(m,'move');const id=card(m,'1_196','table').id;m=step(m,'move:'+id+':'+m.locations[1]);assert.deepEqual(project(m,'dark').characterStudy.groups.map(g=>[g.raiders,g.bonus]),[[0,0],[4,2]]);
 m=createScenario('tusken-band');for(let n=0;n<3;n++)m=ready(deploy(m,'1_196'));m=losses(m,true);const power=m.battle.power.dark;assert.equal(power,13);m=step(m,pick(m,'forfeit:').id);assert.equal(m.battle.power.dark,power);assert.equal(project(m,'dark').characterStudy.groups[0].bonus,0);
});
test('Luke movement shifts support without changing printed stats',()=>{let m=createScenario('luke-arrives');m=ready(deploy(m,'101_2'));m=ready(deploy(m,'1_28'));m=phase(m,'move');const luke=card(m,'101_2','table').id;m=step(m,'move:'+luke+':'+m.locations[1]);assert.equal(rules.characterForfeit(m,card(m,'1_28','table').id),3);assert.equal(project(m,'light').table.find(c=>c.blueprint==='1_28').stats.forfeit,'2');m=finish(m);assert.equal(m.turn.moved.length,1)});
test('corrupt board, duplicate Luke and unsupported hand fail closed',()=>{let m=createScenario('luke-arrives');m.cards[m.locations[0]].blueprint='1_124';assert.throws(()=>assertMatch(m),/Tatooine/);m=ready(deploy(createScenario('luke-arrives'),'101_2'));const other=card(m,'101_2');m.players.light.hand=m.players.light.hand.filter(id=>id!==other.id);other.zone='table';other.location=m.locations[0];assert.throws(()=>assertMatch(m),/Duplicate Luke/);m=createScenario('tusken-band');m.cards[m.players.dark.hand[0]].blueprint='101_5';assert.throws(()=>assertMatch(m),/Unsupported character study/)});
test('600 seeded complete paths restore every choice without leaking the opposing hand',()=>{
 let seed=22831,states=0;const counts={deploy:0,battle:0,move:0,draw:0,play:0,forfeit:0};for(const scenario of ['luke-arrives','luke-support','tusken-band'])for(let i=0;i<200;i++){
  let m=createScenario(scenario);m=until(m,x=>x.complete,x=>{states++;for(const side of ['dark','light']){assert.deepEqual(project(x,side),project(clone(x),side));assert.deepEqual(project(x,side).players[side==='dark'?'light':'dark'].hand,[])}seed=(Math.imul(seed,1664525)+1013904223)>>>0;const cs=prompt(x).choices,c=cs[(seed>>>8)%cs.length],kind=c.id.split(':')[0];if(kind in counts)counts[kind]++;return c.id});assert.equal(m.complete,true);
 }for(const [kind,n] of Object.entries(counts))assert.ok(n>0,kind);console.log({characterStates:states,actions:counts});
});

test('all twelve executed GEMP character outcomes match native results',()=>{const data=load(new URL('./gemp/character-oracle-result.json',import.meta.url)).branches;assert.equal(data.length,12);for(const {name,...expected} of data)assert.deepEqual(runPath(name).facts,expected,name);});
