import test from 'node:test';import assert from 'node:assert/strict';
import {engine,load} from './load-engine.mjs';
import {observe,runPath,paths} from './integration-paths.mjs';
const {createScenario,concedeGame,applyCommand,assertMatch,project,prompt}=engine;
const scenarios=load(new URL('../../lib/native-proof/catalog.ts',import.meta.url)).scenarios;
function verify(before,side){const end=concedeGame(before,side,before.engine+':'+before.revision);assertMatch(JSON.parse(JSON.stringify(end)));assert.equal(prompt(end),null);for(const seat of ['dark','light']){const view=project(end,seat);assert.equal(view.complete,true);assert.equal(view.prompt,null);assert.equal(view.concededBy,side);assert.equal(view.winner,side==='dark'?'light':'dark');assert.deepEqual(view.players[seat==='dark'?'light':'dark'].hand,[]);}const frozen=structuredClone(end);delete frozen.concededBy;frozen.revision=before.revision;frozen.log=before.log;assert.deepEqual(frozen,before);assert.throws(()=>applyCommand(end,side,{prompt:end.engine+':'+end.revision,choice:'pass'}));assert.throws(()=>concedeGame(end,side,end.engine+':'+end.revision));return end;}
test('either seat can concede in every study, independently of decision ownership',()=>{for(const {id} of scenarios)for(const side of ['dark','light'])verify(createScenario(id),side);});
test('concession preserves paid effects and private cards at every integration decision',()=>{let n=0;observe((before,choice,after)=>{if(!before.winner){verify(before,'dark');verify(before,'light');n++;}});try{for(const path of paths)runPath(path);}finally{observe(undefined);}assert.ok(n>100);});
test('completed lab checkpoint can be conceded while Life Force still remains',()=>{const m=runPath('last-hand').m;assert.equal(m.complete,true);assert.equal(m.winner,null);verify(m,'light');});
test('natural terminal winner cannot be replaced by concession',()=>{const m=runPath('last-reserve').m;for(const side of ['dark','light'])assert.throws(()=>concedeGame(m,side,m.engine+':'+m.revision));assert.equal(m.winner,'dark');});
test('stale concession and invalid seats or terminal metadata are rejected',()=>{const m=createScenario('last-force');assert.throws(()=>concedeGame(m,'light',m.engine+':99'));assert.throws(()=>concedeGame(m,'unknown',m.engine+':0'));for(const patch of [{concededBy:'invalid'},{concededBy:'light',winner:'dark'}])assert.throws(()=>assertMatch({...m,...patch}));});
test('a setup concession remains terminal when its pending setup choice is replayed',()=>{const m=createScenario('opening-table'),p=prompt(m),end=verify(m,'light');assert.throws(()=>applyCommand(end,p.side,{prompt:p.id,choice:p.choices[0].id}));assert.deepEqual(end.setup,m.setup);});
